### ISSUE TITLE
Expanding the structure tree to show column names

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#2016]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 2048
Originally created at: Thu Mar  7 10:26:26 2013
Originally last updated at: Thu Mar  7 10:26:26 2013

It would be very helpful if the db structure tree in the left side could be expanded to show column names for the tables and possibly indices. When using the SQL editor one would then be able to see the actual column names. 
An option is to open a window for the table and look in the stucture tab. However, then you would have to shift between your query  and the table window. Also, if the table contains millions of records it may take a long time to open.\n\n**Operating system:**\nLinux 32-bit

**Comment by pawelsalawa** [comment]
Originally created at: Thu Mar  7 10:26:26 2013

You should already be able to do that. See this:
<a target="\\_blank" href="http://img5.imageshack.us/img5/8308/shot95.png">http://img5.imageshack.us/img5/8308/shot95.png</a>

If you don't have it the same way, check out settings:
<a target="\\_blank" href="http://img195.imageshack.us/img195/3231/shot96.png">http://img195.imageshack.us/img195/3231/shot96.png</a>
There's an option &quot;Show column names linked under table&quot;. Have it checked.

**Comment by pawelsalawa** [comment]
Originally created at: Thu Mar  7 10:26:26 2013

_Status changed to **rejected**_

**Rejection reason:**
Already implemented.

**Comment by lallulli** [comment]
I think this request is also relevant to SQLiteStudio 3.x, i.e., I cannot find a way to expand automatically the tree nodes to show column names. Should I open a separate enhancement request? Thanks!

**Comment by pawelsalawa** [comment]
Well, it's not automatic, but it's there. If you want option for automatic expanding, please report a new issue to track it down.
