### ISSUE TITLE
Customize UI Background Color

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#2803]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 2915
Originally created at: Wed Jul  8 12:31:37 2015
Originally last updated at: Wed Jul  8 12:31:37 2015

Hello,

I use Sqlite every day on large-ish monitors, and it would be extremely useful if I could choose a darker, non-white background color for both the database side-bar and the main UI.  The current options for foreground colors on the Tools -&gt; Configuration -&gt; Look &amp; Feel -&gt; Colors panel are just fine, but could we have background options too?

I have turned down the brightness and contrast as far as I can without it upsetting the other programs I use, and so being able to choose a different background color would eliminate a lot of eye strain. :)

Hope this makes sense.  Thanks for reading.

Andrew Britton.

**Comment by pawelsalawa** [comment]
Originally created at: Wed Jul  8 12:31:37 2015

You can adapt everything with Qt's pseudo CSS for the UI. Hit F11 key. Then add something like:

QAbstractItemView {
       background: grey;
}

I'm not sure what elements of the UI will need this tuning, you would have to experiment with it.

Here's a full reference of styles available in Qt apps: <a target="\\_blank" href="http://doc.qt.io/qt-5/stylesheet-reference.html">http://doc.qt.io/qt-5/stylesheet-reference.html</a>

**Comment by pawelsalawa** [comment]
Originally created at: Wed Jul  8 12:31:37 2015

Ok, thankyou. Trying this now.

**Comment by pawelsalawa** [comment]
Originally created at: Wed Jul  8 12:31:37 2015

I've found the rgb color I want, but is there a way to save the QAbstractItemView parameters so they reapply at each SQLiteStudio startup? I'm totally new to QT. :)

**Comment by pawelsalawa** [comment]
Originally created at: Wed Jul  8 12:31:37 2015

It used to work (save) last time I tried it, but it clearly does not work anymore. I will keep this report as a reminder to fix it. Sorry for this incovenience.

**Comment by audiomuze** [comment]
Wanted to bump this too, that white background is killing my eyes, so much so I can't work for long, the eye strain gets too bad.

**Comment by audiomuze** [comment]
Doing this:
```
QAbstractItemView {
background: grey;
}
```
Gives:
![image](https://user-images.githubusercontent.com/6852511/69490364-b4310100-0e7e-11ea-9a23-785333df933c.png)

Which is a great start, but the code window remains white.

**Comment by pawelsalawa** [comment]
No longer relevant, as dark theme was introduced in #3623
