### ISSUE TITLE
Bind parameters by name

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#291]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 436
Originally created at: Thu Nov  3 15:42:59 2011
Originally last updated at: Thu Nov  3 15:42:59 2011

Rather than asking for the value of a paramter for each occurance of it in the query, it would be useful if you could bind the same value to all occurances of the named parameter, rather than doing positional binding.\n\n**Operating system:**\nWindows 7

**Comment by pawelsalawa** [comment]
Originally created at: Thu Nov  3 15:42:59 2011

Good point. I'll implement it, but I'm not sure if in 2.0.x series or in 2.1.0.

I'll keep you informed here in this report.

**Comment by pawelsalawa** [comment]
Originally created at: Thu Nov  3 15:42:59 2011

Implemented in 2.1.0.

**Comment by pawelsalawa** [comment]
Originally created at: Thu Nov  3 15:42:59 2011

_Status changed to **assigned**_

**Comment by pawelsalawa** [comment]
Originally created at: Thu Nov  3 15:42:59 2011

_Status changed to **done**_

**Comment by JrgMyr** [comment]
> Rather than asking for the value of a paramter for each occurance of it in the query,
> it would be useful if you could bind the same value to all occurances of the named parameter
> Status changed to done

Sorry. This does not work on my system. SQLiteStudio v3.2.1 on Win7.
Parameters are asked several time if they appear more than once in a query. Tested with :Name and @Name.

**Comment by pawelsalawa** [comment]
This issue was referring to a very old SQLiteStudio (2.x.x series). At the time of closing this issue the 3.x.x series did not support bind parameters yet. It was implemented in 3.x.x later and the same problem as described here applies again.

Having that said, I will reopen it now, as it makes sens to fix this in 3.x.x too.
