### ISSUE TITLE
Insert Row Problem

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#2932]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3048
Originally created at: Tue Mar 22 12:08:14 2016
Originally last updated at: Tue Mar 22 12:08:14 2016

I create base, create table, add colomns. All this with success.
But I can't insert row in table. Fields signed as &quot;read only&quot;.
Console Error Print:
[14:03:45] Cannot edit this cell. Details: The query execution mechanism had problems with extracting ROWID's properly. This might be a bug in the application. You may want to report this.

**Plugins loaded:**
PopulateConstant, SqlFormatterSimplePlugin, ScriptingTcl, MultiEditorTextPlugin, JsonExport, SqlEnterpriseFormatter, PopulateRandomText, MultiEditorDateTimePlugin, XmlExport, MultiEditorNumericPlugin, PdfExport, HtmlExport, PopulateSequence, PopulateDictionary, MultiEditorDatePlugin, PopulateRandom, MultiEditorBoolPlugin, JavaScriptHighlighterPlugin, SqliteHighlighterPlugin, PopulateScript, MultiEditorHexPlugin, ConfigMigration, Printing, MultiEditorTimePlugin, SqlExport, CsvImport, DbSqlite2, DbAndroid, DbPluginSqlite3, CsvExport, RegExpImport, ScriptingSql, ScriptingQt

**Version:**
3.0.7

**Operating System:**
Windows 7, 64bit

**Comment by pawelsalawa** [comment]
Originally created at: Tue Mar 22 12:08:14 2016

Can you provide example DDL of the problematic table?

**Comment by pawelsalawa** [comment]
No response from author for two years.

**Comment by tamlin-mike** [comment]
Sorry for the necro, but I just encountered "problems with extracting ROWID's" myself in 3.0.6, so figured I might as well document it.

In the SQL editor view I had a query containing "myfieldname!=123", i.e. without surrounding spaces around `!=`. The query ran just fine, but trying to edit any cell only met with that error. Adding surrounding spaces around `!=` made the problem vanish.

Current suspicion would be the expression parser for this case is not using the same mechanism (or (E)BNF) as when running the query.

++luck;
