### ISSUE TITLE
Highlight current row

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#2958]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3074
Originally created at: Thu May 12 13:40:12 2016
Originally last updated at: Thu May 12 13:40:12 2016

When a cell is selected in the data tab or the query results window it would be nice if the background of the cell''s row (and maybe column) was highlighted with a light grey or something. This way, one could easily read the data in the same row without mentally switching to the previous or next row. This would be especially useful for big tables.\n\n**Operating system:**\nWindows 7

**Comment by pawelsalawa** [comment]
Originally created at: Thu May 12 13:40:12 2016

_Status changed to **rejected**_

**Rejection reason:**
When the cell is selected, appropriate header column and left-side column row header are highlighted (on Windows the font if made bold).

Both horizontal as well as vertical headers are always visible, so this feature would be redundant.

**Comment by pawelsalawa** [comment]
Originally created at: Thu May 12 13:40:12 2016

I know the header gets highlighted with a bold font, but if the table has many columns and the screen is big, one may get lost anyway. Would you accept a patch for this? I can do it when I have some free time.

**Comment by patarapolw** [comment]
> When the cell is selected, appropriate header column and left-side column row header are highlighted (on Windows the font if made bold).

Not highlighted in Mac theme:

![screen shot 2018-09-23 at 19 25 09](https://user-images.githubusercontent.com/21255931/45927986-855f8800-bf66-11e8-9d03-3698ff03cb6f.png)

Get highlighted only for the left side column in the other themes (not the header row):

![screen shot 2018-09-23 at 19 24 48](https://user-images.githubusercontent.com/21255931/45927995-a1fbc000-bf66-11e8-8aa0-485923927a69.png)
![screen shot 2018-09-23 at 19 24 26](https://user-images.githubusercontent.com/21255931/45927996-a7f1a100-bf66-11e8-9e87-52a46f8c7caa.png)

I am using Mac BTW.

Would be better if it is highlighted with YELLOW or ORANGE.
