### ISSUE TITLE
3.1.0 on ix86_64 has GLIBCXX_3.4.20 error.

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#2989]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3105
Originally created at: Sun Jun 19 03:01:59 2016
Originally last updated at: Sun Jun 19 03:01:59 2016

The error received is as follows. The executable then fails to run.
Looking on Google, it appears that the new executable has been bound to the wrong library.
I am running Linux Mint 17.3.
/usr/lib/x86\\_64-linux-gnu/libstdc++.so.6: version `GLIBCXX\\_3.4.20'' not found (required by /opt/SQLiteStudio/lib/libcoreSQLiteStudio.so.1)\n\n**Operating system:**\nLinux 64-bit\n\n**Version:**\n3.1.0

**Comment by pawelsalawa** [comment]
Originally created at: Sun Jun 19 03:01:59 2016

What does this command say for you? Please paste results of:

strings /usr/lib/libstdc++.so.6  | grep GLIBCXX

**Comment by pawelsalawa** [comment]
Originally created at: Sun Jun 19 03:01:59 2016

No such file.
When I enter the command `strings /usr/lib/x86\\_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX`, I have the following returned.
GLIBCXX\\_3.4
GLIBCXX\\_3.4.1
GLIBCXX\\_3.4.2
GLIBCXX\\_3.4.3
GLIBCXX\\_3.4.4
GLIBCXX\\_3.4.5
GLIBCXX\\_3.4.6
GLIBCXX\\_3.4.7
GLIBCXX\\_3.4.8
GLIBCXX\\_3.4.9
GLIBCXX\\_3.4.10
GLIBCXX\\_3.4.11
GLIBCXX\\_3.4.12
GLIBCXX\\_3.4.13
GLIBCXX\\_3.4.14
GLIBCXX\\_3.4.15
GLIBCXX\\_3.4.16
GLIBCXX\\_3.4.17
GLIBCXX\\_3.4.18
GLIBCXX\\_3.4.19
GLIBCXX\\_DEBUG\\_MESSAGE\\_LENGTH

**Comment by pawelsalawa** [comment]
Originally created at: Sun Jun 19 03:01:59 2016

I will try to rebuild 3.1.0 binary for linux 64 on older Linux box. I will let you know once it's uploaded, so you can try it out.

**Comment by pawelsalawa** [comment]
Originally created at: Sun Jun 19 03:01:59 2016

_Status changed to **assigned**_

**Comment by pawelsalawa** [comment]
Originally created at: Sun Jun 19 03:01:59 2016

Please try this one and let me know whether it works for you. If yes, then I will switch the official package with this one:

<a target="\\_blank" href="http://sqlitestudio.pl/temp/sqlitestudio-3.1.0.tar.xz">http://sqlitestudio.pl/temp/sqlitestudio-3.1.0.tar.xz</a>

**Comment by pawelsalawa** [comment]
Originally created at: Sun Jun 19 03:01:59 2016

That version at least loads, but has the following errors displayed in the bottom pane.

[19:40:45] Cannot load plugin DbSqliteCipher. Error details: Cannot load library /opt/SQLiteStudio/plugins/libDbSqliteCipher.so: (libcrypto.so.1: cannot open shared object file: No such file or directory)

[19:40:46] Could not find Android Debug Bridge application. &lt;a href=&quot;select\\_adb://&quot;&gt;Click here&lt;/a&gt; to point out the location of the ADB application, otherwise the Android SQLite plugin will not support USB cable connections, only the network connection..

**Comment by pawelsalawa** [comment]
Originally created at: Sun Jun 19 03:01:59 2016

You can unload DbAndroid plugin if you don't use it. Second warning will disappear.

First warning is about missing openSSL library, or at least it cannot locate libcrypto.so.1 which is part of openSSL. Maybe it's named differently on your system? Then it's enough to make a symbolic link to match the name.

**Comment by pawelsalawa** [comment]
Originally created at: Sun Jun 19 03:01:59 2016

_Status changed to **done**_

**Comment by pawelsalawa** [comment]
Originally created at: Sun Jun 19 03:01:59 2016

Found from Google how to unload a plugin. Instructions for this are missing from the SQLiteStudio manual.

I have found libcrypto.so.1. It is here on Linux Mint:  /lib/x86\\_64-linux-gnu/libcrypt.so.1 . Why is this not being found? Your recommendation was to link it. To what?

**Comment by trax100** [comment]
Hi,
I have similar problem with Version 3.2.1
~~~
$ strings /usr/lib/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
~~~
Will you help me?
BR

**Comment by pawelsalawa** [comment]
It's because old Linux version that you use.
