### ISSUE TITLE
Contents of SQL Editor huge, Studio hang

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3023]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3141
Originally created at: Fri Aug  5 03:09:38 2016
Originally last updated at: Fri Aug  5 03:09:38 2016

I accidentally paste huge SQL to the panel, so now SQLite Studio is not responding, any way to clear the cache?\n\n**Operating system:**\nWindows 7\n\n**Version:**\n3.1.0

**Comment by pawelsalawa** [comment]
Originally created at: Fri Aug  5 03:09:38 2016

I think you can delete your configuration file (it's in C:/Users/&lt;your user name&gt;/AppData/Roaming/sqlitestudio )

**Comment by pawelsalawa** [comment]
Originally created at: Fri Aug  5 03:09:38 2016

I was wondering where the configuration file located. Thanks. It's working.

**Comment by pawelsalawa** [comment]
Originally created at: Fri Aug  5 03:09:38 2016

TODO: prevent pasting innormous amount of contents to SQL editor.

**Comment by pawelsalawa** [comment]
During initial tests, contents over 200k of characters causes the app to choke.
In such case need to stop all the additional features over the text editor to not influence performance for big contents. Then retest how much more is handled well to identify final limit to be applied.

**Comment by walker-tx** [comment]
Sorry for resurrecting this ancient issue, but I'm experiencing this on OSX now. Every time I close and re-open the UI, it picks up where it left off and just hangs on the massive text paste. 

Is it possible to clear the cache on OSX, too? I'm having trouble finding it.

**Comment by pawelsalawa** [comment]
Sure. Configuration location for each platform is described at https://github.com/pawelsalawa/sqlitestudio/wiki/Configuration_directory_location

**Comment by walker-tx** [comment]
thank you!
