### ISSUE TITLE
High dpi aware Windows

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3046]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3164
Originally created at: Thu Sep 15 11:19:04 2016
Originally last updated at: Thu Sep 15 11:19:04 2016

Hi, 

Could you add the following line before you create your QApplication to enable your application to be high dpi aware. Qt does all the rest for you. Right now it is usable but the sizes not in proportion. If more info needed, just ask :)

QApplication::setAttribute(Qt::AA\\_EnableHighDpiScaling);

PS: Nice software! I like using it!

Thomas

**Comment by pawelsalawa** [comment]
Reference info:
https://stackoverflow.com/questions/1126816/windows-how-to-test-ui-under-high-dpi

**Comment by regs01** [comment]
It works fine with high dpi, except for toolbar icons. Those won't scale and remains very tiny. Everything else is fine. At least on Windows.

**Comment by pawelsalawa** [comment]
Sample command for VBox to force highdpi: `.\vboxmanage controlvm "Ubuntu64" setvideomodehint 4000 2200 32`

**Comment by pawelsalawa** [comment]
![image](https://user-images.githubusercontent.com/481846/83926508-47ca7f00-a78a-11ea-9ede-40147664371a.png)

**Comment by ygoe** [comment]
At least in the latest available release 3.2.1 nothing is improved. The toolbar icons are unreadable (at 200%), the panels are too small (and even constantly revert their size although I have made them larger) and the panel close and pin buttons are so tiny they're almost impossible to target. Is there any plan to actually publish any fixes on this?

**Comment by pawelsalawa** [comment]
This is fixed for 3.2.2, yet to be released.

**Comment by ygoe** [comment]
That's what my question was about. Do you really want to close all those 100 bugs first before releaseing another version in a year? Those milestones look rather huge to me. Patch releases (0.0.1) are usually a lot smaller. And it takes forever to complete that, keeping all those fixed bugs open for the users. Maybe smaller milestones would be more helpful, and give you feedback of your implementation quicker.

**Comment by regs01** [comment]
With 3.3.0 dpi scaling seem to be broken. Either it forces 200% on 150% screen or it does scaling twice. Everything appears huge.

**Comment by regs01** [comment]
Looking around the solution. There see, to be 2 approaches.

One is setting QT_SCALE_FACTOR_ROUNDING_POLICY for Windows to PassThrough. qBittorrent and Okular uses it.

Another is setting QT_SCALE_FACTOR_ROUNDING_POLICY for Windows to RoundPreferFloor and Qt::AA_UseHighDpiPixmaps to true. Kdenlive and Shotcut using it. This one also requires. 

RoundPreferFloor doesn't work for me. Doesn't scale anything. PassThrough is working flawlessly.

Out of box (Round)

<img width="965" alt="SQLiteStudio_2021-02-22_06-21-58" src="https://user-images.githubusercontent.com/10468217/108652955-64544600-74d6-11eb-9abb-280a18a2e78c.png">


RoundPreferFloor 
<img width="917" alt="SQLiteStudio_2021-02-22_06-21-26" src="https://user-images.githubusercontent.com/10468217/108653003-7a620680-74d6-11eb-9e70-57bea29ad300.png">

PassThrough
<img width="917" alt="SQLiteStudio_2021-02-22_06-20-25" src="https://user-images.githubusercontent.com/10468217/108653011-7fbf5100-74d6-11eb-8bc7-3255ac75319a.png">

**Comment by pawelsalawa** [comment]
Thanks, @regs01!
Can we continue this discussion in #3987 (if there will be anything else to mention)?
