### ISSUE TITLE
error: ambiguous overload for &acirc;operator&gt;&acirc; (operand types are &acirc;QChar&acirc; and &acirc;int&acirc;)

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3116]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3266
Originally created at: Sun Jan 29 11:50:25 2017
Originally last updated at: Sun Jan 29 11:50:25 2017

On ArchLinux with [testing] and [kde-unstable], using Qt 5.8.0. Building from AUR (https://aur.archlinux.org/pkgbase/sqlitestudio/). The error seems pretty self-explanatory. Here''s the full output: https://gist.githubusercontent.com/hauzer/9b389011f0d11308977ca10b81e3df39/raw/3b382eb097bddd4f42e5ecd8827ba415150c9648/gistfile1.txt\n\n**Operating system:**\nLinux 64-bit\n\n**Version:**\n3.1.1

**Comment by studiofuga** [comment]
This patch fix this issue.

[0001-Fix-3116-Compile-under-Qt-5.8.0.patch.txt](https://github.com/pawelsalawa/sqlitestudio/files/1643755/0001-Fix-3116-Compile-under-Qt-5.8.0.patch.txt)

**Comment by pawelsalawa** [comment]
Thanks for the patch! I will incorporate it as soon as I have a chance to test it (I need to check whether it doesn't break compilation with older Qt).

**Comment by pawelsalawa** [comment]
Fixed with commit a1fd3a21e13784e6d705e52701bd3e4cca288598
