### ISSUE TITLE
error: calling ''operator()'' with incomplete return type ''QVariant''

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3139]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3290
Originally created at: Mon Mar 20 17:06:05 2017
Originally last updated at: Mon Mar 20 17:06:05 2017

This happens with some qt versions, only on FreeBSD 12. It looks like you use QVariant somewhere without including it.

--error log--
c++ -c -O2 -pipe -fstack-protector -fno-strict-aliasing -I/wrkdirs/usr/ports/databases/sqlitestudio/work/SQLiteStudio3/coreSQLiteStudio -std=c++11 -pedantic -std=gnu++11 -Wall -W -pthread -fPIC -DCORESQLITESTUDIO\\_LIBRARY -DQT\\_NO\\_DEBUG -DQT\\_SCRIPT\\_LIB -DQT\\_NETWORK\\_LIB -DQT\\_CORE\\_LIB -I. -I. -I../guiSQLiteStudio -I/wrkdirs/usr/ports/databases/sqlitestudio/work/SQLiteStudio3/../output/build/guiSQLiteStudio -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtScript -I/usr/local/include/qt5/QtNetwork -I/usr/local/include/qt5/QtCore -I../../output/build/coreSQLiteStudio -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-clang -o ../../output/build/coreSQLiteStudio/utils\\_sql.o common/utils\\_sql.cpp
In file included from common/utils\\_sql.cpp:1:
In file included from /wrkdirs/usr/ports/databases/sqlitestudio/work/SQLiteStudio3/coreSQLiteStudio/common/utils\\_sql.h:5:
In file included from /wrkdirs/usr/ports/databases/sqlitestudio/work/SQLiteStudio3/coreSQLiteStudio/parser/token.h:4:
In file included from /wrkdirs/usr/ports/databases/sqlitestudio/work/SQLiteStudio3/coreSQLiteStudio/common/utils.h:4:
In file included from /wrkdirs/usr/ports/databases/sqlitestudio/work/SQLiteStudio3/coreSQLiteStudio/coreSQLiteStudio\\_global.h:4:
In file included from /usr/local/include/qt5/QtCore/qglobal.h:83:
In file included from /usr/local/include/qt5/QtCore/qcompilerdetection.h:1001:
In file included from /usr/include/c++/v1/utility:198:
In file included from /usr/include/c++/v1/\\_\\_tuple:16:
/usr/include/c++/v1/type\\_traits:4301:23: error: calling ''operator()'' with incomplete return type ''QVariant''
\\_LIBCPP\\_INVOKE\\_RETURN(\\_VSTD::forward&lt;\\_Fp&gt;(\\_\\_f)(\\_VSTD::forward&lt;\\_Args&gt;(\\_\\_args)...))
~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/\\_\\_config:390:15: note: expanded from macro ''\\_VSTD''
#define \\_VSTD std::\\_LIBCPP\\_NAMESPACE
              ^
/usr/include/c++/v1/type\\_traits:4198:23: note: expanded from macro ''\\_LIBCPP\\_INVOKE\\_RETURN''
    noexcept(noexcept(\\_\\_VA\\_ARGS\\_\\_)) -&gt; decltype(\\_\\_VA\\_ARGS\\_\\_) \
                      ^~~~~~~~~~~
/usr/include/c++/v1/type\\_traits:4318:9: note: in instantiation of exception specification for ''\\_\\_invoke&lt;std::\\_\\_1::function&lt;QVariant (const QList&lt;QVariant&gt; &amp;, Db \\*, bool &amp;)&gt; &amp;, const QList&lt;QVariant&gt; &amp;, Db \\*, bool &amp;&gt;'' requested here
        \\_VSTD::\\_\\_invoke(\\_VSTD::declval&lt;\\_Fp&gt;(), \\_VSTD::declval&lt;\\_Args&gt;()...));
        ^
/usr/include/c++/v1/\\_\\_config:390:15: note: expanded from macro ''\\_VSTD''
#define \\_VSTD std::\\_LIBCPP\\_NAMESPACE
              ^
/usr/include/c++/v1/functional:1591:33: note: in instantiation of template class ''std::\\_\\_1::\\_\\_invokable\\_r&lt;void, std::\\_\\_1::function&lt;QVariant (const QList&lt;QVariant&gt; &amp;, Db \\*, bool &amp;)&gt; &amp;, const QList&lt;QVariant&gt; &amp;, Db \\*, bool &amp;&gt;'' requested here
                                \\_\\_invokable&lt;\\_Fp&amp;, \\_ArgTypes...&gt;::value&gt;
                                ^
/usr/include/c++/v1/functional:1616:9: note: in instantiation of default argument for ''\\_\\_callable&lt;std::\\_\\_1::function&lt;QVariant (const QList&lt;QVariant&gt; &amp;, Db \\*, bool &amp;)&gt; &gt;'' required here
        \\_\\_callable&lt;\\_Fp&gt;::value &amp;&amp; !is\\_same&lt;\\_Fp, function&gt;::value
        ^~~~~~~~~~~~~~~
/usr/include/c++/v1/functional:1618:5: note: in instantiation of default argument for ''function&lt;std::\\_\\_1::function&lt;QVariant (const QList&lt;QVariant&gt; &amp;, Db \\*, bool &amp;)&gt; &gt;'' required here
    function(\\_Fp);
    ^~~~~~~~~~~~~
/usr/include/c++/v1/functional:1578:28: note: while substituting deduced template arguments into function template ''function'' [with \\_Fp = std::\\_\\_1::function&lt;QVariant (const QList&lt;QVariant&gt; &amp;, Db \\*, bool &amp;)&gt;, $1 = (no value)]
class \\_LIBCPP\\_TEMPLATE\\_VIS function&lt;\\_Rp(\\_ArgTypes...)&gt;
                           ^
/usr/include/c++/v1/functional:1670:9: note: ''operator()'' declared here
    \\_Rp operator()(\\_ArgTypes...) const;
        ^
/usr/local/include/qt5/QtCore/qmetatype.h:1893:1: note: forward declaration of ''QVariant''
QT\\_FOR\\_EACH\\_STATIC\\_CORE\\_CLASS(QT\\_FORWARD\\_DECLARE\\_STATIC\\_TYPES\\_ITER)
^
/usr/local/include/qt5/QtCore/qmetatype.h:115:21: note: expanded from macro ''QT\\_FOR\\_EACH\\_STATIC\\_CORE\\_CLASS''
    F(QVariant, 41, QVariant) \
                    ^\n\n**Operating system:**\nFreeBSD 64-bit\n\n**Version:**\n3.1.1

**Comment by pawelsalawa** [comment]
Originally created at: Mon Mar 20 17:06:05 2017

_Status changed to **assigned**_

**Comment by pawelsalawa** [comment]
Originally created at: Mon Mar 20 17:06:05 2017

Please release the version with the fixes of these nuisance bugs. It has been about 9 months since the last release.

**Comment by pawelsalawa** [comment]
Originally created at: Mon Mar 20 17:06:05 2017

same error here : FreeBSD11.1/AMD64 -- port version: 3.1.1\\_3

**Comment by pawelsalawa** [comment]
Originally created at: Mon Mar 20 17:06:05 2017

Why don't you release the fix for this compiler error?

**Comment by yurivict** [comment]
@pawelsalawa Please apply the same patch as here: https://svnweb.freebsd.org/ports?view=revision&revision=454970

**Comment by pawelsalawa** [comment]
Thanks @yurivict !

**Comment by yurivict** [comment]
You're welcome!
No problem at all.

Thank you for your hard work on this wonderful project!
