### ISSUE TITLE
Cannot use special characters

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3146]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3297
Originally created at: Wed Mar 29 16:37:41 2017
Originally last updated at: Wed Mar 29 16:37:41 2017

On OSX we can use special (accented) characters by pressing a key (for example 'a') and keep it pressed. After a while a small window appears in which we can select one of the accented 'a' characters. In SQLiteStudio the key just keeps repeating. It is not even possible to copy and paste an accented character (at least not in this dialog).

It would be very nice to be able to use accented characters

**Plugins loaded:**
Printing, MultiEditorTextPlugin, CsvExport, MultiEditorDatePlugin, ConfigMigration, CsvImport, MultiEditorNumericPlugin, DbSqlite2, MultiEditorHexPlugin, PopulateDictionary, MultiEditorTimePlugin, PopulateScript, PopulateRandomText, PopulateConstant, ScriptingSql, PopulateSequence, DbSqliteWx, ScriptingQt, SqlEnterpriseFormatter, MultiEditorDateTimePlugin, DbPluginSqlite3, SqliteHighlighterPlugin, JsonExport, ScriptingTcl, RegExpImport, XmlExport, JavaScriptHighlighterPlugin, MultiEditorBoolPlugin, PdfExport, DbSqliteCipher, HtmlExport, SqlFormatterSimplePlugin, PopulateRandom

**Version:**
3.1.1

**Operating System:**
MacOS X 10.10 Yosemite, 64bit

**Comment by tuffnatty** [comment]
This is the QT bug https://bugreports.qt.io/browse/QTBUG-71394 fixed in QT 6.2. Probably will be fixed when/if #4553 is done.

**Comment by pawelsalawa** [comment]
Thanks for hinting this!

**Comment by tuffnatty** [comment]
Confirming as fixed with the Qt 6 build (which needs 10.14, so won't help the original poster without an OS update).

**Comment by tuffnatty** [comment]
And the behavior with Qt 5.15.12 is that the input method window appears, but the key keeps repeating. So you can select your needed character but need to delete the extra characters after.
