### ISSUE TITLE
Can't open an database with no file name extension

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3211]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3362
Originally created at: Mon Oct  2 12:49:06 2017
Originally last updated at: Mon Oct  2 12:49:06 2017

Can't open a db with the name &quot;db&quot; 

**Plugins loaded:**
Printing, JsonExport, XmlExport, MultiEditorHexPlugin, ScriptingSql, PopulateRandomText, PopulateConstant, MultiEditorTextPlugin, PdfExport, RegExpImport, PopulateScript, DbSqliteWx, ConfigMigration, MultiEditorDateTimePlugin, MultiEditorBoolPlugin, JavaScriptHighlighterPlugin, SqlEnterpriseFormatter, DbSqlite2, MultiEditorNumericPlugin, MultiEditorDatePlugin, ScriptingQt, PopulateRandom, DbPluginSqlite3, PopulateDictionary, CsvExport, HtmlExport, MultiEditorTimePlugin, ScriptingTcl, SqliteHighlighterPlugin, PopulateSequence, SqlExport, CsvImport

**Version:**
3.1.1

**Operating System:**
Linux 4.13.4-1-ARCH, 64bit

**Comment by studiofuga** [comment]
This doesn't seem to be a bug. If the file is named "db" (without .db extension) it will not be listed with the default file filter "*.db", but it will be listened, and opened, when you select "all files" from the dropdown list.

**Comment by pawelsalawa** [comment]
Correct. Closing.
