### ISSUE TITLE
Crashed. On editing database.

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3219]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3370
Originally created at: Mon Oct 23 14:39:00 2017
Originally last updated at: Mon Oct 23 14:39:00 2017

the application crashes when  try to edit the database. This happens if the path to the database file has been changed.
step:
1. Add database to application.
2. Through the file manager change the path to the file. For example, change one char of a parent directory.
3. Open applicatino &quot;Sqlitestudio&quot;
4. The database will be flagged with an error. Press &quot;Edit 
database&quot;
5. Crash!
\n\n**Operating system:**\nWindows 7\n\n**Version:**\n3.1.1

**Comment by studiofuga** [comment]
This is a duplicate of #3235

**Comment by pawelsalawa** [comment]
That's right. Closing.
