### ISSUE TITLE
only first 1000 lines are displayed

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3230]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3381
Originally created at: Tue Oct 31 09:40:55 2017
Originally last updated at: Tue Oct 31 09:40:55 2017

Using Adobe Photoshop Elements v.13 I wanted to look inside the database, named catalog.pse13db. My collection has about 47000 items but only the first 1000 are displayed.
Is this a bug or a limiting feature?

**Plugins loaded:**
MultiEditorDateTimePlugin, XmlExport, CsvImport, MultiEditorTextPlugin, PopulateScript, PdfExport, PopulateDictionary, ConfigMigration, DbSqliteWx, DbSqlite2, SqliteHighlighterPlugin, RegExpImport, DbSqliteCipher, HtmlExport, JavaScriptHighlighterPlugin, ScriptingQt, MultiEditorDatePlugin, JsonExport, DbSqliteSystemData, ScriptingTcl, SqlEnterpriseFormatter, MultiEditorHexPlugin, ScriptingSql, CsvExport, MultiEditorBoolPlugin, PopulateConstant, PopulateRandom, Printing, DbPluginSqlite3, MultiEditorTimePlugin, SqlExport, PopulateRandomText, PopulateSequence, MultiEditorNumericPlugin

**Version:**
3.1.1

**Operating System:**
Windows 10, 64bit

**Comment by studiofuga** [comment]
This is not a bug. The following entries can be displayed by changing the "page".

**Comment by pawelsalawa** [comment]
Correct. Closing.
