### ISSUE TITLE
CLI download not executable on MacOS

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3232]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3383
Originally created at: Sat Nov  4 21:11:46 2017
Originally last updated at: Sat Nov  4 21:11:46 2017

when running CLI according to instructions, I get:
&quot;dyld: Library not loaded: @rpath/libcoreSQLiteStudio.1.dylib
  Referenced from: /Users/gregorywoods/Applications/SQLiteStudio.app/Contents/MacOS/sqlitestudiocli
  Reason: image not found
Abort trap: 6
logout
&quot;\n\n**Operating system:**\nMac OS X (other)\n\n**Version:**\n3.1.1

**Comment by tuffnatty** [comment]
Works for me

**Comment by pawelsalawa** [comment]
It might be that it's no longer relevant, as it's very old issue, reported for 3.1.1 and over 5 years ago.
Since it worked for you, I'm closing it.
