### ISSUE TITLE
App crash after file location change

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3235]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3386
Originally created at: Tue Nov 14 08:49:23 2017
Originally last updated at: Tue Nov 14 08:49:23 2017

When I moved db file, runned this program and tried to edit db with error the app has crashed. It's replicable.

**Plugins loaded:**
MultiEditorHexPlugin, JsonExport, ScriptingSql, ScriptingQt, DbSqliteCipher, DbPluginSqlite3, SqliteHighlighterPlugin, ScriptingTcl, PopulateSequence, MultiEditorDatePlugin, PopulateConstant, PdfExport, MultiEditorTimePlugin, DbSqliteWx, JavaScriptHighlighterPlugin, PopulateScript, PopulateDictionary, MultiEditorNumericPlugin, PopulateRandomText, MultiEditorBoolPlugin, DbSqlite2, ConfigMigration, SqlEnterpriseFormatter, DbSqliteSystemData, MultiEditorTextPlugin, RegExpImport, Printing, SqlExport, MultiEditorDateTimePlugin, PopulateRandom, CsvImport, CsvExport, XmlExport, HtmlExport

**Version:**
3.1.1

**Operating System:**
Windows 10, 64bit

**Comment by studiofuga** [comment]
This fixes the issue


[0001-Fix-Bug-3235-App-Crash-afret-file-location-change.patch.txt](https://github.com/pawelsalawa/sqlitestudio/files/1646309/0001-Fix-Bug-3235-App-Crash-afret-file-location-change.patch.txt)

**Comment by pawelsalawa** [comment]
Perfect. Thanks! It will be applied as soon as I have little time to sit down to the code.
