### ISSUE TITLE
No longer populates DEFAULT values on manual insert

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3251]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3402
Originally created at: Thu Dec 28 22:57:18 2017
Originally last updated at: Thu Dec 28 22:57:18 2017

I have a table with some DEFAULT values declared:
default date(''now'')
and
default &quot;a string&quot;

The worked in 3.0.6 as expected, but on upgrading these are no longer populated when I use the manual &quot;insert row&quot; feature.\n\n**Operating system:**\nWindows 7\n\n**Version:**\n3.1.1

**Comment by pawelsalawa** [comment]
Confirmed for: default "a string" (double quotes are stripped in final DDL)
Confirmed for: date("now") (the DEFAULT dialog doesn't recognize syntax correctly)

**Comment by pawelsalawa** [comment]
SQLiteStudio does not put DEFAULT value if you leave column empty, because you may actually want to insert NULL. To enforce default value, define NOT NULL too. If you don't want to define NOT NULL, you can change SQLiteStudio behavior in Configuration -> Data browsing -> Use DEFAULT value

**Comment by alejosimon** [comment]
Hello friend,
the default string still does not work with single quotes. my version of sqlitestudio is 3.2.1

According to sqlite.org ... https://www.sqlite.org/lang_keywords.html
'keyword'  | A keyword in single quotes is a string literal.
"keyword" | A keyword in double-quotes is an identifier.

you should consider the single quotes as default empty string.
Thanks!
