### ISSUE TITLE
Host Sqlitestudio.pl not found when updating or sending reports within SQLiteStudio.

### ISSUE THREAD

**Issue by Gadget-Geek** [pawelsalawa/sqlitestudio#3257]
### Details
When I attempt to check for updates, report a bug, or propose a new feature via the options in the Help menu, the status box always reports the following error: "An error occurred while (operation): Host Sqlitestudio.pl not found." I have no problem accessing the host [https://sqlitestudio.pl/](url) via my browser; could it be a firewall in my way?

### Steps to reproduce
From the Help menu, choose any of the following options:

- Check for updates
- Report a bug
- Propose a new feature

If reporting a bug or proposing a new feature, complete and submit the form.

### Operating system
Microsoft Windows 7 Professional

### SQLiteStudio version
SQLiteStudio v3.1.1

**Comment by pawelsalawa** [comment]
This is a temporary issue caused by migration to github. It will be solved soon on server side (sqlitestudio.pl hosting server), which SQLiteStudio is reaching out to for reporting bugs, so no changes on application code is needed. I think it's a matter of one week or something around that.
