### ISSUE TITLE
Question: Can we add a close command?

### ISSUE THREAD

**Issue by stefanos82** [pawelsalawa/sqlitestudio#3266]
First of all @pawelsalawa great job!

I remember when i first tried sqlitestudio when it was implemented in Tcl and didn't like it 😄 now it looks so awesome!

Question: I have just downloaded the latest version available (3.1.1) and can't find any `Close` button.

Also, I cannot open menu with Alt-key. I find it very convenient to either press `Ctrl-Q` or press `Alt`, the underscored menu bar, the key it's underscored, and again the key that represents the `Close`.

Is it easy to add it?

**Comment by yurivict** [comment]
Please also close the window on Alt-F4.

**Comment by mperry2** [comment]
This is indeed OS dependent. For example, on Windows I can press Alt-F4 and it will close SQLiteStudio.

**Comment by stefanos82** [comment]
At least we need a menu bar with a "File > Close" option...
