### ISSUE TITLE
Support bind params

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3268]
### Details
Version 3 has missing feature of version 2, which is support for bind params within the query. Bind params should show a dialog when query is executed to provide values.

**Comment by chriszrc** [comment]
Hi, thanks for adding bind param support! I'm looking at the official docs here:

https://www.sqlite.org/lang_expr.html#varparam

And it indicates that params in the format of "?1" or "?2" should work, but I get this in sqlite studio (v3.2.1)

```
[15:13:44] Error while executing SQL query on database 'client_sqlite': Error while preparing statement: could not bind parameter :arg01
```

Using just a "?" works, I'm wondering if this should be supported?

**Comment by pawelsalawa** [comment]
Yes, this is a bug. Please report is as a new issue, if you don't mind. It would get lost here in the comments.

**Comment by chriszrc** [comment]
done - https://github.com/pawelsalawa/sqlitestudio/issues/3549
