### ISSUE TITLE
Enhance argument handling in custom functions

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3272]
Currently custom SQL functions editor do not respect names of parameters declared in the functions, only an order.

This should be enhanced, so if user defines parameters, they are respected on function's code.

**Comment by Antonio-52** [comment]
Please apologize me, but I cannot understand the explanation.
I defined  the custom SQL function left(arg, len) with the following codes:
1. select substr(arg, 1, len)
2. select substr(@arg, 1, @len)
3. select substr(@1, 1, @2)
but none works.
Can you please suggest an example on how to correctly pass parameters?
Thank you.
