### ISSUE TITLE
Save Queries

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3273]
It would be a really nice feature if you could save the queries that you've written. The way the applicaion works right now requires me to leave the window open at the bottom even if I don't need the query at the current moment. If I could save the query and close the window that would be great.	
OS:

Version:

**Comment by jclark58** [comment]
I would endorse this request.  I have lost queries that I have been developing when the application has crashed.  If Queries are able to be saved in the database and Run, Edit, Delete options, it would make SQLiteStudio a more complete product.  Given that a View is basically a stored query the ability to have Update queries and others stored in the db would seem to be straightforward.   Then all we need are Reports and a scriptable GUI, and we have a platform independent web application development aka msaccess

**Comment by pawelsalawa** [comment]
If you were executing these queries, then you can find them in "History" tab of SQL Editor window.

**Comment by jclark58** [comment]
Many Thanks!  it would still be useful to Save SQL files in the database interface or is this a limitation of SQLite?

**Comment by pawelsalawa** [comment]
It could be saved in SQLiteStudio configuration (and that's the whole idea behind this GitHub issue here).

User's custom database is not really best place to store it, but it's not bad idea to consider it as an option.

**Comment by jclark58** [comment]
OK, every query that relates to the custom database should be able to stored in it.

**Comment by pawelsalawa** [comment]
Queries are metadata, not data. It could be stored there, but it's not good practice for production databases.

**Comment by jclark58** [comment]
OK, so where are the existing Views stored in Sqlite Studio?

**Comment by pawelsalawa** [comment]
Views are database objects, to be used on production.

Queries are... just queries. You either use them from database editor app (like SQLiteStudio) or from application that is intended to use that database, in which case the query should be included in the application code, not in database.

**Comment by aps2011** [comment]
I use a very simple home-brewed database loaded in SQLiteStudio to hold code snippets. Tables are:

- SQLite version (with comments on supported features such as CTE, window functions)
- Databases (name, description, comments, target minimum SQLite version)
- Code Snippets (name, description, code, comments, type (SQL, DDL etc) target minimum SQLite version)
- Code used in database (to resolve many-to-many relationship: comments, foreign keys)

It's all very basic and requires some key strokes to copy and paste code but it does help with re-use of queries etc. and help avoid the loss of code from accidentally closing an editor window.

**Comment by pawelsalawa** [comment]
I just realized this issue is duplicate of #4065 (or the other one is duplicate of this one).

I'm currently implementing #4065 for 3.4.0, so I'll close this one.
