### ISSUE TITLE
Upgrade script broknen when there is a default value in new column

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3274]
If default value is set to a column (string value with double quotes e.g. for guid column type), the generated upgrade script gets broken and must be edited manually in order to be accepted.

**Plugins loaded:**
PdfExport, PopulateDictionary, Printing, CsvExport, JsonExport, JavaScriptHighlighterPlugin, PopulateRandomText, PopulateScript, MultiEditorTextPlugin, MultiEditorDateTimePlugin, DbSqliteSystemData, HtmlExport, RegExpImport, DbPluginSqlite3, CsvImport, ScriptingTcl, XmlExport, DbAndroid, SqlEnterpriseFormatter, SqlExport, PopulateRandom, MultiEditorBoolPlugin, SqliteHighlighterPlugin, PopulateConstant, MultiEditorHexPlugin, MultiEditorNumericPlugin, DbSqlite2, DbSqliteCipher, PopulateSequence, MultiEditorTimePlugin, ScriptingSql, DbSqliteWx, MultiEditorDatePlugin, ScriptingQt, ConfigMigration

**Version:**
3.1.1

**Operating System:**
Windows 7, 64bit
OS:
Windows 7, 64bit
Version:
3.1.1

**Comment by mslavkovski** [comment]
In case of a guid as default value, it is rendered without double quotes and the '-' character is breaking the script.

**Comment by pawelsalawa** [comment]
Duplicate of #3251
