### ISSUE TITLE
Migrate DbAndroid's jar file source code to GitHub.

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3278]
The jar file that is used on Android side to communicate between DbAndroid plugin and Android device was stored in old SVN repo. Source code of it has to be migrated to GitHub and made public again.

**Comment by volodymyr-gz** [comment]
@pawelsalawa Looking forward to it, as I would like to contribute my changes which prevent database version downgrade

**Comment by pawelsalawa** [comment]
https://github.com/pawelsalawa/sqlitestudio-android
