### ISSUE TITLE
View guid data types

### ISSUE THREAD

**Issue by GLeBaTi** [pawelsalawa/sqlitestudio#3286]
### Details
I have a table: PIDValueHistory { Id(Guid), ClientVersion(nvarchar) } 
When i see table data in sqlitestudio, i see no human readable characters.

Screenshot:
[http://ibb.co/ibFpCc](url)
[http://ibb.co/iR5ZdH](url)

### Operating system
Windows 10

### SQLiteStudio version
3.1.1

**Comment by pawelsalawa** [comment]
1. Screenshot links do not work.
2. Regardless of 2, SQLiteStudio shows whatever is in database. If you see no readable characters, it means no readable characters are there in the table. Probably some other application of yours is converting this binary data to some kind of series of characters, but this is up to that application.

Closing, as this is not SQLiteStudio bug. It's a specifics of database usage by other application.

**Comment by GLeBaTi** [comment]
Sorry. Copy and paste link directly to browser address field.
Visual studio sqlite extension show normal guid in view. 
SQLiteStudio convert binnary guid to text. How can i view as binnary in grid view?
Sorry, but registration in sqliteStudio forum is not working (server error 500)

**Comment by pawelsalawa** [comment]
Well, you can write virtually any conversion function you wish and use it with: `SELECT yourFunction(column) ...`.

How to create custom functions in SQLiteStudio: https://github.com/pawelsalawa/sqlitestudio/wiki/User_Manual#custom-sql-functions

Example functions: https://github.com/pawelsalawa/sqlitestudio/wiki/Scripts_repository

If you tell me how Visual Studio decodes these binary values into nice readable strings, I can even try to write such function for you here.

**Comment by GLeBaTi** [comment]
@pawelsalawa 
`SELECT hex(Id) FROM PIDValueHistory` solve my problem. But this is handmade :smirk:
