### ISSUE TITLE
Execution of SQL file

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3292]
### Details
Allow executing huge SQL sets directly from file. In version 2.x.x it used to be a command in right-click context menu on a database.

**Comment by pawelsalawa** [comment]
Related to #3023

**Comment by digocesar** [comment]
There is a night build of release 3.2 that I can try to run scripts of huge files?

**Comment by pawelsalawa** [comment]
No, sorry. This ticket is still open, meaning it's not implemented. Also there are no nightly builds being processed currently. Maybe in future I will enable such builds if I have good platforms for it.
