### ISSUE TITLE
Changing default code asisstant shortcut for OS X

### ISSUE THREAD

**Issue by mrkafk** [pawelsalawa/sqlitestudio#3293]
### Details
Default shortcut for query execution on OS X is `Cmd-Space`.  However, on newer versions of OS X (like El Capitan or later) that shortcut is taken by Spotlight. 

Proposal: change the default to `Ctrl-Space`, with added benefit of making it consistent across platforms and helping SquirrelSQL refugees.

### Operating system
OS X El Capitan.

### SQLiteStudio version
3.1.1

**Comment by pawelsalawa** [comment]
1) Cmd-Space? I believe that query execution shortcut is F9, isn't it?
2) The Cmd-Space is rather for invoking code assistant. Can you confirm?
3) Are you saying that Ctrl-Space is the shortcut that SquirrelSQL uses for their query execution? Or is it for code assistant there?

I guess you are referring to code assistant.
If Spotlight introduces problem here I need to check it. I didn't notice it yet, cause I use very little of MacOS. Perhaps switching to mentioned Ctrl+Space combination will be the best choice.

**Comment by mrkafk** [comment]
@1,2 . Sorry, it was late, you're right of course. I was trying to code-complete table name by using Cmd-Space. Had to change it to Ctrl-Space.

@3. Ctrl-Space in SquirrelSQL is for code completion / code assistant, like completing a name of  table or column.

Spotlight is a problem: https://support.apple.com/kb/PH25624?viewlocale=en_US&locale=en_US

**Comment by pawelsalawa** [comment]
Okay. I guess Ctrl-Space is the most reasonable choice then.
