### ISSUE TITLE
SQLiteStudio 3.1.1 crash: editing database in "(error)" state

### ISSUE THREAD

**Issue by fire-eggs** [pawelsalawa/sqlitestudio#3295]
### Details
Crash when "editing database". Database was "missing".

### Steps to reproduce
(Will use SLS for "SQLiteStudio")
1. Ran SQLiteStudio, added existing database. Viewed tables, if it matters.
1. Closed SLS.
1. In Windows explorer, went to the database location. Renamed the database file.
1. Ran SLS. Database correctly has an "error" marker.
1. Right-clicked on the database entry in SLS. Selected "edit database".
1. SLS crashes.

Ideally, the "edit the database" option should be disabled when the database is in (error) state.

### Operating system
Windows 7.

### SQLiteStudio version
3.1.1

**Comment by pawelsalawa** [comment]
Duplicates #3235
