### ISSUE TITLE
File on https://sqlitestudio.pl is outdated

### ISSUE THREAD

**Issue by drudd75077** [pawelsalawa/sqlitestudio#3297]
### Details
Propose the file on sqlitestudio.pl be updated for fixes that have been made.

### Steps to reproduce
You have several items that appear to be fixed on the issue tracker that look like they'd be really useful. I'm most interested in import functionality improvements.

**Comment by pawelsalawa** [comment]
You can see this issue you mentioned is included in Milestone "3.2", meaning it will be included in version 3.2.0. You can see overview progress of development of version 3.2 here: https://github.com/pawelsalawa/sqlitestudio/milestone/1
