### ISSUE TITLE
Add Configuration Path Alternatives in Documentation

### ISSUE THREAD

**Issue by TehPsychedelic** [pawelsalawa/sqlitestudio#3299]
User Manual mentions this page
https://github.com/pawelsalawa/sqlitestudio/wiki/Configuration_directory_location
But it doesn't exist currently. Tried to do a diff between pages but I didn't find the original one so it may seem as it never existed.

Anyway, I had to check the code and figured out on Win systems if you create a folder
sqlitestudio-cfg 
Inside the App folder and put the settings there, it will work as portable (some of us don't wanna use the PortableApps Platform).
I'm not sure if there are other things to make it portable (e.g if it uses the registry).

But anyway would be good to actually create that page (Configuration_directory_location) in documentation for other users that may wonder the same.

**Comment by pawelsalawa** [comment]
Fixed. Thanks for pointing this out!
