### ISSUE TITLE
interface shown as non-english

### ISSUE THREAD

**Issue by laoshaw** [pawelsalawa/sqlitestudio#3300]
just downloaded the newest release and execute it on ubuntu 16.04 64bit, all interfaces are in non-English I think they look German, how can I get English interface?

**Comment by pawelsalawa** [comment]
Go to ~/.config, there should be file named sqlitestudio
Rename it, or move it away.
Now when you run SQLiteStudio you should be asked for the language you prefer.

**Comment by laoshaw** [comment]
Thanks this fixed it, I must mistakenly have chosen German somehow.
