### ISSUE TITLE
libcrypto.so.1 cannot open shared object file

### ISSUE THREAD

**Issue by laoshaw** [pawelsalawa/sqlitestudio#3301]
### saw error message at the status area

[19:10:20] Cannot load plugin DbSqliteCipher. Error details: Cannot load library /home/test/SQLiteStudio/plugins/libDbSqliteCipher.so: (libcrypto.so.1: cannot open shared object file: No such file or directory)

### Details

I use strace and found all the libcrypto related lines:

<code>
open("./tls/x86_64/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("./tls/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("./x86_64/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("./libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("../tls/x86_64/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("../tls/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("../x86_64/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("../libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("../lib/tls/x86_64/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("../lib/tls/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("../lib/x86_64/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("../lib/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/googie/Qt/5.7/gcc_64/lib/tls/x86_64/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No
such file or directory)
stat("/home/googie/Qt/5.7/gcc_64/lib/tls/x86_64", 0x7fffffd126a0) = -1 ENOENT (No such file or direct
ory)
open("/home/googie/Qt/5.7/gcc_64/lib/tls/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such fi
le or directory)
stat("/home/googie/Qt/5.7/gcc_64/lib/tls", 0x7fffffd126a0) = -1 ENOENT (No such file or directory)
open("/home/googie/Qt/5.7/gcc_64/lib/x86_64/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such
 file or directory)
stat("/home/googie/Qt/5.7/gcc_64/lib/x86_64", 0x7fffffd126a0) = -1 ENOENT (No such file or directory)

open("/home/googie/Qt/5.7/gcc_64/lib/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file o
r directory)
stat("/home/googie/Qt/5.7/gcc_64/lib", 0x7fffffd126a0) = -1 ENOENT (No such file or directory)
open("/home/test/SQLiteStudio/lib/libcrypto.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No suc
h file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 14
</code>

For Ubuntu the libcryto by default is at below but obviously sqlitestudio are not looking into there?

/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0;  /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0

### Steps to reproduce

just launch the program

### Operating system

ubuntu 16.04 64bit

### SQLiteStudio version

3.1.1

**Comment by pawelsalawa** [comment]
You're using a binary from homepage. In that case you need to make libcrypto.so.1 visible to SQLiteStudio.
Make a symlink named libcrypto.so.1 pointing to /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
Put that symlink in a directory where other libraries can be resolved by the system (for example /usr/local/lib ? ) and call "ldconfig" command. Then try to run the app again.

You can also put that symlink in any other directory and use LD_LIBRARY_PATH variable to add it on the fly:

    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/your/custom/directory/with/libcrypto.so.1"
    ./SQLiteStudio

**Comment by laoshaw** [comment]
LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/ ~/downloads/SQLiteStudio/sqlitestudio

This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)

**Comment by laoshaw** [comment]
can't build on ubuntu 16.04 with qt-make 4.x installed either

<code>
./compile.sh 
Is this correct qmake (y/N) /usr/bin/qmake : y
Number of CPU cores to use for compiling (hit enter to use 8): 1
Directory /tmp/aaa/sqlitestudio/output already exists. The script will delete and recreate it. Is that okay? (y/N) : y
cd coreSQLiteStudio/ && /usr/lib/x86_64-linux-gnu/qt4/bin/qmake /tmp/aaa/sqlitestudio/SQLiteStudio3/coreSQLiteStudio/coreSQLiteStudio.pro CONFIG+=portable -o Makefile
/tmp/aaa/sqlitestudio/SQLiteStudio3/coreSQLiteStudio/coreSQLiteStudio.pro:453: Parse Error ('Info.plist')
Error processing project file: /tmp/aaa/sqlitestudio/SQLiteStudio3/coreSQLiteStudio/coreSQLiteStudio.pro
Makefile:34: recipe for target 'coreSQLiteStudio//Makefile' failed
make: *** [coreSQLiteStudio//Makefile] Error 3
cd CsvExport/ && /usr/lib/x86_64-linux-gnu/qt4/bin/qmake /tmp/aaa/sqlitestudio/Plugins/CsvExport/CsvExport.pro CONFIG+=portable -o Makefile
cd CsvExport/ && make -f Makefile 
make[1]: Entering directory '/tmp/aaa/sqlitestudio/output/build/Plugins/CsvExport'
/usr/lib/x86_64-linux-gnu/qt4/bin/uic ../../../../Plugins/CsvExport/CsvExport.ui -o ../../ui_CsvExport.h
make[1]: /usr/lib/x86_64-linux-gnu/qt4/bin/uic: Command not found
Makefile:274: recipe for target '../../ui_CsvExport.h' failed
make[1]: *** [../../ui_CsvExport.h] Error 127
make[1]: Leaving directory '/tmp/aaa/sqlitestudio/output/build/Plugins/CsvExport'
Makefile:55: recipe for target 'sub-CsvExport-make_default' failed
make: *** [sub-CsvExport-make_default] Error 2
</code>

**Comment by pawelsalawa** [comment]
Required Qt version is at least 5.3 - that's if you decide to compile it by yourself.

As for the problems with xcb plugin, see what you will get if you execute:

    ldd ~/downloads/SQLiteStudio/platforms/libqxcb.so

**Comment by laoshaw** [comment]
1. I removed qt4-qmake and installed qt5-qmake, still it's asking for qt4-qmake
<code>
./compile.sh 
Is this correct qmake (y/N) /usr/bin/qmake : y
Number of CPU cores to use for compiling (hit enter to use 8): 4
Directory /home/xxiao/tmp/sql/sqlitestudio/output already exists. The script will delete and recreate it. Is that okay? (y/N) : y
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
make: *** No targets specified and no makefile found.  Stop.
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
make: *** No targets specified and no makefile found.  Stop.
</code>

2. output of ldd ~/downloads/SQLiteStudio/platforms/libqxcb.so
<pre>
	linux-vdso.so.1 =>  (0x00007ffcf91c6000)
	libQt5XcbQpa.so.5 => /home/xxiao/downloads/SQLiteStudio/platforms/../lib/libQt5XcbQpa.so.5 (0x00007f1ac7a36000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f1ac7834000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f1ac7624000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f1ac741c000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f1ac7202000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f1ac6fb6000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f1ac6d94000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f1ac6b51000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f1ac68a7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1ac66a3000)
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007f1ac64a1000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1ac6299000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f1ac5f88000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f1ac5d7e000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f1ac5b6c000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f1ac5832000)
	libEGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa-egl/libEGL.so.1 (0x00007f1ac55f7000)
	libQt5Gui.so.5 => /home/xxiao/downloads/SQLiteStudio/platforms/../lib/libQt5Gui.so.5 (0x00007f1ac4e4f000)
	libQt5DBus.so.5 => /home/xxiao/downloads/SQLiteStudio/platforms/../lib/libQt5DBus.so.5 (0x00007f1ac4bce000)
	libQt5Core.so.5 => /home/xxiao/downloads/SQLiteStudio/platforms/../lib/libQt5Core.so.5 (0x00007f1ac44b3000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f1ac4240000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1ac4023000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1ac3ca1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1ac3998000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1ac3782000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1ac33b8000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f1ac31b3000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f1ac80f3000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f1ac2faf000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f1ac2da9000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f1ac2b80000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1ac2966000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f1ac2741000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1ac7f86000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f1ac24d1000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f1ac22cc000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f1ac20c9000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f1ac1ec6000)
	libxcb-xfixes.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007f1ac1cbe000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f1ac1ab7000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f1ac18b4000)
	libgbm.so.1 => /usr/lib/x86_64-linux-gnu/libgbm.so.1 (0x00007f1ac16a6000)
	libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f1ac1497000)
	libwayland-server.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-server.so.0 (0x00007f1ac1285000)
	libmirclient.so.9 => /usr/lib/x86_64-linux-gnu/libmirclient.so.9 (0x00007f1ac0fde000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f1ac0dcd000)
	libicui18n.so.56 => /home/xxiao/downloads/SQLiteStudio/platforms/../lib/libicui18n.so.56 (0x00007f1ac0933000)
	libicuuc.so.56 => /home/xxiao/downloads/SQLiteStudio/platforms/../lib/libicuuc.so.56 (0x00007f1ac057b000)
	libicudata.so.56 => /home/xxiao/downloads/SQLiteStudio/platforms/../lib/libicudata.so.56 (0x00007f1abeb98000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f1abe968000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f1abe765000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f1abe55f000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f1abe346000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f1abe140000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f1abdf1e000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f1abdcfc000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f1abda1b000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f1abd813000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f1abd5d4000)
	libmircommon.so.7 => /usr/lib/x86_64-linux-gnu/libmircommon.so.7 (0x00007f1abd38d000)
	libmirprotobuf.so.3 => /usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3 (0x00007f1abd11b000)
	libcapnp-0.5.3.so => /usr/lib/x86_64-linux-gnu/libcapnp-0.5.3.so (0x00007f1abce93000)
	libmircore.so.1 => /usr/lib/x86_64-linux-gnu/libmircore.so.1 (0x00007f1abcc8a000)
	libboost_system.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 (0x00007f1abca86000)
	libprotobuf-lite.so.9 => /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9 (0x00007f1abc855000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f1abc641000)
	libboost_filesystem.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0 (0x00007f1abc429000)
	libkj-0.5.3.so => /usr/lib/x86_64-linux-gnu/libkj-0.5.3.so (0x00007f1abc200000)

</pre>

**Comment by pawelsalawa** [comment]
Ad. 2) I don't know why it's failing. Looks fine to me. I cannot help you with that one.

Ad. 1) Find where you have real qmake for your Qt 5. I'm guessing it may be `/usr/lib/x86_64-linux-gnu/qt5/bin/qmake`.

Check what is it's version:

    /usr/lib/x86_64-linux-gnu/qt5/bin/qmake --version

Make sure it's at least 5.3. Then Run compiling script with path to that qmake as a parameter:

    ./compile.sh /usr/lib/x86_64-linux-gnu/qt5/bin/qmake

**Comment by laoshaw** [comment]
Thanks for the helps. ubuntu 16.04 has an aweful installation for qt5 indeed. I will stop here for now.
