### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3303]
### Details
Integrate GitHub repo with one of CI/CD solutions:

- Travis CI
- CircleCI

Both offer Linux & MacOS builds as of now.

**Comment by pawelsalawa** [comment]
Add also Windows builds with ci.appveyor.com (free for opensource). The only problem is it currently supports only MSVC projects, so SQLiteStudio has to either be migrated to MSVC (not a simple task) or ci.appveyor.com will hopefully support MINGW some time soon.

**Comment by rindeal** [comment]
And Linux distro package building could be automatized with [openSUSE Build Service](https://build.opensuse.org/).

**Comment by pawelsalawa** [comment]
It appears that Travis CI supports now also Windows and MacOS X.

**Comment by rindeal** [comment]
I'd wait for Github Actions CI/CD https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/. It should land sometime in November.

**Comment by pawelsalawa** [comment]
That is fantastic news! I would not have time to set up Windows/MacOS until that day anyway, so that should be a good moment to sit down a little bit on it.

I'd love to make it finally all automated, as making 3 platform builds is a hell.

**Comment by pawelsalawa** [comment]
This is now done.
