### ISSUE TITLE
App crashes when opening tables with more than 30000 lines

### ISSUE THREAD

**Issue by uretepzh** [pawelsalawa/sqlitestudio#3305]
### Details
In my database (60MB total size) with various tables: when opening two tables with more than 30000 lines and approx. 70 columns, the app crahses. Larger tables cannot be opened at all.

###Bug report
"not enough resources available"

### Operating system
Windows 10, 64 bit, 16GB RAM, i7-6700 CPU " 3.4GHz

### SQLiteStudio version
SQLite 3.1.1. on c-Drive

**Comment by nishanthkarthik** [comment]
I tried opening the `places.sqlite` file used by firefox in sqlitestudio linux. Mine is about 50MB. The `moz_places` database file has about 100k rows with 15 columns. I was able to view 99999 rows with 15 columns in a single list with my memory usage at 1.2 GB. 

Assuming scaling is linear, 100k * 15 = 1.5m => 1.2 GB. Extrapolating using this,
2 * 30k * 70 = 4.2m => 3.36 GB. According to [msdn](https://blogs.msdn.microsoft.com/tom/2008/04/10/chat-question-memory-limits-for-32-bit-and-64-bit-processes/), running a 32 bit application on Windows 64 bit has an upper limit of 4 GB on memory. So, we are running very close to the limit here.

@pawelsalawa Is it a good idea to start distributing 64 bit builds for Windows in addition to the current 32 bit releases? Are there any constraints that prevent this?

**Comment by pawelsalawa** [comment]
I think that the only constraint is compiler under Windows, being Mingw, which for Qt is provided only in 32-bit version.

I tried once the VC compiler, but I ran to so many problems, that I withdrawn it at that moment, as it requires a lot of effort. If you want you may try and build it with VC compiler (I mean install free Visual C++, then open Qt MaintenanceTool installed together with Qt, install the VC distribution of Qt and VC toolchain for Qt and try to compile project with that Kit under QtCreator).

**Comment by lallulli** [comment]
Could [Mingw-w64](https://wiki.qt.io/MinGW-64-bit) help?

**Comment by pawelsalawa** [comment]
Looks good, but I don't have time to compile entire Qt every time I setup an environment or Qt is upgraded. I barely have time to work on current issues in the project...

I see it in different way - no desktop application should be consuming that much memory. Escpecially not SQLiteStudio, which is aiming to be lightweight.

I will be profiling memory usage to see if there is a major problem to be fixed. If not, then I will take different measures to prevent such problems (i.e. disallow loading this many rows at single page).

I will keep updating this issue with details on my investigation progress.

**Comment by pawelsalawa** [comment]
100k rows with 15 columns gives 1 500 000 cells. For each cell there is a data to be displayed (from few to dozens of bytes), then there are various metadata, like "is the cell pending commit?" or "does it hold truncated value" or "pointer to a column structure that describes this cell", etc. So each of such cells has an overhead + actual data to be displayed.

From my calculations, single cell has weight of around 700 bytes, while most it is occupied by Qt rendering engine of a cell.

To address the problem, I introduced dynamic row limits for tables (apart from normal, configurable limit), so if someone opens table with a lots of columns and has a rows per page limit configured to 99999, then the limit will be overwritten by SQLiteStudio to suitable number and the user will be notified about it in status bar. This way memory consuption for a single table window should never grow over 150MB (more or less).
