### ISSUE TITLE
GridView in Table window not updated if schema changes

### ISSUE THREAD

**Issue by studiofuga** [pawelsalawa/sqlitestudio#3308]
### Details
If the schema of a table changes, even if "refresh schema" is clicked, the GridView in a Table Window isn't updated, though the Structure is. Need to disconnect and reconnect the db.

### Steps to reproduce
Open a table, open a Grid View. Then from outside the app, change the Table schema, adding a field for example. Then on the app, click on Refresh schema (F5). The Structure is updated, the Data view isn't.

### Operating system
Tested on MacOS.

### SQLiteStudio version
v.3.1.1

**Comment by pawelsalawa** [comment]
If you want to refresh grid view (including new columns) hit the Refresh on the GridView tab, not in structure tab.
