### ISSUE TITLE
Import CSV No Name

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3315]
When importing a CSV file, a new table is created, but no name is given to the new table.  I input a name in the first step of the import wizard, but that name only carries through when creating the first table, not in subsequent attempts.  My workaround is to rename the new table and give it a name.

**Plugins loaded:**
DbSqliteCipher, ScriptingQt, PopulateRandom, DbSqliteSystemData, ScriptingTcl, SqlEnterpriseFormatter, DbSqliteWx, MultiEditorDateTimePlugin, PopulateSequence, CsvExport, RegExpImport, MultiEditorTextPlugin, CsvImport, PopulateConstant, MultiEditorBoolPlugin, JsonExport, SqlExport, MultiEditorDatePlugin, ConfigMigration, PopulateDictionary, Printing, PopulateScript, DbSqlite2, PopulateRandomText, MultiEditorTimePlugin, MultiEditorNumericPlugin, HtmlExport, MultiEditorHexPlugin, ScriptingSql, XmlExport, JavaScriptHighlighterPlugin, DbPluginSqlite3, SqliteHighlighterPlugin, PdfExport

**Version:**
3.1.1

**Operating System:**
Windows 10, 64bit
OS:
Windows 10, 64bit
Version:
3.1.1

**Comment by pawelsalawa** [comment]
What do you mean it's created only when creating first table? How many tables are you expecting to be created?

When you import data from CSV, it's imported to a single table which you specified.

Please clarify what table and when exactly it's not created.

**Comment by piotr-lesniak** [comment]
@pawelsalawa 
Let me add what I found for same behavior.
1. In a particular DB, press Import, later press from CSV.
2. Write name of table in Table field and press ENTER (do not click anywhere, just press Enter from your keyboard - that is important).
3. Complete Input file and Press Finish (by clicking on it).

When Import is done, table exist in DB but table name is empty.
V.3.0.6
