### ISSUE TITLE
Could not add database.

### ISSUE THREAD

**Issue by ehinolakingsley** [pawelsalawa/sqlitestudio#3317]
### Details
I try adding a database that is secured with a password.
i was expecting it to ask for password but instead it threw and error Could not add database.
 
### SQLiteStudio version
version 3.

**Comment by pawelsalawa** [comment]
You need to know which encryption engine is used for this particular database. There is several. SQLiteStudio supports few: SQLCipher, wxSQLite and system.data.SQLite. It for example does not support the SSE (paid extension from SQLite developers).

Once you know which method is used and it's supported by SQLiteStudio you should pick proper SQLite engine in your Database edition dialog. There is a dropdown where you can pick SQLite 3, SQLite 2, but also SQLCipher, wxSQLite and (under Windows only) system.data.SQLite.

**Comment by ehinolakingsley** [comment]
Thanks
