### ISSUE TITLE
SQLiteStudio crashed when copy / paste a View

### ISSUE THREAD

**Issue by csanyipal** [pawelsalawa/sqlitestudio#3321]
### Details
I can copy a View, but when Paste it, SQLiteStudio crashed.

### Steps to reproduce
1. Right click with mouse on a _View_name_ in the **Views** tree and choose Copy in the context menu
2. Right click on the **Views** in the **Views** tree with mouse and choose Paste from the context menu
3. SQLiteStudio crashed

### Operating system
Gentoo Linux

### SQLiteStudio version
SQLiteStudio v3.1.1

### BackTrace informations
Application: sqlitestudio (sqlitestudio), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f6528968740 (LWP 12519))]

Thread 5 (Thread 0x7f646e976700 (LWP 12527)):
#0  0x00007f65261d5b93 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f65267007e8 in QWaitCondition::wait(QMutex*, unsigned long) () from /usr/lib64/libQt5Core.so.5
#2  0x00007f65266fd0a0 in ?? () from /usr/lib64/libQt5Core.so.5
#3  0x00007f6526700181 in ?? () from /usr/lib64/libQt5Core.so.5
#4  0x00007f65261ce8b7 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f65255ecccf in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7f648bfff700 (LWP 12523)):
#0  0x00007f65261d9a5d in read () from /lib64/libpthread.so.0
#1  0x00007f6520f31c30 in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007f6520eed2fe in g_main_context_check () from /usr/lib64/libglib-2.0.so.0
#3  0x00007f6520eed7d4 in ?? () from /usr/lib64/libglib-2.0.so.0
#4  0x00007f6520eed94c in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#5  0x00007f65268f0a0b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#6  0x00007f652689ef8a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#7  0x00007f65266fbc63 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#8  0x00007f6526700181 in ?? () from /usr/lib64/libQt5Core.so.5
#9  0x00007f65261ce8b7 in start_thread () from /lib64/libpthread.so.0
#10 0x00007f65255ecccf in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7f65111b2700 (LWP 12522)):
#0  0x00007f65261d5786 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f6524ec5834 in ?? () from /usr/lib64/libQt5Script.so.5
#2  0x00007f6524ec5879 in ?? () from /usr/lib64/libQt5Script.so.5
#3  0x00007f65261ce8b7 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f65255ecccf in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f65119b3700 (LWP 12521)):
#0  0x00007f65255e192d in poll () from /lib64/libc.so.6
#1  0x00007f6520eed836 in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007f6520eed94c in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007f65268f0a0b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007f652689ef8a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007f65266fbc63 in QThread::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x00007f651c6e8505 in ?? () from /usr/lib64/libQt5DBus.so.5
#7  0x00007f6526700181 in ?? () from /usr/lib64/libQt5Core.so.5
#8  0x00007f65261ce8b7 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f65255ecccf in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f6528968740 (LWP 12519)):
[KCrash Handler]
#6  0x00007f6527d4c7b0 in DbTreeModel::dropDbTreeItem(QList<DbTreeItem*> const&, DbTreeItem*, Qt::DropAction, bool&) () from /usr/lib64/libguiSQLiteStudio.so.1
#7  0x00007f6527d4cdbd in DbTreeModel::pasteData(QMimeData const*, int, int, QModelIndex const&, Qt::DropAction, bool*) () from /usr/lib64/libguiSQLiteStudio.so.1
#8  0x00007f6527d53d31 in DbTree::paste() () from /usr/lib64/libguiSQLiteStudio.so.1
#9  0x00007f6527ee1a36 in ?? () from /usr/lib64/libguiSQLiteStudio.so.1
#10 0x00007f65268c8df9 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#11 0x00007f65274e8862 in QAction::triggered(bool) () from /usr/lib64/libQt5Widgets.so.5
#12 0x00007f65274eaee0 in QAction::activate(QAction::ActionEvent) () from /usr/lib64/libQt5Widgets.so.5
#13 0x00007f6527669aca in ?? () from /usr/lib64/libQt5Widgets.so.5
#14 0x00007f6527671024 in ?? () from /usr/lib64/libQt5Widgets.so.5
#15 0x00007f65276720e2 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib64/libQt5Widgets.so.5
#16 0x00007f652752e140 in QWidget::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#17 0x00007f6527674563 in QMenu::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#18 0x00007f65274eee0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#19 0x00007f65274f74b7 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#20 0x00007f65268a024a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#21 0x00007f65274f5bdd in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib64/libQt5Widgets.so.5
#22 0x00007f65275484f6 in ?? () from /usr/lib64/libQt5Widgets.so.5
#23 0x00007f652754aa43 in ?? () from /usr/lib64/libQt5Widgets.so.5
#24 0x00007f65274eee0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#25 0x00007f65274f6671 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#26 0x00007f65268a024a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#27 0x00007f6526debd3b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib64/libQt5Gui.so.5
#28 0x00007f6526ded965 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib64/libQt5Gui.so.5
#29 0x00007f6526dc9e3b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Gui.so.5
#30 0x00007f651cc3afb0 in ?? () from /usr/lib64/libQt5XcbQpa.so.5
#31 0x00007f6520eed637 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#32 0x00007f6520eed8a0 in ?? () from /usr/lib64/libglib-2.0.so.0
#33 0x00007f6520eed94c in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#34 0x00007f65268f09ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#35 0x00007f652689ef8a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#36 0x00007f65268a7514 in QCoreApplication::exec() () from /usr/lib64/libQt5Core.so.5
#37 0x0000564be23ce3eb in ?? ()
#38 0x00007f6525514541 in __libc_start_main () from /lib64/libc.so.6
#39 0x0000564be23ce63a in ?? ()

**Comment by pawelsalawa** [comment]
Duplicates #3171
