### ISSUE TITLE
String interpreted as Number

### ISSUE THREAD

**Issue by dawid2k** [pawelsalawa/sqlitestudio#3327]
### Details
For fields "STRING" and "TEXT" data types string is interpreted as number and SQLite Studio automatically change view of data to exponential notation if there are in string "xx0E" espression..

for example input "120E40" give result "1.2e+42"

Input
![input](https://user-images.githubusercontent.com/39727753/40650308-4828c7e2-6333-11e8-9411-1d0b70c581e6.png)

Result
![result](https://user-images.githubusercontent.com/39727753/40650318-4be039f6-6333-11e8-90e9-0dd98b7abdf6.png)

### Steps to reproduce
Just make a table with "STRING" OR "TEXT" field and try input string including "0E" 

### Operating system
Any..

### SQLiteStudio version
Latest.

**Comment by pawelsalawa** [comment]
Duplicates #3215
