### ISSUE TITLE
Large CSV files (60MB) don't import

### ISSUE THREAD

**Issue by thomasnield** [pawelsalawa/sqlitestudio#3340]
Hi, 

I tried to import one of these large CSV files into SQLiteStudio, and it is churning for a really long time to the point I'm not convinced it's working reasonably. 

http://opendata.toronto.ca/revenue/parking/ticket/parking_tickets_2016.zip

So I had to resort to the command line to import the CSV, and it did so in just a few seconds. 

```shell 
> sqlite3
> .open tom.db
> .mode csv
> .import Parking_Tags_Data_2016_1.csv parking
```

Can we improve the means in which CSV files are imported via SQLiteStudio to match the performance of the plain SQLite3 implementation?

**Comment by pawelsalawa** [comment]
Duplicates #3191
