### ISSUE TITLE
Add support for SDCard-located databases in Android plugin

### ISSUE THREAD

**Issue by NoahNyy** [pawelsalawa/sqlitestudio#3345]
### Details
I create a db in SDCard with `ContextWrapper`, the SqlitesStudio has connect to my device, but i couldnt see the table.
我用`ContextWrapper`创建数据库, 数据库的位置是在 sd 卡里边的, 链接成功之后, 看不到我自己创建的表

**Comment by pawelsalawa** [comment]
Currently only databases built-into the Android application are supported, but this issue report will improve it to allow any database location.

**Comment by NoahNyy** [comment]
Thanks. after reading the source code, I find the method `start` can use a `Context` param. Its useful.

By the way, My English is pool, it is happy that U can understand what I write  =. =

我发现`start`方法可以传一个`Context`参数, 我可以用它连接我想要的数据库, 所以问题解决了,  感谢

**Comment by shaojiankui** [comment]
Override the "SQLiteStudioService.instance().start" argument content databaseList() method

`public class APP extends Application {

    @Override
    public String[] databaseList() {
        String[] databaseList = super.databaseList();
        String[] temp = new String[databaseList.length + 1];
        for (int i = 0; i < databaseList.length; i++) {
            temp[i] = databaseList[i];
        }
        temp[databaseList.length] = FileManager.getRootFilePath() + "pss.db";
        return temp;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        SQLiteStudioService.instance().start(this);
    }`

**Comment by NoahNyy** [comment]
是的啊，你这个阔以哦

**Comment by pawelsalawa** [comment]
Duplicates #3411
