### ISSUE TITLE
Creating Composite Primary Key failed

### ISSUE THREAD

**Issue by csanyipal** [pawelsalawa/sqlitestudio#3351]
### Details
When I attempt to create in the table structure view bellow by clicking the 'Add table primary key' a composite primary key, and select two columns of the table, and click Apply, I get the composite primary key, which contains '&' and '[' and ']' characters which is wrong. So when I want commit this change, I get error message. So, I can't create a composite primary key in SqliteStudio.

### Steps to reproduce
1. In the table structure view bellow click the 'Add table primary key'.
2. There select two table columns out there.
3. Click Apply.
4. Get the wrong code which can be seen on the 'DDL' tab, like this:
```
CREATE TABLE OraRend (
    OrarendNapja      INT,
    HanyadikIskolaOra INT,
    azOsztaly         INT REFERENCES OsztalyEvfTagok (azOsztaly) ON DELETE CASCADE
                                                                 ON UPDATE CASCADE,
    PRIMARY KEY (
        [&OrarendNapja] ASC,
        [&azOsztaly] ASC
    )
    ON CONFLICT ROLLBACK
);
```
5. Commit this change with 'Commit structure changes' button.
6. Get the error message:
[12:12:51] Could not commit table structure. Error message: expressions prohibited in PRIMARY KEY and UNIQUE constraints

### Operating system
Gentoo Linux operating system.

### SQLiteStudio version
SQLiteStudio v3.1.1

**Comment by pawelsalawa** [comment]
Duplicates #3347

**Comment by pawelsalawa** [comment]
A temporary workaround is to switch to different UI theme in SQLiteStudio configuration (Look&Feel -> Style page).
