### ISSUE TITLE
Cannot load plugin DbSqliteCipher.

### ISSUE THREAD

**Issue by thwaller** [pawelsalawa/sqlitestudio#3384]
### Details
Receive this in "status" section:
"[10:24:45] Cannot load plugin DbSqliteCipher. Error details: Cannot load library /home/xxxxxxxx/devel/apps/SQLiteStudio/plugins/libDbSqliteCipher.so: (libcrypto.so.1: cannot open shared object file: No such file or directory)".

### Steps to reproduce
Open SQLiteStudio

### Operating system
Linux - Ubuntu 18.04 MATE

### SQLiteStudio version
v3.1.1

**Comment by pawelsalawa** [comment]
I'm guessing a problem with OpenSSL installation, but let's check for sure. What does this command print:

`ldd /home/brian/devel/apps/SQLiteStudio/plugins/libDbSqliteCipher.so`

**Comment by thwaller** [comment]
`$ ldd /home/brian/devel/apps/SQLiteStudio/plugins/libDbSqliteCipher.so
	linux-vdso.so.1 (0x00007ffc43f28000)
	libcrypto.so.1 => not found
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f288038c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f288016d000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f287fddf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f287fa41000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f287f829000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f287f438000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f287f21b000)
	libicui18n.so.60 => /usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007f287ed7a000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f287e9c3000)
	libdouble-conversion.so.1 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007f287e7b2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f287e5ae000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f287e298000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2880d9e000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f287c6ef000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f287c47d000)
$`

**Comment by pawelsalawa** [comment]
> libcrypto.so.1 => not found

Okay, so now, what does this print:

`locate libcrypto.so`

**Comment by thwaller** [comment]
> $ locate libcrypto.so
/snap/core/4650/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/snap/core/4830/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/snap/core/4917/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/snap/pulsemixer/1/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/snap/pulsemixer/23/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/snap/pulsemixer/8/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/snap/spotify/13/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/snap/spotify/15/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/snap/spotify/16/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/usr/lib/i386-linux-gnu/libcrypto.so.1.1
/usr/lib/x86_64-linux-gnu/libcrypto.so
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
$

**Comment by pawelsalawa** [comment]
Yeah, I was about to suggest this.
