### ISSUE TITLE
Select to view returns false

### ISSUE THREAD

**Issue by Oleg-Motus** [pawelsalawa/sqlitestudio#3386]
### Details
The view request does not work correctly
### Steps to reproduce
Ctalog
https://drive.google.com/drive/folders/1Xpay55HRE4km4r9cG6_MTn6Hoqzv8t9Q?usp=sharing
contains a database view-select-error.db. Open it In SQLiteStudio. Two queries are in the table "Query". The query A is executed with an error, i.e. returns Terminal = 'A'. The query F works correctly, that is, returns Terminal = 'F'. Application aqlite3.exe works correctly for both. 
See demo: select-error.exe.
### Operating system
Windows7 Corp, Service pack 1.

### SQLiteStudio version
v.3.0.6

**Comment by pawelsalawa** [comment]
This is already solved in 3.1.1. Please use more recent version.
