### ISSUE TITLE
Select from two databases not working

### ISSUE THREAD

**Issue by DannyRitiu** [pawelsalawa/sqlitestudio#3387]
### Details
I have created a big select statement with a couple of left joins and where clauses across two databases, and when I tried to run it always gave me the error 'no such table' or 'no such column'.
If I run an SQL statement in one database it is fine, but whenever I tried to run it on two databases, I got an error. Finally, I "exported the results" using the Toolbar in the SQL editor and after this voilá, the statement was runnnig.

### Steps to reproduce
- Create two databases with a couple of tables
- Create an SQL statement using tables from both databases

### Operating system
I'm on Windows 8.1 x64

### SQLiteStudio version
SQLiteStudio 3.1.1
Also: I don't understand: if I want to have the latest bugfixes do I have to compile my own executable? Or can I download it from somewhere.
I don't have the QT Libraries and I am using SQLitestudio as a helper tool. I don't want to bother with compiling its source code.

By the way: great work and thank you for making it available for us!
Cześć!

**Comment by pawelsalawa** [comment]
Can you provide a minimal example (DDL and SQL statements for both databases or database files themself [in that case zipped and attached to a comment below]) that reproduces the problem? For me it's working correctly, so I have to be missing something that you're doing.

As for the other questions:
As the work on version 3.2 is closing in, new release (and binaries) will be provided rather soon. Here's the link to track progress on 3.2 development: https://github.com/pawelsalawa/sqlitestudio/milestone/1

**Comment by DannyRitiu** [comment]
Dear Pawel!

Thanks for the answer!

I have attached you my databases and the SQL query in the zip. Please note that if you copy the "Clients" and "Orders" tables to the "userdb" everything works fine, so there is no problem in the SQL statement. 

However, when these tables are only in "serverdb", I get an error like "no such tables".

In my C++ software everything works fine, by attaching one DB to another, but in SQLiteStudio 3.1.1 sometimes works, sometimes doesn't.
If you can check this, it would be great!

Also: congrats with finalizing version 3.2. 
Where can I download it from? Is a Win32 executable available somewhere?

Thanks again!


[attach.zip](https://github.com/pawelsalawa/sqlitestudio/files/2206623/attach.zip)

**Comment by pawelsalawa** [comment]
It's not released yet. All pending issues have been completed, but now it's going through the "release checklist": https://github.com/pawelsalawa/sqlitestudio/blob/master/release-checklist.md
Currently at step 1.

It will take some time to complete it. Maybe a week, maybe more.


Thanks for the sample database. I will sit down to it and work with it once I have a little time.

**Comment by pawelsalawa** [comment]
Okay, so here's how it goes.

When you execute query that uses 2 databases (one is attached) you always have that other (attached) referred by some name. For example:

```
ATTACH 'file.db' AS other_db;
SELECT * FROM other_db.table_from_other_db;
```

Even in your C++ app you should be referring to tables in attached database by prefixing them with a attach name. Aren't you?

Now, SQLiteStudio makes this a bit simpler for you. Instead of executing "ATTACH" and then any follow up query, you can simply write your query like the database was already attached and the attach name is the same as database name in the list on the left.

Assuming that you have both databases added to SQLiteStudio under names "userdb" and "serverdb", you can open SQL Editor, select "working" database (on editor's toolbar) "serverdb" and then execute query like this:

```
SELECT ORDERS.ID,
       ORDERS.CLIENTID,
       CLIENTS.NAME,
       ITEMS.ID,
       S1.ENGLISH,
       ORDERS.SIZE,
       SIZES.NAME,
       S2.ENGLISH,
       ORDERS.VARIATIONID,
       S3.ENGLISH,
       ORDERS.QUANTITY,
       ORDERS.PRICE,
       ORDERS.STATUS,
       ITEMS.IMAGE
  FROM ORDERS
       LEFT JOIN
       userdb.VARIATIONELEMENTS ON ORDERS.VARIATIONID = VARIATIONELEMENTS.ID
       LEFT JOIN
       userdb.STRINGS S3 ON VARIATIONELEMENTS.NAME = S3.ID,
       CLIENTS,
       userdb.STRINGS S1,
       userdb.ITEMS
       LEFT JOIN
       userdb.SIZES ON ITEMS.SIZETYPE = SIZES.ID
       LEFT JOIN
       userdb.STRINGS S2 ON (CASE WHEN ORDERS.SIZE = 0 THEN '0' WHEN ORDERS.SIZE = 1 THEN S2.ID = SIZES.SIZEXS WHEN ORDERS.SIZE = 2 THEN S2.ID = SIZES.SIZES WHEN ORDERS.SIZE = 3 THEN S2.ID = SIZES.SIZEM WHEN ORDERS.SIZE = 4 THEN S2.ID = SIZES.SIZEL WHEN ORDERS.SIZE = 5 THEN S2.ID = SIZES.SIZEXL ELSE ORDERS.SIZE END) 
 WHERE ORDERS.GROUPID = 10003 AND 
       ITEMS.ID = ORDERS.ITEMID AND 
       CLIENTS.ID = ORDERS.CLIENTID AND 
       S1.ID = ITEMS.NAMESTRING
 ORDER BY ORDERS.CLIENTID
```

SQLiteStudio will transparently attach userdb for you - just for the time of query execution. It will detach it afterwards. It will always attach referred databases when you use their names in the query.

The referred database doesn't even have to be open. It just has to be on the list.

**Comment by DannyRitiu** [comment]
Thanks Pawel, 

It works and I can use it to test my DBs.
For me it wasn't clear when to use the DB prefix and when is not needed.
I tried to prefix all the tables with userdb. or serverdb. but it didn't work.

As I see I only have to prefix the first time I mention the table in the "FROM" section.

The weird things is that sometimes my statement worked in SQLiteStudio without using the prefixes :)
And yes, in my C++ ap I am not prefixing anything and it works :)
Maybe the Universe likes to play games :p

**Comment by pawelsalawa** [comment]
Okay, let me sort it out.

- Yes, prefixing is needed only in FROM clause. Prefixing for each column mentioning would be necessary if both databases had same column names. In that case you would have to tell SQLite how to distinguish which column you're referring to. In your case this is not necessary. You still can prefix them if you want. If you open serverdb.db with sqlite3.exe, then ATTACH userdb.db as "udb", then you can do following: `select * from Groups;`, so without prefixes, but you can also do this: `select * from udb.Groups;` and even this: `select udb.Groups.ID from udb.Groups;`. It all works.
- Yes, in your C++ application it may work without prefixes. That's right. Once you "ATTACH" the database and it does not have conflicting table names, you may skip database prefix. Actually in SQLiteStudio if you execute "ATTACH" first and then the actual query - it will work the same way.
- In SQLiteStudio you can prefix tables, so SQLiteStudio knows that it should attach that database in the first place. You can skip the "ATTACH" and just user database prefix as on the databases list (you don't need to know full path to db file).
- It's just a matter what is more handy to you - to use ATTACH and query, or use db name in FROM clause in the query (in SQLiteStudio that is).
