### ISSUE TITLE
macOS: SQLiteStudio not present on "Open With" file context menu

### ISSUE THREAD

**Issue by marc-medley** [pawelsalawa/sqlitestudio#3388]
### Details
macOS does not currently show `SQLiteStudio` on "Open With" file selection context menu.

### Steps to reproduce
Select and right click on some sqlite file.

![sqlitecontextmenu](https://user-images.githubusercontent.com/15098151/42653700-0d512c94-85cb-11e8-82df-1b34ecf47d4d.png)

### Operating system
macOS High Sierra

### SQLiteStudio version
SQLiteStudio: 3.1.1

### Possible Fix

Add the following to [SQLiteStudio3/coreSQLiteStudio/Info.plist](https://github.com/pawelsalawa/sqlitestudio/blob/master/SQLiteStudio3/coreSQLiteStudio/Info.plist) 

``` xml
<key>CFBundleDocumentTypes</key>
<array>
  <dict>
    <key>CFBundleTypeExtensions</key>
    <array>
      <string>db</string>
      <string>sqlite</string>
      <string>datastore</string>
    </array>
    <key>CFBundleTypeName</key>
    <string>SQLite Database Document</string>
    <key>CFBundleTypeOSTypes</key>
    <array>
      <string>****</string>
    </array>
    <key>CFBundleTypeRole</key>
    <string>Editor</string>
  </dict>
</array>
```

**Comment by marc-medley** [comment]
After some addition research, I think that `db`, `sqlite` and `sqlite3` would be the common file extensions to add. And not `datastore`.

Valentina Studio includes `datastore` in their "info.plist". However, I can not find `datastore` in regular use as an SQLite file extension.

I did the following searches on my own macOS system.

``` bash
sudo find / -name "*.datastore" -print # items found are not SQLite files.
sudo find / -name "*.db" -print        # long list of SQLite files found.
sudo find / -name "*.db3" -print       # no items found.
sudo find / -name "*.sqlite" -print    # long list of SQLite files found.
sudo find / -name "*.sqlite3" -print   # long list of SQLite files found.
```

The *.datastore instances on my system (e.g. com.apple.Notes.datastore) are either a non-SQLite object files or a directory.

So, this issue should be to add `db`, `sqlite` and `sqlite3` file extension pairing.  Not not to add `datastore`.

``` xml
<key>CFBundleTypeExtensions</key>
<array>
  <string>db</string>
  <string>sqlite</string>
  <string>sqlite3</string>
</array>
```

**Comment by pawelsalawa** [comment]
Thanks!

I think I will add a usual file extensions that are available when you "browse for file to open" from SQLiteStudio. After all they _should_ match.

**Comment by marc-medley** [comment]
Ah, yes. The supported SQLiteStudio "browse for file to open" extension list is would be the appropriate extension set to use.
