### ISSUE TITLE
Please consider making a release

### ISSUE THREAD

**Issue by yurivict** [pawelsalawa/sqlitestudio#3389]
It has been a very long time since the last release.

Thank you.

**Comment by pawelsalawa** [comment]
If you look at a completion status for milestone 3.2 (aka version 3.2) you will see that the relase is closing in. Very soon.

https://github.com/pawelsalawa/sqlitestudio/milestone/1

**Comment by emiliano84** [comment]
Hi @pawelsalawa I see that the milestone 3.2 is complete, but I cannot find any release yet. thanks!

**Comment by pawelsalawa** [comment]
Yes, I'm going through the release checklist: https://github.com/pawelsalawa/sqlitestudio/blob/master/release-checklist.md

It will be available soon. In days.

**Comment by emiliano84** [comment]
@pawelsalawa thanks for your reply, as you moved from GitHub I didn't know if couldn't find it, or is not there yet. cheers! :)
