### ISSUE TITLE
[version 3.2.0] MainWindow::messageFromSecondaryInstance can't be found

### ISSUE THREAD

**Issue by yurivict** [pawelsalawa/sqlitestudio#3397]
This link command fails:
```
c++ -Wl,-rpath=/usr/local/lib -L/usr/local/lib -Wl,-rpath,/usr/local/lib -fstack-protector -pthread -Wl,-rpath,/usr/local/lib/qt5 -o ../../output/SQLiteStudio/SQLiteStudio ../../output/build/sqlitestudio/main.o ../../output/build/sqlitestudio/singleapplication.o ../../output/build/sqlitestudio/qrc_sqlitestudio.o ../../output/build/sqlitestudio/moc_singleapplication.o ../../output/build/sqlitestudio/moc_singleapplication_p.o    -L/usr/local/lib -L/usr/ports/databases/sqlitestudio/work/SQLiteStudio3/../output/SQLiteStudio -lcoreSQLiteStudio -lguiSQLiteStudio -L/usr/local/lib/qt5 -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lkvm -lprocstat -lGL  -L/usr/local/lib
../../output/build/sqlitestudio/main.o: In function `main':
main.cpp:(.text+0x1a9e): undefined reference to `serializeToBytes(QVariant const&)'
main.cpp:(.text+0x1dff): undefined reference to `MainWindow::messageFromSecondaryInstance(unsigned int, QByteArray)'
```

This function is present in ```mainwindow.o```:
```
$ nm ./work/output/build/guiSQLiteStudio/mainwindow.o | grep messageFromSecondaryInstance
0000000000006ed0 T _ZN10MainWindow28messageFromSecondaryInstanceEj10QByteArray
```

but this file isn't in the link command.

FreeBSD 11.2

**Comment by pawelsalawa** [comment]
Also - did you do fresh build from clean source code, or did you just upgrade and did incremental build? If second case, try downloading code to fresh directory and build it from there.

**Comment by yurivict** [comment]
It's a fresh build.
Qt is 5.10.1
Compiler is clang-6.0.1

**Comment by pawelsalawa** [comment]
This is weird... Symbol `serializeToBytes` is in coreSQLiteStudio library and `MainWindow::messageFromSecondaryInstance` is in guiSQLiteStudio library. Both are dynamically linked within the very same command that you pasted. This should work and on Ubuntu and MacOS (where it uses clang too) it works just fine.

Any particular flags to qmake or make you passed on?

**Comment by yurivict** [comment]
This is the same problem as happened before: it conflicts with it's own previous version. It builds fine without it.

**Comment by yurivict** [comment]
This linking command line needs ```-L``` to the newly built libraries before ```/usr/local/lib```.

**Comment by pawelsalawa** [comment]
I see. Okay, let this ticket be for tracking implementation of a fix that you just mentioned.

**Comment by pawelsalawa** [comment]
According to per-commit builds (like this https://github.com/pawelsalawa/sqlitestudio/runs/1876233325?check_suite_focus=true) the `/usr/local/lib` (nor `/usr/lib`) is passed to linker.
