### ISSUE TITLE
BUG: Can no longer export schema only

### ISSUE THREAD

**Issue by bpierson** [pawelsalawa/sqlitestudio#3398]
In the new version 3.2.0, even if `Export data from tables` is unchecked, and using the `SQL` output format the data is still exported. There is no way to export schema only. Using Windows 10.

**Comment by bpierson** [comment]
I know this isn't really the place for random comments, but the updater worked great! So much faster to get incremental bug fixes. Thanks for the quick response.

**Comment by pawelsalawa** [comment]
Remember to manuall install the missing plugin (mentioned in the release news). Automatic updater does not cover missing components (added in new versions) as of yet. I will work to make it work this way too.
