### ISSUE TITLE
Error when importing a text file

### ISSUE THREAD

**Issue by niki7s1x** [pawelsalawa/sqlitestudio#3407]
### Details
I tried to import a text file into the .sqlite database with a country info from GeoNames.org (the table's primary key is "geonameid" as it comes from the originator). At the older versions, especially 3.0.0, the operations completes successfully, but at the newer versions it failed. 

### Steps to reproduce
1. Create a .sqlite database with one table "geoname"; the columns are picked up from the http://download.geonames.org/export/dump/readme.txt -> paragraph "The main 'geoname' table has the following fields";
2. Pick up and extract a .zip file with the country info, for example BG.zip;
3. Try to import the extracted file BG.txt into "geoname" with UTF-8 encoding and tab(\t) separated.

### Operating system
Windows 7 Ultimate, 64 bit.

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Try with version 3.2.1. It has a lot of bugfixes, including import-related.

**Comment by niki7s1x** [comment]
Exactly the version 3.0.0 did the import job (with a little text file correction - replacement of the double quotes(") with single ones, probably because the first are SQLite's reserved words, that messed up the import algorithm).

The problem is persistent in the latest version. This is a bug in the newest versions - broken functionality that have to be repaired.

Here are the files to produce the bug:
[SQLiteStudio_ImportError.zip](https://github.com/pawelsalawa/sqlitestudio/files/2256715/SQLiteStudio_ImportError.zip)

**Comment by pawelsalawa** [comment]
Fixed with #3413
