### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3409]
Hello,

I would love to see the option for a dark theme. 
OS:

Version:

**Comment by rindeal** [comment]
SQLiteStudio already has this support as it supports Qt themes so I'm for example using KDE Breeze Dark theme and it works just fine:

![Screenshot_20190906_090431](https://user-images.githubusercontent.com/5360877/64407720-940a5680-d074-11e9-9ca8-41085167dee7.png)

Although this support could be improved by providing two sets of default font colours for better contrast.

**Comment by TRSx80** [comment]
@rindeal,

Could you give a hint as how to accomplish this?

I already have qt5ct running, and `$QT_QPA_PLATFORMTHEME=qt5ct` set, which works fine for other programs (eg., `keepassxc`) however SQLite Studio doesn't seem to respect those settings.

**Comment by rindeal** [comment]
> Could you give a hint as how to accomplish this?
> 
> I already have qt5ct running, and `$QT_QPA_PLATFORMTHEME=qt5ct` set, which works fine for other programs (eg., `keepassxc`) however SQLite Studio doesn't seem to respect those settings.

QT theming is tricky and KDE themes are not really optimized for running outside of KDE so I can just suggest you to install the whole of KDE and then it should "just work".

**Comment by pawelsalawa** [comment]
Just a note. Since recently I returned to active development of the project (after around 4 years of maintenance only), a big item on my list for nearest release (3.2.2) to do are:
- CI/CD for easier & faster releases (100% done) #3303
- **proper theming of SQLiteStudio** (0%) -> this git issue
- removal of automatic updates - only checking for new version availability will be there, to avoid further problems with upgrades (30% done) #3725

Of course there is many more issues in the 3.2.2 milestone to implement, but I consider these to be critical.

**Comment by TRSx80** [comment]
@pawelsalawa,

Very nice to hear!

I really prefer your interface to SQLiteBrowser, even though that is directly available in Debian and respects the system dark theme.  However I end up using that anyway just because I do a lot of work at night and the bright white on my large monitor is not only jarring but it actually will wake up my wife.  :fearful: :smile: 

I just wanted to express to you though how much I appreciate your work and also sharing it.  Other than this issue, I am really enjoying your software! So, thanks! :beers: 

@rindeal,

Yeah I am much too minimalist to install all of KDE just to get my theming right (I run i3wm, etc...).  However thank you for replying so quickly, I do appreciate it!  :beers:

**Comment by pawelsalawa** [comment]
Note for implementation reference: https://github.com/ColinDuquesnoy/QDarkStyleSheet

**Comment by pawelsalawa** [comment]
https://gist.github.com/skyrpex/5547015

**Comment by pawelsalawa** [comment]
https://gist.github.com/QuantumCD/6245215

**Comment by pawelsalawa** [comment]
Dark theme is now added and can be selected in configuration dialog.
By the way of implementation I decided to remove whole configuration tab regarding colors and use theme-based colors. This is to avoid bad contrasting colors when switching between light/dark themes.

You can see preview of the theme on homepage news page https://sqlitestudio.pl/news/

I'm not closing the ticket, as I'd like to do more work on MacOS dark theme.

**Comment by pawelsalawa** [comment]
Detecting dark mode under Windows 10:
```
QSettings settings("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize",QSettings::NativeFormat);
    if (settings.value("AppsUseLightTheme")==0){...}
```

**Comment by pawelsalawa** [comment]
Pending action: to add "mdi area base" color to extra palette and apply it. Currently in dark mode it is way too bright.

**Comment by TRSx80** [comment]
Very nice work!  Thank you for your efforts, Pawel!  They are greatly appreciated!

Cheers!  :beers:
