### ISSUE TITLE
CSV import strongly broken ! application crash !

### ISSUE THREAD

**Issue by ysalmon** [pawelsalawa/sqlitestudio#3418]
[MPSI.csv.txt](https://github.com/pawelsalawa/sqlitestudio/files/2350010/MPSI.csv.txt)
### Details
I cannot import the attached CSV file (real data replaced for anonymity, SQLstudio has same behaviour with real data).

### Steps to reproduce
Import CSV file into table with the following structure
```
CREATE TABLE "etudiants" (
    id     "INTEGER" PRIMARY KEY,
    nom    "TEXT"    NOT NULL,
    prenom "TEXT"    NOT NULL,
    genre  "TEXT"    NOT NULL,
    classe "TEXT"    NOT NULL,
    option "TEXT",
    groupe "TEXT",
    email  "TEXT"
);
```

Importing without "Ignore errors" leads to "UNIQUE constraint failed: etudiant.id". Importing with "Ignore errors" leads to a crash of SQLStudio. Opening the base again shows the record number 10 was read as id 0.

sqlite3 utility and .import functionality work with said CSV file.

### Operating system
KUbuntu 18.04

### SQLiteStudio version
3.2.1

**Comment by kjkrum** [comment]
I was about to enter a duplicate when I found this. I'm getting the same spurious error message when importing a single row CSV into an empty table, on a column that doesn't even have a UNIQUE constraint. The column only has DEFAULT and COLLATE constraints.

**Comment by kjkrum** [comment]
On further investigation, the column _does_ have a UNIQUE constraint, but this is not shown in SQLiteStudio. The real problem in my case was my expectation that I could import a CSV with column headers and have it import into the correct columns.
