### ISSUE TITLE
Internal indexes are not shown

### ISSUE THREAD

**Issue by AlexeiScherbakov** [pawelsalawa/sqlitestudio#3422]
### Details
sqlite sometimes creates automatic internal indexes (for unique columns) with names like 'sqlite_autoindex_TABLE_N'
They are not shown in SQLiteStudio.

see - https://www.sqlite.org/fileformat2.html#intschema

**Comment by pawelsalawa** [comment]
Go to configuration dialog -> Database list -> Select option "Show system tables and indexes".

**Comment by AlexeiScherbakov** [comment]
Yes, I know about this. But this is option only show system tables, but internal indexes are not shown
Sample:

```
CREATE TABLE database_property (
    id    INTEGER PRIMARY KEY AUTOINCREMENT,
    name  TEXT    NOT NULL UNIQUE,
    value TEXT    NOT NULL
);
```
First screen is taken from SQLiteStudio 3.2.1, second from SQLite Maestro
![default](https://user-images.githubusercontent.com/8665915/45690771-c66b2d00-bb5f-11e8-90fe-161ec2f41cc9.JPG)
![2](https://user-images.githubusercontent.com/8665915/45690778-cb2fe100-bb5f-11e8-8f32-9ae708c7bc0f.JPG)

**Comment by AlexeiScherbakov** [comment]
Full SQL for table
```
CREATE TABLE database_property (
  id     integer PRIMARY KEY AUTOINCREMENT,
  name   text NOT NULL,
  value  text NOT NULL,
  /* Keys */
  UNIQUE (name)
);

CREATE INDEX idx_database_property_name
  ON database_property
  (name);
```

**Comment by pawelsalawa** [comment]
You're absolutely right!
