### ISSUE TITLE
ERR on commiting structure changes using 2 words column names

### ISSUE THREAD

**Issue by phototropist** [pawelsalawa/sqlitestudio#3430]
### Details
On the structure tab we modify columns for a table. Usually we tend to define columns by name but when we want to be specific we use at least 2 words on column name. Say we use this cols and the names are compulsory to understand the data inside them: 
ID, Name, Data A, Data B, so in DDL should be: ID, Name, [Data A], [Data B].
Or even better, despite it's not necessary: [ID], [Name], [Data A], [Data B].
Of course it's possible: ID, Name, DataA, DataB but sometimes a space is necessary for clarity and data understanding.

### Steps to reproduce
Having in mind the details above, if I don't force the GUI to use brackets, I get an error everytime I commit structure changes everytime I use a 2 words column name to define a col inside a table.
I have to use brackets inside the column names on table structure tab to tell the program I want to use 2 words to name the column having the column list with ID, Name, [Data A], [Data B] before commiting the changes. 

### Proposal
Surround the column names with brackets programatically, this way the user won't have to force the GUI to do it.

### Operating system
Windows 7

### SQLiteStudio version
Sqlite Studio 3.2.1 or older.

**Comment by warepilot** [comment]
### Details
Column names with special characters like "Id:" or more than one word "test name" yield to error after commiting structure changes. 
### Step to reproduce
Create columns with special characters which may confuse SQLite on parsing SQL statements. Commit changes on structure tab. That's when error raises.
### Workaround
Quotes must be set explicitly on column edition before commit action. And this happens everytime one changes table structure, even if a column "Id:" already exists. It must be explicitly named again between quotes on the name field of column editor.
### Proposal
Let the program take care of quotes on column edition on name capture process, somehow it's not doing it right now, as standar SQL tells. This may be done using always quotes whether column has special characters or not. Of course, if one decided to use "complex" names for columns, should respect complexity on one's custom SQL statments later.
### Versions
3.2.1 on Wine

**Comment by pawelsalawa** [comment]
There must be something you're doing, that I'm not expecting in this flow. When I rename column to "Id:" it works fine. It produces following DDL to be executed (as previewed before executing):

```
PRAGMA foreign_keys = 0;

CREATE TABLE sqlitestudio_temp_table AS SELECT *
                                          FROM test3;

DROP TABLE test3;

CREATE TABLE test3 (
    a     INTEGER,
    [Id:] INTEGER
);

INSERT INTO test3 (
                      a,
                      [Id:]
                  )
                  SELECT a,
                         b
                    FROM sqlitestudio_temp_table;

DROP TABLE sqlitestudio_temp_table;

PRAGMA foreign_keys = 1;
```

What DDL does it produce for you?

**Comment by warepilot** [comment]
No seriously, I'm not kidding. Apparently this is what happend, but should be something specific on my DB's o charsets... I've reached upto utils_sql >= 115: a wrapper is in charge of this issue... Right now this is working perfecly, colum names "Id:", "Object Name", or "Category", whatever... I can't reproduce the error any more...
As for the DDL, it wraps all columns (as it should, and I like) even if they have no complex names.
However, I read this thing the other day [about wrappers and syntax](https://www.sqlite.org/lang_keywords.html).
So now I'm using double quotes for identifiers instead of brackets on my SQL codes.
### Versions
3.2.1 in Wine 1.6 (with error on column names)
3.2.1 in Wine 4.0 (no error on column names)
Wine version is according to my Linux Distro once updated a few days ago.

**Comment by pawelsalawa** [comment]
I cannot fix something if there's no way to reproduce it. Unfortunately.

**Comment by warepilot** [comment]
The DDL wraps all columns (as I think it should, and I like) even if they have no complex names.
It's not about complex column names (like using 2 words), but about [special characters on names](https://github.com/pawelsalawa/sqlitestudio/issues/3628).

**Comment by pawelsalawa** [comment]
Hm. Actually that makes sense.

**Comment by pawelsalawa** [comment]
Duplicates #3628. Discussion & fix will continue there.
