### ISSUE TITLE
Keep column data width after edits

### ISSUE THREAD

**Issue by rhae** [pawelsalawa/sqlitestudio#3437]
### Details
When editing a column in the data view the column width changes to a default width.
#3121 addresses column width between data reloads. However it would be good if the column width would be kept.
I could also image that sqlitestudio saves the column widths persistently and uses the saved values when it is restarted.

### Steps to reproduce
Open a sqlite file.
Open a data view of a table
Change the column width
Click into the column
Press 'Escape' to cancel editing.
The column width changes.

### Operating system
Linux

### SQLiteStudio version
3.2.1

**Comment by BarryInOttawa** [comment]
I had to pop-out the tables panel as a work-around. Dislodged from the main window, it keeps its set width.

**Comment by BarryInOttawa** [comment]
Also the column widths in the table views are all messed up too.

**Comment by pawelsalawa** [comment]
This is resolved now with #4071 and commit 27591b7961f46b30262f0116ca0349dcb37b577f.
