### ISSUE TITLE
Proposal: Add Foreign-Key-Based Editor in Form View

### ISSUE THREAD

**Issue by fitdev** [pawelsalawa/sqlitestudio#3439]
It would be nice to see a kind of drop-down or an alternative editor when editing values in the columns that are foreign keys. Ideally just display a list of rows from the other table of which the currently edited column is a foreign key.

**Comment by pawelsalawa** [comment]
It's already implemented. Which SQLiteStudio version are you using?

**Comment by fitdev** [comment]
I am using the apparently latest 3.2.1 version, Upon closer examination, yes, you are right, I was able to get the feature working. It must have been introduced recently as I just recently updated to 3.2.1. I guess what confused me was that it is not showing up in the Form view, only in the Grid view. So, perhaps you could expose it in the Form view as well.

Also, what about row/column filtering (in case the referenced table is large)? It would be super nice to be able to somehow customize/restrict the generated drop-down, as you can in Access for example. Though I realize that it may not be possible with SQLite, but as an extension to the SQLite Studio, perhaps?

**Comment by pawelsalawa** [comment]
Moved filtering into separate ticket (#4089), as it's a big effort and not necessarily to be done at the same time as exposing FK dropdown to Form View.
