### ISSUE TITLE
Database list collapses to initial size when table is selected

### ISSUE THREAD

**Issue by vorlov-playrix** [pawelsalawa/sqlitestudio#3443]
### Details
Database list collapses to initial size when table is selected. Also table names that are longer than window are displayed with bigger font than names that fit into a window width.
Maybe that's because of High DPI.

### Steps to reproduce
1. Open SQLiteStudio
2. Add database into a list
3. Make database list wider
4. Double-click on any DB table

### Operating system
Windows 8.1 for one language
One screen with resolution 1920x1080

### SQLiteStudio version
3.2.1 for Windows, installable

**Comment by BarryInOttawa** [comment]
Happens to me too. all the time...EXTREMELY FRUSTRATING !

**Comment by BarryInOttawa** [comment]
I had to pop-out the tables panel as a work-around. Dislodged from the main window, it keeps its set width.

**Comment by stnigg** [comment]
Yes I just wanted to report that rather annoying bug. So I see I am not the only one suffering. Fix would be nice :-)

**Comment by pawelsalawa** [comment]
Duplicates #3421
