### ISSUE TITLE
Auto extension

### ISSUE THREAD

**Issue by zezzagio** [pawelsalawa/sqlitestudio#3444]
### Details

I'd like to have some extensions automatically loaded at startup (or anyway available whenever I open a database.)

Something like a dialog with all the parameters of the load_extension() function to be put in a table of the settings database (it's up to the user to write the correct parameters.) At startup all registered extensions would be loaded.

**Comment by pawelsalawa** [comment]
It's already there (in SQLiteStudio 3.2.x). It's called Extension Manager. You can access it rom Tools menu or rom toolbar (a Brick icon).

**Comment by zezzagio** [comment]
I don't how, it managed to escape me.

Sorry, and thank you.
