### ISSUE TITLE
Error when creating trigger from SQL editor

### ISSUE THREAD

**Issue by JustCameToHelp** [pawelsalawa/sqlitestudio#3445]
### Details
When creating a trigger in SQL editor, SQLiteStudio produces an error:

`[11:41:41] Error while executing SQL query on database 'test': incomplete input`

Creating trigger with user interface works OK.

### Steps to reproduce
```
CREATE TABLE foo (
  n INTEGER
);

CREATE TRIGGER trig
         AFTER UPDATE
            ON foo
BEGIN
  DELETE FROM foo
        WHERE n > 100;
END;
```
Note: After running `CREATE TRIGGER` statement, selected text ends before **first** semicolon.

### Operating system
Ubuntu 16.04.5 LTS

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
It's a problem with proper detection of where the CREATE TRIGGER statement ends. If you select manually the whole CREATE TRIGGER until the final END; and then hit execution, it will run fine.

Still, there is an issue with proper detection o whole statement i it's not preselected manually, so this report will be used to track & fix this.

**Comment by phidrho** [comment]
Hi @pawelsalawa I think I found another example where this breaks.
But I cannot share SQL publicly. How can I privately send you the SQL script with example?

**Comment by pawelsalawa** [comment]
Please send it to support@sqlitestudio.pl
