### ISSUE TITLE
Column widths

### ISSUE THREAD

**Issue by BarryInOttawa** [pawelsalawa/sqlitestudio#3447]
### Details
Table columns default to the width of the data, not the column name. It should be the column name. also, double-clicking on the spacer between columns should snap the width to that of the column names.

Look at any database table. The width for the columns is a mess. It should default to the width of the header, not the data. Header names are all cutoff and you don't know what field you're looking at.

### Steps to reproduce
Look at any database table

### Operating system
Windows 10

### SQLiteStudio version
Latest version (I just installed it).

**Comment by pawelsalawa** [comment]
It used to be the way you suggest it, but there was exactly opposite request and it was changed in 3.1 or 3.2 version. I guess we need to make this as a configurable option.

**Comment by JrgMyr** [comment]
"I guess we need to make this as a configurable option."

Or just compute both and take the larger value of the two.

**Comment by pawelsalawa** [comment]
It used to be aligned to whichever was longer, but users requested to shorten columns to fit just data, because apparently it's often case to have a lot of columns with short values and log column names. In that case you're wasting a log of horizonal space and have to scroll for more columns.

Therefore having it configurable should satisfy both groups.

**Comment by pawelsalawa** [comment]
One more thing - if you don't see what is the column due to this problem, you can hold your mouse cursor over your value and you will see a hint with all details, like column name, constraints, etc.

**Comment by pawelsalawa** [comment]
It seems to be deprecated already, as the application behaves as requested in this issue.
