### ISSUE TITLE
Document datetime detection

### ISSUE THREAD

**Issue by jondo** [pawelsalawa/sqlitestudio#3449]
Sqlite [does not](https://www.sqlite.org/datatype3.html#date_and_time_datatype) have a native DATETIME type, however I notice that SqliteStudio correctly lists fields with "YYYY-MM-DD HH:MM:SS" strings as type DATETIME in the table structure. Can you please describe in the user manual how this is done? Is it some content sniffing, as described e.g. in [Python issue 35145](https://bugs.python.org/issue35145)?

**Comment by pawelsalawa** [comment]
I'm not sure what you mean. SQLiteStudio shows whatever type was assigned to a column (when creating table) in the Structure tab.

**Comment by jondo** [comment]
Sqlite databases have [no DATETIME datatype](https://www.sqlite.org/datatype3.html#date_and_time_datatype). How does SQLiteStudio decide which TEXT fields are DATETIME, when newly connecting to a database file?
Is it done by examining whether the values are of the form "YYYY-MM-DD HH:MM:SS"?

**Comment by jondo** [comment]
Here is an example:
The file [SQLiteStudio-3449.zip](https://github.com/pawelsalawa/sqlitestudio/files/2548185/SQLiteStudio-3449.zip) contains a table t with a TEXT column and a DATETIME column, and a single row with the values "2018-11-05 12:20:30" for each. How does SQLiteStudio know the type of the columns? According to the SQLite documentation linked above, this information is not saved in the file.

**Comment by pawelsalawa** [comment]
Table definition (DDL) is:

```
CREATE TABLE t (
    x TEXT,
    y DATETIME
);
```

It clearly stands that the column "y" has datatype DATETIME.

**Comment by jondo** [comment]
You say this DDL is contained in the example file. Is it obtained via the `PRAGMA table_info()` in `SchemaResolver::getColumnsUsingPragma()`? If so, this issue can be closed.

**Comment by pawelsalawa** [comment]
It is obtained by querying sqlite_master table:

    SELECT sql FROM sqlite_master WHERE name = 't';

**Comment by jondo** [comment]
Sorry for reopening, but I have got another example [2017v2-reduced.zip](https://github.com/pawelsalawa/sqlitestudio/files/2552238/2017v2-reduced.zip), where 
`SELECT sql FROM sqlite_master WHERE name = 't';` does not work. How does SQLiteStudio find out about the DATETIME column here?

**Comment by jondo** [comment]
Ah, my fault: the table is called 't2' here, and the query correctly yields `CREATE TABLE t2 (localtime DATETIME DEFAULT NULL, freq VARCHAR (3))`.
