### ISSUE TITLE
escapeCdata: Additional split of substrings "]]>" in CDATA

### ISSUE THREAD

**Issue by aka-sps** [pawelsalawa/sqlitestudio#3452]
See [Plugins/XmlExport/xmlexport.cpp `escapeCdata`](https://github.com/pawelsalawa/sqlitestudio/blob/2b25508ad3d52248d5bd2dcdff1bd1d952577fec/Plugins/XmlExport/xmlexport.cpp#L446).

CDATA ends with "]]>". The substring of `str` "]]>" requires splitting into different `CDATA` to prevent unexpected termination of CDATA.

Thank you for your job!

**Comment by pawelsalawa** [comment]
I agree.

For implementation reference (that is - for me, in future) here is mentioning how it should be properly split:
https://stackoverflow.com/a/33291585/2792256

**Comment by pawelsalawa** [comment]
...and here https://tech.labs.oliverwyman.com/blog/2007/10/25/xml-cdata-and-escaping/
