### ISSUE TITLE
SQL editor - matching parenthesis pairs highlighting dont't work in 3.2.1

### ISSUE THREAD

**Issue by micha06de** [pawelsalawa/sqlitestudio#3453]
### Details
SQL Editor - Parenthesis matching and the syntax highlighting does not work in version 3.2.1

### Operating system
Linux Mint and Window 10 pro

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Fixed as part of #3459.
In the #3459 apart from keyword/function highlighting problem, a desynchronized highlighting was also fixed, which most likely affected this problem here too. Anyway, checked on 3.2.1 - is reproducible, but on 3.3.0 it's not.
