### ISSUE TITLE
In the German translation, tool-Tip texts are incorrectly assigned in the SQL Editor

### ISSUE THREAD

**Issue by micha06de** [pawelsalawa/sqlitestudio#3454]
### Details
In the German translation, tool-Tip texts are incorrectly assigned in the SQL Editor, e.g. "Open file" and "Save as". 

### Operating system
Linux Mint und Windows 10 Pro

### SQLiteStudio version
3.2.1

**Comment by tuffnatty** [comment]
Closed by #5033.

**Comment by pawelsalawa** [comment]
Fix has been cherry-picked to 3.4.
