### ISSUE TITLE
Open second instance of program

### ISSUE THREAD

**Issue by dgrl** [pawelsalawa/sqlitestudio#3456]
### Details
Please make it possible to open de program 2 times or more at the same time
I need to make a comparissing and cant do that in 1 instance

### Steps to reproduce
Open program and try to open it for the second time 
It will not open 

### Operating system
Win 10

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
It used to be possible, but it's not anymore, because some users asked for it. It seems that having it as an option is (obviously) the best way. It will be done.

**Comment by dgrl** [comment]
Many thanks :-)
