### ISSUE TITLE
SQL editor syntax highlighting

### ISSUE THREAD

**Issue by phototropist** [pawelsalawa/sqlitestudio#3459]
### Details
Last time I checked syntax highlighting didn't work for the SQLite function lower() but it does work with replace(). I'm not sure if there are more functions running away from syntax colors, I still haven't used all of them...

### Steps to reproduce
Write an update query:
update [SampleTable] set [aColumn] = lower([aColumn]);
-- I know "[" and "]" are irrelevant when handling one word elements, but I like them better that way.

### Operating system
This was on Win7 

### SQLiteStudio version
3.2.1

**Comment by JrgMyr** [comment]
I am surprised that replace() actually gets highlighted.
None of sum(), count(), min(), max(), first(), last() or random() get highlighted.
Thought that's intentional and functions did not count as "keywords".

**Comment by pawelsalawa** [comment]
It's because REPLACE is a keyword in SQL: https://sqlite.org/lang_replace.html

**Comment by pawelsalawa** [comment]
It's of course a bug to recognize replace() as keyword.
