### ISSUE TITLE
Compiling ERR under Linux

### ISSUE THREAD

**Issue by phototropist** [pawelsalawa/sqlitestudio#3460]
### Details
Errors after make failing to find a Qt Script, but Qt compiled perfectly.

### Steps to reproduce
I followed the compiling guide for automatic compilation but being unable to find `/home/user/projects/sqlitestudio/scripts/linux` or `compile.sh` under source code of version 3.2.1 I encouraged myself to do a manual compilation... I started with `qmake` and the rest of the story is above on the details section.

### Operating system
Just testing a Mint 19 [x32]

### SQLiteStudio version
Version 3.2.1

### Question or proposal
(1) Would it be possible to find a deb package for this version on SQLiteStudio's web or over here?
(2) How difficult would it be to find this version in a Linux repository for an apt-get installation?

(3) New ideas are poping up on my mind about the FormView and about Reports, I wish I could translate them to code for this great application and find some agreements to store the information about this features on the same database. Stars will rise. Regards.

**Comment by pawelsalawa** [comment]
As for Q & Props - I do not make deb packages, because if I wanted to make all packages that users wish, I would have to spend triple time on releases. I also do not track if any debs are made. Perhaps they are, I don't know.

**Comment by phototropist** [comment]
Well, when I posted this issue I was using SqliteStudio sources on its website which wouldn't contain the scripts. Now I've cloned the sources using `git clone` and tried an automatic compilation executing `compile.sh` (available in master sources - I see some duplicities here), but the answer has been "command not found". I'm going to try manual compilation again and send you the details. Of course I'm using the compilation guide you've written link of... I'll be back...

**Comment by phototropist** [comment]
So what do you think of my question (2)? 
Would it be possible to make the packages available (not the .deb necessarily) in a Linux repository for installing them using apt-get or Synaptic?
What about taking this site as a source code central for SqliteStudio and compiling from here the packages for Windows, Linux repositories, and the rest of supported OS's?
(This last question is because I have found content differences (see posts above) between the sources I've downloaded from git and from SqliteStudio Web)

**Comment by pawelsalawa** [comment]
You don't have Qt5Script installed. Installing it should solve the problem.

As for apt-get or Synaptic - it's still something to master and prepare. What do you mean by "compiling from here the packages for Windows, Linux repositories, and the rest of supported OS's"? Where to compile? Do you mean some kind of CI/CD solution? Something like this perhaps: #3303

I'm really surprised that the "scripts" subdirectory got excluded from sourcecode packages. There is certainly a bug in packaging script (added #3462 to track this). Normally it should be there.

**Comment by phototropist** [comment]
Hey there,
So the things that I have installed related to Qt5Script have similar package names libqt5script5 and libqt5scripttools5. On the other hand QMake is version 3.1 under Qt5.9.5 ...
Explicit expression on compiling like `/opt/Qt/5.9.5/bin/qmake` won't work in automatic compiling, actually for some reason, I don't have any Qt data under `/opt` directory. Manual compiling keeps answering with the same ERR (something not found - what is explained in the posts above)

**Comment by pawelsalawa** [comment]
The libqt5script5 package seems right.

Please re-do `qmake ../../SQLiteStudio3`, then `make` and let me know if you're still getting this `Project ERROR: Unknown module(s) in QT: script`

**Comment by phototropist** [comment]
Actually `qmake does` not give an answer now, everything when allrigt? Maybe because the file `.qmake.stash` was already exists... and yeah, the same ERR on `make`. I'll delete it and retry...

**Comment by pawelsalawa** [comment]
`qmake` did not give any error earlier. It was na info.

What does this tell you? `find / -name "libQt5Script.so" -print`

**Comment by phototropist** [comment]
OK, so I've found that file... What folder should I put in? And how do I work now to compile?

**Comment by pawelsalawa** [comment]
If you found the file, question is why is your `qmake` not seeing it? Do you have several Qt versions installed?

**Comment by pawelsalawa** [comment]
...and why not using Linux binary from SQLiteStudio homepage?

**Comment by pawelsalawa** [comment]
Oh, I see now. It's 32-bit Linux. That make's sense.
Well, sorry, but I'm unable to help you, since it's a Mint issue. I'm not an expert here.

**Comment by phototropist** [comment]
Fresh news! I almost conclude the manual compilation under Linux after stumbling with [https://packages.ubuntu.com/](https://packages.ubuntu.com/) when I was trying to make another one.

The thing is I've found the dang `libQt5Script.so` inside `qtscript5-dev` that I didn't have installed... Once installed with the package manager I executed `make`... and hey, this was different... but I had more errors on lacking packages related to `uitools` and `svg` as compiler said... So I went to the same source and did another search for files inside packages... I had to install absent packages like `libqtscript4-uitools, qttools5-dev, libqt5svg5-dev, libqtscript4-svg`... I guess this version 4 packages weren't necessary (haven't tested) but they were also listed as having the necessary files.

In my last attempt, I tried a `make install` instead of `make` only and everything was going OK until this:

**Comment by pawelsalawa** [comment]
You need to install readline-dev or somethine like that. It's a development headers for readline package. It may also be called libreadline-dev or something like that.

**Comment by phototropist** [comment]
OK, the package is `libreadline-dev` actually and with that installed I have no errors until...
```
collect2: error: ld returned 1 exit status
Makefile:294: recipe for target '../../SQLiteStudio/sqlitestudiocli' failed
make[1]: *** [../../SQLiteStudio/sqlitestudiocli] Error 1
make[1]: going outside directory '/home/sqlitestudio/output/build/sqlitestudiocli'
Makefile:109: recipe for target 'sub-sqlitestudiocli-install_subtargets' failed
make: *** [sub-sqlitestudiocli-install_subtargets] Error 2
```
By the way SqliteStudio seems to be working under Wine. The only problems I've found are:
(1) it crashes importing data
(2) I can't use diacritical marks of my language (but this has to do with Wine itself I guess)

**Comment by phototropist** [comment]
OK, I post here a summary of the whole process. I'm assuming every g++ it's a different compiling line.
```
[qmake and make OK over here]
[...]
g++ -c -pipe -pedantic -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DSYS_PLUGINS_DIR=/usr/lib/sqlitestudio -DCORESQLITESTUDIO_LIBRARY -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../SQLiteStudio3/coreSQLiteStudio -I. -I../../../SQLiteStudio3/coreSQLiteStudio -I../../../SQLiteStudio3/guiSQLiteStudio -I/home/myuser/sqlitestudio/SQLiteStudio3/../output/build/guiSQLiteStudio -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtScript -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o ./keywords.o ../../../SQLiteStudio3/coreSQLiteStudio/parser/keywords.cpp
g++ -c -pipe -pedantic -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DSYS_PLUGINS_DIR=/usr/lib/sqlitestudio -DCORESQLITESTUDIO_LIBRARY -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../SQLiteStudio3/coreSQLiteStudio -I. -I../../../SQLiteStudio3/coreSQLiteStudio -I../../../SQLiteStudio3/guiSQLiteStudio -I/home/myuser/sqlitestudio/SQLiteStudio3/../output/build/guiSQLiteStudio -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtScript -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o ./utils_sql.o ../../../SQLiteStudio3/coreSQLiteStudio/common/utils_sql.cpp
../../../SQLiteStudio3/coreSQLiteStudio/common/utils_sql.cpp: In function ‘QStringList valueListToSqlList(const QVariantList&, Dialect)’:
../../../SQLiteStudio3/coreSQLiteStudio/common/utils_sql.cpp:820:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
                 if (dialect == Dialect::Sqlite3) // version 2 will go to the regular string processing
                 ^~
../../../SQLiteStudio3/coreSQLiteStudio/common/utils_sql.cpp:826:13: note: here
             default:
             ^~~~~~~
g++ -c -pipe -pedantic -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DSYS_PLUGINS_DIR=/usr/lib/sqlitestudio -DCORESQLITESTUDIO_LIBRARY -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../SQLiteStudio3/coreSQLiteStudio -I. -I../../../SQLiteStudio3/coreSQLiteStudio -I../../../SQLiteStudio3/guiSQLiteStudio -I/home/myuser/sqlitestudio/SQLiteStudio3/../output/build/guiSQLiteStudio -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtScript -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o ./token.o ../../../SQLiteStudio3/coreSQLiteStudio/parser/token.cpp
[...]
[All OK over here]
[...]
g++ -c -pipe -pedantic -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DSYS_PLUGINS_DIR=/usr/lib/sqlitestudio -DCORESQLITESTUDIO_LIBRARY -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../SQLiteStudio3/coreSQLiteStudio -I. -I../../../SQLiteStudio3/coreSQLiteStudio -I../../../SQLiteStudio3/guiSQLiteStudio -I/home/myuser/sqlitestudio/SQLiteStudio3/../output/build/guiSQLiteStudio -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtScript -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o ./BigInt.o ../../../SQLiteStudio3/coreSQLiteStudio/rsa/BigInt.cpp
../../../SQLiteStudio3/coreSQLiteStudio/rsa/BigInt.cpp: In copy constructor ‘BigInt::BigInt(const BigInt&)’:
../../../SQLiteStudio3/coreSQLiteStudio/rsa/BigInt.cpp:569:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if (length <= digitCount + 2 || length > (digitCount << 2))
     ^~
../../../SQLiteStudio3/coreSQLiteStudio/rsa/BigInt.cpp:571:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  try
  ^~~
../../../SQLiteStudio3/coreSQLiteStudio/rsa/BigInt.cpp: In function ‘std::ostream& operator<<(std::ostream&, const BigInt&)’:
../../../SQLiteStudio3/coreSQLiteStudio/rsa/BigInt.cpp:632:5: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
     for (int i = number.digitCount - 1; i >= 0; i--)
     ^~~
../../../SQLiteStudio3/coreSQLiteStudio/rsa/BigInt.cpp:635:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
  return cout;
  ^~~~~~
g++ -c -pipe -pedantic -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DSYS_PLUGINS_DIR=/usr/lib/sqlitestudio -DCORESQLITESTUDIO_LIBRARY -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../SQLiteStudio3/coreSQLiteStudio -I. -I../../../SQLiteStudio3/coreSQLiteStudio -I../../../SQLiteStudio3/guiSQLiteStudio -I/home/myuser/sqlitestudio/SQLiteStudio3/../output/build/guiSQLiteStudio -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtScript -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o ./Key.o ../../../SQLiteStudio3/coreSQLiteStudio/rsa/Key.cpp
[...]
[All OK over here]
[...]
g++ -c -pipe -pedantic -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_CORE_LIB -I../../../SQLiteStudio3/sqlitestudiocli -I. -I../../../SQLiteStudio3/coreSQLiteStudio -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o ./moc_clicommandtree.o moc_clicommandtree.cpp
/usr/lib/qt5/bin/moc -DQT_NO_DEBUG -DQT_CORE_LIB --include /home/myuser/sqlitestudio/SQLiteStudio3/../output/build/sqlitestudiocli/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/myuser/sqlitestudio/SQLiteStudio3/sqlitestudiocli -I/home/myuser/sqlitestudio/SQLiteStudio3/coreSQLiteStudio -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/7 -I/usr/include/i386-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/i686-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/7/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include ../../../SQLiteStudio3/sqlitestudiocli/commands/clicommanddesc.h -o moc_clicommanddesc.cpp
g++ -c -pipe -pedantic -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_CORE_LIB -I../../../SQLiteStudio3/sqlitestudiocli -I. -I../../../SQLiteStudio3/coreSQLiteStudio -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o ./moc_clicommanddesc.o moc_clicommanddesc.cpp
g++ -Wl,-O1 -o ../../SQLiteStudio/sqlitestudiocli ./main.o ./cli.o ./clicommand.o ./clicommandfactory.o ./clicommandadd.o ./clicommandremove.o ./clicommandexit.o ./clicommanddblist.o ./clicommanduse.o ./clicommandopen.o ./clicommandclose.o ./clicommandsql.o ./clicommandexecutor.o ./cli_config.o ./clicommandhelp.o ./cliutils.o ./clicommandtables.o ./climsghandler.o ./clicommandmode.o ./clicommandnullvalue.o ./clicommandhistory.o ./clicommanddir.o ./clicommandpwd.o ./clicommandcd.o ./clicommandsyntax.o ./clicommandtree.o ./clicompleter.o ./clicommanddesc.o ./qrc_sqlitestudiocli.o ./moc_cli.o ./moc_clicommand.o ./moc_clicommandadd.o ./moc_clicommandremove.o ./moc_clicommandexit.o ./moc_clicommanddblist.o ./moc_clicommanduse.o ./moc_clicommandopen.o ./moc_clicommandclose.o ./moc_clicommandsql.o ./moc_clicommandexecutor.o ./moc_clicommandhelp.o ./moc_clicommandtables.o ./moc_clicommandmode.o ./moc_clicommandnullvalue.o ./moc_clicommandhistory.o ./moc_clicommanddir.o ./moc_clicommandpwd.o ./moc_clicommandcd.o ./moc_clicommandtree.o ./moc_clicommanddesc.o   -L/home/myuser/sqlitestudio/SQLiteStudio3/../output/SQLiteStudio -lcoreSQLiteStudio -lreadline -lcurses -lQt5Core -lpthread 
/usr/bin/ld: no se puede encontrar -lcurses
collect2: error: ld returned 1 exit status
Makefile:294: recipe for target '../../SQLiteStudio/sqlitestudiocli' failed
make[1]: *** [../../SQLiteStudio/sqlitestudiocli] Error 1
make[1]: se sale del directorio '/home/myuser/sqlitestudio/output/build/sqlitestudiocli'
Makefile:97: recipe for target 'sub-sqlitestudiocli-make_first' failed
make: *** [sub-sqlitestudiocli-make_first] Error 2
```

**Comment by pawelsalawa** [comment]
You don't have ncurses library. You need to install it. I'm not sure how exactly it's called on Mint, but it will be something similar to:

    sudo apt-get install ncurses-dev

If no, please look up in the internet for correct package.

**Comment by phototropist** [comment]
Apparently, packages are `libcunit1-ncurses-dev` and `libghc-ncurses-dev` along with their dependencies, but after installing and a `make` I've only got:
```
cd coreSQLiteStudio/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/myuser/sqlitestudio/SQLiteStudio3/coreSQLiteStudio/coreSQLiteStudio.pro ) && make -f Makefile 
make[1]: entering directory '/home/myuser/sqlitestudio/output/build/coreSQLiteStudio'
make[1]: nothing done for 'first'.
make[1]: going outside directory '/home/myuser/sqlitestudio/output/build/coreSQLiteStudio'
cd guiSQLiteStudio/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/myuser/sqlitestudio/SQLiteStudio3/guiSQLiteStudio/guiSQLiteStudio.pro ) && make -f Makefile 
make[1]: entering directory '/home/myuser/sqlitestudio/output/build/guiSQLiteStudio'
make[1]: nothing done for 'first'.
make[1]: going outside directory '/home/myuser/sqlitestudio/output/build/guiSQLiteStudio'
cd sqlitestudiocli/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/myuser/sqlitestudio/SQLiteStudio3/sqlitestudiocli/sqlitestudiocli.pro ) && make -f Makefile 
make[1]: entering directory '/home/myuser/sqlitestudio/output/build/sqlitestudiocli'
make[1]: nothing done for 'first'.
make[1]: going outside directory '/home/myuser/sqlitestudio/output/build/sqlitestudiocli'
cd sqlitestudio/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/myuser/sqlitestudio/SQLiteStudio3/sqlitestudio/sqlitestudio.pro ) && make -f Makefile 
make[1]: entering directory '/home/myuser/sqlitestudio/output/build/sqlitestudio'
make[1]: nothing done for 'first'.
make[1]: going outside directory '/home/myuser/sqlitestudio/output/build/sqlitestudio'
```
It seems it was better before `ncurses`. I don't know what's wrong. Let's give it a try some other week.

**Comment by pawelsalawa** [comment]
Looks like everything went okay, it's built and there is nothing more to do.

Yes, SU is required only when doing `make install`. Try it out and see if it installs working application. You can always execute `make uninstall` from the same directory (of sourcecode).

**Comment by phototropist** [comment]
**Compilation and installation SUCCESS!** So no more procrastinate. I thought the thing was wrong after seeing so few lines, but now I'm thinking that everything was done from before, that's why so few lines (I guess). It seemed to remain this last step.
So `sudo make install` from `build` directory does the work. I had to put a launcher manually on programming or developing menu group but that's all. The command for the launcher is just `sqlitestudio`.
It's seems to work properly. I haven't tested everything though.
I can say the ERR is SOLVED. Thanks for your support.
