### ISSUE TITLE
Can get data twice without disconnect

### ISSUE THREAD

**Issue by draco961** [pawelsalawa/sqlitestudio#3461]
### Details
Can get data twice without disconnect

### Steps to reproduce
I am connected to my android phone with Android Sqlite plugin, when I update a data on the phone, I refresh my table in SQLiteStudio and i get the updated data, if I do it again and refresh the data, I can't get the data, I must disconnect and reconnect to get it

### Operating system
Windows 10
### SQLiteStudio version
SQLiteStudio 3.2.1 and 3.1.0

**Comment by pawelsalawa** [comment]
This is no longer relevant, as Android plugin is now decomissioned. There are tools build into Android's IDEs that serve similar purpose, but likely better.

**Comment by pawelsalawa** [comment]
Reopened in attempt to still maintain the plugin.

**Comment by pawelsalawa** [comment]
The reason for this bug may be related to #3967
