### ISSUE TITLE
Crash when click in cell

### ISSUE THREAD

**Issue by JajaComp** [pawelsalawa/sqlitestudio#3464]
### Details
The application closes instantly
[base.db3.zip](https://github.com/pawelsalawa/sqlitestudio/files/2632773/base.db3.zip)

### Steps to reproduce
Open DB. Open table "songs" -> "data" -> "Click on any "style_id" with NULL value

### Operating system
Gentoo latest

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Confirmed. Thanks!

This is a problem (probably introduced recently) with initial null value of a FK column. Will be fixed.
