### ISSUE TITLE
Bug importing csv - values changed during import

### ISSUE THREAD

**Issue by ik8sqi** [pawelsalawa/sqlitestudio#3467]
### Details
Import the file attached. There are no errors reported, but the data is being changed during the import. Look for example at the line in the .csv:
2999998464,3000000511,2017370,2017370,,0,0

after importing, that line is not present in the database. You have instead dropped the first digit "2" resulting in this modified record being imported:
999998464,3000000511,2017370,2017370,,0,0

The issue only occurs when importing the .csv as a whole - hundreds of thousands of rows are imported with incorrect values. If instead I try to import a .csv containing only that one single line with the 2999998464, it gets imported correctly.

### Steps to reproduce
Import this .csv into a sqlite database.

### Operating system
macOS Mojave 10.14.1

### SQLiteStudio version
3.2.1

[geoip.zip](https://github.com/pawelsalawa/sqlitestudio/files/2649427/geoip.zip)

**Comment by K6TD** [comment]
I have observed the same problem.  Specifically, the first character of the first field was truncated. .sqlite imported the .csv file fine. V3.2.1

**Comment by carljoseph** [comment]
I'm also having the same issues. Doesn't matter if I try to surrounding the first value in quotes or not

**Comment by pawelsalawa** [comment]
Fixed with #3413
