### ISSUE TITLE
Extension Manager Application Crashed

### ISSUE THREAD

**Issue by sonerb** [pawelsalawa/sqlitestudio#3469]
### Details
Application crashed when extension manager events.

### Steps to reproduce
Open **Extension Manager**

1. Tools -> Open Extension Manager or Toolbar -> Open Extension Manager.
2. Click to **add new extension**
3. Do not select to **extension file** and click to **remove selected extension**
4. (Another way) Do not select to **extension file** and click to empty extension list on left side.
5. Application crashed.

### Operating system
Windows 10 x64 (1709)

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
This appears to be already fixed (by the way of some other bugfix) in 3.2.2 branch.
