### ISSUE TITLE
ROW NUMBER not working

### ISSUE THREAD

**Issue by Dragtsu** [pawelsalawa/sqlitestudio#3473]
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment]
What do you mean it's not working? What are you doing and what do you expect to happen?

**Comment by dkontyko** [comment]
Not sure if this was OP's problem, but I also have a bug relating to rowid. In the FOREIGN KEY drop-down menu, I cannot select the rowid of another table to use as a foreign key.

Steps to reproduce:
1. Create and commit Table A. (Has automatic rowid; I did not add any rowid column manually)
2. Create Table B.
3. Open the Add Column pop-up for Table B.
4. Select the checkbox for Foreign Key and click Configure.
5. Select Table A in the Foreign Table drop-down.
6. Open the Foreign column drop-down menu. Rowid is not listed.


OS: MacOS 10.14.2

SQLite Studio Version: 3.2.1

**Comment by Nordes** [comment]
The feature exists from the version 3.25 and the version 3.24 is the one which is packaged with the SQLite Studio.

Ref.: https://stackoverflow.com/a/53027073/80527
```
UPDATE: sqlite3 version 3.25 now supports window functions including:

row_number() over(order by id)

SQLITE3 Documentation => https://www.sqlite.org/windowfunctions.html
```

**Comment by pawelsalawa** [comment]
Duplicates #3471
