### ISSUE TITLE
data view Right-click,program exit

### ISSUE THREAD

**Issue by NingShenTian** [pawelsalawa/sqlitestudio#3474]
### Details
In data tab,open data view Right-click，program exit。
![2018-12-17 10-04-50](https://user-images.githubusercontent.com/14068570/50062738-c244bf00-01e3-11e9-8c5a-e535e67228c3.png)

### Operating system
Ubuntu 18.10

### SQLiteStudio version
V3.2.1

**Comment by pawelsalawa** [comment]
NOTE: This happens only if you have empty table.

**Comment by pawelsalawa** [comment]
Appears to be fixed with one of previously fixed bugs for 3.2.2. No longer happens in 3.2.2 branch.
