### ISSUE TITLE
Export full database to XML: tags not correct

### ISSUE THREAD

**Issue by gleversluis** [pawelsalawa/sqlitestudio#3479]
### Details
When creating an XML export of a full database, the following tags should be added or updated:
- tables should be enclosed in <tables></tables> tags
- indices should be enclosed in <indices></indices> tags
- triggers should be enclosed in <triggers></triggers> tags
- within each trigger, there are tags <database></database> which seem to be unneeded
- within each trigger, the table is enclosed in <table><table>. The latter is missing the / so it's not recognized as a closing tag.

### Steps to reproduce
- Open a database
- Click Tools - Export
- Select "A database" and click Next
- Select tables; to reproduce the entire problem, include at least one table with triggers. Other than that the selection does not matter.
- Click Next
- Choose Export Format XML, output File and enter a filename. I used UTF-8 encoding but that is not relevant to reproduce the issue.
- Click Finish

In the attached file, the <database></database> tags are in line 142 and the non-closing <table> tag is in line 150.

### Operating system
Windows 10

### SQLiteStudio version
3.2.1
[test2.zip](https://github.com/pawelsalawa/sqlitestudio/files/2709111/test2.zip)

**Comment by pawelsalawa** [comment]
Regarding "enclosed tags" - it is not really necessary to have `<tables>` enclosing `<table>`.
Having repeated elements of different kind at same level is still valid XML. You can see this for better understanding: https://stackoverflow.com/questions/25027180/xml-repeating-elements-is-this-valid

As for the missing "/" - yes, it is a bug and will be fixed within this ticket.
