### ISSUE TITLE
DbSqlite2 fails to build

### ISSUE THREAD

**Issue by yurivict** [pawelsalawa/sqlitestudio#3480]
In the FreeBSD port, I tried to add ```DbSqlite2``` along with other options (that build fine), and ```DbSqlite2``` fails:
```
gmake[2]: *** No rule to make target 'Makefile'.  Stop.
gmake[2]: Leaving directory '/usr/ports/databases/sqlitestudio/work/Plugins/DbSqlite2'
```
There is no ```Makefile``` there.

**Comment by pawelsalawa** [comment]
It's really hard for me to tell you why, as you're not building it according to official instructions and I don't know what was executed prior to this, what is directory structure (where are compilation results, where are sources, etc).

**Comment by yurivict** [comment]
Packaging systems always build within their own framework, but in this case it is straightforward: sources are unpacked into ```/usr/ports/databases/sqlitestudio/work```, then it executes:
```
cd /usr/ports/databases/sqlitestudio/work/SQLiteStudio3 && \
QT_SELECT=qt5 QMAKEMODULES="/usr/ports/databases/sqlitestudio/work/SQLiteStudio3/mkspecs/modules:/usr/local/lib/qt5/mkspecs/modules" OPENSSLBASE=/usr/local OPENSSLDIR=/usr/local/openssl OPENSSLINC=/usr/local/include OPENSSLLIB=/usr/local/lib OPENSSLRPATH=/usr/local/lib XDG_DATA_HOME=/usr/ports/databases/sqlitestudio/work  XDG_CONFIG_HOME=/usr/ports/databases/sqlitestudio/work  HOME=/usr/ports/databases/sqlitestudio/work PATH=/usr/ports/databases/sqlitestudio/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer -I/usr/local/include"  LDFLAGS=" -Wl,-rpath=/usr/local/lib -L/usr/local/lib -Wl,-rpath,/usr/local/lib -fstack-protector " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing  -fno-omit-frame-pointer  -I/usr/ports/databases/sqlitestudio/work/SQLiteStudio3/coreSQLiteStudio -std=c++11 "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" \
gmake INSTALL_ROOT=/usr/ports/databases/sqlitestudio/work/stage
```
and this breaks when ```DbSqlite2``` (that I am just now trying to add) is enabled, but not for any other options.

**Comment by pawelsalawa** [comment]
It looks like this sourcecode distribution is somehow preprocessed, so that gmake works without qmake being invoked prior to it. Normally (when compiling from sources available here, on github) you need to exec qmake first, than make (or gmake).

It looks like just someone who preprocessed this sourcecode package made some mistake with DbSqlite2. I don't even know what are these options you're mentioning, because in official sourcecode there are no such "options".

**Comment by yurivict** [comment]
I'm sorry, I forgot to mention that qmake is also called before gmake:
```
cd /usr/ports/databases/sqlitestudio/work/SQLiteStudio3 && \
/usr/bin/env MAKE=gmake QT_SELECT=qt5 QMAKEMODULES="/usr/ports/databases/sqlitestudio/work/SQLiteStudio3/mkspecs/modules:/usr/local/lib/qt5/mkspecs/modules" QTDIR="/usr/local/lib/qt5" QMAKE="/usr/local/lib/qt5/bin/qmake"  MOC="/usr/local/lib/qt5/bin/moc" RCC="/usr/local/lib/qt5/bin/rcc" UIC="/usr/local/lib/qt5/bin/uic"  QMAKESPEC="/usr/local/lib/qt5/mkspecs/freebsd-$(ccver="$(c++ --version)"; case "$ccver" in *clang*) echo clang ;; *) echo g++ ;; esac)" XDG_DATA_HOME=/usr/ports/databases/sqlitestudio/work  XDG_CONFIG_HOME=/usr/ports/databases/sqlitestudio/work  HOME=/usr/ports/databases/sqlitestudio/work PATH=/usr/ports/databases/sqlitestudio/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin SHELL=/bin/sh CONFIG_SHELL=/bin/sh /usr/local/lib/qt5/bin/qmake -spec /usr/local/lib/qt5/mkspecs/freebsd-$(ccver="$(c++ --version)"; case "$ccver" in *clang*) echo clang ;; *) echo g++ ;; esac)  QMAKE_CC="cc" QMAKE_CXX="c++"  QMAKE_LINK_C="cc" QMAKE_LINK_C_SHLIB="cc"  QMAKE_LINK="c++" QMAKE_LINK_SHLIB="c++"  QMAKE_CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing "  QMAKE_CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing  -fno-omit-frame-pointer  -I/usr/ports/databases/sqlitestudio/work/SQLiteStudio3/coreSQLiteStudio -std=c++11 "  QMAKE_LFLAGS=" -Wl,-rpath=/usr/local/lib -L/usr/local/lib -Wl,-rpath,/usr/local/lib -fstack-protector "  QMAKE_LIBS=""  QMAKE_CFLAGS_DEBUG=""  QMAKE_CFLAGS_RELEASE=""  QMAKE_CXXFLAGS_DEBUG=""  QMAKE_CXXFLAGS_RELEASE=""  PREFIX="/usr/local" CONFIG+="release"  CONFIG-="debug separate_debug_info" -recursive     
```

**Comment by pawelsalawa** [comment]
Okay, we need slightly different information.

Your commands above look more or less okay, but they are actually dedicated for compiling SQLiteStudio itself and not plugins. Plugins are compiled later, thus there has to be another qmake & gmake call for /usr/ports/databases/sqlitestudio/work/Plugins - is there?

If yes, please also have a look at /usr/ports/databases/sqlitestudio/work/Plugins/Plugins.pro - does it contain DbSqlite2? Compare it to https://github.com/pawelsalawa/sqlitestudio/blob/master/Plugins/Plugins.pro

If these directories/files of sourcecode stay in your system and you can manually do something with them, please also try executing qmake manually (in /usr/ports/databases/sqlitestudio/work/Plugins/ ) and see what it says when you do it (it may say nothing). Does it create a Makefile for DbSqlite2 subdirectory?

**Comment by yurivict** [comment]
For each plugin, it does:
```
cd /usr/ports/databases/sqlitestudio/work/Plugins/${plugin} &&\
/usr/bin/env QT_SELECT=qt5 QMAKEMODULES="/usr/ports/databases/sqlitestudio/work/SQLiteStudio3/mkspecs/modules:/usr/local/lib/qt5/mkspecs/modules" OPENSSLBASE=/usr/local OPENSSLDIR=/usr/local/openssl OPENSSLINC=/usr/local/include OPENSSLLIB=/usr/local/lib OPENSSLRPATH=/usr/local/lib XDG_DATA_HOME=/usr/ports/databases/sqlitestudio/work  XDG_CONFIG_HOME=/usr/ports/databases/sqlitestudio/work  HOME=/usr/ports/databases/sqlitestudio/work PATH=/usr/ports/databases/sqlitestudio/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer -I/usr/local/include"  LDFLAGS=" -Wl,-rpath=/usr/local/lib -L/usr/local/lib -Wl,-rpath,/usr/local/lib -fstack-protector " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing  -fno-omit-frame-pointer  -I/usr/ports/databases/sqlitestudio/work/SQLiteStudio3/coreSQLiteStudio -std=c++11 "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" gmake -f Makefile -j8 all
```

**Comment by pawelsalawa** [comment]
1. If yes, please also have a look at /usr/ports/databases/sqlitestudio/work/Plugins/Plugins.pro - does it contain DbSqlite2? Compare it to https://github.com/pawelsalawa/sqlitestudio/blob/master/Plugins/Plugins.pro

2. Was the qmake executed for this particular plugin? Or atleast for Plugins/ directory? The command you pasted above does only the gmake.

**Comment by yurivict** [comment]
It does execute qmake too. The port is too complex, I can't post all commands from it.

But it treats every plugin exactly the same way as every other pluginm by the list, and SqLite2 is the only one that fails.

**Comment by pawelsalawa** [comment]
Well, I can say the same from the other side - all plugins are built the same way and it works if you do it manually, so to me it looks like a bug in the port script, or something.

Still, I'm allowing an idea that maybe it's some mistake in the project's file, but there is no other way than debugging steps executed by the port, because only there it is reproducible. I cannot tell anything about problem that doesn't appear to me.

Please forgive me, but I'm not going to setup FreeBSD virtual machine and learn how to use fbsd ports just to debug this one case ;)

You have answered question no. 2. How about question 1 from my previous post?

Question 3 - are you able to execute any commands just after the port script is finished? I mean to enter this directory where qmake for SQLite2 plugin was (supposedly) executed and to re-execute it again, manually?

**Comment by yurivict** [comment]
I can't reproduce it now, it builds okay. Not sure what was wrong the first time when I tried.

Thank you for your help!
