### ISSUE TITLE
Inability to display View data as View changes committed to the database are being ignored by the application

### ISSUE THREAD

**Issue by Grod56** [pawelsalawa/sqlitestudio#3482]
### Details
Upon completing modifications to my query and committing the changes, the commit button (the green tick button) is still enabled and I am unable to view the View data

### Steps to reproduce
Problem seems to be spontaneous as it is affecting some Views and not others

### Operating system
Microsoft Windows 10 Pro 64 bit

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Perhaps there is an error in the query? Isn't there any error message down in the messages area?

**Comment by pawelsalawa** [comment]
Closing due to lack of feedback from author for long time.
