### ISSUE TITLE
Compatibility with SQLCipher 4

### ISSUE THREAD

**Issue by cokeperez** [pawelsalawa/sqlitestudio#3494]
Hi,

I'm trying to open a ciphered database with SQLCipher 4.x and I can't.

SQLCipher 4.x has new default page size (4096 bytes) and KDF iteration count (256,000), but not even changing them is possible to connect.

Is it possible to add support for SQLCipher 4.x?

Thanks!

**Comment by ed-george** [comment]
Agreed, this would be a massive help - @pawelsalawa if there's something I can do to help here let me know

**Comment by wlodek** [comment]
Are there any chances for the version compatible with SQLCipher 4 ?
The tool SqliteStudio is the best - but it can not open Cipher 4 db.

**Comment by pawelsalawa** [comment]
I don't mind someone creating patch or pull request for this. I simply don't have (yet) time for this.

**Comment by pawelsalawa** [comment]
Covered with #3470
