### ISSUE TITLE
incorrect sqlite syntax for composite primary key

### ISSUE THREAD

**Issue by K6TD** [pawelsalawa/sqlitestudio#3500]
### Details
Sqlite seems to require an attribute style syntax for creating a composite (multi-column) primary key.  Here is the syntax generated:

```
...
CREATE TABLE xxxx (
    PN            TEXT    REFERENCESitem_master (PN)
    mfg_ID            INTEGER NOT NULL
                              DEFAULT (48) 
                              REFERENCES manufacturer_ID (ID) 
                              PRIMARY KEY,
    [mfg name]        TEXT,
    [mfg part number] TEXT    PRIMARY KEY,
);
...
PRAGMA foreign_keys = 1;
```

SQlite supports:
```
...
CREATE TABLE...

PRIMARY (PN, [mfg part number])

};
```

### Steps to reproduce
from the table structure view, select two columns to be primary key.

### Operating system
macOS 10.14.3 (Mojave)

### SQLiteStudio version
V3.2.1

**Comment by pawelsalawa** [comment]
Instead of marking two columns as primary key, you should create normal (not PK) columns and then on the bottom of Structure tab there is frame for table's global constraints, where you can create PK for multiple columns.

This way you will generate proper DDL.

I will keep this issue to track a change, where SQLiteStudio will not allow you yo select 2 columns as PK and will instruct you to do this the way I just described above.

**Comment by pawelsalawa** [comment]
Just investigated this issue. SQLiteStudio alread (in version 3.2.1) makes it impossible to design table with two primary keys separately per column. I'm not sure how did you generate this code. If you try to add second PK column, this is what you will see (disabled PK option):

![image](https://user-images.githubusercontent.com/481846/81450506-df847f80-9182-11ea-83a1-803c12bfeaa2.png)

The way to go with 2-columns (or more) PK is to add primary key in bottom panel:
![image](https://user-images.githubusercontent.com/481846/81450614-165a9580-9183-11ea-862b-e69999faf114.png)
...and that results in proper composite PK statement for SQLite.

I'm closing this now, as it is not valid or not reproducible. If I'm wrong, please comment on it, describing how do you reproduce it and how do you skip disabled option.
