### ISSUE TITLE
There should be a Debian package (in the default repositories)

### ISSUE THREAD

**Issue by jondo** [pawelsalawa/sqlitestudio#3501]
I suggest releasing as Debian packages and getting them included in the Debian repositories (like [SQLitebrowser](https://sqlitebrowser.org/)).
I would prefer this to running directly downloaded binaries or self-made installation scripts.

**Comment by pawelsalawa** [comment]
Are you willing to prepare and maintain such packages? :)

**Comment by jondo** [comment]
Maybe after I have tested SQLitebrowser ;-)

**Comment by jondo** [comment]
Never mind, SQLitebrowser works fine for me.
