### ISSUE TITLE
Show Query Executed

### ISSUE THREAD

**Issue by lavanyadeepak** [pawelsalawa/sqlitestudio#3504]
When a query is executed  by SqliteStudio from designer say after changing the db structure it just shows the status as below

[15:14:11] Committed changes for table 'AppConfig' successfully.

It would be great if Sqlite could also show the generated query for this operation.

**Comment by lavanyadeepak** [comment]
Tools --> DDL History right?

Thanks for the pointer. If that gives me the raw SQL queries I am ok with that. Precisely this is what I was looking for to see what queries it generates. Because when moving the file to production system we may not be able to install the tool. We can only a sql editor as part of our application and type these ourselves.

Thanks and Regards,

Deepak Kumar Vasudevan
Software Architect
t: +91 94454 07856 **
m: +91 83907 50796 **
e: deepak.vasudevan@outlook.com


www.lavanyadeepak.tk<http://www.lavanyadeepak.tk/>
[twitter icon]<https://twitter.com/lavanyadeepak> [facebook icon] <https://www.facebook.com/ld.lavanyadeepak>  [linkedin icon] <https://www.linkedin.com/in/lavanyadeepak>

 **  We have Zero-Tolerance for Unsolicited Commercial Communication (UCC)


________________________________

**Comment by pawelsalawa** [comment]
No, I thought rather about Configuration -> General -> Don't show DDL preview dialog when committing schema changes

This option should be disabled (so the preview is displayed).

DDL history is also helpful, indeed.

**Comment by lavanyadeepak** [comment]
Hi,

Thank you. Precisely this is what I I was looking for.

[cid:e46bf6ad-34bf-4cef-bf9d-f2bf420ef98a]

Thanks and Regards,

Deepak Vasudevan

________________________________
