### ISSUE TITLE
Uninstaller deletes all files in install folder (not only files owned by SQLiteStudio)

### ISSUE THREAD

**Issue by lallulli** [pawelsalawa/sqlitestudio#3506]
### Details
This issue has been reported by a student of mine. By mistake, she installed SQLiteStudio in `D:\`, i.e. in the root of `D:` unit, where she had other files too (such as pictures and documents). She then uninstalled SQLiteStudio using the uninstaller, and the whole content of `D:` was gone.

### Operating system
MS Windows

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Reported to Qt IFW bugtracker: https://bugreports.qt.io/browse/QTIFW-1318
I'll keep this one here open, until it's resolved in IFW and the fixed version of IFW is used with SQLiteStudio release.

**Comment by pawelsalawa** [comment]
Qt devs have answered as follows:

Installer will give warning about the situation which user has accepted:

> "You have selected an existing, non-empty directory for installation. Note that it will be  completelywiped on uninstallation of this application. It is not advisable to install into this directory asinstallation might fail. Do you want to continue?"

They closed the ticked as something that won't be fixed, because they don't consider this an issue. User is warned and confirms the decision.
