### ISSUE TITLE
Sqlite Compare

### ISSUE THREAD

**Issue by lavanyadeepak** [pawelsalawa/sqlitestudio#3510]
I have a suggestion that when you right click the database node, if it could compare with another database (schema and/or data) it would be a value addition to the product.   We do have similar products in open source here https://www.codeproject.com/Articles/220018/SQLite-Compare-Utility
and it would be good if a similar closest matching one is onboarded into SqliteStudio itself.

**Comment by pawelsalawa** [comment]
Duplicates #3357
