### ISSUE TITLE
Generate Database Scripts

### ISSUE THREAD

**Issue by lavanyadeepak** [pawelsalawa/sqlitestudio#3511]
I have a suggestion to see when you right click the database node if there is a way to generate scripts for all the tables and views (similar to sql server management studio) it would be real value addition to the product.

**Comment by pawelsalawa** [comment]
In SQLite you can get it by: `SELECT sql FROM sqlite_master;`

**Comment by pawelsalawa** [comment]
You can also export a database (right click on a database -> export), have all elements selected and the have "export data" checkbox unselected.
