### ISSUE TITLE
Adding a password ...

### ISSUE THREAD

**Issue by lavanyadeepak** [pawelsalawa/sqlitestudio#3512]
I believe starting with sqlite 3 there is password support. Is there a way Sqlite can add a support for this feature of the database?

**Comment by pawelsalawa** [comment]
It's not quite like that. SQLite3 provides API for implementing encryption (thus password protection). There are several solutions implementing the encryption. SQLiteStudio already supports couple of them (SQLCipher, wxSQLite and System.Data.SQLite). To use it you need to pick proper database driver when creating/opening a database file.
