### ISSUE TITLE
Configurable value quoting in CsvImport plugin

### ISSUE THREAD

**Issue by tomrivera** [pawelsalawa/sqlitestudio#3515]
### Details
Needs a way to change import text qualifier from (") to null or other symbols... like DB browser has ;)

**Comment by pawelsalawa** [comment]
I don't know how DB browser has it. Can you explain a little bit more about what you mean?

Perhaps an example would be helpful with understanding it.

**Comment by tomrivera** [comment]
when you import data from a csv file if there is a (") in the data to be imported it will treat all the data from the first ( " ) to the next one it finds as a single field. for example if you have:
ITEM,BRAND,DESCRIPTION,PRICE
1,BRAND1,1 " WOOD ANCHOR,1.00
2,BRAND1,1/2 " WOOD ANCHOR,.95
3,BRAND2,ANGRY BIRDS,5,00

on the import table you will have something like:
ITEM - BRAND       -    DESCRIPTION                                                - PRICE
1       - BRAND1     - 1 " WOOD ANCHOR,1.002,BRAND1,1/2 "        - .95 
3       - BRAND2     - ANGRY BIRDS                                                   - 5.00

**Comment by tomrivera** [comment]
After looking at the code you might need to check if the csvimport plugin from salsoft used if it has a way of changing or selecting or setting the text qualifier on the import config or something along those lines...

**Comment by pawelsalawa** [comment]
Well, this is according to CSV standard that " quotes a value. According to this standard if you want to have a quote character (") explicitly in a value, escape it with repeating it, so instead of:

    1,BRAND1,1 " WOOD ANCHOR,1.00

you would have

    1,BRAND1,1 "" WOOD ANCHOR,1.00

That's about standard. Now, the possibility to override it as you mentioned may be a good idea, so I will keep this issue open and implement it when possible.

P.S. The "SalSoft" company is my company ;) I wrote the plugin.

**Comment by ar-jan** [comment]
I just wanted to ask the same, it would be a nice feature!

**Comment by tomrivera** [comment]
Before any other comment I will like to thank you for your fast responses and your work with the program. It has a very nice and clean interface, the best feature I have to say is having views. I am making a python program to audit some files against a master file. It converts a binary file to ascii and then loads it to a SQLITE db, then takes the master file in CSV format and also loads it to the db, where then I can work some SQL magic to do the auditing. And long story short I was using your program to cut some corners and view how the DB file was looking, then I saw all the nice features it has, so now I am using it as inspiration to finish mine.  So again thank you for your hard work... 

ps I knew you were SalSoft I was just being my funny self... ;)

**Comment by BR-dev0** [comment]
I've just seen you changed the title of this issue to
> Configurable value quoting in CsvImport plugin

Hopefully, this will include a setting for "no char is used to quote text".    ;-)

I just tried to import the tab-delimitted IMDB files (https://datasets.imdbws.com), which omitted several entries from title.akas and title.principals without error message. Reason is the same as encountred by tomrivera: Quotation marks are interpreted as quote characters, although all strings in these files are to be considered unquoted.

Here is an excerpt of the data causing the erroneous import:
[IMDB_Title_akas_Error.csv](https://github.com/pawelsalawa/sqlitestudio/files/7493193/IMDB_Title_akas_Error.csv)

Apart from such minor inconveniences, your program has always been working well and was a handy way to deal with SQLite databases. Therefore: Thank you very much for your great work!!

**Comment by pawelsalawa** [comment]
Added option:
![image](https://user-images.githubusercontent.com/481846/198895932-d5a07bd4-e816-4689-bde6-e424b1ce35e1.png)

**Comment by pawelsalawa** [comment]
Verified with provided example CSV file and works as expected.

**Comment by BR-dev0** [comment]
> Verified with provided example CSV file and works as expected.

I just did the annual import of the complete IMDB files. SQLiteStudio v3.4.1 finished without errors and correct number of imported rows for each table. So, tweaking the import files isn't necessary, anymore. 

Thank you very much for the added setting!!   :-)
