### ISSUE TITLE
editing table column name is not successful

### ISSUE THREAD

**Issue by phihh** [pawelsalawa/sqlitestudio#3517]
### Details

I want to edit a column name in a table .
### Steps to reproduce

Right click a column name in the table -> modify the column name into another.  I pressed the ok button but it failed to update the column name.
![image](https://user-images.githubusercontent.com/19286863/56080089-1dec2580-5e2f-11e9-90e0-8782df24606e.png)

 The commit button didn't appear to be able to click.

After a first attempt, I want to perfrom the same action again. Editing name the same column just didn't prompt out the action dialog.
### Operating system
Windows 10

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Once you clicked "Ok" you will have "Commit" (or "Rollback") button available in the table window, like here:

![image](https://user-images.githubusercontent.com/481846/56084763-f8174e80-5e37-11e9-9bd3-799785caa2e0.png)

**Comment by phihh** [comment]
> Once you clicked "Ok" you will have "Commit" (or "Rollback") button available in the table window, like here:
> 
> ![image](https://user-images.githubusercontent.com/481846/56084763-f8174e80-5e37-11e9-9bd3-799785caa2e0.png)

thanks a lot . it works again.
