### ISSUE TITLE
Databases view's column width not persisted.

### ISSUE THREAD

**Issue by rmawatson** [pawelsalawa/sqlitestudio#3518]
### Details
It seems that if the left Databases view has been expanded by dragging the column divider, after opening and closing a database this resets the Databases view's column width. It would be nice if this was persisted, or not reset.
![image](https://user-images.githubusercontent.com/5624991/56231371-94329700-607e-11e9-8c1d-34d1c0318aa5.png)

### Steps to reproduce
connect to and disconnect from a database.

### Operating system
Windows 10

### SQLiteStudio version
v3.2.1

**Comment by loupalladino** [comment]
This issue happens to me also with 3.2.1 on Linux when executing a SQL query (either by pressing the run button or hitting F9) or when switching between window panes (say a SQL editor and an edit table pane).  I'm using PeppermintOS 9, based off Ubuntu 18, I believe.  The vertical column resets itself to the default size/location.

**Comment by pawelsalawa** [comment]
Duplicates #3421
