### ISSUE TITLE
Import data misses first character of the first field

### ISSUE THREAD

**Issue by fdmenendez** [pawelsalawa/sqlitestudio#3520]
### Details
When importing CSV data, the fist character of the first column gets lost for all records
For example a date will be imported like 019-04-18
it does not affect the header

### Steps to reproduce
Import data from CSV default parameters

### Operating system
Windows 10

### SQLiteStudio version
sqlite-tools-win32-x86-3270200

**Comment by mrgchr** [comment]
IMHO, `sqlite-tools`'s behavior is not a issue of this app but I tried to reproduce with `sqlite-tools-win32-x86-3280000`.
As a reuslut, I cannot reproduce an issue you mentioned in my local env(SQLiteStudio v3.2.1).

I've tried following 4 encoding csv files(zipped file attached):

[foobar_csv.zip](https://github.com/pawelsalawa/sqlitestudio/files/3096895/foobar_csv.zip)

1. UTF-8 with BOM/CRLF
1. UTF-8 with BOM/LF
1. UTF-8 without BOM/CRLF
1. UTF-8 without BOM/LF

```
sqlite> .open Sample.sqlite
sqlite> .mode csv
sqlite> .import foobar_CRLFwBOM.csv foobar_CRLFwBOM
sqlite> .import foobar_LFwBOM.csv foobar_LFwBOM
sqlite> .import foobar_CRLF.csv foobar_CRLF
sqlite> .import foobar_LF.csv foobar_LF
sqlite> .quit
```

the import sqlite3 database looks fine in SQLiteStudio(v3.2.1).
![image](https://user-images.githubusercontent.com/27002895/56403760-dede2a00-629d-11e9-9795-c59879f4e398.png)

Would you provide more detailed info such as file encoding, new line character and sqlite script with executed in sqlite-tool ?

**Comment by mrgchr** [comment]
Now, I think I reproduce the issue you mentioned with SQLiteStudio Import Wizard(not `sqlite-tools`).

When CSV file with `LF` new line character, first character will be dropped. 

![image](https://user-images.githubusercontent.com/27002895/56410945-f9260100-62b9-11e9-87f9-aeeea3966a47.png)

![image](https://user-images.githubusercontent.com/27002895/56411007-2a063600-62ba-11e9-8e4f-c7b9269e4294.png)

This issue might be avoided by using csv file with `CRLF` new line.

**Comment by fdmenendez** [comment]
hi
Yes, you are right, that seems to be the problem, my files end with LF. Thanks for finding it out!

btw, is there a way to solve it? i can go ahead and change my files but it would be nice to be able to import regardless the new line encoding.

**Comment by mrgchr** [comment]
Hi @pawelsalawa , @fdmenendez 

How do you see this behavior?
IMPO, some options, like "new line character" combo box in "Data source option" in wizard might be preferable.

**Comment by pawelsalawa** [comment]
As far as I remember this should be handled automatically (any kind of new line separator should be supported - Windows/Linux/Mac). It looks like a bug and need to investigate where it happens.

**Comment by davecampbell** [comment]
i just ran across this bug / condition - glad it is formally recognized here.
my use-case:
made a 'report' from a monitoring tool (logicmonitor), specifying 'csv' as output.  no other parameters were offered (such as newline character).
when i used this file as the import source - it dropped the first character of the first field in every record.
can confirm that the line-endings are LF, not CRLF.
`l$ head device-inventory-all-details-20190614181741.csv | cat -e
Device,hardwaremodel,ips,model,hostname,categories,sysinfo,groups,displayname$
1st Floor MDF,,"169.254.17.12,169.254.17.13,169.254.17.11,10.10.0.138,10.255.4.227",,10.10.0.138,"snmp,snmpTCPUDP",Ruckus Wireless Inc (C) 2006 ,appriss-net/Wireless,1st Floor MDF$
ls-idf1-1-18,,"10.10.0.246,169.254.17.12,169.254.17.13,169.254.17.11,10.255.4.216",,10.10.0.246,"snmp,snmpTCPUDP",Ruckus Wireless Inc (C) 2006 ,appriss-net/Wireless,ls-idf1-1-18$
ls-idf1-1-20,,"10.255.4.221,10.10.0.247,169.254.17.12,169.254.17.13,169.254.17.11",,10.10.0.247,"snmp,snmpTCPUDP",Ruckus Wireless Inc (C) 2006 ,appriss-net/Wireless,ls-idf1-1-20$`

can confirm that re-importing after running 'unix2dos' on the file did work CORRECTLY.

i also vote that the import should handle both newline sequences identically.

**Comment by hurricanescout** [comment]
I was having the same issue (first char dropped on csv import). I was able to remedy by first opening the database file BEFORE importing the CSV. If I only imported the CSV it would drop the first char. but by first creating the sqlite file, then opening it, then following @mrgchr I was able to successfully import including first char.

**Comment by davecampbell** [comment]
wow - i can't believe i see my name in this issue from 18 months ago!  i just hit this BUG again.
this time - an export from pgadmin and then simple import using Sqlitestudio.

the comment from @hurricanescout about "opening" the database file before importing did not work for me or i don't understand what 'opening a database file' means.  like 'connected'?  isn't the database 'open' when you do an import?  i know it is 'connected'.

i think this is a big miss in the product - a simple check for the line termination sequence is pretty standard stuff.

i see it is on the next milestone - i hope you have a chance to fit this in soon.

i can always run the 'unix2dos' on the CSVs before importing, as i did before.

**Comment by Drinkler** [comment]
I ran in the same problem. On windows you can easily change the eol encoding with notepad++. From the "Edit" menu, select "EOL Conversion" -> "Windows (CR + LF)". After that I could import my csv file without any cut of characters.
