### ISSUE TITLE
Adding Terminal Support

### ISSUE THREAD

**Issue by richierh** [pawelsalawa/sqlitestudio#3521]
### Details
I would like to have sqlitestudio with Local Terminal (on Linux) support. Because I need it to use sqlitestudio alongside with schemacrawler to see ERD / Schema  of my database.

**Comment by pawelsalawa** [comment]
Do you mean the sqlitestudiocli command (that is already there)?

**Comment by pawelsalawa** [comment]
Not clarified. Still not clear = not valid.
