### ISSUE TITLE
Fail to start on windows server 2008

### ISSUE THREAD

**Issue by maumad** [pawelsalawa/sqlitestudio#3523]
### Details
On start presents the following message : This application failed to start because it could not find or load the Qt platform plugin "windows" in "".
Available paltform plugins are: "windows"
Reinstalling the application may fix this problem.

### Steps to reproduce
Install in windows server 2008 standart without Hyper-V as admin.
Run as admin.
Portable equal.

### Operating system
windows server 2008 standart without Hyper-V SP2 32bit

### SQLiteStudio version
V3.2.1

**Comment by pawelsalawa** [comment]
Did you download the installer from sqlitestudio.pl or from somewhere else?

**Comment by maumad** [comment]
Hi Pawel,
Thank you by the rapid answer. 
I download it from sqlitestudio.pl.

Best regards and congratulations for the great work.

**Comment by pawelsalawa** [comment]
You're emphasising "whithout Hyper-V" - is this essential? If you enable Hyper-V, then does it work?

**Comment by maumad** [comment]
'Whithout Hyper-V' is the windows version.
Meaning doesnt have the Hyper-V service available.

**Comment by pawelsalawa** [comment]
If you go into installation directory of SQLiteStudio, there should be directory called platforms. In that directory there should be file named "windows.dll" or somehow silmilar.

Is it there?

**Comment by maumad** [comment]
confirmed

**Comment by maumad** [comment]
It seems that the program doesnt recognize windows server 2008 as a windows OS.

**Comment by pawelsalawa** [comment]
I think Windows 2008 is no longer supported by Qt 5.3 (just like Windows XP is not supported either) and that's why you have this error.

**Comment by maumad** [comment]
It can be that case.
What is the older program version that runs on XP?

**Comment by pawelsalawa** [comment]
It's hard to tell that from top of my head. It will be quicker if you try out last version of 3.1 series and 3.0 series. Here are links:

https://sqlitestudio.pl/files/sqlitestudio3/complete/win32/sqlitestudio-3.1.1.zip
https://sqlitestudio.pl/files/sqlitestudio3/complete/win32/sqlitestudio-3.0.7.zip

**Comment by maumad** [comment]
version 3.1.1 running ok.
Thank you very much for the support.

Best regards
