### ISSUE TITLE
SIGSEGV on Addition of JOIN to existing query

### ISSUE THREAD

**Issue by SilverNexus** [pawelsalawa/sqlitestudio#3525]
### Details
If you load an existing query into the SQL Editor, say to make a view similar to one you already have, and then try to add a join to an existing subquery by typing it in where it goes in the query, SQLite Studio throws a SIGSEGV in the QString destructor.

![2019-05-12-121148_1366x768_scrot](https://user-images.githubusercontent.com/3587118/57585061-d352dd00-74b0-11e9-9b59-30310bd6dd09.png)

Stack trace from gdb:
#0  0x0000000000407d43 in QString::~QString() ()
#1  0x00007ffff79b4cb6 in yy_reduce(yyParser*, int) ()
   from /home/dan/Downloads/SQLiteStudio/lib/libcoreSQLiteStudio.so.1
#2  0x00007ffff79b5bee in sqlite3_parse(void*, int, Token*, ParserContext*) ()
   from /home/dan/Downloads/SQLiteStudio/lib/libcoreSQLiteStudio.so.1
#3  0x00007ffff79bb141 in Parser::parseInternal(QString const&, bool) ()
   from /home/dan/Downloads/SQLiteStudio/lib/libcoreSQLiteStudio.so.1
#4  0x00007ffff7369247 in SqlEditor::parseContents() ()
   from /home/dan/Downloads/SQLiteStudio/lib/libguiSQLiteStudio.so.1
#5  0x00007ffff6184bc9 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /home/dan/Downloads/SQLiteStudio/lib/libQt5Core.so.5
#6  0x00007ffff6184ef6 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /home/dan/Downloads/SQLiteStudio/lib/libQt5Core.so.5
#7  0x00007ffff61913e7 in QTimer::timeout(QTimer::QPrivateSignal) ()
   from /home/dan/Downloads/SQLiteStudio/lib/libQt5Core.so.5
#8  0x00007ffff61916b8 in QTimer::timerEvent(QTimerEvent*) ()
   from /home/dan/Downloads/SQLiteStudio/lib/libQt5Core.so.5
#9  0x00007ffff6185adb in QObject::event(QEvent*) ()
   from /home/dan/Downloads/SQLiteStudio/lib/libQt5Core.so.5
#10 0x00007ffff6b1854c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /home/dan/Downloads/SQLiteStudio/lib/libQt5Widgets.so.5
#11 0x00007ffff6b1f897 in QApplication::notify(QObject*, QEvent*) ()
   from /home/dan/Downloads/SQLiteStudio/lib/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#12 0x00007ffff61599f8 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /home/dan/Downloads/SQLiteStudio/lib/libQt5Core.so.5
#13 0x00007ffff61ad08e in QTimerInfoList::activateTimers() ()
   from /home/dan/Downloads/SQLiteStudio/lib/libQt5Core.so.5
#14 0x00007ffff61ad8a9 in ?? ()
   from /home/dan/Downloads/SQLiteStudio/lib/libQt5Core.so.5
#15 0x00007ffff1261417 in g_main_context_dispatch ()
   from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff1261650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff12616dc in g_main_context_iteration ()
   from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff61adbaf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/dan/Downloads/SQLiteStudio/lib/libQt5Core.so.5
#19 0x00007fffef8599a1 in ?? ()
   from /home/dan/Downloads/SQLiteStudio/platforms/../lib/libQt5XcbQpa.so.5
#20 0x00007ffff615826a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/dan/Downloads/SQLiteStudio/lib/libQt5Core.so.5
#21 0x00007ffff6160da4 in QCoreApplication::exec() ()
   from /home/dan/Downloads/SQLiteStudio/lib/libQt5Core.so.5
#22 0x0000000000405e65 in main ()

### Steps to reproduce
Take an existing query with a subquery and load it into the SQL Editor. Attempt to add a join to the subquery by typing it after any existing joins in the subquery. SQLite Studio crashes.

Note that I only have thus far tested changes in subqueries, rather than the outermost query. I will update when I gather additional information on this.

### Operating system
Linux Mint 19

### SQLiteStudio version
3.2.1

**Comment by CMayo64** [comment]
Also experiencing this application crash on build SQLite Studio v3.2.1 on MACOS.

**Comment by pawelsalawa** [comment]
I cannot reproduce it.

Could anyone provide a 100% reproducible SQL? Otherwise I'm unable to fix something I cannot reproduce.

**Comment by SilverNexus** [comment]
WITH CardAppearances AS
(
    SELECT
        CardID,
        COUNT(CardID) AS NumAppearances
    FROM GameCards
    GROUP BY CardID
),
CardUsages AS
(
    SELECT
        CardID,
        COUNT(CardID) AS NumUsage
    FROM GameCards
    WHERE WasUsed = 1
    GROUP BY CardID
)

SELECT
    CardName,
    CardCost,
    COALESCE(NumUsage, 0) AS NumUsage,
    NumAppearances,
    CAST(COALESCE(NumUsage, 0.0) * 100.0 AS DOUBLE) / NumAppearances AS Pct
FROM Card c
INNER JOIN CardAppearances a
    ON c.CardID = a.CardID
LEFT JOIN CardUsages u
    ON c.CardID = u.CardID
ORDER BY
    CardCost ASC,
    CAST(COALESCE(NumUsage, 0.0) * 100.0 AS DOUBLE) / NumAppearances DESC,
    NumAppearances DESC,
    CardName ASC


Attempting to add an INNER JOIN to either subquery on the WITH clause causes a crash.
The tables referenced in the query (and their foreign key constraint-related tables) can be created as follows:
CREATE TABLE Expansion (ExpansionID INTEGER PRIMARY KEY, ExpansionName STRING NOT NULL UNIQUE);

CREATE TABLE Player (PlayerID INTEGER PRIMARY KEY, PlayerName STRING UNIQUE);

CREATE TABLE Game (GameID INTEGER PRIMARY KEY, GameDate STRING, NumPlayers INTEGER NOT NULL, UsedColonies INTEGER NOT NULL DEFAULT (0), UsedDarkAges INTEGER DEFAULT (0) NOT NULL, Dealer INTEGER REFERENCES Player (PlayerID), OnlyUsedSet INTEGER REFERENCES Expansion (ExpansionID), OnlyUsedSet2 INTEGER REFERENCES Expansion (ExpansionID), IsPreset INTEGER DEFAULT (0) NOT NULL);

CREATE TABLE CardType (TypeID INTEGER PRIMARY KEY NOT NULL, TypeName STRING UNIQUE);

CREATE TABLE Card (CardID INTEGER PRIMARY KEY, CardName STRING UNIQUE, CardCost INTEGER NOT NULL, CanOverpay INTEGER NOT NULL DEFAULT (0), CanReduceCost INTEGER NOT NULL DEFAULT (0), TypeID INTEGER NOT NULL DEFAULT (0) REFERENCES CardType (TypeID), ExpansionID INTEGER REFERENCES Expansion (ExpansionID));

CREATE TABLE GameCards (GameID INTEGER REFERENCES Game (GameID), CardID INTEGER REFERENCES Card (CardID), WasUsed INTEGER NOT NULL DEFAULT (1), WasBane INTEGER NOT NULL DEFAULT (0));

**Comment by pawelsalawa** [comment]
That does the job (reproduces problem). Thanks!
