### ISSUE TITLE
Bug: TEXT columns are truncated to 100 chars in Grid Views

### ISSUE THREAD

**Issue by fitdev** [pawelsalawa/sqlitestudio#3526]
### Details
Whenever I am browsing the records of a Table, or viewing the results of a SELECT query, all TEXT fields seem to be truncated to 100 or 101 characters. This is highly misleading as the data is actually there - it's just not being displayed, nor does the UI show any indication (like ...) that not the entire value was retrieved.

### Steps to reproduce
Just have a table with TEXT column that has data in it exceeding say 120 UTF8 characters, and try browsing for that data.

### Operating system
Windows 10 1803 x64

### SQLiteStudio version
2.2.1

**Comment by pawelsalawa** [comment]
Duplicates #3269
