### ISSUE TITLE
SQL syntax color option

### ISSUE THREAD

**Issue by phototropist** [pawelsalawa/sqlitestudio#3527]
### Details
I've got a dark theme using QT5 appearance applet provided on Linux so I have even treeview and gridview with black background and white foreground colors.

### Steps to reproduce
This new color configurations also affect SQL editors on syntax. The problem is there's no color option for operators or brackets. So when I go to Look and Feel and I select black background on SQL editors I don't see parenthesis and such on code because these ones are black too.
Another problem I've found is that when SQL editors are affected by dark appearance provided by QT5 appearance applet, if I select white background for SQL editors I can't see column names in code because these ones are white too.
Right now I have everything in dark theme and I'm taking care o parenthesis and operators but it would be nice to be able to config colors having in mind this QT5 appearance applet and/or brackets and operators color option and valid objects (columns, tables) color option.

### Operating system
Linux

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Will be covered with #4006
