### ISSUE TITLE
Question : How to use the VACUUM command in the source code?

### ISSUE THREAD

**Issue by libaineu2004** [pawelsalawa/sqlitestudio#3529]
### Details
How to use the VACUUM command in the C++ source code?
I want to use "VACUUM"command to empty the database.But the execution fails, the program will throw an exception. My C++ source code is like this:
sqlite3* db;  
sqlite3_open("testdb.db" ,&db);  
sqlite3_exec(db,"VACUUM; ",0,0,0);  

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.
Win7,x64
### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.
3.2.1

**Comment by pawelsalawa** [comment]
This is not SQLite support forum. This is github project of SQLiteStudio, which is management tool for SQLite databases.

This is a good question to be asked on StackOverflow.
