### ISSUE TITLE
Right-align Numerical Data Columns

### ISSUE THREAD

**Issue by JrgMyr** [pawelsalawa/sqlitestudio#3534]
Is there a way to get a right-aligned result column?

Some integer-only columns do that but a SUM(<int-values>) or even COUNT(*) always comes out left-aligned.

COUNT() can only return an integer value. Other numerical aggregation functions always return numerical values.

Wouldn't it be nice if they trigger a flag "column to be right-aligned"?

**Comment by pawelsalawa** [comment]
By design it should work and since it's not working this way, it's a bug to fix.
