### ISSUE TITLE
RANK() -> Error while executing SQL query on database : syntax error

### ISSUE THREAD

**Issue by ButterMyButtAndCallMeABiscuit** [pawelsalawa/sqlitestudio#3536]
### Details
Unable to run queries with RANK()

### Steps to reproduce
 CREATE TABLE dane (
    dzien DATETIME,
    stan  MONEY
);
 

CREATE TABLE kalendarz (
    dzien         DATETIME,
    dzien_roboczy DATETIME
);

    
INSERT INTO kalendarz
VALUES ('2019-04-29 00:00:00.000','2019-04-29 00:00:00.000'),
('2019-04-30 00:00:00.000','2019-04-30 00:00:00.000'),
('2019-05-01 00:00:00.000','2019-05-02 00:00:00.000'),
('2019-05-02 00:00:00.000','2019-05-02 00:00:00.000'),
('2019-05-03 00:00:00.000','2019-05-02 00:00:00.000'),
('2019-05-04 00:00:00.000','2019-05-02 00:00:00.000'),
('2019-05-05 00:00:00.000','2019-05-02 00:00:00.000'),
('2019-05-06 00:00:00.000','2019-05-06 00:00:00.000'),
('2019-05-07 00:00:00.000','2019-05-07 00:00:00.000');

INSERT INTO dane
VALUES ('2019-04-29 00:00:00.000','795.29'),
('2019-04-30 00:00:00.000','117.44'),
('2019-05-01 00:00:00.000','400.45'),
('2019-05-02 00:00:00.000','391.09'),
('2019-05-03 00:00:00.000','197.55'),
('2019-05-04 00:00:00.000','357.61'),
('2019-05-05 00:00:00.000','168.88'),
('2019-05-06 00:00:00.000','930.18'),
('2019-05-07 00:00:00.000','826.36');

SELECT t.dzien ,
       t.stan ,
       t.dzien_roboczy
FROM   (   SELECT d.dzien ,
                  d.stan ,
                  k.dzien_roboczy ,
                  RANK() OVER ( PARTITION BY k.dzien_roboczy
                                ORDER BY d.dzien DESC ) score
           FROM    dane d
                  LEFT JOIN  kalendarz k ON k.dzien = d.dzien ) AS t
WHERE  t.score = 1;

### Operating system
Windows 10 64bit

### SQLiteStudio version
3.2.1

**Comment by ButterMyButtAndCallMeABiscuit** [comment]
Window function support was added to SQLite with release version **3.25.0** (2018-09-15)

In version **3.28.0** (2019-04-16), windows function support was extended to include the EXCLUDE clause, GROUPS frame types, window chaining, and support for "<expr> PRECEDING" and "<expr> FOLLOWING" boundaries in RANGE frames.

**Comment by Qlikeers** [comment]
What is the solution? I have this problem.
