### ISSUE TITLE
Add aggregate function StdDev to Wiki page

### ISSUE THREAD

**Issue by JrgMyr** [pawelsalawa/sqlitestudio#3540]
SQLite offers an "Average" function but no "Standard Deviation" function. This is easy to build using the Function Editor as an "Aggregate Function" by the name of StdDev:

Initialize:
    n=0;
    summe=0.0;
    quadrate=0.0;

Each Loop:
    n++;
    summe = summe + arguments[0];
    quadrate = quadrate + (arguments[0] * arguments[0]);

Finally:
    return Math.sqrt(quadrate / n - (summe / n * summe / n));

Can I make changes to the Wiki page (https://github.com/pawelsalawa/sqlitestudio/wiki/Scripts_repository) in order to include it there next to the any() function?

Best, Jörg

**Comment by pawelsalawa** [comment]
Done. Thanks!
