### ISSUE TITLE
More Keyboard Shortcuts Please

### ISSUE THREAD

**Issue by JrgMyr** [pawelsalawa/sqlitestudio#3541]
When editing tables in 'Data View' then [Ctrl-Enter] commits the changes. That is very good. But in other edit dialogues there is no keyboard shortcut to commit the changes.

Could we have [Ctrl-Enter] = "Commit Changes" in all dialogues where it fits?
At least in 'Create View', 'Edit View' and in the 'Functions Editor'.

Best regards, Jörg

**Comment by JrgMyr** [comment]
Yes, Ctrl-Enter or Ctrl-S.

**Comment by JrgMyr** [comment]
Seems like in "sqleditor.h" there are already CFG_KEY_LIST elements that "consume" Ctrl-S and Ctrol-O:
```
    CFG_KEY_ENTRY(SAVE_SQL_FILE,   QKeySequence::Save,                QObject::tr("Save contents into a file"))
    CFG_KEY_ENTRY(OPEN_SQL_FILE,   QKeySequence::Open,                QObject::tr("Load contents from a file"))

```
Certainly [F9], Ctrl-Return and Ctrl-Backspace
```
    CFG_KEY_ENTRY(EXEC_QUERY,             Qt::Key_F9,                 QObject::tr("Execute query"))
    CFG_KEY_ENTRY(SAVE_SQL_VIEW,        Qt::CTRL + Qt::Key_Return,                QObject::tr("Save contents into view"))
    CFG_KEY_ENTRY(REFRESH_SQL_VIEW,  Qt::CTRL + Qt::Key_Backspace,                QObject::tr("Reload contents from view"))
```
would still be possible to execute a view, to save it to the database or discard changes and reload view from database.

**Comment by JrgMyr** [comment]
Could v3.4.0 please have more keyboard shortcuts?
Yes?

**Comment by pawelsalawa** [comment]
I've just planned it for 3.4.1. I don't want to postpone 3.4.0 further (than what is already planned).

**Comment by pawelsalawa** [comment]
Functions editor, extensions editor, collations editor, snippets editor, table window structure tab, view window query tab - all have now standarized shortucts for committing or rolling back pending changes: `Ctrl+s` / `Esc`. All of them are configurable.
