### ISSUE TITLE
Databases Splitterbar

### ISSUE THREAD

**Issue by macxicon** [pawelsalawa/sqlitestudio#3548]
### Details
Could u please correct behavior when enlarging the Databases view and then clicking with mouse in it, it's width get's again reduced to it's previous (min) value.

Tankx !!

### Steps to reproduce
drag splitterbar of Databases view to the right, click on a db, it jumps back to it's minimum width

### Operating system
Windows 10
### SQLiteStudio version
3.2.1

**Comment by macxicon** [comment]
![image](https://user-images.githubusercontent.com/53119608/61579790-11e8c180-ab0a-11e9-842a-a67f204a8b1a.png)
![image](https://user-images.githubusercontent.com/53119608/61579798-39d82500-ab0a-11e9-8907-1fabaed6bf7e.png)

**Comment by pawelsalawa** [comment]
Duplicates #3421
