### ISSUE TITLE
Selecting page to view when using Views does not load entered page, instead loads current page+1

### ISSUE THREAD

**Issue by audiomuze** [pawelsalawa/sqlitestudio#3559]
### Details
If you define a View then use it to filter data you cannot navigate to a page by entering the page number and clicking the right arrow - it simply loads current page +1 rather than loading the specified page.

### Steps to reproduce
Open a table containing multiple pages - browse data without a View and enter a page number.  The corresponding page will be loaded.

Now define a View, browse the view and try the same thing.  You can basically only navigate from 1 forward in single page increments or from last page backwards in single page decrements.

### Operating system
Linux

### SQLiteStudio version
3.2.1

**Comment by audiomuze** [comment]
Same bug applies to paging through the results of any query returning multiple pages.

**Comment by pawelsalawa** [comment]
I cannot confirm this. I just tried with both a View and query results - in both cases pagination works just fine. Can you share query which you're executing?

**Comment by audiomuze** [comment]
Ironically I can't recreate it either.  I'd been working on that large table for  a few hours when I created two views and tried to use them to focus on the fields I was interested in.  The views worked but navigating to a specific page number simply didn't work - the system would pause as it loaded the page and then present page 2.

I then tried a straight query and got the same outcome.  I didn't think to quit sqls and   reload it.  But trying the same views with sqls just started operated as expected.  Memory leak perhaps?

**Comment by audiomuze** [comment]
Actually, I just managed to recreate it.  I'm using the view "select title, composer, artist, performer, albumartist from audio order by title, artist"

I then clicked on the composer column to sort the view by composer and tried to navigate to page 45 ... page 2 is presented.  So the minute you sort the view by a column it seems all bets are off.

**Comment by audiomuze** [comment]
Now able to reproduce without changing a sort order.  If you want the table uploaded for you to test with I can do so.

**Comment by pawelsalawa** [comment]
Yes, please attach the DB here to comment (you can drag & drop files to comment field to attach them). If it prevents you from attaching "db" file, then zip it and attach zipped.

I tried to reproduce it on my own with what you described, but I was still unable. Having your DB would clarify it for me. Thanks!

**Comment by audiomuze** [comment]
I'd prefer to send your a private dropbox link rather than put the db in the public domain - there a way for me to get it to you other than dropping it here?

**Comment by pawelsalawa** [comment]
You can upload it here: https://www.dropbox.com/sh/cwmhpimuniqicds/AACpic3bJlrEKaU4lxIHMpP6a?dl=0

**Comment by pawelsalawa** [comment]
Once you do it, respond here and I will unpublish the folder.

**Comment by audiomuze** [comment]
It's uploaded.

**Comment by pawelsalawa** [comment]
I see the folder to be empty.

**Comment by audiomuze** [comment]
Not sure what happened - I couldn't upload to the link you sent so I added itto my dropbox and uploaded to that.  Here's a link:
https://www.dropbox.com/s/yj8awp19wv9xi14/alib-wip.rar?dl=0

Please let me know when you have it.

**Comment by pawelsalawa** [comment]
I downloaded it. You can remove it. Thanks!
I'll work on reproducing the bug now and will get back to you.

**Comment by pawelsalawa** [comment]
It seems to be working correctly for me.

How do you know that you're on page 2 and not 45?

**Comment by audiomuze** [comment]
It shows page 2 and the data displayed is what I'd expect to see on page 2, not on page 45.

Have you tried what I set out here?: https://github.com/pawelsalawa/sqlitestudio/issues/3559#issuecomment-523994970

**Comment by pawelsalawa** [comment]
Yes, I tried exactly that. The thing is - how do I know that this is page 2 and not 45? According to what SQLiteStudio shows, it's presenting rows 45000-45999, which is expected. How do I know this is not true?

**Comment by pawelsalawa** [comment]
I mean - what data should I see on page 45?

**Comment by audiomuze** [comment]
In the page indicator it shows page 2 rather than 45 which is what was entered. I'm not sure what should be in page 45, I was looking for a composer somewhere around the middle of the distribution alphabetically.  Page 2 show's the next progression in the composer sort order leading on from page 1.

**Comment by pawelsalawa** [comment]
Weird. It's working correctly for me, that is - it's showing page 45. Yeah, you can record it. Maybe there is something I'm missing here.

**Comment by audiomuze** [comment]
Just want too check, you're using a Linux build our Windows build?

**Comment by pawelsalawa** [comment]
I was doing it on Windows previously, but now I checked it on Linux (Kubuntu) and it also works fine.

1. I enter the SQL query you mentioned and execute it.
2. I click on composer to sort by it.
3. I click on page field to modify it.
4. I enter value 45 and hit Enter to apply it.
5. Results are loading for page 45 and page field contains number 45, as on the attached picture.

![image](https://user-images.githubusercontent.com/481846/63805939-cef4e780-c91a-11e9-9a86-8fdaa1d0d9c1.png)

**Comment by audiomuze** [comment]
I'll play around to recreate the condition then record proceedings and post here. I'm definitely not imagining it. 

As an aside, in your screendump you're at record 44001/453k - how many pages do you have?

**Comment by pawelsalawa** [comment]
454 pages

**Comment by audiomuze** [comment]
Could be page size has something to do with it.  My browse settings are such that it yields only 91 pages:

![image](https://user-images.githubusercontent.com/6852511/63837603-af3ddd80-c973-11e9-9715-673237d4cb25.png)

**Comment by pawelsalawa** [comment]
It may be. Can you try setting this to 1000 and then try?
There is already another github issue reported for problems with bigger row limits: #3558

**Comment by audiomuze** [comment]
I'm afraid that doesn't fix it.  I changed the setting, applied it, quit sqlitestudio and relaunched it.  Then activated the following view:
`select title, composer, artist, performer, albumartist from audio order by composer, title, artist`
Hovered cursor over page entry box to see there are now 454 pages.  Typed in 45 and hit the Next Page arrow which took me to page 45.  All good.  Then I entered 420 and hit the Next Page arrow which took me to page 46.  Tried again, which got me to page 47.  From thereon out, no matter what number is entered hitting the Previous or Next page button decrements or increments the page by 1.

**Comment by audiomuze** [comment]
I'll run a screen record session

**Comment by pawelsalawa** [comment]
I think I know what the problem is. You're hitting "arrow" button. This button does not get you to page that you entered, but to "next" page, relatively to current page.

If you want to go to page you entered, then type the number and hit "Enter" on your keyboard.

Also please notice, that if you move your mouse cursor over any of "arrow" buttons and wait a second or two, a help hint will appear telling you, that particular button takes you to next page, or previous page, or last page, or first page - depending on which button you're holding your mouse over at the moment.

**Comment by audiomuze** [comment]
Of course, as I try to screen record now I can't reproduce.  Having said that I think you're right about the arrow usage - I started using them because I had multiple occasions where entering a value and pressing enter did nothing to trigger a new view.  Sorry to have wasted your time with this.  If it recurs I'll record and upload.
