### ISSUE TITLE
Tried to commit a cell which is not editable (yet modified and waiting for commit)! This is a bug. Please report it.

### ISSUE THREAD

**Issue by audiomuze** [pawelsalawa/sqlitestudio#3560]
### Details
Ran a query using distinct.  Edited fields in results, tried to commit.

### Steps to reproduce
select distinct title, composer from audio order by title;

### Operating system
Linux
### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Did you parhaps paste (ctrl+v) the new value?

**Comment by pawelsalawa** [comment]
...if yes, then here's a bug reported for this already: #3537

**Comment by audiomuze** [comment]
Almost a certainty that's exactly what I'd done forgetting I'd used the distinct clause.
