### ISSUE TITLE
SQLiteStudio. exe has stopped working on right click on blank table area

### ISSUE THREAD

**Issue by johnFA90** [pawelsalawa/sqlitestudio#3571]
### Details
SQLiteStudio. exe has stopped working on right click on blank table area

### Steps to reproduce
Open a blank table (no rows) -> go to tab "Data" and right click on blank area.

### Operating system
Windows 10 Version 1809 (OS Build 17763.678)

### SQLiteStudio version
SQLiteStudio v3.2.1

**Comment by pawelsalawa** [comment]
Duplicates #3565
