### ISSUE TITLE
Problems with removing databases from list on OSX

### ISSUE THREAD

**Issue by wlodek** [pawelsalawa/sqlitestudio#3578]
### Details
Removing database from list doesn't take effect

### Steps to reproduce
Add database to the list of databases. Delete it (remove from list)

### Operating system
MacOSX High Sierra 10.13.6

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Are you sure you are confirming the removal in the yes/no dialog?
If yes, can you please run SQLiteStudio in debug mode and copy-paste output of debug when you do the database removal from list?

Here's how you start it in debug mode:

    /Applications/SQLiteStudio.app/Contents/MacOS/SQLiteStudio -d --debug-stdout

(the path may differ if you installed it in different place)

**Comment by wlodek** [comment]
Mr. Paweł

I am very, very sorry. I usually work on Windows version, where buttons are
in reverse order and YES button is on the left and NO on the right. I'm so
used to the fact that the YES button in Windows applications is always on
the left side that I clicked habitually on the button on the left. Sorry
for taking your time.

Regards

Włodzimierz Kessler

Email: kessler.wlodek@gmail.com

Mobile: +48 601 068 700

Facebook Messenger: @signum.net

Skype: signum-net

WhatsApp, Viber





pon., 16 wrz 2019 o 00:17 Paweł Salawa <notifications@github.com>
napisał(a):
