### ISSUE TITLE
Segfault on SELECT on a view with "union"

### ISSUE THREAD

**Issue by rkoe** [pawelsalawa/sqlitestudio#3581]
### Details
SQLiteStudio segfaults on some SELECTs on an other view; probably only when the other view uses "UNION" in its own SELECT, and only if the name of the other view is not written in parentheses.

Test results (run e.g. in SQL editor or in a view):
- "SELECT 0 FROM view1" -> segfault
- "SELECT 0 FROM (view1)" -> works

Error-messages:
```
WARNING:  QSocketNotifier: Invalid socket 7 and type 'Read', disabling...
WARNING:  QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
WARNING:  QSocketNotifier: Invalid socket 7 and type 'Read', disabling...
...
WARNING:  QObject::~QObject: Timers cannot be stopped from another thread
...
WARNING:  QSocketNotifier: Invalid socket 7 and type 'Read', disabling...
Segmentation fault
```

### Operating system
Linux

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
I've tried to reproduce it with `viewB` from the database you provided in #3580 but I was unable to do so. I tested it on 3.2.1.
If you still can reproduce, please post the recipe here and I will reopen.
