### ISSUE TITLE
Table lost when moved to a wxSQLite DB

### ISSUE THREAD

**Issue by ghost** [pawelsalawa/sqlitestudio#3582]
### Details
According to SQLiteStudio these wxsqlite.db are read only bases, so it didn't accept the table I moved and the table was gone on origin.db after moved.
### Steps to reproduce
Create a wxSQLite DB, drag and drop a table in it from another database on the list.
The program will say: this database is read only. And the table will dissapear from origin DB.
### Versions
SQLiteStudio 3.2.1 on Wine
### Proposal
If a table can't be moved in any circumstances shouldn't be deleted from origin.
If a table has been effectively moved, then remove it from origin after successful operation.

**Comment by pawelsalawa** [comment]
May I ask why did you use Wine for it? Do you still struggle with native Linux installation? Did you try a ready-to-use binaries in form of an installator from the home page?

**Comment by pawelsalawa** [comment]
(of course I will try to reproduce it myself on native Linux and other platforms too)

**Comment by warepilot** [comment]
According to [download page](https://sqlitestudio.pl/index.rvt?act=download), available version for Linux are x64... I guess you talk about the precompiled *.tar.xz ... As I'm on a x32 system, right now I'm [at this point](https://github.com/pawelsalawa/sqlitestudio/issues/3572#issuecomment-536303511)... Unless you tell me that the tar file classified on x64 will run on my x32...

**Comment by pawelsalawa** [comment]
Right. 32bit binaries are no longer provided.

Regardless of that, the bug is acknowledged and will be fixed in 3.2.2.

**Comment by pawelsalawa** [comment]
Although, I'm not sure why is target database considered as read only for you. Is the target file writable?

**Comment by warepilot** [comment]
File has been created with the very SQLiteStudio, not sure if that affects somehow.
The moment I dropped my table on the encrypted db, it said something like "these bases are considered read only".

**Comment by pawelsalawa** [comment]
Okay. I'll look into that.
