### ISSUE TITLE
Window functions support

### ISSUE THREAD

**Issue by mburakkalkan** [pawelsalawa/sqlitestudio#3584]
### Details
The new window functions support which has come since sqlite 3.25 doesn't supported by sqlite studio 3.2.1. I could easily get them work by downloading and replacing the sqlite3.dll with latest version. It executes the query then shows the results without any problem but query editor still underlines the query as error.

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Duplicates #3471
