### ISSUE TITLE
Long results get truncated in Grid view and Form view

### ISSUE THREAD

**Issue by CBke** [pawelsalawa/sqlitestudio#3585]
Hi

When a query returns a long string it gets truncated.

`WITH RECURSIVE cnt (
    x
)
AS (
    SELECT 1
    UNION ALL
    SELECT x + 1
      FROM cnt
     LIMIT 1000000
)
SELECT group_concat(x) LongString
  FROM cnt
 GROUP BY '1';`

Windows 10 v3.2.1 SQLite v3.24.0
![Untitled](https://user-images.githubusercontent.com/957837/66054131-d28c1780-e533-11e9-9d20-b4e0913fea04.png)

**Comment by pawelsalawa** [comment]
Duplicates #3269
