### ISSUE TITLE
Can't copy without headers

### ISSUE THREAD

**Issue by tedstriker2** [pawelsalawa/sqlitestudio#3586]
### Details
In the context menu for a query result, there's an option to "Copy", and an option to "Copy with headers" (the column name). I don't want to copy the header, but it's happening anyway.

### Steps to reproduce
Run a query, then try to copy a cell without headers.

### Operating system
Windows 10

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
I just did. Works here.
Try selecting a single cell and copy only it. Is header included anyway?
I did it for both single cell and for all cells - in both cases works correctly for me.

If you still have problem - can you please record how you do it? Usually in cases like this (works for me but not for someone else) there is some important piece missing and misunderstanding. Recording should resolve it.

In Windows 10 you can record easily with Win+g -> then record button. After recording is done you can find your record file in "My Videos".

**Comment by tedstriker2** [comment]
[SQLiteStudio (3.2.1) - [SQL editor 1] 2019-10-03 10-43-15.mp4.zip](https://github.com/pawelsalawa/sqlitestudio/files/3686948/SQLiteStudio.3.2.1.-.SQL.editor.1.2019-10-03.10-43-15.mp4.zip)

I recorded a video as you requested where I selected a single cell, brought up the context menu with a right mouse click, and chose "Copy". Unfortunately, the video did not capture the context menu, but I did _not_ select "Copy with headers". You can see from the video that the header was included anyway.

**Comment by pawelsalawa** [comment]
From what I see, the "insert_sql" (supposed header, right?) is pasted at the end, so it cannot be header.

If you copy header, it is pasted as first.

I'm suspecting that you actually have "insert_sql" word at the end of your cell value. Switch to "Form View" tab and see the whole value there.

**Comment by tedstriker2** [comment]
"insert_sql" is the header, and it is not part of the cell value. Also, the same query works fine in version 3.0.6 of SQLiteStudio, which I'll go back to using now.

**Comment by pawelsalawa** [comment]
Is it possible, that you share the SQL query you're executing here?

**Comment by tedstriker2** [comment]
Yes, here's the SQL query:

```
/* DO NOT "INSERT OR"! The primary key will increase no matter what! */
SELECT
    data_content,
    data_category,
    max_valid_target,
    data_len,
    max_freq_rank,
    'INSERT INTO dmz_txt (data_content, data_category, max_valid_target, data_len, max_freq_rank) VALUES ('
    ||quote(data_content)
    ||', '
    ||quote(data_category)
    ||', '
    ||max_valid_target
    ||', '
    ||data_len
    ||', '
    ||max_freq_rank
    ||');' insert_sql,
    1 severity
FROM
(
SELECT
    dta.abbv_txt data_content,
    dta.data_category,
    MAX(ifnull(dtmt.valid_target, 0)) max_valid_target,
    LENGTH(dta.abbv_txt) data_len,
    MAX(
        round(CAST(LENGTH(dta.abbv_txt) - 2 AS REAL) * 0.5),
        CAST(3 AS REAL)
        ) max_freq_rank
FROM dmz_txt_attr dta
LEFT JOIN dmz_txt_match_tgt dtmt
ON
    dtmt.orig_source = dta.orig_source
WHERE
    dta.abbv_txt IS NOT NULL
    AND (
        dta.orig_source LIKE 'IMPORT/%'
        OR dtmt.valid_target IS NOT NULL
    )
/* Make sure no data_keys are created for duplicate content */
GROUP BY
    dta.abbv_txt,
    dta.data_category
) ld
WHERE
    NOT EXISTS (
        SELECT
            1
        FROM dmz_txt cd
        WHERE
            cd.data_content = ld.data_content
            AND cd.data_category = ld.data_category
            AND cd.max_valid_target >= ld.max_valid_target
    )
ORDER BY
    max_valid_target,
    data_category,
    data_content
    --RANDOM()
;
```

**Comment by pawelsalawa** [comment]
Okay, I got it reproduced. Even with this significantly simplified query:

```
SELECT a, b,
    'INSERT INTO dmz_txt (data_content, data_category, max_valid_target, data_len, max_freq_rank) VALUES ('
    ||a
    ||', '
    ||b
    ||');' insert_sql,
    1 severity
FROM (SELECT * from test3) ld;
```

There is some problem with interpreting string concatenations, apparently.

**Comment by tedstriker2** [comment]
I'm glad you were able to reproduce the issue. Thanks for looking into it.
