### ISSUE TITLE
Losing data on fixing bad rows after UNIQUE constraint errors

### ISSUE THREAD

**Issue by ghost** [pawelsalawa/sqlitestudio#3588]
### Details
After commit action I have UNIQUE constraint errors (constraint required). When I try to edit the bad row for fixing on the error column, data get vanished. On the other hand, commit process rises false positive on that constraint.

### Steps to reproduce
Insert a big bunch of rows. Paste data. You may have UNIQUE constraint error as you configured for the table whenever you commit. Try to edit the bad row on cell related to that constraint (a STRING type). Data will vanish. I think all that happens when the pasted string is really long, but it happens with BLOB as well.

### Versions
3.2.1 on Wine

**Comment by pawelsalawa** [comment]
"data get vanished" <- from only the cell you tried to edit, or all pasted rows disappear?

**Comment by warepilot** [comment]
Right. From the cell I'm trying to fix, only.

**Comment by pawelsalawa** [comment]
I see. Okay, I think I know what may be wrong with it. It looks like the flag "limited preload" is incorrectly set to true upon pasting and when you try to edit it, application tries to "load full value" from DB, so you edit full value (not shortened, view-only value), which is not there yet and results in loading empty value. I'm writing it down here to catch-up quickly with it when I sit down to it.

**Comment by rkoe** [comment]
This not only happens when pasting large data, but also when manually entering data (one or a few rows) into SQLiteStudio.
