### ISSUE TITLE
row_number() function not working

### ISSUE THREAD

**Issue by nant1086** [pawelsalawa/sqlitestudio#3591]
### Details
row_number() is a sqlite function and I can't use it from query editor

### Steps to reproduce
just execute a query against any table
select row_number() over (order by Name) RowNum from Table;

### Operating system
windows 10

### SQLiteStudio version
3.11.2
Qt version 5.11.3
Sqlite Version 3.27.2

**Comment by pawelsalawa** [comment]
This function relies on SQLite version being more recent and it's already planned with #3470
