### ISSUE TITLE
SQL syntax control, specifically on Trigger code editors

### ISSUE THREAD

**Issue by ghost** [pawelsalawa/sqlitestudio#3592]
### Details
OK button not enabling after TRIGGER code fixing, unless I go to the end of line and write ";".
### Steps to reproduce
(1) Error on row commit: the table has triggers.
(2) Another table is not found in trigger code (because it couldn't be updated automatically and forgot to review it myself as the program warns).
(3) Fix the trigger code at the point where that lost table is (but OK won't enable).
(4) Go to the very end of code, delete and rewrite the semicolon. (OK button enables)
### Notes
On changing names to columns or tables, triggers and views do not update entirely. To be specific this happens after FROM or WHERE clauses of TRIGGERS and VIEWS.
### Versions
3.2.1 on Wine 4.0

**Comment by pawelsalawa** [comment]
Reproduced on 3.2.1, already fixed in 3.3.0 (by the way of some other bugfix).
