### ISSUE TITLE
wrong data shown with default constraint

### ISSUE THREAD

**Issue by rkoe** [pawelsalawa/sqlitestudio#3594]
### Details
Directly after adding rows, SQLiteStudio shows wrong values for columns, which were set by a default constraint.
Reloading the table-data fixes this.

As #3580, the reason for this seems to be that SQLiteStudio tries to be "smarter" than the database, and fails.

Solution: Fetch the data of the added rows from the database and show this data; and do not guess what the data may be.

This would probably also improve #3588, since then the "lost" data would be visible before a table-data-reload.

### Steps to reproduce

- `CREATE TABLE test (col1 NOT NULL DEFAULT ('test'));`
- now, click 'Insert row' and 'Commit'
- SQLiteStudio now incorrectly shows `'test'`
- after reload, the correct value `test` (without quotes) is shown.

### Operating system
Linux

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Already resolved, most likely by #3489
