### ISSUE TITLE
Errors when REFERENCES foreign rowid

### ISSUE THREAD

**Issue by ysalmon** [pawelsalawa/sqlitestudio#3596]
``sdaps`` is a Python script that uses sqlite for storing information. It creates a table where a column references the rowid of another table : [the sheets table references the rowid of the survey table](https://github.com/sdaps/sdaps/blob/fd7bf833e09328e6976a44bf59c4cd5261f4e1f1/sdaps/model/survey.py#L50).

In SQLiteStudio 3.2.1, when adding or removing a line in the ``sheets`` table through the data view, or when executing ``DELETE FROM sheets;``, I get a "foreign key mismatch - "sheets" referencing "surveys"". If I look at the structure view, the foreign key part of the offended columns shows as "requires configuration" (red dot) and the foreign column dropdown in the configuration window shows as empty.

Executing the statement ``DELETE FROM sheets;`` in a command-line sqlite client works, so I suspect SQLiteStudio is over-zealous here.

**Comment by pawelsalawa** [comment]
The command-line sqlite tool has foreign-key validation disabled by default (unlike SQLiteStudio). Try enabling it first: `PRAGMA foreign_keys = true;` and re-test.

**Comment by ysalmon** [comment]
Good catch ! So, it is the CLI that is under-zealous by default ?
Is ``sdaps`` at fault for referencing the rowid directly ?

**Comment by pawelsalawa** [comment]
I wouldn't say it's under-zealus. It's about backwards compatibility, as older versions did not support FK validation at all. See https://sqlite.org/pragma.html#pragma_foreign_keys for more.

As for the second question, it was already asked on StackOverflow and well answered: https://stackoverflow.com/questions/17002251/why-does-referencing-a-sqlite-rowid-cause-foreign-key-mismatch - so yes, sdaps is doing it wrong.

**Comment by pawelsalawa** [comment]
Also note, that if you make SQLite column of type INTEGER PRIMARY KEY AUTOINCREMENT - it will automatically be equal to rowid. The underlying implementation of SQLite will simply expose rowid column for this PK named column of yours.

**Comment by ysalmon** [comment]
Thank you so much for your insight and help !
I will be filing an issue at sdaps referencing (c'est le cas de le dire !) your comments.
