### ISSUE TITLE
Crash when disconnecting a DB with an outstanding structural changes

### ISSUE THREAD

**Issue by ysalmon** [pawelsalawa/sqlitestudio#3597]
When I close a structure/data panel and there are outstanding structural changes, SQLiteStudio prompts for confirmation.

When one disconnects a databases, SQLiteStudio tries to close the associated panels and accordingly prompts for confirmation in the same case.
However, if, at the prompt, I cancel, the DB is nonetheless disconnected.

This leaves an open structure/data panel to a disconnected DB. Closing that panel and confirming at the prompt causes a crash to desktop.

**Comment by pawelsalawa** [comment]
I'm not sure to which version was this reported, but I cannot reproduce it on 3.2.1.
