### ISSUE TITLE
Enable JSON extension in SQLite

### ISSUE THREAD

**Issue by Robert-M-Muench** [pawelsalawa/sqlitestudio#3616]
[08:54:41] Could not load data for view: no such function: json_extract

Looks like the Sqlite version wasn't compiled with the JSON extension. Overall, please enable all official SQLite extensions.

Can I replace the used SQlite version?

**Comment by yh2216** [comment]
Could you please tell me when to solve this issue?

**Comment by yh2216** [comment]
I want to replace the sqlite3.dll myself ，as sqliteStudio 3.2.1 directly!
![图片](https://user-images.githubusercontent.com/47512078/110062248-dfa1db80-7da3-11eb-9ef4-6990248bd6ca.png)

**Comment by pawelsalawa** [comment]
SQLiteStudio 3.3.0 no longer has separate dll file for SQLite3, instead it is built into the SQLiteStudio binary.
Fortunately json functions are included there.
