### ISSUE TITLE
Cannot edit this cell, bug?

### ISSUE THREAD

**Issue by tonywang531** [pawelsalawa/sqlitestudio#3617]
### Details
This is the first time I have seen warning message like this. So I report it...
```
Cannot edit this cell. Details: The query execution mechanism had problems with extracting ROWID's properly. This might be a bug in the application. You may want to report this.
```
### Steps to reproduce
This is the query I used. Basically there are some duplicates in the tables, I removed them and attempt to join the id (bar code) that match. I am still new to sql so there maybe better ways.
```
WITH RF AS (
WITH sane2 AS (
        SELECT *,
               substr(date, 1, instr(Date, ' ') - 1) AS Time
          FROM [RF測定データ質量(5665)]
    )
    SELECT Date,
           "バーコード(7桁)"
      FROM sane2
     GROUP BY [バーコード(7桁)],
              Time
),
Curing AS (
WITH sane AS (
        SELECT *,
               substr(date, 1, instr(date, ' ') - 1) AS Time
          FROM 加硫実績2
    )
    SELECT [バーコード (_)],
           [No],
           Date,
           [加硫時間 (sec)]
      FROM sane
     GROUP BY [バーコード (_)],
              time
)
SELECT *
  FROM Curing
       LEFT OUTER JOIN RF 
       ON Curing.[バーコード (_)] = RF.[バーコード(7桁)]
WHERE RF.[バーコード(7桁)] = "BABRGR9";
```

### Operating system
Windows 10 on dell laptop 64 bit 
12GB memory

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Eduting results of Common Table Expression (the "WITH" expression) is not supported and will not be supported any time soon, as it is extreamly difficult (from the code perspective) to track it properly in all cases.

Maybe some day...
