### ISSUE TITLE
Nesting QtScript functions freezes SqliteStudio

### ISSUE THREAD

**Issue by sevaa** [pawelsalawa/sqlitestudio#3620]
QtScript functions can't be used in db.eval() within QtScript functions. Freezes the query.

### Steps to reproduce
Create a database with a table called "t" with a field called "ID", with a record where ID=1.
Register a QtScript function called g with the following text:
`    return 1000;`
Register a QtScript function called f with the following text:
`    var r = db.eval("select count(*) from t where ID=g()");`
`    return r[0][0];`
Execute the following SQL:
`    select f() from t where Nomer=1`

### Operating system
Windows 10 Pro x64

### SQLiteStudio version
3.1.1

**Comment by tuffnatty** [comment]
Cannot reproduce with current code.

**Comment by pawelsalawa** [comment]
Yeah, the report is quite old and the plugin (and the whole scripting framework in the app) was changed significantly. Probably it's no longer relevant.
