### ISSUE TITLE
Feature request: disconnect and reconnect database button

### ISSUE THREAD

**Issue by rickrcomm** [pawelsalawa/sqlitestudio#3621]
In developing an app with Django, I frequently need to see the database contents after an HTML page is processed. Now I need to disconnect the database, select the correct database, connect the database again and then scroll to the table I am interested in. A button to “refresh” the database would be very time saving. Extra points if it displayed the table I was looking at in either schema or data view. 

Nevertheless, the application is SO useful! Thanks for developing it.

**Comment by pawelsalawa** [comment]
There is a "refresh database schema" entry in right-click menu. The same is available with F5 hotkey. Just have a focus in database list when pressing F5.

This will not refresh data inside of your table window. To refresh that - either use button on toolbar of the table window, or - again - press F5, but now with focus in table window.
