### ISSUE TITLE
Lag function is not working in the release 3.2.1

### ISSUE THREAD

**Issue by ishan42d** [pawelsalawa/sqlitestudio#3622]
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment]
What is the lag function?

**Comment by alexandroshdj** [comment]
Lag window function that exists in SQLite3 https://www.sqlite.org/windowfunctions.html
It seems to not be working, it gives an error for the OVER statement (check the same link)

**Comment by pawelsalawa** [comment]
Duplicates #3471

**Comment by helix2001** [comment]
I've used LAG and LEAD function sucessfully with SQLiteStudio 3.2.1. Replaced the bundled sqlite3.dll with version 3.30 32bits and it works like a charm. The SQL syntax after the OVER clause with appear underlined, as if it were an error, but the results are correct.
