### ISSUE TITLE
Error on commiting structure changes when using special characters on names.

### ISSUE THREAD

**Issue by ghost** [pawelsalawa/sqlitestudio#3628]
### Details
The [error](https://github.com/pawelsalawa/sqlitestudio/issues/3430) keeps raising in a way I can't reproduce it to explain. 
It's not about [complex column names (like using 2 words)](https://github.com/pawelsalawa/sqlitestudio/issues/3430), it's about special characters on names.
### Workaround
On editing structure, one can [wrap](https://www.sqlite.org/lang_keywords.html) column names with special characters. Once this is done and shown at structure tab, commiting can be done.
### Versions
This is also happening on 3.2.1 portable version for Linux x64.

**Comment by pawelsalawa** [comment]
I still cannot reproduce it. If you find a way, a recipe to reproduce it, please post it here and I will reopen.
