### ISSUE TITLE
Include option to display number of rows only

### ISSUE THREAD

**Issue by tonywang531** [pawelsalawa/sqlitestudio#3630]
Currently I work with a fairly large database (millions of entries with 1000 + columns). I find myself often need to "play around" to find the right SQL query by trial and error. The problem is the trial and error process is taking a lot of time, usually several minutes. Meanwhile I can only stare at screen and let the studio does its work. Select only a few columns from the results speed the process a little bit, but not by too much. I assume the filtering is taking most of time.

Therefore I thought it would be nice to somehow speed up the progress by just returning the number of rows it will return instead of the actual results. I am not sure how SQL works nor if it is possible. Changing to a proper server SQL variant (MySQL, MongoDB) is currently not possible due to company policy against storing data in the cloud. It would be nice this can be implemented.

**Comment by pawelsalawa** [comment]
You can return number of rows by selecting count(*) instead of column names.

If you limit number of columns and you select just few, it should take that long either way. Is your query selecting from just 1 table, or is it complex query with several joins, etc?

**Comment by tonywang531** [comment]
> You can return number of rows by selecting count(*) instead of column names.
> 
> If you limit number of columns and you select just few, it should take that long either way. Is your query selecting from just 1 table, or is it complex query with several joins, etc?

Thanks for the tip, I will try that! Yes it is a complex query with 4 or 5 table joins based on matching I.D.

**Comment by pawelsalawa** [comment]
Are the id columns indexed in all these tables? It's critical for the speed.

Paweł Salawa
pawelsalawa@gmail.com


wt., 7 sty 2020 o 01:44 tonywang531 <notifications@github.com> napisał(a):

**Comment by tonywang531** [comment]
> Are the id columns indexed in all these tables? It's critical for the speed.

They are not indexed... I misunderstood they have to be unique, but they actually do not have to. How much extra space will it occupy? Does it takes the same space as adding an extra column?

**Comment by pawelsalawa** [comment]
They have to be unique too, but the index can take care of both of these things (just use UNIQUE INDEX).

In terms of space it won't take much. It's like keeping extra integer value per row.
