### ISSUE TITLE
WORK FLOW - queries access/storage/execution SQLiteStudio

### ISSUE THREAD

**Issue by DingBEN** [pawelsalawa/sqlitestudio#3644]
### Details
**Note:** I am walking away from this sort of post.
I have work to do, this is taking away from my commitments.
From this point on I will only report simple errors, or potential bugs.

**workflow scenario**
As I am using the tool, the same clonk moments recur. - That helps me  be able to better see why.
Yes,  I have mentioned this before, but now I can **expose a scenario**.

Where you see the word '**snag**' below, the above and below lines show a hick-up of doing the **wrong thing** and doubling-back to do the **better move**!

**SCENARIO**:
**Say I am in need of a particular data-subSet in a table. ...and I know I have written the query already, it's on disk**
My mind is on data, not what window I am in, not database is current, not anything else...
Thus if I fetch a 'FETCH/SELECT query' from disk, the idea is to place a particular set of data in front of my eyes.

**I need to go to the folder where my [ SELECT-where clause col- name-Filter.sql ]** is, and double click it!
- o! crap **Folder icon** not on the screen!?
- gotta get to a window that has the folder icon(any already loaded SQL Editor Window **IF ANY**!?)
- **snag** -- cringe the flow is smitten!.
- Careful, may be better to **REMEMBER** to start a new SQLEditor window
   because the loaded query will overwrite the current window query
- **snag** -- cringe the flow is smitten!.
- perhaps get in habit to always crank-up a NEW SQL Editor window(**good luck remembering**)

The above snags are a constant pain, clonk moments, even if the first part of it was avoided by slowing down the flow(cringe) having to think to do the second step, rather.

**Other problems associated with the above scenario**
- on a slow machine, or memory high usage instance, going to disk for each SQL needed is a major flow interference... and I suspect even if on fast hardware, constant single fetching of this sort is simply a kludge! (or a quick legacy approach to at least provide the functionality pending a more viable enhancement)
- also applying a query to a 'current'window/database is in the way. A result set should be based on any and all the database/tables that are attached, not narrowed down to a 'current' database.
The [database setting button] needs to disappear, only be present in some sort of specific scenario that requires it!
If a query addresses a database that is not attached, then kick an exception(SQL certainly already does that, since it will err on the table).

**SUGGESTION**: 
- Why not follow the thinking of a data fetch, of any kind, not forcefully a database
  -- and simply fetch the data in a new SQLEditor window so one does not have to constantly trip on 
  what the next move or have to undo a move that is destructive(overwrite of current query)
  -- place confirmation dialogs in the flow to fork to a simple load of the SQL query vs a load and execute, etc...
  -- (or have [load] and a [load/exec] buttons)
- perhaps always load a query to a 'WORK SQL Editor window'
  in the fetch dialog, offer choices
  [overwrite current] - [save current and load]- [load in new window]
- **- simple approach always load in new window... NEVER overwrite!
   (let user cleanup others as needed)** bla bla bla...

- **also why not avoid all of these single fetches of filename.sql** and load all the SQL queries in memory in a pick-and-choose panel, configuration dependent, so the user can place the pertinent queries in the game as the ones to load
{ CONCERN:  - one would not want to have to load a large amount of queries... though, queries are but text and take not much memory, thus a massive count of them could be loaded as long as into a bucketed format.}

- surely, loading queries at start would require a config change to set the folder where queries are stored:  QUERIES - SELECT / QUERIES INSERT / QUERIES INDEX etc... or simply a master folder(QUERIES) and what ever hierarchy the user creates under the master folders is assumed by the system as the buckets.

**2 approaches which use a database** instead of an app panel

1. **HISTORY window potential**
- History stores all the queries (not good for this functionality)
- need a way to quickly point to only the ones that are the type to keep
- also need a drop down with **proper filters(user defined indeces)** to help key on queries
- column sort
- etc... no need to spell out all the functionality...

2. **_REMEMBER, in another post I mentioned that all the queries could be stored in a system database/table/index...(like History).
That is what I do now, rather than save to disk via the 'Save SQL to file (Ctrl+5)' button
All I have to do is to keep that database in the database panel and I can get to my queries 10x faster!_** BUT I have to cut and paste... it is not direct!

Going on hiatus... will respond to replies, if needed.

**Comment by pawelsalawa** [comment]
This is way, waaaaay too long and it's hard to read any specific improvement/enhancement suggestions. If more precise (shorter, straight to the point) description appears and has valid suggestions, I will consider reopening.
