### ISSUE TITLE
How to change data type to timestamp

### ISSUE THREAD

**Issue by tonywang531** [pawelsalawa/sqlitestudio#3662]
I have just noticed recently that some of my data is in the type "timestamp" as stated by Sqlite studio:

![image](https://user-images.githubusercontent.com/51065728/73629597-05d3e400-4697-11ea-81c5-56ece14bdd78.png)

This is actually great because it forces potential String type to timestamp type which avoid potential failures with strftime. I cannot remember how I created the column, probably using Python with sqlite module using to_datetime or similar.

My question is that if I want to change a table of unspecified type to "timestamp" type, there is no such option. Does this have some sort of requirement?

### SQLiteStudio version
Latest version

**Comment by pawelsalawa** [comment]
You can just type "TIMESTAMP" there. It does not have to be listed there in the dropdown.

Actually, the fact that you have "timestamp" column doesn't really change anything in your database. SQLite3 distinguishes only 5 data types and timestamp is not among them. SQLite3 simply allows you to declare any type you want, just to make schema more readable by the user, but that doesn't impact how data is stored or treated by SQLite.
Here are details: https://www.sqlite.org/datatype3.html

SQLiteStudio takes adventage of what type users declare and tries to behave accordingly (show date editors for date/datetime/timestamp types, show spinbox for numeric types, etc), but that's all.

**Comment by tonywang531** [comment]
I see, that is kind of disappointing...
