### ISSUE TITLE
window - TABLE singleCLICK behaves as doubleCLICK !?

### ISSUE THREAD

**Issue by DingBEN** [pawelsalawa/sqlitestudio#3673]
### Details+
**I AM LEAVING THIS as POSTED**, because it is likely occurring to other users
- was boppin'round between windows(work-spaces)
- noticed all of the sudden, I was able to **SINGLE-click** a table in a DB, then **SINGLE-click** another table in another DB and the panel/window/work-space would change nicely.
The work I was performing became easier... and I continued for quite a while with repeated clicks going back and forth, taking advantage of this behavior.
- **...was rejoicing...** LOL there is life under the hood after all, just don't know what/where/how to get this to occur! LOL
- then it **STOPPED! o! nohhh!...** _bummer!_
- see how I rationalized this temporary insanity in **'Steps to reproduce'**

### Steps to reproduce
 - was not able to duplicate it, have no idea how that surfaced _...but was fun while it lasted_
   and what had me was that I was able to click and click and click, and the behavior was solid!

**UPDATE - BRAIN STORM!**
- - -
- wireless mouse phart! _I could be wrong, but it certainly smells of mouse indigestion_
- I have been using a wireless mouse for about 9 months, and have sworn that as soon as I can remember to do it, I am going back to a wired mouse.
- though it does not do too much of that, a wireless simply forever mishits... and why daytrading sites warn of never using a wireless rodent on trade software!
- - -
### SQLiteStudio 3.2.1"

**Comment by tuffnatty** [comment]
@DingBEN Could you please close the issue if this problem is now resolved?
