### ISSUE TITLE
Use latest version of SqLite 3.30.1

### ISSUE THREAD

**Issue by docfresh** [pawelsalawa/sqlitestudio#3680]
Great app. We wish to use the latest version of SQLite that supports window functions (3.25 or higher).  When I open a .db file in SQLiteStudio 3.2.1 and run SELECT sqlite_version() , it returns 3.24.0, even if the .db file was created in a higher version of SQLite (3.30). Thanks

**Comment by pawelsalawa** [comment]
Duplicates #3471
