### ISSUE TITLE
first character cut off when importing CSV

### ISSUE THREAD

**Issue by MichalLeonBorsuk** [pawelsalawa/sqlitestudio#3682]
### Details
I've had the first character lost at a few occasions when importing CSV via Tools->Import. Same scenario works OK from the command line. (.import FILE TABLE)

### Steps to reproduce
1. Create an empty database
2. Import a CSV
3. First character in the first column is missing

The bug may limited to numeric values and comma-separated files. Try this: 
```
lat,lon,zone,MCC,MNC,area,tower_nbr,strength,net_type,detailed_net_type,channel,subch
49.47000000,11.13000000,371,2147483647,2147483647,2147483647,2147483647,-114,LTE,LTE,1801,82

```

### Operating system
Linux xxx 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### SQLiteStudio version
3.22.0 2018-01-22 18:45:57

**Comment by pawelsalawa** [comment]
Duplicates #3614
