### ISSUE TITLE
SUBSTR/INSTR Inconsistency with BLOBs input

### ISSUE THREAD

**Issue by fitdev** [pawelsalawa/sqlitestudio#3691]
### Details
I was trying to extract a substring from a Unicode Text column that is located between 2 known string. To do that I first found the location of the leading string using `INSTR` function and saved the results into a temporary table. So far so good, and `INSTR` reported proper indexes.

Then I proceeded to step to which required `SUBSTR` function to remove all preceding characters: `SELECT <columns>... SUBSTR([ColumnName], <InstrResultFromStep1ReadFromAColumn> + <fixed integer value>) AS NewColumnName...`. The results were that `NewColumnName` contained erroneous `SUBSTR` output: sometimes it was correct, sometimes it took too few characters from the left, and sometimes it took too many characters. In all cases, the second argument of `SUBSTR` supplied as an expression `<InstrResultFromStep1ReadFromAColumn> + <fixed integer value>` is always less than the total length of the first argument, and thus the function should always succeed and produce correct results.

### Steps to reproduce
Check results of `SUBSTR` function on any input with non-ASCII (Unicode) characters.

### Operating system
Win10 x64 1803

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
How does this work if you use https://sqlite.org/cli.html ? Is this working correctly there?

**Comment by fitdev** [comment]
Strangely the results are the same even with the latest version of SQLite CMD Tools. To be more explicit, here's the command:

```sql
CREATE TABLE temp_table2 AS SELECT id, raw, loc1, SUBSTR(raw, loc1+12) AS raw2 FROM temp_table1;
```

I guess it's a bug of sorts in SQLite library itself or I am doing something wrong, which I doubt.

**Comment by pawelsalawa** [comment]
You're using substr() incorrectly. See https://sqlite.org/lang_corefunc.html#substr
If you provide only 2 parameters (where 1st is string value to operate on), then second string is **starting** index, from which string will be taken until the end. If you want to take string from index `0` until `loc1+12`, then you need to do `SUBSTR(raw, 0 loc1+12)`.

**Comment by fitdev** [comment]
Thank you for looking into this. However, I am using it correctly, and I _did mean_ to use `SUBSTR` with 2 parameters where the second parameter is indeed the starting index. I am aware of how `SUBSTR` works, as it is quite similar across programming languages. In fact I also tried a more sophisticated version with 3 parameters, where I would pass the desired length, calculated to being equal to the rest of the string using `LENGTH` function and basic arithmetic.

The issue is that in both cases (whether 2 or 3 parameters are used) the results are wrong in the fact that the returned substring _starts at the wrong index_ most of the time (sometimes too far too the right, sometimes too far to the left). That is the starting index of the substring is totally inconsistent with the one returned by `INSTR` function and the actual correct index (`INSTR` works correctly in all cases as manually verified).

**Comment by pawelsalawa** [comment]
It may be that there is some kind of error in SQLite library, but I highly doubt it, as they have a team (or teams?) of testers.

Quoteing yourself from original post:

> Unicode Text column that is located between 2 known string

Given such problem, your usage is wrong, just like I explained above.

**Comment by pawelsalawa** [comment]
It may be that there is some kind of error in SQLite library, but I highly doubt it, as they have a team (or teams?) of testers.

Quoteing yourself from original post:

> Unicode Text column that is located between 2 known string

Given such problem, your usage is wrong, just like I explained above, because the second token, aka "second known string" is used to cut off everything on the left, whereas this is exactly what you wanted to keep.

**Comment by fitdev** [comment]
That was my initial thought that the bug is highly unlikely to be in the library itself. However, given that I did try it in the latest version of CLI that produced the same erroneous behavior it seems more likely now.

I understand what you mean, but my usage is not wrong. I simplified the example so that the issue is not polluted with unnecessary code and merely mentioned my use case to provide some background. The actual procedure involves 4 steps (in pseudo code):

- IndexOfPrefix = INSTR(input, prefix)
- Input2 = SUBSTR(input1, IndexOfPrefix)
- IndexOfSuffix = INSTR(input2, suffix)
- Result = SUBSTR(input2, IndexOfPrefix, IndexOfSuffix - IndexOfPrefix)

But that is irrelevant to the issue, hence I did not spell it out at first. What matters is that SUBSTR whether with 2 or 3 parameters produces erroneous results that are inconsistent with INSTR (which always produces correct results).

**Comment by pawelsalawa** [comment]
Last step has logical error. You're taking substring of `Input2` (which already is result of a substring on `Input1`) and you start form `IndexOfPrefix`, so in result you're removing `IndexOfPrefix` twice.

**Comment by pawelsalawa** [comment]
Last line should be: `Result = SUBSTR(input2, 0, IndexOfSuffix)`

**Comment by fitdev** [comment]
Right you are! Sorry it was a typo that I made here. I never actually got to step 4 in real life, since it was already broken at step 2. Fortunately, in my particular case input was json, so I used json extracting function instead. However the issues with SUBSTR still stands.

**Comment by pawelsalawa** [comment]
I'm curious. Can you create a sample table with just 1 column and 1 row (effectivly single value), where you apply this algorithm, and you could share it here with me, so I can play with it?

I'm still full of doubts about it :)

**Comment by pawelsalawa** [comment]
...of course including the cell value, prefix and suffix, so I can reproduce the issue.

**Comment by fitdev** [comment]
I have to apologize in opening this issue, as I made a silly mistake which I only now was able to realize.

The type of original column was `BLOB`, not `TEXT` as I initially thought (what put me off was the fact that SQLite Studio being a very good program displays raw binary values, and in may case all raw binary values were actually UTF8-encoded strings, leading me to think they were of type `TEXT`).

When I was creating temp table to store the results of `INSTR` in step 1, the type of `input` became unspecified, but still `BLOB` underneath.

The only thing that is still strange to me is why is there inconsistent behavior of `INSTR` vs `SUBSTR` when operating over UTF8 strings stored as `BLOB`s.

**Comment by pawelsalawa** [comment]
The case when one of parameters is blob and second is string (your case) is not defined as per the docs: https://sqlite.org/lang_corefunc.html#instr

Docs cover only situation when you pass 2 strings or 2 blogs. Thus I would expect undefined behavior from the function.

I agree it should be made clear and predictible, but it's not as bad as it seemed to at the beginning.

**Comment by fitdev** [comment]
Thank you for pointing this out! I guess the behavior that would make sense is that for `TEXT` both functions should operate consistently with chars, whereas for `BLOB`s the behavior would be the same, but they would operate on bytes instead.
