### ISSUE TITLE
High DPI support for Linux (Mint 19.3)?

### ISSUE THREAD

**Issue by Defcon0** [pawelsalawa/sqlitestudio#3693]
Hello,

at first thanks for the great software!

I have a question concerning the support of High DPI monitors like 4K monitors. Is there a plan to support this in the near future?

Thanks in advance!

Bye Defcon0

**Comment by pawelsalawa** [comment]
Rather not in near future, but it's definitely on the list to do.

**Comment by pawelsalawa** [comment]
Duplicates #3046
