### ISSUE TITLE
COMMIT CHANGES BUTTON NOT ACTIVATING AFTER VIEW STRUCTURE MODIFICATION

### ISSUE THREAD

**Issue by Guba666** [pawelsalawa/sqlitestudio#3695]
### Details
Hello. After having changed the Sql that generates a view the COMMIT button doesn't activate and remains gray. To commit the changes I have to click on DATA label above.

### Steps to reproduce
Make a change in the VIEW sql query and the commit doesn't return green.

### Operating system
W10

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
What is initial SQL and what is changed SQL?

I'm asking, cause I'm unable to reproduce it - for me it works all the time.

**Comment by Guba666** [comment]
I'm trying to reproduce a case, but now it seems impossible. 
Maybe I was making some kind of error in the SQL code, so I think now you can close this issue, and in case I see it again I will send you a post privately.

**Comment by Guba666** [comment]
Please send me an e-mail address to make a PayPal donation for the software.

**Comment by pawelsalawa** [comment]
There is a paypal widget on homepage at the bottom for that: https://sqlitestudio.pl/ Thanks!

**Comment by Guba666** [comment]
THe automatic widget doesn't work because I have another PayPal account
that I want to use for this donation while in the browser I have registered
some work account of my company that is different. To use it I should erase
the automatic cookies that bring the payment for onto the company account.
Please send your e-mail paypal account. I will not spread it, I promise.
Thanks

Sergio


Il giorno mar 10 mar 2020 alle ore 12:23 Paweł Salawa <
notifications@github.com> ha scritto:

**Comment by pawelsalawa** [comment]
I don't see any way to send private messages on github, but I don't want to leave another email address of mine for spam bots to crawl.

How about simply opening "private browsing" window in your browser?

**Comment by Guba666** [comment]
Hi Pawel
I sent you a donation of 30€ via PayPal
transaction ID:  6W483341JB198670A

Thanks for your precious tool.

Sergio


Il giorno mar 10 mar 2020 alle ore 18:17 Paweł Salawa <
notifications@github.com> ha scritto:

**Comment by pawelsalawa** [comment]
Thank you!

**Comment by piula** [comment]
Has this issue been fixed? I know that problem, it can be reproced as follows:

1. I'm using a new database, one table: CREATE TABLE a (id INTEGER);
2. Add a view: Name "b", Content "SELECT * FROM a;"
3. Apply it now --> this is no problem
4. Now edit the view: Place cursor behind "*", back-delete the asterisk and type it again.

Result: "Commit" button stays disabled.

**Comment by pawelsalawa** [comment]
Well, your view has not changed in that case, hasn't it? It makes no sense to commit anything.

**Comment by piula** [comment]
Ok, another example:

Same view "b", original content is:

SELECT SUM(id*id) FROM a

Now place the cursor behind the second "id", back-delete it so that id reads

SELECT SUM(id) FROM a

Result: "Commit" stays disabled.

**Comment by pawelsalawa** [comment]
I cannot reproduce it. Works for me.
Are you running version 3.2.1? What operating system?

**Comment by piula** [comment]
Yes, version 3.2.1 on Windows 8.1 x64, but I have similar problem in the office with Windows 10 x64:

Database -> Add -> New -> test.sqlite
Tables -> Add -> Name = "a", Add column "id INTEGER"
Views -> Add -> Name = "b", Content = "SELECT sum(id*id) FROM a" -> Apply

You can even leave it open. Click right to the second "id". Use backspace to delete 3 chars.

You can also use anything else, e.g. "SUM(2+3)", and delete "+3".

Imho it's a delete-only problem. Appearently, SQLiteStudio doesn't check syntax after deletion. If one adds anything else again, be it "+id" or "-7", "commit" gets enabled again.

If you wish, I can try to capture a screen video.

**Comment by pawelsalawa** [comment]
Confirmed.
