### ISSUE TITLE
JSON data does not display properly

### ISSUE THREAD

**Issue by skipmeister123** [pawelsalawa/sqlitestudio#3697]
### Details
I have data in a column formatted as json:

`{
    "0":[]
}`

The trailing `}` does not display, however:
![image](https://user-images.githubusercontent.com/1911919/76576084-712f8380-6497-11ea-99c0-5c2db88ad13a.png)

### Steps to reproduce
- Create a table
- Add a STRING column
- Insert the above data

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.
![image](https://user-images.githubusercontent.com/1911919/76576099-81476300-6497-11ea-940a-564d510da44d.png)

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
How about if you switch to "Form View" (or simply right click and pick "Edit in editor")? Is it there?

**Comment by skipmeister123** [comment]
It’s there, in both instances.



It’s just not there otherwise.  The data is intact, but it doesn’t display properly in list view.  Small but potentially important bug.

**Comment by pawelsalawa** [comment]
So... is there a "new line" character before this right bracket? Becuase that may be the reason. It's not a bug. Grid view has limited view possibilityies. If your value is complex, big or multiline, use Form View or Edit dialog for accessing full value.

**Comment by skipmeister123** [comment]
Correct. However it displays larger datasets without the same issue.

**Comment by pawelsalawa** [comment]
My guess is it depends on what kind of "new line" it is (Windows, Unix or Mac).

**Comment by skipmeister123** [comment]
Perhaps so.  I figured I'd report it, for visibility.  I have to remove all the line breaks, anyway, because sqlite doesn't really like doing queries on JSON data with line breaks. 🤷🏻‍♂️
