### ISSUE TITLE
Cannot manually enter page number in data grid

### ISSUE THREAD

**Issue by fitdev** [pawelsalawa/sqlitestudio#3698]
### Details
When a table or results contain many 1000s of records, results are displayed one page at a time, typically each page having 1000 rows. It is often useful to be able to type in the page number between the `<` and `>` buttons directly, hit Enter and have the program navigate to appropriate page. However hitting Enter does not do anything. The only way to page through the results is one at a time.

### Steps to reproduce
Display results with multiple pages, try entering a page number manually and hitting enter.

### Operating system
Win 10 x64 1803

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
This is exactly how it's supposed to work and on my computer it does.

You must be doing something differntly than me (and many other people :) ). Let's walk though it step by step:

1. You click on this...
![image](https://user-images.githubusercontent.com/481846/76663421-2853f980-6581-11ea-8ec7-9983650b6607.png)
...input box, right?
2. Then you override any value there with new page value of your choice.
3. Then you immediately hit Enter, right? You don't do anything else before Enter?

Questions:
1. Does the input page number revert to previous value? Or does it remain on the new value?
2. How do you tell if the page changed or no? Is there a chance that your new page has same, or very similar data and you didn't notice it's different page?

I'm just excluding any potential, yet easy mistakes.

**Comment by fitdev** [comment]
Thank you for such a quick response.

Yes, what you described is exactly what I do. In fact I tried other variants as well. like hitting / not hitting enter and then using arrow buttons (but they ignore whatever value in entered in the box and always behave as if I never typed anything new into the input box).

> Does the input page number revert to previous value? Or does it remain on the new value?

It remains on the new value until I use one of the left/right buttons. Then it reverts to whatever it was +/- 1 depending on which button I clicked (_not_ +/- 1 from the value I entered).

> How do you tell if the page changed or no? Is there a chance that your new page has same, or very similar data and you didn't notice it's different page?

No chance of that. First of all data across 1000 rows is different enough. Secondly, nothing happens in the UI. When it really fetches new data there is a small delay, in fact UI freezes for like half a second that you can see as it is fetching new records / refreshing controls. Here nothing happens.

**Comment by pawelsalawa** [comment]
That is really weird.

1. How many rows & columns you have in your table?
2. If you use "Go to last page" button (like icon below) which page does it bring you to? 
![image](https://user-images.githubusercontent.com/481846/76679312-d1c9d800-65df-11ea-9e86-1f6a04606d78.png)
3. Is your the custom page you tried to enter manually within the range of 1 to last page as discovered in point 2?

Can you reproduce it on any other table? Try creating a testing table and use "Populate" button from toolbar to put few thousands od rows there and check how it behaves there.

Is it reproducible in this case?

**Comment by fitdev** [comment]
1. I have had various numbers and seen it happen on different databases and tables. 100 000 - 1 000 000 rows fr example and around 10-20 columns.

2. Both the first and last page buttons work correctly all the time.

3. Absolutely! Well within the range.

Now that I have just tried it with a new temp database and temp table as you suggested. It works, even with my real databases and other tables where it did not work just yesterday. And I did not even restart SQLite Studio.

I remember it not working often enough (cannot say for sure whether it was the case every time), so I decided to file an issue yesterday. But now it seems to work very mysteriously. I will keep an eye on it and update the issue once I discover if there is anything specific that causes it to stop working.

**Comment by pawelsalawa** [comment]
Yes. Once I manage to reproduc it, I can fix it.

Are you perhaps having this trouble when browsing TABLE data, SELECT results, or VIEW data, or all of them?

**Comment by fitdev** [comment]
It was mostly TABLE data. Never tried it with SELECT results. And for VIEW data if I recall correctly it behaved the same as with TABLE data.

**Comment by pawelsalawa** [comment]
Okay. I see no other way but getting back to this once you step upon some reproducible case.

**Comment by fitdev** [comment]
Just tried it again with TABLE data (22 000, and 230 000 rows, page size 1000). It did not work in both cases. Does not matter if I first page to last page and try, or stay on first page and try, or advance by one and try. None worked.

However, then I decided to close the tab with the opened table, and reopen it again. Then everything started working again. So, a fix (temporary) is to close the active document and reopen it (just the tab).

This whole behavior is happening within a single session. I did not close SQLite Studio for a few days. Hope it helps.

**Comment by pawelsalawa** [comment]
Could you please start SQLiteStudio in debug mode and use it this way until you reach the problem? You can do it by starting it from command line and adding option `-d`.

Then in the application you have a debug console available under F12 key. You can close the console, it will log in background. When the problem happens, you can re-open the console and see if anything interesting is being logged there when you reproduce the problem.

**Comment by fitdev** [comment]
Just did as you suggested...

1. Start program with -d option
2. It loads my default workspace (all the dbs, tabs, etc.)
3. I try first table with ~200000 rows. It works.
4. I try second table with ~20000 rows. It works.
5. I switch back to the first table (double-click on the node in the tree view), click on Refresh data. Try to change page to 105 (pages go up to 201), and it doe _not_ work!
6. I press F12 to see the console. Nothing interesting. Only initialization messages from 3 minutes before (when the program was starting up).
7. I close the table, I reopen the same table, go to Data tab, wait for it to load, enter 105 again, and it works! No surprise, since I discovered last time that closing and reopening tab fixes the issue.

**Comment by pawelsalawa** [comment]
I got it! It's simpler than I expected.

Basically, when you use "next" or "prev" buttons first and then try to enter number - it won't work anymore. But if you enter number to a freshly open window, it works. Easy to reproduce, so will be fixed.

**Comment by fitdev** [comment]
Yeah, I think that's a correct description; though it may have something to do with the change in the total number of rows between refreshes as well. Glad you were able to reproduce it and will fix it.

**Comment by audiomuze** [comment]
> I got it! It's simpler than I expected.
> 
> Basically, when you use "next" or "prev" buttons first and then try to enter number - it won't work anymore. But if you enter number to a freshly open window, it works. Easy to reproduce, so will be fixed.

Sounds like the same bug I experienced months back but couldn't be replicated on your side.  Glad it's been replicated and confirmed now.
