### ISSUE TITLE
Execute single query in SQL editor

### ISSUE THREAD

**Issue by piula** [pawelsalawa/sqlitestudio#3714]
### Details
Suppose the following code open in .

### Steps to reproduce
1. Open an SQL editor window.
2. Type these commands, place the cursor to the position marked "|" afterwards:

CREATE TABLE a (id INTEGER);|
SELECT * FROM a;

3. Run single query.

Result: Statement 2 will be executed. This is, of course, logical, as the cursor is placed behind the first command. However, imho it would be more intuitive to nevertheless run the 1st statement as to the user, a line break is a harder separator than a semicolon. This behavior is used when the cursor is placed behind the last command, too.

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
It makes sense, although I'm worried about current users - they may get cought by surprise with this change.
I think SQLiteStudio should add a very subtle background on the "current query" every time user moves the cursor, to indicate which query is considered at the moment.

I will keep this issue as proposal for such change.

**Comment by piula** [comment]
Thank you very much. A decent highlighting will already be a great aid.

**Comment by pawelsalawa** [comment]
The behavior (how current query is determined) has not changed, because I have a strong opinion, that it should be consistent (i.e. after `;` it's another query), but I've added a highlighter to mark the current query for user's awareness.

This new highlighting can be disabled in configuration dialog.
