### ISSUE TITLE
Right Click/ Copy with Headers returns the first field name in the SELECT statement rather than the corresponding header

### ISSUE THREAD

**Issue by audiomuze** [pawelsalawa/sqlitestudio#3720]
### Details
Right clicking and selecting "Copy with Headers" to copy a single field value and then pasting it into another app pastes the incorrect field header along with the selected value.  The header that is copied appears to be the first field name in the SELECT statement rather than that of the field from which the selection is made.

### Steps to reproduce
Select a field value to copy, right click on it and select "Copy with Headers" or just select the field value to copy and hit Ctrl-Shift-C.  Now paste the value into a text  editor etc. and observe the result.  The header will be that of the first field named in the SELECT statement.

![image](https://user-images.githubusercontent.com/6852511/79637071-06e3c000-8174-11ea-899b-1751efda8bae.png)

![image](https://user-images.githubusercontent.com/6852511/79637089-2b3f9c80-8174-11ea-89e5-eb478fb4a4ce.png)

### Operating system
Linux, but guessing it's OS agnostic.

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Right. Confirmed here too.
