### ISSUE TITLE
Header Row - unable to view fully

### ISSUE THREAD

**Issue by klootz** [pawelsalawa/sqlitestudio#3722]
Hi,

I am unable to view the full headers after running a query.
![Capture](https://user-images.githubusercontent.com/63172037/79670692-42c86500-8208-11ea-9db2-ded6d78cab36.GIF)
On Windows 10, SQLiteStudio version 3.2.1
Thanks :-)

**Comment by pawelsalawa** [comment]
This is most likely due to scaling up UI elements in your system. I noticed that too on my work laptop.
Definitely something to fix.

**Comment by pawelsalawa** [comment]
In version 3.2.1 (and older) the workaround is to restart the app to have proper dimensions applied to the header (according to enlarged font).

Since 3.3.0 version, the font customization was removed. The application uses system fonts. Thus this should not happen anymore.
