### ISSUE TITLE
SqliteStudio 3.2.1 aborts during import csv

### ISSUE THREAD

**Issue by dmausner** [pawelsalawa/sqlitestudio#3732]
### Details
Attempt to import 83-line CSV file into existing, empty table. After completing import dialog, SqliteStudio aborts. First field is null value corresponding to integer primary key column. Expected import to supply unique primary key values + file's other field values.

### Steps to reproduce
Open merchant.zip. 
Run merchant.sql
Run SqliteStudio.
Import into merchant table. Specify file lakeMerchants.csv (no headers, comma separator, no null)

### Operating system
Windows 10.

### SQLiteStudio version
3.2.1.  Help/check for updates denies other updates exist.

[merchant.zip](https://github.com/pawelsalawa/sqlitestudio/files/4530182/merchant.zip)

**Comment by pawelsalawa** [comment]
Resolved with #3418
