### ISSUE TITLE
UPSERT not recognised even in the latest SQLite Studio

### ISSUE THREAD

**Issue by karolyjozsa** [pawelsalawa/sqlitestudio#3734]
### Details
The latest SQLite Studio should understand the UPSERT stated here:
https://www.sqlite.org/lang_UPSERT.html.
My SQLite Studio only accepts the NOTHING branch, but the UPDATE.

### Steps to reproduce

> INSERT INTO mytable (col1, col2) VALUES (1,2)
> ON CONFLICT DO UPDATE SET (col1, col2) = (1,2);

This SQL statement results the error message:
`Error while executing SQL query on database 'DB': near "UPDATE": syntax error`
Syntax checker marks the UPDATE word and onward red underlined.

### Operating system
Win10

### SQLiteStudio version
v3.2.1
Environment says SQLite 3 version is 3.24.0. I.e. it should be able to understand the upsert.

**Comment by pawelsalawa** [comment]
Action item: to make sure that CI/CD pipeline has UPSERT compile-time option enabled.

**Comment by pawelsalawa** [comment]
This is not a bug. UPSERT requires conflict target (column list), so to fix your query, it should be;
```
INSERT INTO mytable (col1, col2) VALUES (1,2)
ON CONFLICT (col1, col2) DO UPDATE SET (col1, col2) = (1,2);
```

From SQLite documentation:

> The syntax that occurs in between the "ON CONFLICT" and "DO" keywords is called the "conflict target". The conflict target specifies a specific uniqueness constraint that will trigger the upsert. **The conflict target is required for DO UPDATE upserts, but is optional for DO NOTHING.** When the conflict target is omitted, the upsert behavior is triggered by a violation of any uniqueness constraint on the table of the INSERT.
