### ISSUE TITLE
Cant write to a joined table

### ISSUE THREAD

**Issue by egpd1701** [pawelsalawa/sqlitestudio#3738]
### Details
Tried to commit a cell which is not editable (yet modified and waiting for commit)! This is a bug. Please report it.

### Steps to reproduce
select Aircraft.AircraftID, Aircraft.ModeS, Aircraft.Registration, Aircraft.Manufacturer, Aircraft.ICAOTypeCode, Aircraft.Type, Aircraft.SerialNo, Aircraft.PopularName, Aircraft.GenericName, Aircraft.AircraftClass, Aircraft.Engines, Aircraft.RegisteredOwners, Aircraft.UserString3, Aircraft.OperatorFlagCode, Aircraft.ModeSCountry, Flights.Callsign 

From Aircraft

Inner JOIN Flights on Flights.AircraftID = Aircraft.AircraftID

where flights.Callsign like '%log84jn%'

Group By Aircraft.AircraftID

Error that came up when editing a cell from output of joined table

### Win 10 (1909) - 18363.815
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio 3.2.1
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment]
Let me guess - you copy-pasted data into table?

**Comment by egpd1701** [comment]
I coped 1 cell to another cell in a joined form.

This works perfectly well when the tables are singular but just not joined.



If you're not on the edge, then you're taking up too much space!

________________________________

**Comment by pawelsalawa** [comment]
Joining is not a proble. Grouping is.

Generally, when you use GROUP BY, you will be forbidden to edit any results. If you double-click on a cell, you will see corresponding message, stating you cannot do it.

The fact that you could copy-paste value is a bug and it's fixed for upcoming 3.2.2 version #3537
