### ISSUE TITLE
Broke

### ISSUE THREAD

**Issue by NickAtNight62** [pawelsalawa/sqlitestudio#3739]
### Details
[12:46:11] Unable to check for updates (Cannot retrieve remote tree No package sources set for this application..)

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment]
Automatic updates are in process of removal (#3626). It's also mentioned at recent news: https://sqlitestudio.pl/news/#144
