### ISSUE TITLE
What happens to the translation?

### ISSUE THREAD

**Issue by realpack** [pawelsalawa/sqlitestudio#3740]
It's about this commit.
https://github.com/pawelsalawa/sqlitestudio/commit/ded744cf17c74e51ff5db51b3a3872373f49a0ff#diff-4a1f2f515627378c9a4751c9379df400L62-L69

https://github.com/pawelsalawa/sqlitestudio/blob/ded744cf17c74e51ff5db51b3a3872373f49a0ff/Plugins/MultiEditorImage/translations/MultiEditorImage_de_DE.ts#L61-L69

In different languages in different ways, for example Russian:
https://github.com/pawelsalawa/sqlitestudio/blob/ded744cf17c74e51ff5db51b3a3872373f49a0ff/Plugins/MultiEditorImage/translations/MultiEditorImage_ru_RU.ts#L61-L69

**Comment by pawelsalawa** [comment]
Probably I misclicked during conflict resolving. Does thas cause problems in translation? They both seem to be handled similarly, don't they?

**Comment by realpack** [comment]
> Probably I misclicked during conflict resolving. Does thas cause problems in translation? They both seem to be handled similarly, don't they?

Yes, it causes unnecessary bewilderment. I think it's worth fixing it.

**Comment by pawelsalawa** [comment]
Git it. Fixed.
