### ISSUE TITLE
Cant open db on Windows 10 WSL 2

### ISSUE THREAD

**Issue by krateria** [pawelsalawa/sqlitestudio#3742]
### Details
Cant open db on Windows 10 WSL 2
It returns Could not add database /Ubuntu/home/username/file.db

### Steps to reproduce
Open a db file on a WSL2 filesystem, with SQLite Studio Windows version

### Operating system
Windows 10 Release 2004

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
WSL (including 2nd version) isn't reliable environment whether something is broken in the app, or in WSL itself. There are several issues with accessing Linux filesystem from Windows in WSL, for example https://github.com/microsoft/WSL/issues/4260

As far as I know it's not even officially supported to work with Linux files from Windows apps. The other way around is advised (to work with Windows files from Linux apps).

**Comment by 4n70w4** [comment]
the same issue.

![image](https://user-images.githubusercontent.com/38257723/130612796-37d93d5e-7559-4c80-a251-13b34879b433.png)

In this window filepach converted from 
`\\wsl$\Ubuntu\home\us\projects\zz\promo\database\database.sqlite` to `/Ubuntu/home/us/projects/zz/promo/database/database.sqlite` and can't access to file via incorrect path.

**Comment by Underdoge** [comment]
Any updates? Having the same issue here with the latest version 3.4.0

**Comment by pawelsalawa** [comment]
Please see my answer above (from May 6th, 2020).
