### ISSUE TITLE
CLI can't add database that exists

### ISSUE THREAD

**Issue by Lbates35406-github** [pawelsalawa/sqlitestudio#3758]
### Details
First time trying to use SQLite CLI to connect to database

### Steps to reproduce
enter the command
spx>.open C:/ProgramData/StorageCraft/spx/spx.db3
Could not add database C:/ProgramData/StorageCraft/spx/spx.db3 to list.

This database most definitely exists at the path specified.

### Operating system
Windows 2016 Server command prompt window

### SQLiteStudio version
3.1.1

**Comment by Lbates35406-github** [comment]
Well I believe I understand the problem.  I had opened this database in the GUI and apparently it had saved it somewhere.  When I tried to open it in the CLI it errors instead of either saying nothing or saying database already exists in the list.

**Comment by pawelsalawa** [comment]
Also, see `.help` in CLI.
