### ISSUE TITLE
Multiple Instances for Different Users in Ubuntu 18.04

### ISSUE THREAD

**Issue by raprice3** [pawelsalawa/sqlitestudio#3759]
### Details
I installed SQLite Studio in Ubuntu 18.04, and can get it to work fine.  I am having two issues.

First, on a server with multiple users, only one instance of SQLite Studio can be running at once.  I would like for multiple users to be able to use it at once.  This issue applies whether I use the installer or use the portable version.  Maybe this isn't a bug but a limitation.  It would be nice to run multiple instances across different users.

Second, when SQLite Studio (sqlitestudio program) is running, and possibly when the sqlitestudiocli program is running, the syslog gets huge.  I had several instances of sqlitestudiocli running in the background, and I left SQLite Studio running for several days and the syslog file got to 15 GB.  I had to manually terminate the sqlitestudiocli processes, which I ignorantly started by clicking on the icon not understanding the difference between it and sqlitestudio, and closed the SQLite Studio program.  

Here is how I identified sqlitestudiocli processes and manually killed them:

```
richardp@richardp:/$ ps aux | grep -i SQL

richardp  2498 99.5  0.0 2333108 22500 ?       Sl   May12 2881:48 /home/richardp/Downloads/sqlitestudio-3.2.1/SQLiteStudio/sqlitestudiocli
richardp  2511 99.5  0.0 2333096 22600 ?       Sl   May12 2881:41 /home/richardp/Downloads/sqlitestudio-3.2.1/SQLiteStudio/sqlitestudiocli
richardp 10939 81.4  0.0 2333132 22508 ?       Sl   11:30   5:16 /home/richardp/Downloads/sqlitestudio-3.2.1/SQLiteStudio/sqlitestudiocli
richardp 10944 81.4  0.0 2333100 22692 ?       Sl   11:30   5:15 /home/richardp/Downloads/sqlitestudio-3.2.1/SQLiteStudio/sqlitestudiocli
richardp 11212  0.0  0.0  21536  1068 pts/5    S+   11:36   0:00 grep -i SQL
richardp 11231 99.9  0.0 2333136 22576 ?       Sl   Apr24 28628:06 /home/richardp/Downloads/sqlitestudio-3.2.1/SQLiteStudio/sqlitestudiocli
richardp 13337  3.0  0.1 2602828 51348 ?       Sl   12:51   0:00 /home/richardp/Downloads/sqlitestudio-3.2.1/SQLiteStudio/sqlitestudio

kill 2498 
...
```

Here is a snippet of the syslog file that was repeated thousands of times.  The wrds_datasets_all is the name of a database I use.

```
May 14 00:07:57 richardp org.gnome.Nautilus[23491]: atasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds
_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>
wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_
all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datas
ets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_d
atasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wr
ds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_all>wrds_datasets_al
```

I reduced the size of the log as follows after browing to the /var/log directory:

`sudo truncate --size 10000 syslog`

### Steps to reproduce

First issue (only one instance will run for one user): using either the installer or the portable version, open SQLite Studio for one user, then attempt for another user.  I am unable to do it for more than one user at a time.  There is no error message, there is simply no response when attempting with a second user.

Second issue (large syslog file): Open SQLite Studio and leave it open, monitor syslog size.

### Operating system
Ubuntu 18.04

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Issue of running independent instances across different Unix users is now fixed.

Remaining issue is overcrowding the syslog.

**Comment by pawelsalawa** [comment]
The syslog issue happens becasue the `sqlitestudiocli` was executed directly from Nautilus, while `sqlitestudiocli` is pure terminal application and uses the `readline` library, thus when executed from Nautilus may result in lots of logs in syslog, but this is because Nautilus redirects stdoutput to syslog. Ergo, **do not** run `sqlitestudiocli` from Nautilus, but instead from a terminal and everything will be alright.

Closing the bug, as the only other issue was already solved with the recent commit.
