### ISSUE TITLE
Warning about inability to restore the view before databases from the command line are opened

### ISSUE THREAD

**Issue by yurivict** [pawelsalawa/sqlitestudio#3760]
I start SQLiteStudio with a previously-opened database in a command line.
It complains that the view from the not-yet-opened database can't be restored.

See the screenshot:
![image](https://user-images.githubusercontent.com/271906/81969915-84fc8080-95d3-11ea-9c35-b211da86cb57.png)

**Comment by pawelsalawa** [comment]
Windows from temporary databases are not supposed to be restored in next session. If you want to maintain windows between different sessions, have the database added permanently to the database list.

This warning was removed.
