### ISSUE TITLE
drop 

### ISSUE THREAD

**Issue by AGoh2019** [pawelsalawa/sqlitestudio#3761]
1.  drop table command does not function, even with all the databases open 
2.  Would like to be able to create a table using the SQL Editor

Database is open. When trying to drop database called 'proglang_tblcopy' received this feedback:
> [14:50:20] Error while executing SQL query on database 'proglang_tblcopy': no such table: proglang_tblcopy

**Comment by AGoh2019** [comment]
1.  drop table command does not function, even with all the databases open 
2.  Would like to be able to create a table using the SQL Editor

**Comment by pawelsalawa** [comment]
Do you have correct "context database" selected in your SQL Editor? I mean this:

![image](https://user-images.githubusercontent.com/481846/82122984-3861a280-9797-11ea-9fff-4f4129b44c0f.png)

**Comment by AGoh2019** [comment]
And these are the files in my SQLite directory:
   
   - sqldiff.exe
   - sqlite3.def
   - sqlite3.dll
   - sqlite3.exe
   - sqlite_analyzer.exe

Regards,
Andrew Goh S M

 

    On Saturday, 16 May 2020, 11:04:21 pm GMT+8, Paweł Salawa <notifications@github.com> wrote:  
 
 


Do you have correct "context database" selected in your SQL Editor? I mean this:

**Comment by pawelsalawa** [comment]
This is irrelevant. Did you see screenshot from my previous comment?

**Comment by AGoh2019** [comment]
Yes, I took a look at the screen-shot. Maybe, you could write up a tutorial on how to use the latest version of SQLite.
Regards,
Andrew Goh S M

 

    On Sunday, 17 May 2020, 06:04:03 pm GMT+8, Paweł Salawa <notifications@github.com> wrote:  
 
 


This is irrelevant. Did you see screenshot from my previous comment?

**Comment by pawelsalawa** [comment]
What is the problem then? Because initially you wrote you're unable to drop table, but now it seems it's not the problem?

**Comment by AGoh2019** [comment]
Thanks for your time.  I am ordering a book on how to use SQLite productively.
Andrew Goh S M

 

    On Sunday, 17 May 2020, 08:37:58 pm GMT+8, Paweł Salawa <notifications@github.com> wrote:  
 
 


What is the problem then? Because initially you wrote you're unable to drop table, but now it seems it's not the problem?

**Comment by pawelsalawa** [comment]
So... is there a question?

**Comment by AGoh2019** [comment]
No, not for the moment.  I would like to suggest to the maintainers of SQLite Studio to prepare a tutorial for those like myself who are using SQLite to learn SQL. What is most frustrating is when the documentation doesn't show examples of how the different commands are used.
Andrew Goh S M

 

    On Monday, 18 May 2020, 01:52:16 am GMT+8, Paweł Salawa <notifications@github.com> wrote:  
 
 


Reopened #3761.

**Comment by pawelsalawa** [comment]
Believe me, there is so much work on the project itself, I would rather not spend my time on tutorials. Escpecially there is tons of materials all over the internet.
