### ISSUE TITLE
Drop

### ISSUE THREAD

**Issue by AGoh2019** [pawelsalawa/sqlitestudio#3762]
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by AGoh2019** [comment]
Database is open. When trying to drop database called 'proglang_tblcopy' received this feedback:
[14:50:20] Error while executing SQL query on database 'proglang_tblcopy': no such table: proglang_tblcopy

**Comment by pawelsalawa** [comment]
Duplicate of #3761
