### ISSUE TITLE
Generated columns support

### ISSUE THREAD

**Issue by PieterJvZ** [pawelsalawa/sqlitestudio#3763]
Add support for generated columns introduced in recent SQLite versions.

**Comment by pawelsalawa** [comment]
Full support is planned for 3.3.0.

Currently I'm working on 3.2.2, which is mostly about bugfixes (but will have minor features added too). It will also use more recent SQLite version, so you should be able to work with these columns from SQL Editor window level (but not from Table Window yet).

I think it may take around 2 months to release 3.2.2 (as a lot of bugs have accumulated throughout couple of years, during which I wasn't as actively developing the project).

After that I will work on 3.3.0, which may take another couple of months.

**Comment by PieterJvZ** [comment]
Thank you so much. Your product is absolutely brilliant. Keep up the good work. There are thousands of us out there truly appreciating your extra-ordinary programming skills and commitment :)
