### ISSUE TITLE
No navigation to unloaded rows

### ISSUE THREAD

**Issue by balajiramanathan** [pawelsalawa/sqlitestudio#3765]
### Details
If a table, view or query has too many columns, the number of rows loaded is restricted (seems to be about 150k total data elements across all rows and columns).  When this happens, only the top n rows of the table are loaded, and you can't navigate to the later ones using the arrow keys or any other method.  I can set the default to load less than n rows, then the arrow keys work to move around from one set of n rows to the next set of n rows, etc., but if the default number of rows to be loaded is greater than n, I am stuck with the first n rows.

### Steps to reproduce
Create a large table with more than 300 columns and more than 10000 rows.  Set the number of rows per page to 10000 (under Settings -> Data browsing and editing -> Number of Data Rows per page).  Load the table data.  It will load about 5000 rows and there will be no way to look at an unloaded row (row 6000 or 10000 for example).

### Operating system
Windows 7

### SQLiteStudio version
SQLite 3.31.1

**Comment by balajiramanathan** [comment]
I have attached screenshots using a table with 97 columns and 3488 rows.  I set the number of rows per page to 5000.  As you can see, SQLiteStudio loaded only 1546 rows because of the number of columns, but there is no way to go to any rows beyond the 1546 because the arrow keys for navigating pages are disabled at the top of the view.

![Capture](https://user-images.githubusercontent.com/11827185/82130384-8a52fa00-9790-11ea-8bd8-d08388420cd6.PNG)
![Capture1](https://user-images.githubusercontent.com/11827185/82130385-8aeb9080-9790-11ea-865f-b6d85109eab0.PNG)

**Comment by pawelsalawa** [comment]
This one is fixed for 3.2.2, here: #3558

**Comment by balajiramanathan** [comment]
Thank you very much.
