### ISSUE TITLE
3.31 manual dll replacement workarounds

### ISSUE THREAD

**Issue by tinmanjk** [pawelsalawa/sqlitestudio#3768]
I was excited by this [post ](https://sqlitestudio.pl/news/#144) on the official website, mentioning newer version support (SQLite3 version updated to 3.30/3.31 ). 
However, the latest download release is still 3.2.1 which has the 3.24 sqlite library (not 3.30/3.31).

Until 3.2.2 is released, what would be a safe workaround(s)?

Besides the one for the newer ALTER TABLE enhancements mentioned in the official [documentation](https://www.sqlite.org/lang_altertable.html) in the Comparability Note section, are there other adjustments needed to be made to have an acceptable use?

**Comment by pawelsalawa** [comment]
You may replace sqlite3.dll in SQLiteStudio's directory with the new version from sqlite.org. It won't give you nice UI interface for new fewatures from SQLite 3.31, but at least you will be able to execute new queries from SQL Editor.

**Comment by tinmanjk** [comment]
Ok, so SQLCipher's plug-in stopped working with the newer version of the library.

**Comment by pawelsalawa** [comment]
Well, yeah. It uses it's own SQLite version internally. For that one to update you need to wait for new SQLiteStudio version.

**Comment by tinmanjk** [comment]
Yeah, I know. Should be 3.20.1 while main SQLiteStudio uses 3.24. So already a mismatch there but still working. 
Anyway, wanted to mention it in case somebody else stumbles upon this issue in the meantime.

**Comment by sergiozacca** [comment]
Hi, in addiction to this, is there any way to use a newer SQLite version in SQLiteStudio for Mac, like can be done in Windows changing the dll file?

**Comment by sergiozacca** [comment]
Thanks, it worked! I founded it on /Applications/SQLiteStudio.app/Contents/Frameworks, then I have copied a newer version (from other tool) and now I can work if a higher version.
