### ISSUE TITLE
Default Data Types Dropdown 

### ISSUE THREAD

**Issue by tinmanjk** [pawelsalawa/sqlitestudio#3769]
Would it be possible to limit the default data types to 4-5 based on storage classes/type affinities, i.e. INTEGER, REAL etc.
Alternatively maybe we could delete the ones that are default now.

Reason is that the dropdown (although you can bypass it by typing) is somewhat cluttered and maybe a bit misleading to an uninitiated sqlite beginner.

**Comment by pawelsalawa** [comment]
Right. I was already considering redesign of that. I would like this to be part of #3727

**Comment by tinmanjk** [comment]
Great, thanks!
