### ISSUE TITLE
semicolon separator in group_concat() function causes an error

### ISSUE THREAD

**Issue by ciaranmcnamara** [pawelsalawa/sqlitestudio#3777]
Using a semicolon as a separator in group_concat fails with a "Result set expired or no row available error". E.g. the first SELECT below is successful, but the second fails. 
I'm using version 3.1.1 of SqliteStudio.

CREATE TABLE test (name, year);
INSERT INTO test VALUES ("James", 1899), ("William", 1908), ("William", 1909), ("Kate", 1899), ("Patrick", 1910), ("Patrick", 1911);
SELECT name, group_concat(year,"|") AS years FROM test GROUP BY name ORDER BY name;  -- Successful
SELECT name, group_concat(year,";") AS years FROM test GROUP BY name ORDER BY name;  -- Error, Result set expired or no row available

**Comment by pawelsalawa** [comment]
Please try with SQLiteStudio 3.2.1 first. If the problem exists there too, please report back here, in comment. If it works in 3.2.1, please also tell it works, so I can close this ticket. Thanks.

**Comment by ciaranmcnamara** [comment]
I tried with SQLiteStudio 3.2.1, & received error 'Error while executing SQL query on database 'test': unrecognized token: "") LIMIT 1000 OFFSET 0"'

**Comment by pawelsalawa** [comment]
You must have done something differently. I just tried exactly your example and I got:
![image](https://user-images.githubusercontent.com/481846/82953448-15ab6700-9fab-11ea-9d28-cd2527fb3e0b.png)

Perhaps you're selecting only a part of query when you execute? Be aware, that if you select any text and execute - only selected text is executed. If you don't select anything, a single, entire query under current insertion cursor position will be executed.

**Comment by ciaranmcnamara** [comment]
Thanks, Paweł. I've checked again - when the entire query is selected, it works as intended. With nothing selected (cursor at start of line), the "unrecognised token" error occurs & the query, up to first semicolon is highlighted.

![sqlitestudio-highlight](https://user-images.githubusercontent.com/1372986/82961699-07167d00-9fb6-11ea-9c4f-d90618d1f824.png)

With nothing selected (cursor placed after quoted semicolon), the "Result set expired or no row available" error occurs & the query is highlighted from the quoted semicolon to the final semicolon. I think the parser may be confused by the quoted semicolon. But selecting the entire query works, as does Export, so you can close this issue.

**Comment by pawelsalawa** [comment]
You're right. A peculiar bug ;)

**Comment by bpierson** [comment]
@pawelsalawa my guess is that since the `;` is a SQL statement terminator, your parser is probably looking for the first instance of that as the statement terminator, even if it appears within a string. So it is selecting up to that point and attempting to run.

**Comment by pawelsalawa** [comment]
Covered with #3445
