### ISSUE TITLE
Unable to download Version 3.2.1

### ISSUE THREAD

**Issue by cmhausknecht** [pawelsalawa/sqlitestudio#3790]
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment]
Can you be more precise? Are you downloading file from https://github.com/pawelsalawa/sqlitestudio/releases ?

**Comment by cmhausknecht** [comment]
Hi

 

I started with this site:  https://sqlitestudio.pl/features/  I went through the steps for the github sign up ended up with sqlitestudio-2.1.3, which is not the correct version.  I can’t seem to find the link I actually used, but once at the github site now, I don’t know what I am supposed to do to download the software.  By the way I did try one of the other downloader sites (I think is it was filehorse.com) and I got a malware alert, so I abandoned that one.  While I had the 2.1.3 active, it did not actually act like a download though I was able to open the application.  I tried to click on the options to check for updates to see if that might find the newer version but it did not.

 

I have Windows 7 OS.  From this screen here, what would I click to get the software downloaded?  What I am using it for is an online training class in SQL for beginners.  Are you able to advise?

 



 

 

 

Thank you

Carol H

 

Carol Hausknecht

Contact information:

Home 330-245-1801 

Cell 440-227-8427

**Comment by pawelsalawa** [comment]
I'm not sure why would you need to sign up at github.

All you needed to do is to click Download link:
![image](https://user-images.githubusercontent.com/481846/83815360-4fbdec80-a6c0-11ea-8514-2f887a6d5dc8.png)

It would redirect you to the releases page: https://github.com/pawelsalawa/sqlitestudio/releases
where you download file for your operating system:
![image](https://user-images.githubusercontent.com/481846/83815505-a3303a80-a6c0-11ea-9a9e-9ee11335f445.png)


OR...


Go to https://sqlitestudio.pl/ and hit "Download" button.
![image](https://user-images.githubusercontent.com/481846/83815591-ce1a8e80-a6c0-11ea-8f8d-f943f68dbb1e.png)

It will automatically detect correct file for your operating system and start the download.

**Comment by cmhausknecht** [comment]
I am not sure either.  I did try the suggestion you have at the bottom and it did appear to provide the zip file, which opens to this

 



 

 

And it further opens to his (partial snip)



 

 

And then I get to this.  It did not open like the instructor’s demo showed where I would accept defaults as I stepped through a set up wizard.  So I am not sure if I got what I should have gotten or not.  I also used Google Chrome for the download, though I don’t know if that should make a different or not.

 



 

 

Thank you

Carol H

 

Carol Hausknecht

Contact information:

Home 330-245-1801 

Cell 440-227-8427

**Comment by pawelsalawa** [comment]
Unfortunately, whatever pictures you posted, they're not visible.

Anyway. Yes. You will download a zip. Alternative to zip is an installer (you know, that "next", "next", "next", "done"), but for that you would have to go with the first approach (the Relases page).

Anyway, since you have the zip:
![image](https://user-images.githubusercontent.com/481846/83816737-5f8b0000-a6c3-11ea-90db-6c4270202e46.png)

Just unzip it. You will get SQLiteStudio directory. Go into it. You will have files like:
![image](https://user-images.githubusercontent.com/481846/83816819-982ad980-a6c3-11ea-879f-af1957d0082e.png)


Double click on the one I marked.

**Comment by cmhausknecht** [comment]
Ok.  I will work with it..  What I sent was snips of the directory.  I did not get a Wizard like I would usually get for downloaded zip files. Thank you very much for your help.

 

Thank you

Carol H

 

Carol Hausknecht

Contact information:

Home 330-245-1801 

Cell 440-227-8427
