### ISSUE TITLE
SQL runtime crashes. How can I retrieve the unsaved SQL, 3.2.1

### ISSUE THREAD

**Issue by MinaAndLuoXia** [pawelsalawa/sqlitestudio#3796]
### Details
SQL runtime crashes. How can I retrieve the unsaved SQL, 3.2.1

### Operating system
Ubuntu 18.04.1

### SQLiteStudio version
3.2.1

**Comment by MinaAndLuoXia** [comment]
￣へ￣

**Comment by pawelsalawa** [comment]
If you executed it at least once, you will have it in History tab in SQL editor:
![image](https://user-images.githubusercontent.com/481846/84898394-7825ed80-b0a7-11ea-8c1f-bb064a749aad.png)

**Comment by MinaAndLuoXia** [comment]
Thank you. It solved my problem
