### ISSUE TITLE
how to use placeholder query?

### ISSUE THREAD

**Issue by liyonghuan** [pawelsalawa/sqlitestudio#3797]
like ?1 or ${NAME}

**Comment by pawelsalawa** [comment]
The ?1 format is correct. The ${NAME} is incorrect.
See https://sqlite.org/lang_expr.html (paragraph 4) for all possible bind parameter formats.

Also be aware, that support for bind parameter is present in SQLiteStudio 3.2.1, but I not in 3.1.x, so be sure to use latest version.

**Comment by liyonghuan** [comment]
I see. Thank you.
