### ISSUE TITLE
Display blobs as "human readable" GUIDs and paste .NET GUIDs 

### ISSUE THREAD

**Issue by gentledepp** [pawelsalawa/sqlitestudio#3798]
### Details
We are using SQLite in a mobile application (built with Xamarin and .NET/C#). For our primary keys, we mainly use `System.Guid` s which are stored as blobs in SQLite for technical and performance reasonss.
Now, when opening such a database in SQLite Studio, it is hard to quickly find rows, because
1. the cells containing guids are shown as unreadable blobs
![image](https://user-images.githubusercontent.com/1175751/85002474-381d4400-b155-11ea-9110-7aae2c4f4f90.png)
Now, to convert it to the string representation known to us .NET developers, we need to use the following SQL monstrosity:
```sql
SELECT
  substr(hguid, 7, 2) || substr(hguid, 5, 2) 
    || substr(hguid, 3, 2) || substr(hguid, 1, 2) || '-'
  || substr(hguid, 11, 2) || substr(hguid, 9, 2) || '-'
  || substr(hguid, 15, 2) || substr(hguid, 13, 2) || '-'
  || substr(hguid, 17, 4) || '-'
  || substr(hguid, 21, 12)

AS guid
FROM (SELECT hex(id) AS hguid from contentitems)
limit 1;
```
At least then, we get the desired result:
![image](https://user-images.githubusercontent.com/1175751/85004039-5ab05c80-b157-11ea-8635-250537815820.png)

2. When searching for a specific row by guid, this does not work either.
What we'd like to do is 
```sql
select * from contentitems where id = '100F0000-1B41-4DFE-AF44-087F7C20657C'
```
💡 Note: This sample uses the very same identity as in the first sample above.
However, in order to actually search for this identity, we need to use a different format - the one that is created by SQLite Studio when creating a select query for the row:
![image](https://user-images.githubusercontent.com/1175751/85002836-b1b53200-b155-11ea-811e-9592191e44e9.png)
 ```sql 
...
WHERE Id = X'5C903CAF35BA4D428196C9D4E7347C52';
```

Now we would love to have the following two features
1. Add a settings to SQLite Studio "attempt to display blobs as guids"
Iin case a blob column is exactly 16 bytes long (or even better: If all rows in that column are either 16 bytes long or null) try to display them as guids

2. Add another option to actually use guid values in filters.
I am not sure whether there is a *clean* way to extend the SQL parser to support something like:
```sql
...
WHERE Id = G'100F0000-1B41-4DFE-AF44-087F7C20657C';
``` 
If that is not possible or not wanted, maybe just add a "Paste GUID" to the context menu:
![image](https://user-images.githubusercontent.com/1175751/85003623-bfb78280-b156-11ea-9fb0-27192a8f9613.png)

which takes a string of form `100F0000-1B41-4DFE-AF44-087F7C20657C` and pastes it as
```sql
X'5C903CAF35BA4D428196C9D4E7347C52' /*100F0000-1B41-4DFE-AF44-087F7C20657C*/
```
Notice that it would be great to have the original guid as a comment for better readability.

This would really mean a big improvement in our daily work.
Would this be a feature you could think of?
Please let us know your thoughts!

**Comment by gentledepp** [comment]
@BrayanKhosravian, @bruzkovsky

**Comment by pawelsalawa** [comment]
GUID representation is very specific for your particular solution (Xamarin) and is not universal for SQLite in general.

It could be done as additional plugin (or simply use the custom function as shown below), but being honest with you - there are more urgent matters than this to be done. We can leave the issue on the list for reference.

You can create SQL function to make you work with guids easier:

![image](https://user-images.githubusercontent.com/481846/85020654-f0a4b100-b170-11ea-905c-522afd3a6fbc.png)

Make sure to commit the function in the end. Then you can use it like:
```
SELECT guid(Id), ...
```
```
...
WHERE guid(Id) = '100F0000-1B41-4DFE-AF44-087F7C20657C';
```

**Comment by gentledepp** [comment]
THIS IS ALL WE NEED! 
Awesome - thanks! 🎉
