### ISSUE TITLE
Image in BLOB field is not visible in editor

### ISSUE THREAD

**Issue by Orlando522** [pawelsalawa/sqlitestudio#3801]
Hello,
I'm new in using SQLiteStudio 3.2.1 on Linux Mint 19.3 Cinnamon.
I have already created database in SQLite and when I try to show image in editor view from blob field nothing is visible only some small white rectangle in top left corner.
Is it bug or should I change some settings ?
Thanks

**Comment by pawelsalawa** [comment]
Can you show a screenshot of what you mean?

**Comment by Orlando522** [comment]
This is Hex view
![obrazek](https://user-images.githubusercontent.com/62427576/85230149-8e58e400-b3ee-11ea-811a-0a50da26cdda.png)
And this is Image view
![obrazek](https://user-images.githubusercontent.com/62427576/85230163-a597d180-b3ee-11ea-89f9-f1ffa4f1dec4.png)

**Comment by Orlando522** [comment]
I tried to insert GIF and PNG images and that was OK. Problem is only with JPG images.

**Comment by pawelsalawa** [comment]
I see.

Can you run SQLiteStudio in debug mode? (add `-d --debug-stdout` option in command line). Once in debug mode, go to this Image tab and then see in your command line if there are any relevant messages about this problem.

**Comment by Orlando522** [comment]
Unfortunately I don't know hot to run it in debug mode because executable file is associated with Wine emulator that I don't understand. It should be Linux version so why it is associated with Wine ? I'm using portable version. If I try to type `sqlitestudio -d --debug-stdout` then answer is "command not found".

**Comment by pawelsalawa** [comment]
It looks like you've downloaded Windows version then.
Where did you download it from, and which file exactly?

Normally, when you go to https://sqlitestudio.pl/ you will have a "download" button in front of you, pointing to appropriate (Windows, Linux or MacOS) file, depending on operating system which you currently use. Just click to download and you should have correct file for your system.

**Comment by Orlando522** [comment]
That strange, because I downloaded `sqlitestudio-3.2.1.tar.xz` file.

**Comment by pawelsalawa** [comment]
Okay. I don't know why it's associated with Wine then.
Nevertheless, once you decompressed the archive, open terminal and go to the directory created from decompressing:
```
cd path/to/SQLiteStudio
```
and from there:
```
./sqlitestudio -d --debug-stdout
```

**Comment by Orlando522** [comment]
so this is result:
![obrazek](https://user-images.githubusercontent.com/62427576/85265790-15e83680-b473-11ea-9054-b96b523d848e.png)

**Comment by pawelsalawa** [comment]
Just to be sure - this is output **after** you tried to show image in the "Image" tab?

**Comment by Orlando522** [comment]
Yes

**Comment by Orlando522** [comment]
But this report is after open the DB. When I tried to show Image nothing is added to the terminal.

**Comment by pawelsalawa** [comment]
Is there a chance you could share such problematic image file with me?
I think it's best if you sent it to support@sqlitestudio.pl, so it's not processed in any way by github.

**Comment by Orlando522** [comment]
I've sent it to the mail.

**Comment by pawelsalawa** [comment]
After followup in emails, this seems to be affecting 3.2.1, but is fixed in 3.2.2 (in development).
