### ISSUE TITLE
Long text in VIEW unviewable and uncopiable.

### ISSUE THREAD

**Issue by ysalmon** [pawelsalawa/sqlitestudio#3802]
### Details
When a VIEW has a cell with a lengthy text, switching to the Form display in the Data panel shows an empty text. So does the Show value in a viewer feature. The Copy and Copy with headers also give an empty text (the content of the clipboard is erased).

This does not happen if the text is not too lengthy (in which case I can read it in the Table display of the Data panel). It also does not happen for a long text (the same, actually) taken from the Data display of a TABLE 

At some point, SQLStudio complained that it had a problem while modifying the cell, and the extraction request could not get the rowid.

### Operating system
KUbuntu 20.04.

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
1. How long values are we talking about?
1. Is there a chance the value starts with many new-line characters and it seems empty in text box, while the value starts below if you scroll? I know it may sound stupid, but I'd like to be sure and exclude this case.
1. Is the value textual only, or binary value?
1. Could the value be modified in between showing in Grid view and switching to Form View (or copying)? I'm asking, because showing in Form View or copying triggers another `SELECT`, which loads full value of a cell (as in Grid View it is preliminary limited to avoid memory overuse). So, since there is another `SELECT`, it could be that another application erased value, this second query returns empty string.

**Comment by ysalmon** [comment]
281 chars in my example. No new-line char at all. Pure text (French).

I do not understand point 4.

**Comment by pawelsalawa** [comment]
Is there any other application (other than SQLiteStudio) working on this database at the same time when you're browsing it?

**Comment by ysalmon** [comment]
No.

**Comment by pawelsalawa** [comment]
Is this result of your custom SQL `SELECT`, or is it directly table data browsing?
If it's result of a query, is there a chance you share here this query?

**Comment by ysalmon** [comment]
The problem does not occur when viewing a TABLE. It occurs when I view a VIEW.

The corresponding query is
```sql
SELECT tbl_etu.id,
       tbl_etu.nom,
       tbl_etu.prenom,
       tbl_etu.classe,
       tbl_etu.groupe,
       tbl_etu.option,
       ROUND(SUM(mpsi_o_juin_result.points * mpsi_o_juin_struct.points / mpsi_o_juin_struct.bareme), 2) AS note,
       mpsi_o_juin_copie.commentaire AS commentaire
  FROM (
           (
               SELECT *
                 FROM etudiants
                WHERE classe IN (MPSI1, MPSI2, MPSI3) AND 
                      option IN ("INFO") 
           )
           AS tbl_etu
           LEFT JOIN
           (
               mpsi_o_juin_result
               JOIN
               mpsi_o_juin_struct USING (
                   question,
                   item
               )
           )
           ON tbl_etu.id = mpsi_o_juin_result.id_eleve
       )
       LEFT JOIN
       mpsi_o_juin_copie ON tbl_etu.id = mpsi_o_juin_copie.id_eleve
 GROUP BY tbl_etu.id;
```

**Comment by ysalmon** [comment]
Also note that when selecting the cell in the grid display, going to the form display where the text appears empty, and going back to the grid view, the text in the cell appears to be deleted (which cannot be since this is a view) and I need to refresh the display to restore it.

**Comment by pawelsalawa** [comment]
I see. Thanks.
It seems to be some kind of problem with views. I need to investigate it.

**Comment by pawelsalawa** [comment]
What's interesting - there seems to be some kind of similar case in #3801. In 3.2.1 the blob there is also truncated, which causes incorrect image rendering.

Good news that it works correctly in the "in-development" 3.2.2, so it's fixed, but I'm not sure which change fixed it.
