### ISSUE TITLE
SQLCipher plugin cannot load on ubuntu

### ISSUE THREAD

**Issue by DarkDeveloper-Plant** [pawelsalawa/sqlitestudio#3807]
### Details
Hi. I installed the latest version of sqlite studio and ubuntu but the problem that i am facing is this error:
`Cannot load plugin DbSqliteCipher. Error details: Cannot load library ../SQLiteStudio/plugins/libDbSqliteCipher.so: (libcrypto.so.1.0.0: cannot open shared object file: No such file or directory)`
so what should i do?
### Operating system
ubuntu 20.04 LTS

### SQLiteStudio version
v3.2.1

**Comment by pawelsalawa** [comment]
```
$ cd /usr/lib/x86_64-linux-gnu
$ sudo ln -s libcrypto.so.1.0.0 libcrypto.so.1
```

Duplicates #3384
