### ISSUE TITLE
In Windows XP 32 bits.

### ISSUE THREAD

**Issue by tellts** [pawelsalawa/sqlitestudio#3817]
Please excuse me for distracting you from important matters. Tell me, is there a version for the old operating system?

**Comment by pawelsalawa** [comment]
2.x.x series should work. You can find it at dropbox share: https://www.dropbox.com/sh/wb03rvcjxwu4wol/AACe3zsTD33GKyAvE2L4mThOa?dl=0

I will perhaps create a dedicated subpage for these versions, but it's not priority at the moment.

**Comment by tellts** [comment]
Thanks!
