### ISSUE TITLE
[other help] how to transform this config to sqlcipher command line

### ISSUE THREAD

**Issue by gMan1990** [pawelsalawa/sqlitestudio#3819]
- gui config
![gui config](https://user-gold-cdn.xitu.io/2020/2/24/17072e7d7aaaf49c)
- sqlcipher cli
SQLCipher version 3.28.0 2019-04-16 19:49:53

**Comment by pawelsalawa** [comment]
```
PRAGMA cipher_use_hmac = OFF;
```

**Comment by gMan1990** [comment]
@pawelsalawa But I got `file is not a database`
```text
> sqlcipher your.db
SQLCipher version 3.28.0 2019-04-16 19:49:53
Enter ".help" for usage hints.
sqlite> PRAGMA key = 'your.key';
sqlite> PRAGMA cipher;
AES-256-CBC
sqlite> PRAGMA kdf_iter = 4000;
sqlite> PRAGMA cipher_page_size = 1024;
sqlite> PRAGMA cipher_use_hmac = OFF;
sqlite> .tables
Error: file is not a database
```

**Comment by pawelsalawa** [comment]
I'm assuming that you replace the `your.key` with your actual password that you use in SQLiteStudio for this database file.

**Comment by gMan1990** [comment]
@pawelsalawa yes, `your.db` `your.key` replace with actual

**Comment by pawelsalawa** [comment]
Why did you close this issue? Does it work now?

**Comment by gMan1990** [comment]
@pawelsalawa
1. use `cipher_migrate`, and file will in-place upgrade

```text
> unzip -q WxFileIndex.db.zip WxFileIndex-4.db
replace WxFileIndex-4.db? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
> sha1sum WxFileIndex-4.db
d12098c98c7ff3cb80ed9a2620871703163c167f  WxFileIndex-4.db
> sqlcipher WxFileIndex-4.db
SQLCipher version 3.28.0 2019-04-16 19:49:53
Enter ".help" for usage hints.
sqlite> PRAGMA key = '5871277';
sqlite> PRAGMA cipher_migrate;
0
sqlite> .tables
WxFileIndex2
sqlite> .exit
> sha1sum WxFileIndex-4.db
e28309d371e62637b1ea8e73fb4515b2e3ad262d  WxFileIndex-4.db
```

2. got `Error: file is not a database`, help!

```text
> unzip -q WxFileIndex.db.zip WxFileIndex-4.db
replace WxFileIndex-4.db? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
> sha1sum WxFileIndex-4.db
d12098c98c7ff3cb80ed9a2620871703163c167f  WxFileIndex-4.db
> sqlcipher WxFileIndex-4.db
SQLCipher version 3.28.0 2019-04-16 19:49:53
Enter ".help" for usage hints.
sqlite> PRAGMA key = '5871277';
sqlite> PRAGMA cipher;
AES-256-CBC
sqlite> PRAGMA kdf_iter = 4000;
sqlite> PRAGMA cipher_page_size = 1024;
sqlite> PRAGMA cipher_use_hmac = OFF;
sqlite> .tables
Error: file is not a database
```

**Comment by pawelsalawa** [comment]
Does it work when you open it from SQLiteStudio using SQLCippher database type?

**Comment by gMan1990** [comment]
@pawelsalawa 

1. img

<img width="288" alt="QQ20200802-040310@2x" src="https://user-images.githubusercontent.com/5050994/89109583-2a0d5380-d475-11ea-8564-ed82af7e3d03.png">

2. db

[WxFileIndex-4.db.zip](https://github.com/pawelsalawa/sqlitestudio/files/5011165/WxFileIndex-4.db.zip)

**Comment by pawelsalawa** [comment]
I'm curious about the file name. Isn't it encrypted with WxSqlite? How about if you try to open the file with WxSqlite plugin under SQLiteStudio. Does it work too?

**Comment by gMan1990** [comment]
@pawelsalawa what is the WxSqlite? I don't know.

**Comment by pawelsalawa** [comment]
Okay, according to this page https://github.com/Tencent/wcdb they use SQLCipher.
 Perhaps it's about SQLCipher version that you use. Your (3.28) is quite recent, while the one distributed with SQLiteStudio 3.2.2 is 3.20.1.

Try playing with SQLCipher's other compatibility setting. Quoting their page:

> To open an older database use the compatibility PRAGMAs to adjust settings back to their previous values. For example, to open a SQLCipher 3 database using SQLCipher 4, use the following statement after opening and keying the database: PRAGMA cipher_compatibility = 3;.
Quote from: https://www.zetetic.net/blog/2018/12/18/sqlcipher-401-release/

**Comment by gMan1990** [comment]
@pawelsalawa
- `PRAGMA cipher_compatibility = 3;` Doesn't work!
- Another help, think you first! 233

```text
sqlcipher-3.4.2> ./configure
configure: error: Library crypto not found. Install openssl!"

/usr/local/ssl/lib/libcrypto.a
/usr/local/Cellar/openssl@1.1/1.1.1d/lib/libcrypto.a
/usr/local/Cellar/openssl/1.0.2r/lib/libcrypto.a
/usr/local/Cellar/openssl/1.0.2s/lib/libcrypto.a
```

**Comment by pawelsalawa** [comment]
Have you tried `PRAGMA cipher_compatibility = 2;` and `PRAGMA cipher_compatibility = 1;` ?

About compiling yourself - I won't be able to help you.

**Comment by gMan1990** [comment]
@pawelsalawa
- `PRAGMA cipher_compatibility = 2;`, I tried, but also doesn't work!

----
Thank you so much, `PRAGMA cipher_compatibility = 1;` is right.

**Comment by wangxiaoran1995** [comment]
> Have you tried `PRAGMA cipher_compatibility = 2;` and `PRAGMA cipher_compatibility = 1;` ?
> 
> About compiling yourself - I won't be able to help you.

Thank you so much, PRAGMA cipher_compatibility = 1; is right.
