### ISSUE TITLE
SQLiteStudio fails to load SQLite3 db with generated VIRTUAL column.

### ISSUE THREAD

**Issue by eulaly** [pawelsalawa/sqlitestudio#3820]
### Details
Loaded SQLite3 db generated via Python 3; when I added a generated column to one of the tables, SQLiteStudio threw an error.

### Steps to reproduce
Create a SQLite3 db from Python3 using sqlite3 module with no generated/computed columns. Repeat, adding a generated VIRTUAL or STORED column in one of the tables. 
Created tables:
CREATE TABLE IF NOT EXISTS cars 
                (name text NOT NULL,
                vin text PRIMARY KEY,
                plate text,
                title text,
                gas_tank integer,
                mpg real,
                mileage integer DEFAULT 0)
CREATE TABLE IF NOT EXISTS transactions
                (txn_type TEXT,
                datetime TEXT,
                gas REAL,
                cost REAL,
                note TEXT,
                trip_mileage INTEGER,
                mileage INTEGER,
                car_id TEXT,
                mpg REAL AS (trip_mileage/gas) VIRTUAL,   # removing this line, the db loads fine. both databases work fine in other programs.
                FOREIGN KEY(car_id) REFERENCES cars(name))
### Operating system
Windows 10.

### SQLiteStudio version
v3.2.1

**Comment by pawelsalawa** [comment]
This should be resolved when SQLite version is bumped with #3470

**Comment by JrgMyr** [comment]
Eulaly: do you mean "generated columns" as introduced with SQLite version 3.31.0 (Jan. 2020)?
SQLiteStudio (v.3.2.1) runs on SQLite version 3.24.0 (June 2018).

So in a way to throw an error is the documented and expected behaviour.
See https://sqlite.org/gencol.html, section "3. Compatibility".

**Comment by pawelsalawa** [comment]
Covered by #3763
