### ISSUE TITLE
"Load SQL From File" button fails

### ISSUE THREAD

**Issue by JrgMyr** [pawelsalawa/sqlitestudio#3824]
If I open the SQL editor with Alt-E, then an icon (the small floppy disk) shows up that allows to "save SQL to file".

There is a selector next to it which also offers to "load SQL from file". But actually that also "saves to" instead of "loads from".
Is this a known front-end issue (in the German language frontend)?

Good thing: Ctrl-S and Ctrl-O both work as expected (correctly).

Best, Jörg

**Comment by pawelsalawa** [comment]
I cannot confirm it. To me the it works fine:
![image](https://user-images.githubusercontent.com/481846/88462096-1aa46e00-cea9-11ea-96a1-1a1e6545bab6.png)

It shows "Open file" dialog and when I select the file - it's content land into SQL editor.

![image](https://user-images.githubusercontent.com/481846/88462159-8c7cb780-cea9-11ea-8886-638ae7a1754b.png)

**Comment by JrgMyr** [comment]
Must be a translation issue. In my Germany language Windows application these things happen:
- The diskette symbol says "SQL in Datei speichern (Strg +  S)" = "save to file" which is correct. It does save.
- The small selector icon (black triangle, pointing down) says "SQL aus Datei laden" = "load from file" which is wrong. However, it correctly opens the "Save as" dialog box.
- The open older icon says "Zeile löschen (Strg + O)" = "delete line" which is wrong. However, it correctly opens the "Open file" dialog box.
With "says" I mean the hint that appears when the mouse cursor hovers over the icon.
Best, Jörg

**Comment by pawelsalawa** [comment]
That may be very likely. Translations went through a major rework in for 3.3.0 version - it is done with CrowdIn portal ( https://github.com/pawelsalawa/sqlitestudio/wiki/Language_Translations ). I'm not sure if anyone fixed it there already, but I will keep this issue open to get back to it when it comes to 3.3.0 release.

Still, currently I'm working on 3.2.2 release, to fix numerous bugs in 3.2.1 and then I will focus on 3.3.0.

**Comment by JrgMyr** [comment]
I found the bug in the file "SQLiteStudio3/guiSQLiteStudio/translations/guiSQLiteStudio_de_DE.ts"
The messages in German are shifted by one against the messages in English.
Line 4836 onwards.

**Comment by pawelsalawa** [comment]
You've created a Pull Request recetly, which is now merged. Does it fix this issue mentioned above, or is there more?

**Comment by pawelsalawa** [comment]
Just verified, that the current translation (in master branch, for 3.4.0) seems to be correct.
