### ISSUE TITLE
QtScript not returning anything

### ISSUE THREAD

**Issue by rashenoy** [pawelsalawa/sqlitestudio#3826]
### Details
QtScript function doesnt return anything from the script function.

### Steps to reproduce
FunctionName : getValue
Arguments: var1
Type of function: Scalar
Implementatin Language: QtScript
`function getValue()
{
  return arguments.length;
}`
Added this in SQl query
getValue(ZEVENTENTITY.ZVALUE) as mtype

I get
[20:19:05] Query finished in 0.001 second(s).
But mtype is null

Attached screen shot
![Screenshot 2020-07-27 at 8 22 16 PM](https://user-images.githubusercontent.com/8740439/88556632-df3fa600-d046-11ea-9685-bc355aae2396.png)

### Operating system
MacOS Catalina

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
The "Function implementation code" is already a body of your function. You don't need to repeat function name there.

Just keep the `return arguments.length` part, remove all the rest and you will be fine.
