### ISSUE TITLE
Crash at start-up when registered extension not found

### ISSUE THREAD

**Issue by jannick0** [pawelsalawa/sqlitestudio#3828]
### Details
App crashes at start-up when it does find a registered extension. 

### Steps to reproduce
- register an extension `E` using the extension manager
- close application
- move shared library (`dll` on Windows) belonging to extension `E` away from where app expects it to be (e.g. reaname it)
- reopen app ... and it crashes

Current workaround: remove `settings3` in [configuration folder](https://github.com/pawelsalawa/sqlitestudio/wiki/Configuration_directory_location) and configure again.

### Operating system
Windows 10

### SQLiteStudio version
Version 3.2.1

**Comment by pawelsalawa** [comment]
I was able to reproduce it on 3.2.1, but on upcoming 3.3.0 it appears to be already fixed by some other bugfix.
