### ISSUE TITLE
Databases pane won't keep adjusted width

### ISSUE THREAD

**Issue by fmc-coder** [pawelsalawa/sqlitestudio#3834]
### Details
When I increase the width of the Databases pane and right click into it for the submenu and then click out of that menu or make a selection, the Database pane reverts back to its original size. However, if I resize it and close the app and reload it, it holds its size. I use .ini files, too, to retain user preferences. Yours reverts when I click into that pane after altering its width.

### Operating system
Linux Mint 20

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Duplicate of #3421
