### ISSUE TITLE
Bug executing on macOS with case-sensitive file system.

### ISSUE THREAD

**Issue by carlinix** [pawelsalawa/sqlitestudio#3835]
### Details
I've found two bugs when running on macOS using a **case sensitive**  file system.

The first is related to the libPdfExport.dylib. I've found this warning message:

```
[15:33:58] Cannot load plugin Printing. Error details: Cannot load library 
/Applications/SQLiteStudio.app/Contents/PlugIns/libPrinting.dylib: 
(dlopen(/Applications/SQLiteStudio.app/Contents/PlugIns/libPrinting.dylib, 10): Library not loaded: 
@loader_path/../plugins/libPdfExport.dylib
  Referenced from: /Applications/SQLiteStudio.app/Contents/PlugIns/libPrinting.dylib
  Reason: image not found)

```
The problem is due to the wrong case in the path: **@loader_path/../plugins/libPdfExport.dylib** where the correct needs to be **@loader_path/../PlugIns/libPdfExport.dylib**.

As a workaround, I've made a symbolic link pointing to PlugIns (`ln -s PlugIns plugins`).

The second bug is observed when I've tried to run the **sqlstudiocli**:

```
dyld: Library not loaded: @rpath/libcoreSQLiteStudio.1.dylib
  Referenced from: /Applications/SQLiteStudio.app/Contents/MacOS/sqlitestudiocli
  Reason: image not found
```
I think that it's necessary to apply some command like: `install_name_tool -change @rpath/libcoreSQLiteStudio.1.dylib ...`

### Steps to reproduce
Run the application on any macOS with **case-sensitive** file system, in my case APFS.

### Operating system
macOS Catalina 10.15.6 APFS case-sensitive.

### SQLiteStudio version
SQLite Studio 3.2.1

**Comment by pawelsalawa** [comment]
Fixed with https://github.com/pawelsalawa/sqlitestudio/pull/3836
