### ISSUE TITLE
Gui not showing anymore after latest windows 10 2004 update

### ISSUE THREAD

**Issue by shdf2** [pawelsalawa/sqlitestudio#3840]
### Details
I just applied all the windows 10 updates, version 2004, with all patchs, on my computer. and now my sqlitestudio portable doesn't show the gui anymore. i can see it in the process list. i can kill the process, but when i run it again there is the same behavior.

### Operating system
windows 10 updates, version 2004 up to date

### SQLiteStudio version
sqlitestudio 3.2.1 portable

**Comment by pawelsalawa** [comment]
Can you please reset configuration and retry? To reset, rename config file to some other and then start the app.

Config file location is: https://github.com/pawelsalawa/sqlitestudio/wiki/Configuration_directory_location

**Comment by shdf2** [comment]
Finally i found out that it was a disconnected network drive on which i have a database linked to sqlitestudio. so i disconnected that mapped drive from my PC and now i can see the GUI again.

Sorry for reporting this as a bug...
