### ISSUE TITLE
Window functions do not work in a View

### ISSUE THREAD

**Issue by Chrisryansmith** [pawelsalawa/sqlitestudio#3852]
This code works just fine as a Query in SQLlite Studio, but not as a View

SQL: 
select Year (times)100+Quarter as Period,Region, Subregion,Country, Vendor, Channel_type, Channel_group, POT, Units, round(Units/cast(Sum(Units) Over(Partition by Country, Vendor) as float),2) AS pct_country_vendor,round(Units/cast(Sum(Units) Over(Partition by Subregion, Vendor) as float),2) AS pct_subregion_vendor from d_channel_q22020
Where Period IN (Select distinct Year(times)100+Quarter AS Period from d_channel_q22020 ORDER BY Period DESC LIMIT 4)

Table: d_channel_q22020
Year,
Quarter,
       Region,
       Subregion,
       Country,
       Vendor,
       Channel_type,
       Channel_group,
       POT,
       Units

**Comment by pawelsalawa** [comment]
It will become supported together with upgrade to newer SQLite version, to be done with #3470

**Comment by Chrisryansmith** [comment]
Unfortunately this is not the case. I am using 3.33.0 (latest) SQLite with the latest SQLlite Studio. The code works fine in SQL Editor but not when saved as a view. Odd right?

**Comment by pawelsalawa** [comment]
Yes. Just upgrading SQLite will not work in this case, because it required adjustments in the SQL parser built in SQLiteStudio. The issue mentioned above covers that too.

**Comment by pawelsalawa** [comment]
Yes, that is correct.
