### ISSUE TITLE
How to save changes in .sqlite file or disable WAL-mode?

### ISSUE THREAD

**Issue by ghcusr** [pawelsalawa/sqlitestudio#3853]
I need to modify the .sqlite file a little (just add some string in a table) When I do it all changes save in a new created .sqlite-wal file. How can I save added strings in original .sqlite file?

**Comment by pawelsalawa** [comment]
WAL file should exist only until you commit transaction. Did you manually start a transaction? (i.e. did you type `BEGIN` or 'SAVEPOINT` in your SQL queries?)

Normally all changes - once committed - are saved to the original file, as expected.
