### ISSUE TITLE
Supporting "WINDOW" and "DENSE_RANK" instructions

### ISSUE THREAD

**Issue by SteX986** [pawelsalawa/sqlitestudio#3854]
### Details
Supporting "WINDOW" sqlite instructions (DENSE_RANK, etc)
[SAMPLE query with window.TXT](https://github.com/pawelsalawa/sqlitestudio/files/5369451/SAMPLE.query.with.window.TXT)

### Steps to reproduce
I'm opening a view with a DENSE_RANK () function, but it says error because it can't create the window

### Operating system
Windows 10. SQLite3.dll manually update to last version

### SQLiteStudio version
Latest 3.2.1

**Comment by SteX986** [comment]
SQLite Studio answer to this query is:
[08:46:13] Could not process the V Devices - MISSING view correctly. Unable to open a view window.

**Comment by pawelsalawa** [comment]
This will be resolved by #3470

**Comment by SteX986** [comment]
Thank you so much! Looked for dense_rank but didn't found any double post, sorry
Thank you for your work, too!!
