### ISSUE TITLE
Thank you very much for the free open source program!

### ISSUE THREAD

**Issue by mrkaban** [pawelsalawa/sqlitestudio#3855]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D1%83/%D0%BF%D1%80%D0%BE%D1%87%D0%B5%D0%B5/sqlitestudio-%D1%81%D0%B2%D0%BE%D0%B1%D0%BE%D0%B4%D0%BD%D1%8B%D0%B9-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80-sqlite-%D0%B1%D0%B0%D0%B7-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85.html).

The project is interesting, so please don't abandon it!

**Comment by pawelsalawa** [comment]
I'm sorry I had to edit your post and remove the link, but it did not look safe and I don't want this project to have suspicious links originating from it.

Thanks for your kind words though!
