### ISSUE TITLE
Could not process the view correctly

### ISSUE THREAD

**Issue by sakhnik** [pawelsalawa/sqlitestudio#3857]
### Details
Unable to open the view in our database. The schema is:
```
CREATE TABLE IF NOT EXISTS "sql-products" ("id" INTEGER, "name" TEXT, "price" TEXT);
CREATE TABLE IF NOT EXISTS "sql-all" ("ProductID" TEXT, "Text1A" TEXT, "Text2A" TEXT, "Text3A" TEXT, "Text4A" TEXT, "Text5A" TEXT, "RetailValue" TEXT, "RetailPrice" TEXT, "QVCPrice" TEXT, "ThreeTierPrice" TEXT, "ThirdMsg" TEXT, "PriceCode" TEXT, "SH" TEXT, "FreeSH" TEXT, "ReducedSH" TEXT, "NrPayments" TEXT, "PmtAmt" TEXT, "ID" INTEGER);
CREATE VIEW "view-join" AS SELECT DISTINCT ProductID, RetailValue, name, price FROM 'sql-all' JOIN 'sql-products' ON 'sql-all'.ID='sql-products'.id
```

### Steps to reproduce
* Open the database with the above schema
* Double click on the `view-join`
* Observe the status message in red: "Could not process the view correctly. Unable to open a view window."

I traced the the code until the parser reported "Syntax error" on our "CREATE VIEW".

### Operating system
Windows, Arch Linux

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Does this query work for you when you execute it from SQL editor window?
```
SELECT DISTINCT ProductID, RetailValue, name, price FROM 'sql-all' JOIN 'sql-products' ON 'sql-all'.ID='sql-products'.id
```

**Comment by sakhnik** [comment]
Yes, it does. It displays the records. However, there's a warning:
[16:21:06] SQLiteStudio was unable to extract metadata from the query. Results won't be editable.
