### ISSUE TITLE
block certain column names

### ISSUE THREAD

**Issue by TokyoWarfare** [pawelsalawa/sqlitestudio#3858]
### Details
Today I ran into an issue that kept me blocked for a while, I named a column GROUP

If you do so, later on in the queries it will raise an exception since GROUP turns out its a command name XD, so it could be interesting that columns can´t be named like commands or any other thing that could trash a query. 

Cheers.

**Comment by pawelsalawa** [comment]
It is allowed to name the column using command keyword, but in that case you need to enclose it in one of a quoting wrappers. If you created such column - go to its DDL tab and see how SQLiteStudio wraps it (probably [group], or "group", or other). SQLite3 supports 4 different wrappers. See SQLite docs for more details.

**Comment by TokyoWarfare** [comment]
Ah! tx, a a rookie I was not aware of any of this info. Imagine me preparing the sql string where all looked "normal" and it was glitching, till I realized what was going on XD, will not happen again.
