### ISSUE TITLE
AndroidStudio4.0's db file Cann't correct import.

### ISSUE THREAD

**Issue by zhangdanfenggg** [pawelsalawa/sqlitestudio#3860]
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment]
Please correct your report - provide details what you're trying to do, what you expect to happen and what is wrong.
