### ISSUE TITLE
Error on commit edited results from query.

### ISSUE THREAD

**Issue by ramonneves** [pawelsalawa/sqlitestudio#3864]
### Details
Hello, 
I ran a query to return some data with empty cells and the next row ID, to make it easier to edit in the query results. After editing the empty results and try to commit, the editor gives me the following error:
[10:24:27] Tried to commit a cell which is not editable (yet modified and waiting for commit)! This is a bug. Please report it.

### Steps to reproduce
Run the following query:
`SELECT  * FROM MACHINE_STATUS WHERE 1 = 1
AND Equipment = '' 
UNION ALL
SELECT  MS1.* FROM MACHINE_STATUS MS1
JOIN MACHINE_STATUS MS2 ON MS1.Id = MS2.Id +1
AND MS2.Equipment = '' 

ORDER BY ID`

it returns this result set:
![image](https://user-images.githubusercontent.com/32772357/98946543-c6aeab00-24d2-11eb-827c-c34f931b0a19.png)

I edit the result filling the empty Equipments with the following cell value and press commit.

### Operating system
Windows 10 Pro 64 bits 

### SQLiteStudio version
v3.2.1

**Comment by pawelsalawa** [comment]
You must be doing something differently. In general if you do any `SELECT ..... UNION ..... SELECT` (no matter if it's `UNION` or `UNION ALL`), no results from such query will be editable and you will see message like:
![image](https://user-images.githubusercontent.com/481846/107878578-f3a89a80-6ed3-11eb-8130-926d1c6d3048.png)

I cannot reproduce the problem according to your description above. If the problem still exists, please post reproducible recipe and I will reopen.
