### ISSUE TITLE
Column titles and row numbers cut off on bottom

### ISSUE THREAD

**Issue by hudcap** [pawelsalawa/sqlitestudio#3865]
### Details
Any time I'm looking at data in grid view, the bottom of all the column titles and row numbers are cut off (image below).
I think these issues might be related, but they're closed: #679 & #829
I'm not using a large font size, but my display resolution is high (2256 x 1504).

![image](https://user-images.githubusercontent.com/4990645/98958172-01631400-24d0-11eb-8313-ce41befc2333.png)

### Steps to reproduce
Open table or sql query results in grid view.

### Operating system
Windows 10

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Resolved with #3046
