### ISSUE TITLE
LEAD (expression) OVER (ORDER BY expression1) does not work

### ISSUE THREAD

**Issue by averov90** [pawelsalawa/sqlitestudio#3867]
### Details
When I enter a command with LEAD, an error occurs, although sqlite itself supports this command.
Error text: `Error while executing SQL query on database 'testdb': near "(": syntax error`

### Steps to reproduce
Create DB, create table with next shema:
```
CREATE TABLE attr (
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL
);
```
Execute next sql command: `SELECT LEAD(id, 1) OVER(ORDER BY id) from attr `
You will get described above error.

### Operating system
windows 10 pro, build 19042

### SQLiteStudio version
SQLiteStudio v3.2.1
portable version

**Comment by pawelsalawa** [comment]
This will be resolved by #3726
