### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: uitools

### ISSUE THREAD

**Issue by tieugene** [pawelsalawa/sqlitestudio#3870]
What package provides it?
Fedora/CentOS

**Comment by pawelsalawa** [comment]
I'm not really a CentOS expert, but throwing `centos qt uitools` into Google gives first answer about `qt5-qttools-devel`.

**Comment by tieugene** [comment]
> I'm not really a CentOS expert, but throwing `centos qt uitools` into Google gives first answer about `qt5-qttools-devel`.

Google lies:
```
bash-5.0$ rpm -qa | grep qttools
qt5-qttools-libs-designercomponents-5.15.1-1.fc33.x86_64
qt5-qttools-common-5.15.1-1.fc33.noarch
qt5-qttools-libs-designer-5.15.1-1.fc33.x86_64
qt5-qttools-libs-help-5.15.1-1.fc33.x86_64
qt5-qttools-5.15.1-1.fc33.x86_64
qt5-qttools-devel-5.15.1-1.fc33.x86_64
```

**Comment by pawelsalawa** [comment]
Okay. It looks you got it covered.

**Comment by tieugene** [comment]
> Okay. It looks you got it covered.

But problem not solved.

**Comment by pawelsalawa** [comment]
As I said, I'm not CentOS expert. You need to ask people who know CentOS. This requires knowledge (of the proper package) specific to a certain Linux distribution.

**Comment by tieugene** [comment]
> As I said, I'm not CentOS expert. You need to ask people who know CentOS. This requires knowledge (of the proper package) specific to a certain Linux distribution.

Maybe [this](https://doc.qt.io/qt-5/qtuitools-index.html) is source of the problem:
"Qt UI Tools is available under commercial licenses from The Qt Company. Since Qt 5.11, it is also available under the BSD 3-Clause "New" or "Revised" License".

Then it is not included into Fedora/CentOS official repos.

Need consult with Ubuntu/Debian/other users who use fresh (e.g. 5.15) Qt5.

**Comment by pawelsalawa** [comment]
Please read it carefully. It says that it is available under both commercial and BSD licenses. The BSD license is super liberal and there is no reason for CentOS not to have this package.

**Comment by tieugene** [comment]
> Please read it carefully. It says that it is available under both commercial and BSD licenses. The BSD license is super liberal and there is no reason for CentOS not to have this package.

I found it: qt5-qttools-static
Maybe not bad idea to note this in build instruction for RH-based distros (using static libraries in packaging is rare case).
