### ISSUE TITLE
create table with generated column failed with syntax error

### ISSUE THREAD

**Issue by wushuzh** [pawelsalawa/sqlitestudio#3885]
### Details

Try to create the table based on https://sqlite.org/gencol.html

```
CREATE TABLE t1(
   a INTEGER PRIMARY KEY,
   b INT,
   c TEXT,
   d INT GENERATED ALWAYS AS (a*abs(b)) VIRTUAL,
   e TEXT GENERATED ALWAYS AS (substr(c,b,b+1)) STORED
);
```

The error msg is 
```Error while executing SQL query on database 'testdb': near "as": syntax error```

The same sql is OK with sqlite3 cli and DB browser for sqlite.

### Steps to reproduce

execute the create table sql

### Operating system
Windows 10

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
This will be covered by #3470
