### ISSUE TITLE
RightClick on DataGridView leads to crash

### ISSUE THREAD

**Issue by xuanjueheshang** [pawelsalawa/sqlitestudio#3891]
### Details
2020-12-16, it crashed during my first use. After many tests, I found the possible problem.

### Steps to reproduce
1. Create A New Table with no data item;
2. Open Data Grid View;
3. RightClick on the content region;
4. Crash and exit.

### Operating system
win10, version 1909

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
Duplicate of #3565
