### ISSUE TITLE
UPDATE SET not working on MAC OS 

### ISSUE THREAD

**Issue by DarrellJonsson** [pawelsalawa/sqlitestudio#3892]
### Details
Here you describe your problem details, or proposal for enhancement.
UPDATE SET is not working on Mac OS
### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

Run UPDATE statements like the following 
* on both MAC and PC
* using the same SQL Database.
* 
UPDATE Images
SET rating  = 
(SELECT rating
FROM aaRatingsTravel
WHERE Images.id = aaRatingsTravel.images_id

**NOTE: This exact statement runs on SQLITE STUDIO on PC 
but does not run in SQLITE Studio on MAC CATALINA**
In SQLITE Studio on Mac return error -- _near '=': syntax error_
)
### Operating system
This applies only to bug reports. If this is a feature request, delete this section.
MAC OS - CATALINA
### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.
v3.2.1

**Comment by tuffnatty** [comment]
Can't reproduce on MacOS High Sierra 10.13.6, SQLite Studio 3.2.1.

**Comment by pawelsalawa** [comment]
I also cannot reproduce it. It looks like the query on Mac wasn't equal after all. It had some extra character (or missing one) that caused the syntax error.
