### ISSUE TITLE
renturn  404

### ISSUE THREAD

**Issue by cyfbj** [pawelsalawa/sqlitestudio#3925]
https://sqlitestudio.pl/files/depends/win32_deps.zip   return 404

**Comment by pawelsalawa** [comment]
Thank for pointing this out. The file has been moved to dropbox, under link: https://www.dropbox.com/s/q4krormuq1e35li/win32_deps.zip?dl=1

I have update the wiki page https://github.com/pawelsalawa/sqlitestudio/wiki/Instructions_for_compilation_under_Windows to include the new URL.

Did you find the invalid link on some other page, that I should also update?

**Comment by cyfbj** [comment]
dropbox.com         The site is not accessible in China

**Comment by pawelsalawa** [comment]
I see. I've uploaded them to https://github.com/pawelsalawa/sqlitestudio/releases/tag/3.2.1.
