### ISSUE TITLE
How to check whether SQLiteStudio is using build-in REGEXP oder extension?

### ISSUE THREAD

**Issue by orangelynx** [pawelsalawa/sqlitestudio#3937]
It's very useful that SQLiteStudio has built in support von regular expressions via REGEXP, however I feel the used Qt implementation is much slower compared to running a sqlite shell with a pcre wrapper extension loaded (on unix). I therefore compiled pcre and a wrapper extension on windows and loaded it into SQLiteStudio, which accepts it fine. However, I cannot tell if the REGEXP function is now caught by SQLiteStudio and Qt or by my custom extension. Which one takes precedence and how can i verify this?

**Comment by pawelsalawa** [comment]
REGEXP implementation in SQLite3 is done via registering `regexp()` custom function. 
The way that SQLiteStudio initializes database upon opening is that it loads all registered extensions first - registered extensions are those added in the Extensions Manager window - this one:
![image](https://user-images.githubusercontent.com/481846/106636643-6a63a080-6582-11eb-81c8-fbab08220d1c.png)
Then it registers all functions (including the `regexp()`).

Now, according to this documentation: https://sqlite.org/appfunc.html#multiple_calls_to_sqlite3_create_function_for_the_same_function whichever function implementation is registered later - will be in use.

This means that if you load extension through the Extension Manager, you will still use SQLiteStudio REGEXP implementation. If you want to use your own - provided by extension, you will need to load the extension manually, later, using `SELECT load_extension(...);` call.
