### ISSUE TITLE
Export to SQL ignores table name

### ISSUE THREAD

**Issue by Stitch10925** [pawelsalawa/sqlitestudio#3959]
When exporting a query to SQL, the "*Table name to use for INSERT statement*" parameter is ignored resulting in a file with content like this:

> INSERT INTO  (Col1, Col2, Col3) VALUES ('Val1', 'Val2', 'Val3')

instead of:

> INSERT INTO **MyTable** (Col1, Col2, Col3) VALUES ('Val1', 'Val2', 'Val3')

Extra Info:

- Export format: SQL
- Output: Clipboard
- Export format options
  - Table name: MyTable
  - Generate create: unchecked
  - Include the query: unchecked
  - Use sql formatter: unchecked

SqlLiteStudio version: 3.2.1
OS: Win 10 Pro

**Comment by pawelsalawa** [comment]
There is a problem with respecting changes in the export dialog. Once you export in certain configuration and you try to re-do it with different configuration, it's being disregarded.

A workaround is to restart SQLiteStudio.

The bug will be fixed in 3.3.0.
