### ISSUE TITLE
Unexpected behaviour of "Default Value Constraint Edit" Dialog.

### ISSUE THREAD

**Issue by GigoMego** [pawelsalawa/sqlitestudio#3974]
### Details
While editing contents of textbox inside default Value Constraint Edit Dialog window, the mechanism that ensures validation of value works strange way. For example If i put "0" then two spaces and then i erase these spaces with backspace key and "0" remains as content of text box, i cannot apply changes because "apply" button is grayed out. Deleting remaining one character in text box and putting it back again fixes button state.

### Steps to reproduce
Open edit dialog for **Default value** of **INTEGER** field, put "0" and two spaces, erase spaces pressing backspace twice, despite fact that value is correct **Apply** button is grayed out.

### Operating system
Win 10

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
It was caused by the same bug as in #3459 - which is fixed for upcoming 3.3.0 (which is to be expected soon).
