### ISSUE TITLE
Get "The database has been closed" when running cron, not running directly"

### ISSUE THREAD

**Issue by aakjpe** [pawelsalawa/sqlitestudio#3978]
Have a simple Java program that connects to the SQLite database. Works ok when I run the bash script directly from a shell on my mac. But when I run the same script in a cron job, I get the message "The database has been closed"

[dbConnect-bash.txt](https://github.com/pawelsalawa/sqlitestudio/files/5987969/dbConnect-bash.txt)

Script attached

Crontab:
50 23 * * * /Users/kjellpettersen/NetBeansProjects/dbConnect/build/classes/dbConnect.bash > /Users/kjellpettersen/NetBeansProjects/dbConnect/build/classes/dbcon.log 2>&1

What can be the difference when running as a cron job?

Running from a shell:

kjellpettersen@Kjell-Pettersens-iMac classes % ./dbConnect.bash
db: /Volumes/Seagate Expansion/Database/BackupDB.db
/Users/kjellpettersen/NetBeansProjects/dbConnect/build/classes
Connect to jdbc:sqlite:/Volumes/Seagate Expansion/Database/BackupDB.db
Connection OK

From cron:
db: /Volumes/Seagate Expansion/Database/BackupDB.db
/Users/kjellpettersen/NetBeansProjects/dbConnect/build/classes
Connect to jdbc:sqlite:/Volumes/Seagate Expansion/Database/BackupDB.db
The database has been closed

**Comment by pawelsalawa** [comment]
Does this have anything to do with SQLiteStudio? If not, I recommend you to ask this on the StackOverflow, as there is way, way more people that could help you.

Here I don't really know how to help with your case.

**Comment by aakjpe** [comment]
Hi.

 

I agree with you, not a SQliteStudio issue.

Will try StackOverflow

 

Thank you.

 

Kp

 

 

Fra: Paweł Salawa <notifications@github.com>
Svar til: pawelsalawa/sqlitestudio <reply@reply.github.com>
Dato: tirsdag 16. februar 2021 11:54
Til: pawelsalawa/sqlitestudio <sqlitestudio@noreply.github.com>
Kopi: aakjpe <kjell@kjellpettersen.com>, Author <author@noreply.github.com>
Emne: Re: [pawelsalawa/sqlitestudio] Get "The database has been closed"when running cron, not running directly" (#3978)

 

Does this have anything to do with SQLiteStudio? If not, I recommend you to ask this on the StackOverflow, as there is way, way more people that could help you.

Here I don't really know how to help with your case.
