### ISSUE TITLE
Math Functions Not Compiled In

### ISSUE THREAD

**Issue by btribley** [pawelsalawa/sqlitestudio#4011]
select floor(2) gets "no such function: floor". Same with Trunc.
See https://www.sqlite.org/draft/lang_mathfunc.html 
Is it possible to compile my own with -DSQLITE_ENABLE_MATH_FUNCTIONS compile-time option enabled? If so how to patch it in?

**Comment by pawelsalawa** [comment]
You're referring to "draft" (see your link), which refers to not-yet released SQLite version 3.35.0 (lease date is set to March 30). When SQLite 3.35 is release, you may expect SQLiteStudio to follow the upgrade soon with these functions enabled.
