### ISSUE TITLE
DEFECT: Dark Mode - Import/Export wizards do not go dark & text cannot be seen

### ISSUE THREAD

**Issue by data-geek1** [pawelsalawa/sqlitestudio#4012]
Description
-------------
When SQLITE v3.34.1 is in dark mode the 'Import Data' & 'Export Data' pop-up wizards have a white background and the field title text is missing. The field title text may be due to the text colour changing to white [in dark mode] thus is blending into white background i.e. the text is there but is hidden by the white background that should be dark.

[White vs. Dark Mode_compressed.pdf](https://github.com/pawelsalawa/sqlitestudio/files/6079306/White.vs.Dark.Mode_compressed.pdf)

(not putting duplicated details for the Export wizard purely to reduce size of this post and can be part of your re-testing and any further regression testing)

Environment Details
----------------------
SQLiteStudio 3.34.1
'Precompiled Binaries for Windows' - "32-bit DLL (x86) for SQLite version 3.34.1"

Expected Result
-----------------
The Import wizard has DARK background when Fusion Dark is selected in configuration settings. And the following Import pop-up wizard shows: - 'Table to import to' = Database, Table - 'Data source to import from' [in CSV type]= "Data source type", "Options", "Input file", "Text encoding", "Ignore errors", "Data source options", "First line represents CSV column names", "Field separator", and "NULL values"

Actual Result
--------------
The Import wizard has WHITE background when Fusion Dark is selected in configuration settings. And the following Import pop-up wizard shows: - 'Table to import to' = field titles aren't displayed - 'Data source to import from' = field titles aren't displayed

Steps to Recreate
--------------------
1. Highlight table name
2. Press right-mouse-button and select 'Import into table' / 'Export the table'
3. Compare the Import pop-up window with the Expected & Actual results.

**Comment by MH15** [comment]
I'll take a swing at this if work has not yet begun. This is actually one of the only issues I've encountered with the software so I'd love to fix it if help is needed.

**Comment by Qriist** [comment]
I confirm this bug still exists in 3.3.2, and with the x64 binaries.
