### ISSUE TITLE
Import file wizard crashes when a CSV is not uploaded comma separators and a custom separator cannot be entered

### ISSUE THREAD

**Issue by data-geek1** [pawelsalawa/sqlitestudio#4013]
**Description**
When the "Custom" is selected on the 'Field Separator' drop-down the user cannot enter a separator value in the custom field because the field does not become active in "Custom" mode.
In addition when a CSV file is uploaded with anything but a "," [comma] e.g. ";" semi-colon the program crashes.

**Environment**
SQLiteStudio 3.34.1
'Precompiled Binaries for Windows' - "32-bit DLL (x86) for SQLite version 3.34.1"

**Expected Result**
"Custom" Mode = the custom separator field becomes ACTIVE and the user can enter a custom separator.
Separator value "," [comma] = CSV file data is imported into desired table.
Separator e.g. ";" [semi-colon] = CSV file data is imported into desired table.

**Actual Result**
"Custom" Mode = the custom separator field remains DEACTIVATED so the user cannot enter a custom separator.
Separator value "," [comma] = CSV file data is imported into desired table.
Separator e.g. ";" [semi-colon] = CSV file data is NOT imported into desired table and the program crashed requiring to end process in task manager.

**Steps to Recreate**
"Custom" Field
----------------
1. Highlight table name to import data.
2. Press right-mouse-button and select 'Import into table' / 'Export the table'.
3. Select the CSV file to be imported and then press 'Next' button. 
4. Select "Custom" option on the 'Field Separator' drop-down list.
5. Press the custom separator for active cursor and then type the desired custom separator character(s).
6. Compare the "Custom" Mode with the Expected & Actual results.
[White vs. Dark Mode_compressed.pdf](https://github.com/pawelsalawa/sqlitestudio/files/6079427/White.vs.Dark.Mode_compressed.pdf)

1. Highlight table name to import data.
2. Press right-mouse-button and select 'Import into table' / 'Export the table'.
3. Select the CSV file to be imported and then press 'Next' button. 
4. Select [e.g. comma, semi-colon, tab] option on the 'Field Separator' drop-down list.
5. Compare the Separator values with the Expected & Actual results.

**Comment by pawelsalawa** [comment]
I cannot reproduce any of this.

1. Whenever I pick "Custom:" as separator, the separator field becomes active, as expected.
2. If I load CSV file with any other separator (and I define it in Custom separator field), it loads correctly.
3. If I load CSV file with any other separator (and pick for example `;` semicolon for the separator), it also loads correctly.

There is no SQLiteStudio 3.34.1. There is SQLiteStudio 3.3.2 (at the time I'm writing this). Version 3.34.1 is for SQLite database, not for SQLiteStudio.

Also, there is no 32-bit binary for Windows anymore. Only 64 bit.

**Comment by data-geek1** [comment]
I have tried importing a csv with 'custom' selected but the custom but the custom field is still not active. I have even deleted everything and downloaded a whole gui plus downloaded the 64-bit windows dependencies, plus even downloaded latest binaries from sqlite.org, but still not working.
Perhaps you could help to determine that either I may be missing from download or maybe there is something else the matter. Thanks

**Comment by pawelsalawa** [comment]
You don't need the "dependencies" - these are only needed if you're compiling SQLiteStudio from source code by yourself. All you need is only the zip file that you download if you hit "Download" button on https://sqlitestudio.pl

I still cannot reproduce your problem. I open import dialog, click Next to get to the last page and there I have CSV format selected, with `;` separator initially:

![image](https://user-images.githubusercontent.com/481846/117159854-ec04dd80-adc0-11eb-8f7d-3f7a8778e4e8.png)

Then I change it to custom and the field on the right side becomes editable:

![image](https://user-images.githubusercontent.com/481846/117159923-fb842680-adc0-11eb-89ce-9b668039ca66.png)

Then I click on that editable field and type `|` there:

![image](https://user-images.githubusercontent.com/481846/117159976-076fe880-adc1-11eb-8eda-890505a0ab4a.png)

Are you saying it doesn't work like this for you?

Are you using version 3.3.3? You can see it at the title bar:

![image](https://user-images.githubusercontent.com/481846/117160159-2d958880-adc1-11eb-898c-93de263fcc40.png)

**Comment by data-geek1** [comment]
I think I see the problem: the custom field on your screenshot an 'white on red' exclamation mark "!"; whereas mine does not have the exclamation mark hence my customer field if not active.

Thinking over this, when I deleted my old version SQLiteStudio (just deleted the files) and then downloaded the latest 3.3.3 file, when I launched the 3.3.3 program it was already connected to all of my databases and my most recent SQL Editor was open (i.e. the same one I had open in the prior version). I wonder whether there is a log file issue where the log files for the old version is still dictating the functionality of the latest 3.3.3 version, which would make sense because there is not 'uninstall' program.

When you downloaded the 3.3.3 to your device (after you deleted your previous SQLiteStudio folders & files), did you delete any of the log files that would be naturally deleted if there was an uninstall program?


![SQLITE_ImportWizard](https://user-images.githubusercontent.com/80007365/119652205-b1b9b980-be1d-11eb-8327-9bd3967cf155.JPG)

**Comment by pawelsalawa** [comment]
The only way to not have the "red circle with white exclamation" and not seeing anything in this field at the same time is to put a whitespace in this field (that you marked with red). Otherwise I can freely enter anything I want there. I have tried Fusion Dark theme too - just to be sure. All good as well.

Answering your other question - yes, there is a configuration file, which will be reused if you change SQLiteStudio version. It should not have anything to do with your problem, but we can do an experiment.

1. Run SQLiteStudio

Find out where your config is:
![image](https://user-images.githubusercontent.com/481846/119730098-a2fef100-be75-11eb-9269-d4b5956f38a6.png)

![image](https://user-images.githubusercontent.com/481846/119730172-b611c100-be75-11eb-95a1-8b929de412fa.png)

![image](https://user-images.githubusercontent.com/481846/119730277-d5a8e980-be75-11eb-93cb-96980225521a.png)

2. Close SQLiteStudio.

3. Go to this directory.

4. There will be a file called `settings3`. Rename it to anything else.

5. Run SQLiteStudio again. This time it will be "fresh". Try to reproduce your problem.

**Comment by data-geek1** [comment]
Done this and its worked i.e. the custom field is now active and has the '_white on red_' exclamation mark, plus I can enter any character I like. Thank you!

I would like to add though that I'm probably not the only person who is experiencing this issue. Therefore perhaps it would be wise to have an action list of things for a user to look-for / change when they download a future version, especially if they have previously used a legacy version.

**Comment by pawelsalawa** [comment]
Would you be willing to share the old configuration file with me so I could reproduce and investigate the problem?

Things that are stored In the file are:
- configuration dialog settings
- history of SQL queries executed
- history of DDL (tables, views) changes (only structure, not the data)
- remembered values of SQL query positional parameters (if you executed queries with `?` or `:param` parameters in SQL editor)
- list of databases (name, path to file)

Things that are **NOT** stored in configuration file:
- table data
- registered database files
