### ISSUE TITLE
Table structure change - improper quoting

### ISSUE THREAD

**Issue by tedstriker2** [pawelsalawa/sqlitestudio#4018]
### Details
I renamed some columns in a table. The automatically generated SQL to copy the table, drop it, and rename the copy has improper quotes around the star (after SELECT). Here's a screenshot:

![image](https://user-images.githubusercontent.com/56124863/110172174-5c43b280-7dc2-11eb-913b-21f2c4c479f6.png)

### Steps to reproduce
Change a table.

### Operating system
Windows 10

### SQLiteStudio version
3.3.1

**Comment by pawelsalawa** [comment]
I knew skipping unit test for this will bite me back...

**Comment by tedstriker2** [comment]
Unwanted quotes are also being placed around numbers. I understand that SQLite has weak typing, so treating numbers as text is not as serious an issue.
