### ISSUE TITLE
Highlight parenthesis match in different way than "selected text"?

### ISSUE THREAD

**Issue by tedstriker2** [pawelsalawa/sqlitestudio#4019]
### Details
The parenthesis match highlighting looks exactly the same as the selected text highlighting. Could it be a different foreground or background color so I can tell them apart? Here's a screenshot of the current look:

![image](https://user-images.githubusercontent.com/56124863/110180837-23123f00-7dd0-11eb-9dee-084825582c19.png)

### Steps to reproduce
Highlight next that is next to a parenthesis.

### Operating system
Windows 10

### SQLiteStudio version
3.3.1

**Comment by pawelsalawa** [comment]
I'll try to squeeze it into 3.3.2, but I cannot promise it, as there is that other urgent bug to fix.

It depends how much effort it will turn out to be to implement this. Either 3.3.2 or 3.3.3.

**Comment by tedstriker2** [comment]
No problem! For me it is a minor issue. Thanks!
