### ISSUE TITLE
Passing SQL script in command line

### ISSUE THREAD

**Issue by jiangweiatgithub** [pawelsalawa/sqlitestudio#4024]
### Details
If that is not available, then I guess that would be a great feature to have

Thanks!

**Comment by mslavkovski** [comment]
Does separating each command with a semicolon, then selecting the entire script, and running it is doing
 the job?

I already use that for executing hundreds of commands.

**Comment by pawelsalawa** [comment]
@mslavkovski Here it is about executing SQL directly from file, without loading it into the SQL editor.

@jiangweiatgithub You can execute it by right-clicking on the database and using this:
![image](https://user-images.githubusercontent.com/481846/110919950-17b59b00-831d-11eb-91f5-e1eecb69fa3e.png)

**Comment by jiangweiatgithub** [comment]
Is there any way to automate this from a command line?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pawelsalawa** [comment]
Currently no.

**Comment by pawelsalawa** [comment]
Why would you use SQLiteStudio for such simple task? Isn't it better to use official sqlite3.exe? It's lighter and in many cases will be faster, because it does not have to handle all the extra features that SQLiteStudio has.

**Comment by jiangweiatgithub** [comment]
My script contains the REGEX function, which is vailable in SQLiteStudio, but not in sqlite3.exe. I will need to run the script from another batch script.

**Comment by pawelsalawa** [comment]
Okay. I'll keep the issue open then.

**Comment by jiangweiatgithub** [comment]
Is this feature going to be added soon?

**Comment by pawelsalawa** [comment]
I don't think so. There is a lot of features pending, many of which have higher priority.

**Comment by pawelsalawa** [comment]
I mean I scheduled it for 3.4.0, so it's planned sooner than later, but still there is 3.3.3 pending with more urgent fixes. Then 3.4.0 is major version and will take a bit longer to implement.

**Comment by pawelsalawa** [comment]
Apart from allowing script in command line, it will also require the target database name or file to be passed in the command line too, in order to make this even possible.
