### ISSUE TITLE
Default value is blank in Structure tab

### ISSUE THREAD

**Issue by jaypdl** [pawelsalawa/sqlitestudio#4034]
### [Details]
When in the structure tab of an open table, the Default Value column is blank. It doesn't say null, and it doesn't say what the assigned default is. It is just blank.

In image: 3.2.1 Displaying correctly on left, and 3.3.2 on the right displaying nothing for "Default value"
![Image of Issue](https://i.imgur.com/sGy0DzP.png)

### Steps to reproduce
Open Database, Open Table, Select Structure tab.

### Operating system
Windows 10 Pro 20H2

### SQLiteStudio version
3.3.2, (last version that Default value populated: 3.2.1)

**Comment by pawelsalawa** [comment]
Do you have any DEFAULTs defined, or you're just saying that the "NULL" is missing? What if you define some DEFAULT value - is it shown then?

**Comment by jaypdl** [comment]
I updated with an image comparing 3.2.1 and 3.3.2 with the same DB and table

**Comment by pawelsalawa** [comment]
I see. Thank you. Can you also please show me what is on the DDL tab in 3.3.2 version?

**Comment by jaypdl** [comment]
Sure thing. Here's 3.2.1 and 3.3.2 again:

![Image of Issue](https://i.imgur.com/qOVkzN5.png)

**Comment by pawelsalawa** [comment]
Thank you!
