### ISSUE TITLE
Some concatenated text can not be copied

### ISSUE THREAD

**Issue by tedstriker2** [pawelsalawa/sqlitestudio#4035]
### Details
I build a SQL statement from a query, and sometimes when I copy the statement all I get is an empty string. I apologize in advance for how hard this will be to reproduce - sometimes I can copy one result row, but not another!

### Steps to reproduce
Here's one query where the issue occurs (I need to copy the contents of the "insert_sql" column):

```
SELECT
    dts.tbl_name,
    dts.max_rowid,
    dts.num_rows,
    dts.max_rowid - dts.num_rows ld_offset,
    (CASE
        WHEN
            dmn.attr_lbl IS NULL
        THEN
            'INSERT INTO dmz_magic_numbers (attr_lbl, attr_val) VALUES ('
            ||quote(v.attr_prefix||dts.tbl_name)
            ||', '
            ||(dts.max_rowid - dts.num_rows)
            ||');'
    END) insert_sql,
    (CASE
        WHEN
            ss.name IS NOT NULL
        THEN
            1
        ELSE
            2
    END) severity
FROM dmz_tab_stats dts
LEFT JOIN sqlite_sequence ss
ON
    ss.name = dts.tbl_name
CROSS JOIN
(
SELECT
    'max_rowid offset/' attr_prefix
) v
LEFT JOIN dmz_magic_numbers dmn
ON
    dmn.attr_lbl = v.attr_prefix||dts.tbl_name
WHERE
    dts.max_rowid > dts.num_rows + (dts.num_rows * 0.1) + ifnull(dmn.attr_val, 0)
    AND dts.tbl_name != 'dmz_prog_stats'
    AND NOT EXISTS (
        SELECT
            1
        FROM v_tab_fk vtfk
        WHERE
            vtfk.tbl_name = dts.tbl_name
            AND vtfk.fk_on_delete = 'CASCADE'
    )
ORDER BY
    severity,
    ld_offset DESC,
    dts.tbl_name
;
```
Note: If I switch to "form view" or click the double blue arrows to "Load remaining part of value" then the column text disappears. What is even stranger: The entire value was already visible, so there was no need for the double blue arrows.

### Operating system
Windows 10

### SQLiteStudio version
3.3.2

**Comment by pawelsalawa** [comment]
Are you copying SQL statement (the query or its part), or are you copying results? It seems like you mean results, but I want to be sure, because initially you wrote you're copying "statement".

Anyway, assuming you mean results, all you described makes sense. It looks like this particular column has quite complex expression, thus maybe "load full value" functionality doesn't work properly in some cases (when result value is longer then 100 chars). That would also explain disappearing value when you click double-arrow or switching to Form View.

This is obviously a bug and I'll try to reproduce it and fix it.

**Comment by tedstriker2** [comment]
Yes - I encountered the bug while trying to copy query results. In this case, the "results" are actually statements that the query is building for me. Here is the output that could not be copied within SQLite:

```
INSERT INTO dmz_magic_numbers (attr_lbl, attr_val) VALUES ('max_rowid offset/file_version', 929908);
```

**Comment by tedstriker2** [comment]
Update: I found a simpler version of the query that demonstrates the bug:

```
SELECT
    (CASE
        WHEN
            dmn.attr_lbl IS NULL
        THEN
            'INSERT INTO dmz_magic_numbers (attr_lbl, attr_val) VALUES ('
            ||quote(v.attr_prefix||dts.tbl_name)
            ||', '
            ||(dts.max_rowid - dts.num_rows)
            ||');'
    END) insert_sql,
    1 severity
FROM
(
SELECT
    'file_version' tbl_name,
    929908 max_rowid,
    0 num_rows
UNION ALL
SELECT
    'file_versio' tbl_name,
    929908 max_rowid,
    0 num_rows
UNION ALL
SELECT
    'file_versionx' tbl_name,
    929908 max_rowid,
    0 num_rows
) dts
CROSS JOIN
(
SELECT
    'max_rowid offset/' attr_prefix
) v
LEFT JOIN
(
SELECT
    NULL attr_lbl
) dmn
ON
    dmn.attr_lbl = v.attr_prefix||dts.tbl_name
WHERE
    NOT EXISTS (
        SELECT
            1
        FROM v_tab_fk vtfk
        WHERE
            vtfk.tbl_name = dts.tbl_name
            AND vtfk.fk_on_delete = 'CASCADE'
    )
;
```
Note that the bug only happens with the "NOT EXISTS" based on "v_tab_fk", so here's the DDL for that view:

```
CREATE VIEW v_tab_fk AS
SELECT
    sm.name tbl_name,
    fk."from" col_name,
    fk."table" fk_tbl_name,
    fk."to" fk_col_name,
    fk.on_update fk_on_update,
    fk.on_delete fk_on_delete,
    fk."match" fk_match
FROM sqlite_master sm
CROSS JOIN pragma_foreign_key_list(sm.name) fk
WHERE
    sm.type = 'table'
;
```
The bug will happen when the resulting column is >= 100 characters.

**Comment by pawelsalawa** [comment]
Thank you! That should be more than enough to reproduce it.
