### ISSUE TITLE
Portable setting folder doesn't work

### ISSUE THREAD

**Issue by mateusz-sokrates** [pawelsalawa/sqlitestudio#4043]
### Details
After unpacking the zip archive and creating the "sqlitestudio-cfg" directory next to "SQLiteStudio.exe", the settings file is created in [...]\AppData\Local\SalSoft\SQLiteStudio\ not in the "sqlitestudio-cfg" folder.

### Operating system
Windows 10 Pro x64 20H2 (19042.867)

### SQLiteStudio version
3.3.2

**Comment by pawelsalawa** [comment]
I might have broken this in 3.3.x... I'll look into it.
