### ISSUE TITLE
Not able to use latest version of SQLite with SQLiteStudio

### ISSUE THREAD

**Issue by balajiramanathan** [pawelsalawa/sqlitestudio#4044]
### Details
Previously, I used to be able to drop a sqlite.dll file into the sqlitestudio folder on my computer as and when new versions of sqlite are released, and sqlitestudio was able to use the new version of sqlite with all its speed improvements, bug fixes etc.  Now, this does not seem to be possible.  SQLiteStudio is compiled with the sqlite inside it, and it is not possible to change that version of sqlite until a new version of SQLiteStudio is released with the new sqlite compiled in.

This is very inconvenient and makes sqlitestudio obsolete almost as soon as a new version comes out.  For example, SQLiteStudio is using sqlite version 3.34.1 while sqlite has already released 3 or 4 new versions and is at 3.35.3.  Given that the release frequency of sqlitestudio is much lower than that of sqlite, there has to be some way of moving sqlitestudio to newer versions of sqlite as they are released.  The inability to do that will make sqlitestudio pretty much unusable, especially when the sqlite version release fixes bugs or introduces important new features.

Last year, after sqlite introduced window functions, I continued using sqlitestudio with a new version of sqlite that included that feature even though sqlitestudio refused to allow me to edit views with window functions in them (I am not sure why sqlitestudio needs to worry about parsing and understanding SQL - that should be left up to SQLite, but I am not knowledgeable enough to go there), but I could still select * from such views, and everything worked great.  If SQLite introduced such a useful new feature right now, depending on what it is, everybody has to make a choice about whether they want the feature or they want to use sqllitestudio, because doing both has been made impossible.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment]
Yeah... I know. I wasn't 100% convinced with this decision, although it was the only way to make sure SQLiteStudio uses correct verion of SQLite when is being built with GitHub Actions. For some reason it is extremely hard to get it done right with GitHub Actions. Trying to remove SQLite packages, or even deleting files directly with `rm` fails (often quietly) randomly.

I will revisit it once more, because I understand the importance of having is as a shared library.
