### ISSUE TITLE
Generated columns included in insert statements on SQL export.

### ISSUE THREAD

**Issue by hal2000gh** [pawelsalawa/sqlitestudio#4060]
### Details
Generated columns are included in the exported SQL code. Running this code causes a "cannot INSERT into generated column" error.

### Steps to reproduce

Create a database and the following table:
```
CREATE TABLE Test (
    data INTEGER,
    calc INTEGER AS (data * 2) 
);
```

Export the DB via Tool -> Export -> A database

The generated code looks like this:
```
--
-- File generated with SQLiteStudio v3.3.2 on So Apr 11 14:44:08 2021
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: Test
DROP TABLE IF EXISTS Test;

CREATE TABLE Test (
    data INTEGER,
    calc INTEGER AS (data * 2) 
);

INSERT INTO Test (data, calc) VALUES (1, 2);
INSERT INTO Test (data, calc) VALUES (2, 4);
INSERT INTO Test (data, calc) VALUES (3, 6);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;


rollback transaction;

```
 Column **calc** must not be included in the insert statements.

### Operating system
Windows

### SQLiteStudio version
3.3.2

**Comment by pawelsalawa** [comment]
Note to myself:
The same seems to be affecting export of SQL query results if the query contains expression columns. For example for query: `select typeof(column1), * from a1;` the exported (as SQL format) data is:
```
INSERT INTO aa ("typeof(column1)", column1, column2) VALUES .....;
```

**Comment by pawelsalawa** [comment]
Okay, exporting just any query result (like my example above) can always lead to weird inserts and that cannot (and should not) really be solved.

Still, exporting a table (or a database) should result in proper SQL and that I will fix with here.

**Comment by hal2000gh** [comment]
Great, thanks!
