### ISSUE TITLE
Repository/collection of SQL scripts

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#4065]
It would be nice to have global SQL editor scripts, not associated with a specific database, saved in SQLite database which is automatically attached/connected at application launch.

Perhaps it could work as a "code snippets" too (i.e. small script easily accessible with some context menu, or from code assistant).

**Comment by JrgMyr** [comment]
Would be nice if that allows to store queries with parameters and update queries.

**Comment by audiomuze** [comment]
This would be a great addition.  I have many code snippets and entire scripts comprising 100's of lines that I reuse periodically.  Managing them within SQLiteStudio's "windows" capability is not a great experience - too easy to accidentally close a window and lose the code (there's even a option to close all windows and lose all code in one action) and no way to easily sort or organise them by project etc).

Ideally one would b able to associate databases and scripts with a particular project and also have a code/ script repository which enables code to be checked in and then imported into projects as required.  The version checked into a project would live within the project and not have any relationship with the code/script repository unless explicitly checked back in or added as a new entry.

**Comment by sa2000a** [comment]
Hi - if it is easier, I would be happy with an export feature to export **all** my queries history to a text file - or a csv file export giving the fields you currently hold/display

**Comment by pawelsalawa** [comment]
Created #4286 for the same.

**Comment by tuffnatty** [comment]
It would also be really great if one could assign such script to a keyboard shortcut.

**Comment by pawelsalawa** [comment]
@audiomuze How do you imagine these "projects"? I mean SQLiteStudio does not have concept of projects.

**Comment by pawelsalawa** [comment]
Code Snippets are now implemented for 3.4.0.
To define them, you can use the Code Snippets editor window.
To use them, hit the "code assistant" hotkey twice.
You can define snippet hotkeys, that you can use when the snippets are presented in the code assistant.

**Comment by pawelsalawa** [comment]
![image](https://user-images.githubusercontent.com/481846/184448190-56e6eedb-6081-47fe-81e0-1fd48987e279.png)

![image](https://user-images.githubusercontent.com/481846/184448221-75151908-c927-4d41-9401-711e672fa960.png)

**Comment by norrye** [comment]
If I terminate sqlitestudio because of a query that I have not optimised or is taking a long time due to a poorly thought out script (i.e. leaving where clauses out...), will I lose the sqleditor windows I have open?

**Comment by pawelsalawa** [comment]
@norrye  I don't think your question is relevant to this very issue (of SQL scripts collection). Anyway, to answer your concerns - in version 3.4.0 the state of SQLiteStudio (editor windows, etc) is saved on the fly, so if it crashes, you should be able to get your last (or almost last) work state after next start. You should not lose your work.
