### ISSUE TITLE
Proposal for enhancement: Columns orders in Tree View similar as Structure order aka design order

### ISSUE THREAD

**Issue by EmmanuelSimond** [pawelsalawa/sqlitestudio#4085]
### Details
Proposal for enhancement: SAME Columns orders in Tree View as defined by design in  the Structure tab

### Steps to reproduce
Create a table with columns
Unfold view in the Treeview 

![SQLiteStudio_screenshot_1](https://user-images.githubusercontent.com/15954677/115998825-65464880-a5e9-11eb-9219-c949b19fd027.png)

It seems the order of the columns displayed in the Tree View is ALPHABETICAL ASCENDING. 
It should be the same at the order of the Columns as defined & seen in the Structure Tab.

### Operating system
Win7

**Comment by tuffnatty** [comment]
Works for me with "Sort table columns alphabetically" setting switched off.
