### ISSUE TITLE
Keyboard shortcuts standardization

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#4088]
- `F2` should be for entering cell editing
- Configuration dialog could be open with F10

**Comment by JrgMyr** [comment]
May I add a minor bit to that:
- Ctrl-R could be "Refresh the view" in the View Editor
- Ctrl-S could be "Commit the view changes" (aka. save the view)
- [F9] could execute a query/view (as in the SQL Editor). [Alt]-[Right] already does that but is less intuitive.
