### ISSUE TITLE
Shortcut for changing font-size in editor

### ISSUE THREAD

**Issue by bnetz** [pawelsalawa/sqlitestudio#4092]
I am using SQLiteStudio in school with my students. The standard font in the editor is too small in my opinion (maybe as mentioned in issue #4082), esp. if one student shows his screen to another.
It would be very comfortable it the font-size in the editor-window could be adjusted with some shortcut like alt+ or strg+ or strg-mousewheel.

**Comment by ysalmon** [comment]
Alternatively, or in addition to that, the default font size for the main parts (iirc, 8) is too small. It should be increased to 12, the default font size of most text processors, at least for the SQL editor.

**Comment by bnetz** [comment]
Cool, thanks!
