### ISSUE TITLE
Foreign key field entries frequently break SQLiteStudio

### ISSUE THREAD

**Issue by balajiramanathan** [pawelsalawa/sqlitestudio#4093]
### Details
Unfortunately, I can't give you the steps to reproduce the error since it occurs at random.  What happens is that when I try to enter any value in a foreign key field, the value 1 gets entered there automatically, and it is impossible to change it without pulling down the dropdown arrow and choosing some other value.  When you have a foreign key reference table with thousands of rows, this is very tedious and error-prone.  Sometimes, if I do manage to change the entry in that field using the keyboard, and then try to commit the change, SQLiteStudio crashes (SQLiteStudio has stopped responding, Close the program, Windows is looking for a solution to the problem, blah blah blah, you get the general idea).

Here is my suggestion:  give people an option to either use drop-down arrow while entering foreign key fields or let them just enter the value using keyboard.  This hybrid approach is causing lots of problems.  I have also noticed that there is significant noticeable lag when I move the cursor to some foreign key fields if the referenced table is large because it looks like some query is running in the background to populate the dropdown in realtime.  Getting rid of the dropdown will solve that problem also.  Let the user enter the correct value or encounter error message about invalid value if they choose to turn off the dropdown option.  Not allowing me to opt out of the dropdown and causing crashes and delays in data entry is very painful for me.  Also, after program crashes, I have to check lots of entries to see what was committed before the crash and what was in process but didn't make it into the database before the crash.  Total waste of time and effort, and makes me paranoid about errors in my database that I was not careful enough to catch and correct.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
Windows 7 Home Premium

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
I will try to reproduce it. It looks like it happens if foreign tables are big, so I will try it this.

I will also add a configuration checkbox to disable dropdowns entirely, because I understand your struggle.

**Comment by balajiramanathan** [comment]
Thank you very much, Pawel.
