### ISSUE TITLE
Filtering by column values is not reversible

### ISSUE THREAD

**Issue by balajiramanathan** [pawelsalawa/sqlitestudio#4095]
### Details
If you use "Show filter inputs per column" and enter a value to filter on, you can't go back to unfiltered view

### Steps to reproduce
Open a table in data view
Right click on a column header and choose "Show filter inputs per column"
Enter a value to filter that column by - the results now reflect just rows that passed that filter
Now click the "x" near the filter value to remove the filter - the value disappears, but the table remains filtered
Even refreshing the data using the blue refresh button does not get back the unfiltered view - in fact, that recreates the filtered view with the value repopulated in the filter field
The only way to go back to unfiltered view is to close the window, and open the table again in new window

### Operating system
Windows 7

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
You can apply "no filter" by hitting Enter key in the cleared filter input.

Still, this is unintuitive and inconvenient. I agree. Hitting "x" should apply the filter at once.

**Comment by balajiramanathan** [comment]
Thank you, Pawel.  Yes, I now see that I can delete the value entered in the filter field and hit return to go back to unfiltered view.  It is a little unintuitive given that the global filter works differently (hitting the "x" deletes and disables the filter at the same time).

I have also noticed that even after filtering a column using the column level filters, it is possible to click on the column header and choose to turn off "Show filter inputs per column".  This is a problem because now, the view on the screen is filtered, but you have absolutely no idea what criteria was used for the filter.  Unless you know that the filter value may be hidden, and you choose to show filter inputs at the column level, the filter remains hidden but active, and can cause a lot of confusion.

**Comment by pawelsalawa** [comment]
Yes, that's even bigger problem. Anyway, the bugfix is scheduled for 3.4.0.
