### ISSUE TITLE
No ability to filter by exact match

### ISSUE THREAD

**Issue by balajiramanathan** [pawelsalawa/sqlitestudio#4096]
### Details
The filter works on partial contents of columns also.  If I filter for 50, the results show columns with not just 50, but also 150, 250, 500, 1505, etc.  It would be good to have an option to be able to filter for specific value instead of filtering for that value to be part of the contents of the column.

Perhaps a checkbox next to the filter input box can be provided where I can toggle between current behavior and filtering for exact matches.  Thank you.

**Comment by pawelsalawa** [comment]
When you turn on column filter inputs, the main filter becomes disabled and the filter mode (dropdown on the right of the main filter input) is still active, except it has only 2 options available then. The mode applies to column filter inputs, as long as they are shown.

You can switch to "RegExp" filter mode to be able to match strictly "50", by typing (with RegExp mode): `^50$`.

Still, I agree that it would be nice to have "strict" filter mode, which matches full values as you described. I will consider this issue report as enhancement proposal for that feature.
