### ISSUE TITLE
Table/View disappears from the Databases panel when using Drag & Drop 

### ISSUE THREAD

**Issue by ghost** [pawelsalawa/sqlitestudio#4098]
### Details
A table / view disappears from the Tree panel (database schema) when it is dragged and dropped onto the SQL editor panel. It requires a refresh of the database schema to make the object visible in the Tree panel again.

### Steps to reproduce
Drag any table or view from the Tree control and drop it anywhere in the SQL editor.

### Operating system
macOS Catalina 10.15.7

### SQLiteStudio version
SQLiteStudio 3.3.3

**Comment by forna** [comment]
Still happening in 3.4.0

**Comment by pawelsalawa** [comment]
Yes, because it's assigned (and already fixed) in the 3.4.1 version. It is to be released in few days, I hope.
