### ISSUE TITLE
Underscore column names not visible in Data view.

### ISSUE THREAD

**Issue by nexcentric** [pawelsalawa/sqlitestudio#4121]
If you have a column name containing underscore, they are not visible in Data view, as in the attached image:

![Capture](https://user-images.githubusercontent.com/56408907/119357960-692cbf80-bca8-11eb-8ee7-77cf68379944.PNG)

They are visible here:
![Capture2](https://user-images.githubusercontent.com/56408907/119358196-b14be200-bca8-11eb-97ce-4e94ade5e880.PNG)

**Comment by pawelsalawa** [comment]
It looks more like an issue with font size vs header size. The font is not fitting into the header, unless there is a sorting icon displayed, which enlarges the header slightly.

**Comment by pawelsalawa** [comment]
Are you perhaps scaling your desktop (like 125% or 150%) due to HighDPI display?

**Comment by nexcentric** [comment]
> Are you perhaps scaling your desktop (like 125% or 150%) due to HighDPI display?

Hi, my desktop is just the default one, no dpi modifications, etc. My monitor is a 1920x1200 Dell screen.

**Comment by tuffnatty** [comment]
A duplicate of #3502.
