### ISSUE TITLE
Copying output of SQL sometimes crashes SQLiteStudio

### ISSUE THREAD

**Issue by balajiramanathan** [pawelsalawa/sqlitestudio#4129]
### Details
Sorry, I can't reproduce the problem reliably.  But I ran a query (it uses recursive CTE's and generates about a million rows of output in the recursive part.  The final output is just one of those rows.  The query takes about 1000 seconds to finish running.  After the output is displayed, I highlighted one of the output columns and hit ctrl+c to try and copy that value to a different program.  My cursor turned into a blue donut and even though I waited for several hours, the program never gave me back control.  I had to eventually close the program because it would not respond.

I am not sure exactly what was going on, but it felt to me as if even though the output of the query was displayed on the screen, when I click on one of the displayed values to copy it, the program is trying to rerun the query to compute that value again.  In this case, because the query is very compute and memory-intensive, it crashes the program and makes it impossible to recover gracefully.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
Windows 7 Home Premium 64-bit

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
What you described is exactly what's happening.

Because SQLiteStudio is cutting off long values (longer than 100 chars) initially to safe memory, if you try to copy the value, it will try to again execute the query to load full value and copy to clipboard the full value, not just limited 100 chars.

This is a though one, because it's really hard to make a decision what is right here:
- to remove the 100 chars limit and let queries like yours run just once (so no subsequent loading of full value) - this has a disadventage when an user loads results of 300 columns and each cell has 30KB of data (times 1000 rows, so 30KB * 1000 * 300 = around 9GB of memory). There were users that did that and the app was crashing due to running out of memory.
- to keep the 100 chars limit, so the above case does not happen, but then queries like yours cause troubles...

**Comment by balajiramanathan** [comment]
Interesting.  Do the results of the query have to be stored in memory for it to be displayed on the screen?  I mean, if the query produced 1000 rows of output, at any time, on the screen you can only show about 40 or 50 rows.  So, is there some paging mechanism that will allow you to load only the visible rows in memory and keep the rest in a temporary file or something like that?

Secondly, assuming you don't remove the 100-character limit, then when the user tries to copy some result from the query, you are going to have to rerun the query to get the full values.  That leads to the first case anyways.  To me, it seems as if the first case is the lesser of the two evils.  Let the user make sure their query doesn't produce 9 GB of data to display.

As an aside, the query I ran, even though the intermediate results may have contained a million rows, the final result was just a single row, and I doubt that row was even 1KB in total length.  Pretty small amount of final output.

**Comment by pawelsalawa** [comment]
Regarding keeping in memory - there is a reason for that too. If we decided to use "database cursor" and just fetch columns/rows currently visible, we would need to keep the active executed statement and not close it. That would work, but the side effect is that we also keep the lock on the queried tables. We prevent any other applications from modifying data until we release the executed statement and that's a big problem.

I guess just letting user worry about memory usage might be a better approach. I will still need to think about it when I sit down to this one.

**Comment by balajiramanathan** [comment]
If you keep a cursor open and therefore the statement is kept active, will that lock all the tables that the statement uses?  I can see how that can be a bit of a problem.  If the user tries to modify any of those tables when the statement is active, maybe you can provide a pop-up choice:  keep the cursor active, or close the statement (no more updates in the query window) and allow the update to go through.  The user can then decide which is more important.

**Comment by pawelsalawa** [comment]
Users do not like to be asked such questions :) They often don't know. No worries. I will address this concern. I've added this issue to 3.4.0 milestone.

**Comment by balajiramanathan** [comment]
Thank you for the explanation, Pawel.  Hope this resolves the issue in most cases.
