### ISSUE TITLE
Not Align Column

### ISSUE THREAD

**Issue by kelicto** [pawelsalawa/sqlitestudio#4136]
Version 3.3

![image](https://user-images.githubusercontent.com/23723575/121330563-b49dc980-c948-11eb-8066-9495f6da8b2d.png)

**Comment by pawelsalawa** [comment]
It is expected. SQLiteStudio aligns numbers to the right and text to the left. In SQLite each individual cell can contain different data types (unlike in other databases, where datatype is determined per entire column).
