### ISSUE TITLE
not open my database django project

### ISSUE THREAD

**Issue by avinash1041** [pawelsalawa/sqlitestudio#4137]
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment]
No details on the issue. If details are added, I'll reopen.
