### ISSUE TITLE
Error with SQL script (which succedded under CLI)

### ISSUE THREAD

**Issue by DavidKonicek** [pawelsalawa/sqlitestudio#4140]
### Details
SQL scripts, which can be run under SQLite CLI with no problems, fails under SQLite Studio.

### Steps to reproduce
(1) Download https://github.com/jpwhite3/northwind-SQLite3/blob/master/Northwind.Sqlite3.create.sql
(2) Run sqlite3.exe, create a fresh new database (open --new xxxx.sqlite), run this script (.read Northwind.Sqlite3.create.sql)  ... no problems
(3) Run SQLite Studio, create another (!!!) fresh new database (Database > Add database > Plus icon > enter some file name)
(4) Database > Connect to the database,  Shift+F10 > Execute SQL from file , run this script
(5)  .... execution errors (despite chosen encoding)

### Operating system
Win7 Proffessional EN

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
Attaching the file here, just in case it was modified under the link mentioned above.e
[Northwind.Sqlite3.create.sql.zip](https://github.com/pawelsalawa/sqlitestudio/files/6724238/Northwind.Sqlite3.create.sql.zip)

**Comment by DavidKonicek** [comment]
Thanks. I have another workaround, it's OK. But please note, CLI interface of SQLite doesn't need changes in the script and can work with the original made by Hoti (and linked the above).
