### ISSUE TITLE
[feature request] Store active database selection in Database widget when database disconnected.

### ISSUE THREAD

**Issue by Bogdan107** [pawelsalawa/sqlitestudio#4148]
SQLiteStuido 3.3.3

### Steps:
1) open two databases;
2) select table in any database;
3) press Disconnect button on toolbar;
4) Expected behaviour - save cursor in Databases widget to last viewed file;
5) Unexpected behaviour - Databases widget resets cursor from active/last opened database;

WARNING: SQLIteStudio **COMPLETELY** RESET CURSOR in Database widget aftre Disconnect command!

### What I want:
After calling Disconnect button, cursor in Databases widget **must** stay on the last opened database file (last opened - is that, which table/view/etc opened in right panel).
This behaviour allow to call Disconnect and Connect buttons without reselect needed database file in Databases widget.
Selecting _last opened_ database file in Database widget by moving mouse - is wasted time (#4146).

**Comment by Bogdan107** [comment]
At now, Disconnect and Connect toolbar buttons use cursor from "Databases" widget to know "current selected database".
May it use also a database from current tab, opened in right panel, if database cursor lost in Databases widget?

**Comment by pawelsalawa** [comment]
The databases list does not lose cursor. It's always there. I don't really think it's a good idea. It will confuse people.

**Comment by Bogdan107** [comment]
> The databases list does not lose cursor. It's always there. I don't really think it's a good idea. It will confuse people.

Open databse1. Then open database2. Open table1 from any database. Tab for table1 opens in right-panel.
While Tab activated - click Disconnect button on toolbar. Then cursor in Databases widget will be lost - no database1 neither database2 selected in Databases widget. Also, Connect button disabled.

Expected behaviour:
After clicking Disconnect button - cursor in Databases widget must stay in Databases widget on the database line, which was disconnected by clicking Disconnect button. And Connect button must be enabled for connecting last disconnected database.

**Comment by pawelsalawa** [comment]
I see. Okay.
