### ISSUE TITLE
Unclickable column NN : Hidden by the dropdown on its left

### ISSUE THREAD

**Issue by Raphael-MOUQUIN** [pawelsalawa/sqlitestudio#4150]
<img width="535" alt="scrshot_SQLiteStudio3 3 3_HIDDEN_COLUMN_NN" src="https://user-images.githubusercontent.com/86474028/124496902-5da9d980-ddba-11eb-9021-3befd6bd89da.PNG">

### Details
just clicked "New Database" then this "Edit table definition" window appeared but unable to click in the NN column due to the overlap of the dropdown on its left

### Steps to reproduce
Issue is always present  . 

### Operating system
Win7

### SQLiteStudio version
3.3.3

**Comment by Raphael-MOUQUIN** [comment]
Notice: System UI is set as follow:
**PPP custom 144dpi ppi, Font Segoe 9 pts**

<img width="294" alt="PPP custom 144dpi ppi, Font Segoe 9 pts" src="https://user-images.githubusercontent.com/86474028/124497592-59ca8700-ddbb-11eb-834c-3f86804ee31f.PNG">

**Comment by pawelsalawa** [comment]
I don't know what application you're showing, but it's not SQLiteStudio.

**Comment by Raphael-MOUQUIN** [comment]
Mr Salawa @pawelsalawa  , my apologizes , i'm sorry , i got confused , it's your twin-brother DB Browser for SQLite : 
<img width="320" alt="scrshot_DB Browser for SQLiteStudio-3 12 1_ABOUT_POPUP" src="https://user-images.githubusercontent.com/86474028/124625087-c9a14600-de7d-11eb-9c0e-217b199dacb8.PNG">
