### ISSUE TITLE
SqliteStudio v 3.3.3 not run under windows 7

### ISSUE THREAD

**Issue by versionzer0** [pawelsalawa/sqlitestudio#4152]
### Details
After Download SQliteStudio v3.3.3, and run it, Error message Show that:
This version of SQLiteStudio.exe is not compatible with the version of Windows you're running.
Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, 
and then contact the software publisher.
The sqlitestudiocli.exe, also same Error.

### Steps to reproduce
Download Latest SqliteStudio v 3.3.3 with:
SHA256: DA888B08B075C71999002B903757D7842746925D8092C00EFBD11FC594192494
check sha256
Run SqliteStudio.exe
.
I test this version on 2 separated PC with Windows 7 OS.
### Operating system
OS Name:                   Microsoft Windows 7 Enterprise
OS Version:                6.1.7601 Service Pack 1 Build 7601
32bit version
### SQLiteStudio version
SqliteStudio v3.3.3

**Comment by pawelsalawa** [comment]
Version 3.3.3 binaries are 64 bit. I'm working on making version 3.4.0 to be released with both 32 and 64 bit.

**Comment by pawelsalawa** [comment]
If I remember correctly, the last 32-bit version so far was 3.2.1

**Comment by pl77** [comment]
Also, Windows 7 is long since end of life, so please don't spend too much time on issues for it.
