### ISSUE TITLE
Drag&Drop a table broken (UI Bug)

### ISSUE THREAD

**Issue by TrashAccount3424** [pawelsalawa/sqlitestudio#4162]
### Details
Drag&Drop a table into the Query window remove the table from the Table-tree (needs a refresh to show it again)
This was not the case in previous versions of this tool.

### Steps to reproduce
-

### Operating system
Windows 10

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
Duplicate of #4098
