### ISSUE TITLE
Upgrade `SQLite3MultipleCiphers` dependency to newest version available prior to the release

### ISSUE THREAD

**Issue by m4heshd** [pawelsalawa/sqlitestudio#4171]
### Details
First of all, I'm really grateful that this project supports `SQLite3MultipleCiphers` which is rare to come.

I think this upgrade is necessary along with SQLite `v3.36.0` mostly because `SQLite3MultipleCiphers` been having issues with `WAL` journal mode (https://github.com/utelle/SQLite3MultipleCiphers/issues/39). It's been fixed and the journaling mechanism for `WAL` apparently have received a complete revamp which leaves users with corrupted databases or invalidated journal files when opened via `SQLiteStudio`. It also leaves all the journal files even on a successful disconnection without a `checkpoint` being performed.

Applications tend to use latest versions of dependencies and this is a lot of trouble to users who depend on `SQLiteStudio` to monitor and manage their DBs in development. I think this is what the author of #4108 trying to describe which I'm also experiencing right now. In my case `WAL`, is absolutely necessary to prevent unintended locking and possible corruption or data loss.

Currently only solution seems to be to enable `mc_legacy_wal` on the database which is not recommended.

### Steps to reproduce
1. Create an encrypted database with the latest version of `SQLite3MultipleCiphers`
2. Open with `SQLiteStudio` and do some changes to the database _(Add tables, data etc..)_
3. Disconnect the database and try to open with the latest version of `SQLite3MultipleCiphers`

It'll either say the database is corrupted or none of the changes you did through `SQLiteStudio` are reflected on the database. If you open it back up with `SQLiteStudio` you can actually see that none of those changes are there because they were all in the journal file which got invalidated.

**Comment by pawelsalawa** [comment]
At the moment all SQLite engines (vanilla SQLite3, MultipleCiphers and SQLCipher) got updated to the most recent 3.39.2, but I will keep this issue open until the last moment before release, so that if any further updates are released along the way, they get into the release of SQLiteStudio.

**Comment by pawelsalawa** [comment]
Updated to 3.39.4.
