### ISSUE TITLE
Cannot select columns to populate with data

### ISSUE THREAD

**Issue by DinoMah** [pawelsalawa/sqlitestudio#4177]
### Details
I was trying to populate a table but I cannot select the columns to populate because there are no columns to select.

### Steps to reproduce
Just try to populate a table and you cannot select columns to populate.

### Operating system
Ubuntu 20.04, also happens in Windows 10 21H1

### SQLiteStudio version
SQLiteStudio 3.3.3

**Comment by pawelsalawa** [comment]
Can you show the screenshot?

**Comment by DinoMah** [comment]
![image](https://user-images.githubusercontent.com/42949369/127751345-051d40f1-86b0-45ae-913c-7d0ba5475a87.png)

**Comment by pawelsalawa** [comment]
And how does the table look like? Can you share DDL?

**Comment by DinoMah** [comment]
![image](https://user-images.githubusercontent.com/42949369/127755156-6063c7a6-9d00-42f0-b0b7-d2e1748bb9e3.png)

**Comment by pawelsalawa** [comment]
This is quiet incredible. I cannot reproduce it. Is there a chance that you share the database file? (for example by zipping it and attaching here to the post? ...if you don't mind that anybody could download it). If not you could also send it over to support@sqlitestudio.pl.

**Comment by DinoMah** [comment]
[db.zip](https://github.com/pawelsalawa/sqlitestudio/files/6913577/db.zip)

**Comment by pawelsalawa** [comment]
I can reproduce it, thus I can fix it. Thank you. I will schedule fix for 3.4.0.

**Comment by pawelsalawa** [comment]
I think that the problem may be  when you have only 1 table in the database.

I found a temporary workaround - have another database with a table (or another table in the same database). When the populate dialog appears, choose different database/table and then choose again the Registro. Then column are shown properly.
