### ISSUE TITLE
Mouse click on field in table or query results browse immediately triggers and opens Edit dialogue rather than position editor cursor

### ISSUE THREAD

**Issue by audiomuze** [pawelsalawa/sqlitestudio#4191]
### Details
Mouse click on a field in a table or "query results" browse immediately triggers field edit for non-blob fields and opens the edit Edit dialogue if field type is blob.  A single click should serve only to position the editor cursor.  A double click should be required to enter edit mode..

### Steps to reproduce
Browse a table or run a query on a table and when viewing results left click mouse button on a "cell".  The Edit dialogue is immediately opened.

### Operating system
Linux

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
Doesn't seem to be happening for me, although I checked it on Windows. I don't have Linux workstation near by. Are you able to verify this on your side somewhere on Windows?

**Comment by audiomuze** [comment]
Will check, could also be KDE Plasma mouse behaviour, but don't think so because I've not seen it in any other app.  Will revert.

**Comment by audiomuze** [comment]
My bad.  It was a KDE Plasma setting that needed changing.
