### ISSUE TITLE
Предлагаю добавить галочку для включения/выключения Clear Type (смазанных шрифтов, сглаженных шрифтов)

### ISSUE THREAD

**Issue by SashaGaran** [pawelsalawa/sqlitestudio#4199]
Мне нравится Эта программа, но не нравятся в Ней смазанные шрифты. Предлагаю добавить в меню настройки шрифтов галочку включения выключения смазанных шрифтов.
Как Вам такая идея?

**Comment by pawelsalawa** [comment]
I don't know why you assume that everybody speaks Russian. I don't. Thanks to Google Translator:

> I like This program, but I don't like the blurry fonts in It. I suggest adding a checkbox to turn off blurry fonts in the font settings menu.
> How do you like this idea?

SQLiteStudio does not enable blurry fonts. Perhaps this is due to some high dpi scaling? I don't know.

**Comment by SashaGaran** [comment]
Привет, Pawelsalawa! 🖐
А, да. Действительно проблема в масштабировании DPI в настройках Windows.
Спасибо.

> DeepL Translate:
> 
> Hi Pawelsalawa! 🖐
> Ah, yes. Really the problem is the DPI scaling in the Windows settings.
> Thanks.
