### ISSUE TITLE
How to change text colour in editor?

### ISSUE THREAD

**Issue by audiomuze** [pawelsalawa/sqlitestudio#4201]
### Details
I changed themes from my old config carried over from previous versions of SQLiteStudio to the current release.  This caused the editor screen to enter  dark theme (which I prefer to the stark white background).  However, my inline  comments are now invisible if not selected.

![image](https://user-images.githubusercontent.com/6852511/131348196-45b31412-2188-41e9-8afa-fc50e988a586.png)

![image](https://user-images.githubusercontent.com/6852511/131348404-1fa1cd7c-d179-40b9-858f-dac2d6046932.png)

![image](https://user-images.githubusercontent.com/6852511/131348486-ef284547-8c61-471d-a0c1-163120791c4c.png)

How can I alter the colour attributes of comments without having to discard all my code snippets embedded in
~/.config/SalSoft/SQLiteStudio/settings3?

### Steps to reproduce
Changed theme.

### Operating system
Arch Linux, KDE Plasma
### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
Color customization is on list of tasks for 3.4.0. Until then I'm not sure what you can do...
Have you tried restarting the app - are the colors still this way?

**Comment by audiomuze** [comment]
> Have you tried restarting the app - are the colors still this way?

Yip, it retains the color scheme.  I'll have to copy and save each of the windows to a Sublime window then delete ~/.config/SalSoft/SQLiteStudio/settings3 and create new windows.  Editor window management is SQLiteStudio's achilles heel, it'd be really useful to be able to check-in code for subsequent access and reuse rather than relying on an ever increasing number of editor windows - I'll raise a feature request.

**Comment by pawelsalawa** [comment]
You mean something like this? #4065
