### ISSUE TITLE
"Generate query from selected cells" generate wrong SQL from HEX (BLOB)

### ISSUE THREAD

**Issue by OrihuelaConde** [pawelsalawa/sqlitestudio#4216]
### Details
The tool "Generate query from selected cells" with a column of type blob (hex - GUID) the SQL generated is wrong.

### Steps to reproduce
Select any cell of a table that has an hex value (like blob) and then use the tool "Generate query from selected cells".

![image](https://user-images.githubusercontent.com/12591371/133719067-e2f45850-f1f5-4fe9-8e2d-b2d382f4a45d.png)

### Operating system
Windows 10 Pro 21H1

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
Fixed together with #4306
