### ISSUE TITLE
using column and table name starting with $ character

### ISSUE THREAD

**Issue by mohrlex83** [pawelsalawa/sqlitestudio#4239]
### Details
When you open a table to see the data, if the table name starts with $ it gives an error.

The SQL correct form is put table names and field name between [ ]:
Example
SELECT [columname] FROM [tablename]
INSERT INTO [tablename] ([columname]) VALUES (value)
UPDATE [tablename] SET [columname]=value

**Comment by pawelsalawa** [comment]
Fixed togheter with #4362
