### ISSUE TITLE
Some generated QM files are not loaded

### ISSUE THREAD

**Issue by yfdyh000** [pawelsalawa/sqlitestudio#4263]
### Details
I noticed that some generated translations are not loaded from the software. I didn't see the reason from the code.
Known, including MultiEditorImage_zh_CN.qm and SqlFormatterSimple_zh_CN.qm files.

### Steps to reproduce
Opening like the SqlFormatterSimple_zh_CN.ts file, use lrelease to qm, copy it to SQLiteStudio\msg or translations folder.
Open the software, switch the language to Simplified Chinese and restart it.
Check the options interface for the SQL Simple plugin in the Configuration dialog. It is kept in English.

### Operating system
Win10

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
In 3.3.x branch translation files had to be managed manually, so that could cause the problem. In master branch (for 3.4.0) this is all handled automatically, so such problems should not happen anymore.
