### ISSUE TITLE
Request: Include sqlitestudio.svg in the Portable distribution

### ISSUE THREAD

**Issue by sgornick** [pawelsalawa/sqlitestudio#4264]
After installing SQLiteStudio using the portable version (which is the only version type, until the installer returns, in v3.4.x, per a comment seen in Issue #4087), an Ubuntu user then needs to create a .desktop launcher / icon / shortcut.  Useful (but not required) for that is the [sqlitestudio.svg](https://raw.githubusercontent.com/pawelsalawa/sqlitestudio/master/SQLiteStudio3/guiSQLiteStudio/img/sqlitestudio.svg) file.

But the Portable version does not include that file.  Prior releases used to find that file in the app_icon directory, but according to comment under Issue #3265, this occurs thanks to the installer, which the latest release, (v3.3.x at the time of this writing) does not have.  And I am unsure if that is for Windows only anyway?

So my request is to have this file included, somewhere, in the Portable release.  Even if the installer returns in v3.4.x, I think the .svg image would be useful in the Portable version even.

**Comment by pawelsalawa** [comment]
Why not just `wget https://raw.githubusercontent.com/pawelsalawa/sqlitestudio/master/SQLiteStudio3/guiSQLiteStudio/img/sqlitestudio.svg`?

**Comment by sgornick** [comment]
Getting that manually is one additional manual step that a user would need to perform to simply get a launcher to appear properly and work properly.

Compressed that image adds just 100K to the size of the portable release.   With that image file included in the portable release, a person can simply unzip the portable release from the SQLiteStudio website, then download the corresponding .desktop file from wherever, or copy and paste from a StackExchange post, for example, and boom -- they are in business.

**Comment by bobOnGitHub** [comment]
Haven't used SqliteStudio in a while.

Just putting finishing touches to move to linux with some system config scripts/automation and I've been looking all morning for this icon.

When you launch the app in KDE (5.18 / I forget how I did that originally) you can then pin it to the taskbar and you get an icon but there is no icon file anywhere to use in a .desktop file - KDE automagically grabs the icon data from the app and adds it to a  config file (base64?)... anyway, finding the image is the problem. So cheers @sgornick for linking it here :+1:

Being able to script an install is important as eventually you may have to upgrade / reproduce your pc and having to manually do that is never pleasant. You need the svg for this so making it easily findable would be a good thing.

Excellent project / application though - very much in the same vein as Sqlite itself : simple to use, straightforward, no nonsense , does-what-it-says-on-the-tin. Very refreshing in today's world so @pawelsalawa, I'd just like to add a big thankyou  :+1: for all your efforts ! (I know.... cash'd be better  :disappointed: )

**Comment by TomasAsadauskas** [comment]
We need that icon and *.desktop file for Linux integration.
