### ISSUE TITLE
"Disconnect from the database" should be available when database has been opened

### ISSUE THREAD

**Issue by yfdyh000** [pawelsalawa/sqlitestudio#4273]
### Steps to reproduce
1. Start program and open a database through like "Open with...".
2. The database is expanded and operable, it is temporarily added to the list. Try to disconnect the connection, but the toolbar button and menu are unavailable (disabled), until you once manually selected the database from the list,

### Operating system
Win10

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
This is somewhat discussable. What if you already had other (permanent) databases added? If you need to explicitly select database to disconnect, you won't disconnect from the one you did not expect.

**Comment by yfdyh000** [comment]
Automatically select the currently open database in the list is correct, since it is the current working database.

**Comment by pawelsalawa** [comment]
Right.
