### ISSUE TITLE
What is the Latest Version of SQLiteStudio that Can Run on Windows XP SP3?

### ISSUE THREAD

**Issue by spaceman5** [pawelsalawa/sqlitestudio#4303]
Hi

I am using Windows XP SP3, and downloaded sqlitestudio-3.3.3.zip.

It does not run on XP SP3, so I will download an older version..
Can you please tell me what is the latest version that will run on XP SP3?

Thank you very much

**Comment by pawelsalawa** [comment]
Version 3.2.1 (https://github.com/pawelsalawa/sqlitestudio/releases/tag/3.2.1) should work on XP.
