### ISSUE TITLE
Incorrect format of BLOB literals during export of table data

### ISSUE THREAD

**Issue by electroparusnik** [pawelsalawa/sqlitestudio#4306]
### Details
During export of table data blob literals are enclosed with extra quotes. 
This happens when option 'Use SQL formatter to format exported SQL statements' is checked.
Example:
`INSERT INTO Encryption (
                           Salt
                       )
                       VALUES (
                           'X'120F7741B59F60767418ACBAFD5EE0E31BCA4D91104B46B2095B89F0A60B3B53''
                       );
`
### Steps to reproduce
1. In context menu of table choose 'Export the table'
2. In export dilaog check 'Export table data', select export format 'SQL', check 'Use SQL formatter to format exported SQL statements'

### Operating system
Windows 10

### SQLiteStudio version
3.3.3

**Comment by tuffnatty** [comment]
Also happens with Generate query.
