### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by yangfl** [pawelsalawa/sqlitestudio#4314]
This software is linked against OpenSSL, which is (in)famous for its excemption requirement of GPLv3 license. The main part of sqlitestudio is licensed under GPL-3 with OpenSSL exception, however some files are left over, for example https://github.com/pawelsalawa/sqlitestudio/blob/master/SQLiteStudio3/coreSQLiteStudio/rsa/BigInt.cpp

Another issue is readline, which is GPL-3 only without OpenSSL exception, makes it unsuitable to use along with OpenSSL.

**Comment by pawelsalawa** [comment]
I will probably just remove GPL license contents from individual files, since there is a "main" license in root directory, which is also displayed in the runtime in About/License dialog.
