### ISSUE TITLE
App doesn't accept windows functions

### ISSUE THREAD

**Issue by jimwhurr** [pawelsalawa/sqlitestudio#4318]
### Details

Studio does not recognise the syntax of window-functions.
Studio will not connect to a database that includes a view using window functions

### Steps to reproduce

1. Create a DB with a Transactions table that has at least date (TEXT), account (INT) and amount (DECIMAL) rows, populate with some data 

2. Enter a query with something like:

SELECT date, amount, sum(amount) OVER (
  ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative
FROM Transactions WHERE account=1 ORDER BY date;
 
Studio will not recognise the syntax and refuse to run the query
[13:59:15] Error while executing SQL query on database 'test': near "(": syntax error

(Running the same query in sqlite3 will work)

sqlite> SELECT date, amount, sum(amount) OVER (
   ...>   ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative
   ...> FROM Transactions WHERE account=1 ORDER BY date;
2021-03-31|20830.39|20830.39
2021-04-01|-145|20685.39
2021-04-01|-42.47|20642.92
2021-04-01|-13.37|20629.55
2021-04-01|-26.02|20603.53
2021-04-06|-14.24|20589.29
2021-04-06|-2716.98|17872.31
2021-04-06|-50|17822.31
2021-04-06|-16.87|17805.44
2021-04-06|-1000|16805.44
...

3. Then  create a new view in sqlite3 based on the query above, e.g.

CREATE VIEW [Statement] AS
      SELECT date, amount, sum(amount) OVER (
            ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
      ) AS cumulative
      FROM Transactions WHERE account=1 ORDER BY date;

You will now find that sqlitestudio will not properly load the DB.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

Wnindow 10

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

SQLiteStudio: 3.2.1
SQLite3: 3.24.0

**Comment by pawelsalawa** [comment]
Window functions are supported with SQLiteStudio 3.3.x.
Update the application.

**Comment by jimwhurr** [comment]
> Window functions are supported with SQLiteStudio 3.3.x. Update the application.

Thanks :)

PS
I had clicked the update button on the help menu before I submitted and it said I had the latest
