### ISSUE TITLE
Unable Windows Font EUDC.TTE

### ISSUE THREAD

**Issue by YannDX** [pawelsalawa/sqlitestudio#4323]
### Details
After intalling new version 3.12.2-x64 (onto my working version 3.11.2 just at the time),
I've got a warning window :+1: 

> Unable to open "C:\\Windows\\FONTS\\EUDC.TTE"
> QPaintDevice:Cannot destroy painte device that is being painted    (3lines)

according to https://bugreports.qt.io/browse/PYSIDE-1620  and https://docs.microsoft.com/de-de/windows/win32/intl/eudc
 I corrected the registry by deleting all 'SystemDefaultEUDCFont' keys in HKCU\EUDC\codes\

Still the 3 lines, but working (so fast,thanks for the tool)  

### Operating system
Windows 7 SP1 x64 

### SQLiteStudio version
3.12.2-x64

**Comment by pawelsalawa** [comment]
You are reporting issue to the SQLiteStudio. Are you sure that you're using SQLiteStudio?

SQLiteStudio currently is in version 3.3.3.

**Comment by SidShakal** [comment]
@pawelsalawa I think you're right. I just found this bug report while looking for info on the same error I just got in [DB Browser for SQLite](https://github.com/sqlitebrowser/sqlitebrowser) version 3.12.2, which was released back in May 2021. That's probably the project this report was meant for. :)
