### ISSUE TITLE
Can not view data if table containing special characters and no spaces.

### ISSUE THREAD

**Issue by mvbentes** [pawelsalawa/sqlitestudio#4331]
### Details
You can not show data for a table whose name contains special characters, such as `TEST#TABLE`. You also can not run any GUI operation that generates sql code, such as rename the table. Queries run fine when it is wrapped, but the GUI does not wrap it.
Also, the SQL Formater (CTRL + T) will remove wrapping brackets when they exist around such table in the editor.

### Steps to reproduce

1. Create a table named `TEST#TABLE`. 
2. Try to switch to Data tab.
3. Get error `Could not load data for table TEST#TABLE. Error details: Error while executing SQL query on database 'MYDATABASE': near "#TABLE": syntax error`

### Operating system
Windows 10

### SQLiteStudio version
3.4 - I just checked the code and the problem seems to be in following function:

		bool doesObjectNeedWrapping(const QString& str)
		{
			if (str.isEmpty())
				return true;

			if (isObjWrapped(str))
				return false;

			if (isKeyword(str))
				return true;

			for (int i = 0; i < str.size(); i++)
				if (doesObjectNeedWrapping(str[i]))
					return true;

			if (str[0].isDigit())
				return true;

			return false;
		}

**Comment by pawelsalawa** [comment]
There was similar bug regarding `$` character. It's easy to fix and I will fix it in 3.4.0.

**Comment by mvbentes** [comment]
Thank you for the reply and for the great work on this software!
