### ISSUE TITLE
Crashing when filling table with data

### ISSUE THREAD

**Issue by monkeyfuckeddog** [pawelsalawa/sqlitestudio#4340]
My table define is here:
test(id,name,name2)

Then I fill table with random text for name, name2 field, it crashed.

both name and name2 fill settings is:
Minimum length:4
Maximum length:4
Alpha and Numeric checked。

**Comment by pawelsalawa** [comment]
Which SQLiteStudio version are you using?

**Comment by monkeyfuckeddog** [comment]
Got it！

**Comment by monkeyfuckeddog** [comment]
Win10
SqliteStudio:3.3.3 便携版

**Comment by lanmanck** [comment]
丢人，真丢人

**Comment by monkeyfuckeddog** [comment]
Got it！

**Comment by pawelsalawa** [comment]
While it's reproducible in 3.3.3, it looks to be already fixed in upcoming 3.4.0
