### ISSUE TITLE
Paste Null values directly

### ISSUE THREAD

**Issue by leyan** [pawelsalawa/sqlitestudio#4357]
When pasting values inside the grid view, I would like to be able to automatically paste NULL values. Currently, I have to paste the values into new rows and then press Backspace on all the cells where I want to see NULL values, as opposed to an empty string.

Is there a way to do it today? A setting I did not see? Otherwise, I would be willing to contribute it. In that case what would be the recommended approach? Do we need a setting to control which value is converted to NULL when pasting data?

**Comment by pawelsalawa** [comment]
![Recording 2022-01-03 at 23 02 58](https://user-images.githubusercontent.com/481846/147985321-1d30a500-b1a7-4c26-82c4-29fe821bb7d3.gif)

**Comment by leyan** [comment]
Sorry if I was not clear, I meant pasting from an external source, for example from a spreadsheet like LibreOffice Calc or Excel.

**Comment by pawelsalawa** [comment]
How would SQLiteStudio know that you're pasting NULL and not empty string? What if someone else wants to paste empty string?

**Comment by leyan** [comment]
That's why I was wondering about a configurable setting. A user could configure a special string, like "NULL" for example, to represent null values coming from an external source, without impacting other users.

Or in a first step, maybe only make it work for other data types where SQLiteStudio could guess that an empty string is not what the user wanted?

**Comment by pawelsalawa** [comment]
Okay. Let's keep it as feature request.

**Comment by JrgMyr** [comment]
The CSV import function has a field to tell what NULL values should look like.
You could possibly import your data from a CSV format instead of a spreadsheet.
Depending where the data originates that might be the same number of manual steps.
