### ISSUE TITLE
Dark theme does not work

### ISSUE THREAD

**Issue by Mohsyn** [pawelsalawa/sqlitestudio#4360]
### Details
Setting Fusion Dark theme results in following error message
[xx:xx:xx] Could not set style: Fusion Dark

### Steps to reproduce
Tools > Open configuration Dialog > Look and Feel > Style > Current Style > Change to Fusion Dark > Apply

### Operating system
Windows 10

### SQLiteStudio version
3.3.3 portable

**Comment by pawelsalawa** [comment]
Have you perhaps upgrade SQLiteStudio onto the existing, older version?
It may be that you have some conflicting versions of some files.

**Comment by Mohsyn** [comment]
> Have you perhaps upgrade SQLiteStudio onto the existing, older version? It may be that you have some conflicting versions of some files.

No. It is a fresh install.

**Comment by pawelsalawa** [comment]
Do you have another Qt installation on your Path in Windows?

**Comment by Mohsyn** [comment]
I had "010 Text Editor" on path which is a qt app
removed from path and bingo the dark theme works now.
pretty strange though.

**Comment by pawelsalawa** [comment]
Theoretically Windows should prioritize Qt from local directory over the other one, but when it comes to some transient dependencies, I imagine it can be not as straight forward.
