### ISSUE TITLE
Many warning and error with VS2017+Qt5.14.1

### ISSUE THREAD

**Issue by lanmanck** [pawelsalawa/sqlitestudio#4361]
### Error and warning
see pictures
![微信截图_20220106133905](https://user-images.githubusercontent.com/3500166/148334441-87dfd187-ab0e-4d6e-8475-a8f3d1b69dd9.png)

![微信截图_20220106133925](https://user-images.githubusercontent.com/3500166/148334447-c20d0a3e-14b0-4eb2-8793-73a1c6581a22.png)

### QtCreator 4.11.1 X64
Open pro and build

**Comment by pawelsalawa** [comment]
That's the reason I use Mingw64 to compile. I had an attempt to compile SQLiteStudio with VC++ couple of years back and I abandoned it after 2 days of fight.

I have never used VC compiler before, thus I may not be aware of some standards that I'm breaking there, when coding with Mingw.

Anyway, I won't be able to help with this.

**Comment by lanmanck** [comment]
got it,thanks
