### ISSUE TITLE
WAL mode not handled correctly

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#4369]
As discussed in #4368, the `pragma journal_mode = wal` should work in a way that it creates wal files upon changes in database, but deletes them (after committing into the main db file) when closing last connection. That's how sqlite3.exe works, but for some reason SQLiteStudio fails to do it - the wal file remains.

**Comment by gavinmcniff** [comment]
As of V3.4.4 the .wal and .shm files seem to remain in place after closing SQLite Studio. Disconnecting in SQLite Studio works fine, just when closing the program directly. Maybe disconnect skipped somehow. Didn't happen in V2.

**Comment by gavinmcniff** [comment]
Update. Seemed to work correctly in V3.1.1

**Comment by pawelsalawa** [comment]
Is your database file placed on a network shared drive? Or any other drive that is not a simple partition on your disk?

**Comment by gavinmcniff** [comment]
The file is in a folder on a local drive but the folder is assigned a drive letter (X:) using subst command. SQLite Studio is connected to the file using the drive letter X: System is Windows 10 Pro with all updates etc.

**Comment by pawelsalawa** [comment]
Can you try with a regular drive? I'd like to eliminate this potential cause (I'm not sure how SQLite itself handles such drives).

**Comment by pawelsalawa** [comment]
I've created #4949 to fix it in recent version.

**Comment by gavinmcniff** [comment]
Thanks for your efforts in creating and maintaining SQLite Studio. Looking at #4949, I can add that that it's enough to attach to the database file and then close SQLite Studio. No I/O is required.
