### ISSUE TITLE
Website HTTPS bad certificate

### ISSUE THREAD

**Issue by tenbob** [pawelsalawa/sqlitestudio#4390]
Hi. I just wanted to report a small problem with the website certificate.

Steps to reproduce.

1. Search Google for SQLiteStudio
2. The first hit tells you to go to `https://www.sqlitestudio.pl/`
3. Follow the link.
4. Browser displays "Warning: Potential Security Risk Ahead" and blocks the site.

I think the problem is that your LetsEncrypt certificate includes this domain.
`https://sqlitestudio.pl/`

but not this domain
`https://www.sqlitestudio.pl/`

That is, it is missing the `www` subdomain. HTH.

**Comment by pawelsalawa** [comment]
The `www.sqlitestudio.pl` immediately redirects to `sqlitestudio.pl` (using HTTP code 302), because there is nothing at `www.`. The page is under `sqlitestudio.pl`. I simply never cared about certificate at `www.`, because it automatically redirects to the page without `www.`.

**Comment by tenbob** [comment]
Hi Pawel. Thanks for your quick reply. 

In the OP I made a mistake. The error occurs when you search with DuckDuckGo (not Google). For some reason it sends you to a www link instead of the correct URL of sqlitestudio.pl. Maybe the www URL did exist in the past. 

I only mentioned it because people may be frightened by the browser warning and not trust the software.

I think it's easy to fix this in cPanel. Just add the www domain to the certificate along with the other URLs.

**Comment by pawelsalawa** [comment]
I see. Thanks for letting me know. I've expanded the certificate to address this.

**Comment by tenbob** [comment]
Hi Pawel. I tested it and it's working OK now. Thanks, Bob
