### ISSUE TITLE
Support for Strict Tables

### ISSUE THREAD

**Issue by GarageLube** [pawelsalawa/sqlitestudio#4415]
### Details
The latest version of SQLite has support for STRICT tables. Please can you upgrade SQLiteStudio to the latest version i.e. 3.38.0? Replacing sqlite3.dll with the latest dll has allowed me to use the STRICT feature when creating tables, however SQLiteStudio cannot understand strict tables once they have been created.
By the way, I really enjoy using your software.
Thanks very much
Jeff

**Comment by pawelsalawa** [comment]
Duplicates #4214
