### ISSUE TITLE
Concated columns show wrong values, after another column is sorted

### ISSUE THREAD

**Issue by JP95Git** [pawelsalawa/sqlitestudio#4416]
### Details

Concated columns show wrong values, after another column is sorted.

### Steps to reproduce

Create a sample table with these data:
```
--
-- File generated with SQLiteStudio v3.3.3 on Sa Mrz 12 10:39:21 2022
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: test
DROP TABLE IF EXISTS test;

CREATE TABLE test (
    id     INTEGER PRIMARY KEY AUTOINCREMENT,
    name1  VARCHAR,
    name2  VARCHAR,
    number INTEGER
);

INSERT INTO test (id, name1, name2, number) VALUES (1, 'namenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamename31', 'name32', 3);
INSERT INTO test (id, name1, name2, number) VALUES (2, 'namenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamename21', 'name22', 2);
INSERT INTO test (id, name1, name2, number) VALUES (3, 'namenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamename11', 'name12', 1);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
```

Then run this query:
`select ID, name1 || name2 as names, name2, number from test`

Click on the arrows "Load remaining part of the value". Everything looks fine.

Sort for column name2.

Click on the arrows "Load remaining part of the value". The column names now shows the wrong values.

### Operating system
Windows 10

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
This is no longer relevant for 3.4.0, as it has the "blue arrows" for loading remaining data removed. Now whole data is loaded at once and I have just verified your example that it works correctly in 3.4.0.
