### ISSUE TITLE
SQL Editor window gets into background when submitting 'drop view'

### ISSUE THREAD

**Issue by droth4711** [pawelsalawa/sqlitestudio#4418]
### Details
While working in a SQL Editor window and submitting a 'drop view ...' statement, the top window switches to another tool window, if there was a window open for the dropped view. This is very irritating, because one is working in a SQL Editor and suddenly by dropping a view another window is in your focus.

### Steps to reproduce
a) Double click a view to open a window for the view. 
b) Open another view or table to have a second window.
b) Open a SQL Editor window as a third window and write 'drop view ' for the view opened in step a).

### Operating system
MS Windows 10 20H2

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
Can you record this behavior and post it here? You can do it easily with for example https://gifcap.dev/

**Comment by droth4711** [comment]
![Recording 2022-03-15 at 15 02 36](https://user-images.githubusercontent.com/74593471/158394993-36b38bf1-7920-4e5c-8c33-84f4e5bc60ec.gif)

**Comment by pawelsalawa** [comment]
Ohh, I see. Okay. Thank for the recording, it makes the reproduction much easier.

**Comment by droth4711** [comment]
Thank you for considering this! And a great thank you for this awesome tool!
