### ISSUE TITLE
Full values cannot be loaded when select accesses table from another database

### ISSUE THREAD

**Issue by droth4711** [pawelsalawa/sqlitestudio#4419]
### Details
In 'Grid view' the context menu 'Load full values' from the column header doesn't work, when the select includes access to another database.

### Steps to reproduce
Create a select statement e.g. by unioning two results from different databases. Then, 'Load full values' has no effect. Please note that the captured procedure in the GIF doesn't include the context menu popping up (for whatever reason).

### Operating system
MS Windows 10 2H1

### SQLiteStudio version
3.3.3

**Comment by droth4711** [comment]
[]
![Recording 2022-03-17 at 09 14 35](https://user-images.githubusercontent.com/74593471/158766970-eb538865-ed4a-42aa-869b-ee62a4fcc375.gif)
(url)

**Comment by pawelsalawa** [comment]
Closely related to #4240
