### ISSUE TITLE
Portable Configurations for Windows

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#4422]
Even if there is `sqlitestudio-cfg` folder, the application creates system-wide entries to keep track of "single application instance". Under windows this is done with Registry, on Unixes it is probably a config directory in user's folder.

### Discussed in https://github.com/pawelsalawa/sqlitestudio/discussions/4421

<div type='discussions-op-text'>

<sup>Originally posted by **Stephen-Leibowitz** March 22, 2022</sup>
There are instructions for a [Portable Configuration](https://github.com/pawelsalawa/sqlitestudio/wiki/Configuration_directory_location#portable-configuration).

But the program still creates and writes to a registry key:
HKEY_CURRENT_USER\Software\SalSoft

Is there a way for it to write to the application folder instead?
</div>

**Comment by Stephen-Leibowitz** [comment]
SQLiteStudio is now listed in the Portable Freeware Collection. It had been [originally submitted in 2014](https://www.portablefreeware.com/forums/viewtopic.php?t=21842), but was not considered portable in Windows by the standards of TPFC. With this registry fix (#4422) a part of 3.4.2, I was able to write [the entry](https://www.portablefreeware.com/index.php?id=3087) and get it approved.
