### ISSUE TITLE
[Enhancement] Option to switch between Sort or Select on Header click 

### ISSUE THREAD

**Issue by Mohsyn** [pawelsalawa/sqlitestudio#4435]
### Details

More often than not I intuitively try to select columns by clicking on headers to copy and end up sorting it instead.
I am sure this is the case with most people who are used to click on headers to select rows/columns at one go.
If there is an option to switch between sorting and selecting, it would be a real help.

**Comment by pawelsalawa** [comment]
Perhaps double-click for sorting would be more expected, I agree.

**Comment by Mohsyn** [comment]
is this incorporated in 3.4.0 nightly ?

**Comment by pawelsalawa** [comment]
Yes, it's in code base for 3.4.0.
There is no "nightly" anymore, but rather "weekly", being build at Sunday-Monday night.
