### ISSUE TITLE
Tried to commit a cell which is not editable (yet modified and waiting for commit)!

### ISSUE THREAD

**Issue by mostafa901** [pawelsalawa/sqlitestudio#4438]
### Details

1. Run a query script
2. Click on a column header to sort
3. Copy a value from any cell
4. Past it in some selected cells from the sorted column
5. Error is born

see the attached video for a quicker illustration
https://user-images.githubusercontent.com/12208720/166623651-6b54d483-eb2a-43e3-b671-41dd6e879bed.mp4

### Operating system
https://user-images.githubusercontent.com/12208720/166623651-6b54d483-eb2a-43e3-b671-41dd6e879bed.mp4

Windows 11

### SQLiteStudio version
V 3.2.1

**Comment by pawelsalawa** [comment]
This was fixed in #3537
Please use more recent version.
