### ISSUE TITLE
Populate table does not show any column

### ISSUE THREAD

**Issue by fernandoribeira** [pawelsalawa/sqlitestudio#4444]
### Details
Failed to use "Populate table" feature

### Steps to reproduce
I downloaded the program, unzipped it, run it, created a new database, a new table with the command below:

CREATE TABLE contacts (
	contact_id INTEGER PRIMARY KEY,
	first_name TEXT NOT NULL,
	last_name TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
	phone TEXT NOT NULL UNIQUE
)

The table and fields were created successfully.

I right-clicked on the table name and selected "Populate table".

The "Populate table" screen is displayed, the fields "Database", "Table", "Number of rows..." appear, however, just below, the "Columns" area appears with a red exclamation mark and no column appears for be selected.

Leaving the mouse on the question mark informs you that no column has been selected.

### Operating system
Windows 10

### SQLiteStudio version
Version 3.3.
![Error](https://user-images.githubusercontent.com/24855807/168125319-9e381cfb-4b03-4a0d-b23f-ba101c680f95.PNG)
3

**Comment by pawelsalawa** [comment]
It was fixed in #4177.
You can download nightly build of 3.4.0 https://github.com/pawelsalawa/sqlitestudio/actions
