### ISSUE TITLE
3.3.3 the version is set to Chinese, and some places do not display Chinese or English status

### ISSUE THREAD

**Issue by qq1242592914** [pawelsalawa/sqlitestudio#4455]
3.3.3 the version is set to Chinese, and some places do not display Chinese or English status

**Comment by pawelsalawa** [comment]
I think version 3.3.3 wasn't 100% translated.

**Comment by Out-Of-Rain** [comment]
Yes, it's a bit terrible.

**Comment by pawelsalawa** [comment]
Translation for 3.4.0 is much better (100% or almost 100%), so this is no longer relevant for upcoming 3.4.0.
