### ISSUE TITLE
Preview tables in graphic mode connected with others along primary keys and foreign keys and data types

### ISSUE THREAD

**Issue by rabihf** [pawelsalawa/sqlitestudio#4459]
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment]
Duplicate of #2865
