### ISSUE TITLE
Can't save changes to a rc4 encrypted database

### ISSUE THREAD

**Issue by kingstien** [pawelsalawa/sqlitestudio#4468]
### Details
Can't save changes to a rc4 encrypted database.

### Steps to reproduce
1.Create a db use System.Data.SQLite.dll v1.0.102.0
2.Use ChangePassword Method set a password
3.Use SqliteStudio open it and create a table and commit
4.Reboot SqliteStudio 

### Operating system
Window 10

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
Which database driver/plugin are you using in SQLiteStudio to open the database?

**Comment by kingstien** [comment]
> Which database driver/plugin are you using in SQLiteStudio to open the database?

I used the wxSQLite driver and i found after SQLiteStudio cllosed the shm and wal file still exists.when is use my application open the db and close normaly the shm and wal files gone and the changes applied.

**Comment by pawelsalawa** [comment]
It seems like the transaction was not committed. did you successfully commit changes?

**Comment by kingstien** [comment]
> It seems like the transaction was not committed. did you successfully commit changes?

yes.the logs shows it successed.

**Comment by pawelsalawa** [comment]
What logs?

**Comment by kingstien** [comment]
> What logs?

the Status panel on the bottom of the gui

**Comment by pawelsalawa** [comment]
I see.
Frankly speaking I have no idea why it doesn't merge the WAL file. It should happen upon closing the database, which should happen when you close SQLiteStudio.

How about you disconnect from the database explicitly by clicking "disconnect" before closing SQLiteStudio?

**Comment by kingstien** [comment]
> I see. Frankly speaking I have no idea why it doesn't merge the WAL file. It should happen upon closing the database, which should happen when you close SQLiteStudio.
> 
> How about you disconnect from the database explicitly by clicking "disconnect" before closing SQLiteStudio?

Has no effect.

**Comment by pawelsalawa** [comment]
Is the database file stored on some kind of network drive? A natwork shared folder, or something?

**Comment by kingstien** [comment]
The file is stored on the local hard drive.In the root of E drive.

**Comment by pawelsalawa** [comment]
How about if you - just for a test - create a new database from SQLiteStudio, using same plugin (wxSQLite), create there a table, put a row or two, commit and restart SQLiteStudio. Does it also fail the same way?

If yes, can you try to test the same but with default plugin (SQLite3, not wxSQLite)?

**Comment by kingstien** [comment]
I created new databases with SQLite3 and wxSQLite(encrypted(inclued rc4) or not).They all work fine and i found that there's no shm and wal file created.
When i do nothing changed to my db file then close SQLiteStudio, The shm and wal file will disapper,When i do something then close SQLiteStudio,The shm and wal file stay.
My db file is created by DataGrip and set password with my code.

**Comment by pawelsalawa** [comment]
Is your database accessed by another application at the moment when you close SQLiteStudio? Maybe there are some file locks preventing the WAL file to be merged (written) to the main db file?

**Comment by kingstien** [comment]
there's no other applicatons accessing it.

**Comment by pawelsalawa** [comment]
I'm running out of ideas...

Let's try from another side. Why do you use WAL ([write-ahead log](https://www.sqlite.org/wal.html)) mode? Do you actually need it? Why not to switch the database to the default mode (the Rollback Journal), which doesn't need these extra files?

**Comment by kingstien** [comment]
I did not use WAL mode.Use SQLiteStudio open the databse then the wal generated.

**Comment by pawelsalawa** [comment]
The mode is set on the database file, so if you create the database elsewhere, that other application could have set this mode. Then SQLiteStudio would continue to use it when opening such database file - unless you switch it back to the default explicitly.

**Comment by kingstien** [comment]
The WAL mode is not neessary.I don't known why DataGrip use WAL mode to create the database.It seems i need to recreate a database use SQLiteStudio.

**Comment by TrashAccount3424** [comment]
> The WAL mode is not neessary.I don't known why DataGrip use WAL mode to create the database.It seems i need to recreate a database use SQLiteStudio.

It uses WAL because its faster
Anyway you can run `PRAGMA journal_mode = ....` to change it
See https://www.sqlite.org/pragma.html#pragma_journal_mode

**Comment by kingstien** [comment]
> > The WAL mode is not neessary.I don't known why DataGrip use WAL mode to create the database.It seems i need to recreate a database use SQLiteStudio.
> 
> It uses WAL because its faster Anyway you can run `PRAGMA journal_mode = ....` to change it See https://www.sqlite.org/pragma.html#pragma_journal_mode

Thanks
