### ISSUE TITLE
Zoom in and out

### ISSUE THREAD

**Issue by Poseidon-Killer** [pawelsalawa/sqlitestudio#4491]
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by Poseidon-Killer** [comment]
Zoom in from a text window in the SQL editor

**Comment by pawelsalawa** [comment]
This no longer seems relevant, as it is possible (for some time already) to scale SQL Editor fonts dynamically with `Ctrl`+`MouseWheel`.
