### ISSUE TITLE
feature request: "duplicate selected cells only", "duplicate row"  keyboard shortcut

### ISSUE THREAD

**Issue by dbojan** [pawelsalawa/sqlitestudio#4499]
### Details
if you have to add multiple rows, where part of the rows are the same, it could be useful to copy row from above.
this currently can be done by inserting new row, then copying the row above, without unique row

### Steps to reproduce
-insert a row. fill it by typing values
-insert another row
-select part of the row above without unique column.
-paste in the new row
-fill in the rest of the cells as required

improvement
-insert a row. fill it by typing values
-use a key shortcut: "duplicate selected cells only", which would duplicate them to next row
-or "duplicate row" which would duplicate whole row, without primary key/unique fields
-fill in the rest of the cells as required
-if required, there could be configuration to skip duplicating primary key/unique fields, when using "duplicate row"

ctrl+ins could be used for "duplicate selected cells only"
and 
ctrl+shift+ins could be used for "duplicate row"

**Comment by pawelsalawa** [comment]
I've removed it from the milestone after further analysis. It's a bit confusing and would be use by a very narrow set of users. The same can be achieved the way you already described (inserting rows and copying whatever you need).

**Comment by pawelsalawa** [comment]
Too many options/features is also not good, as it makes the interface less readable. Given that this result is easily achievable with inserting & copy-paste, I'm against adding a dedicated feature. Sorry.
