### ISSUE TITLE
sqlite studio produces incorrect result 

### ISSUE THREAD

**Issue by Pacode74** [pawelsalawa/sqlitestudio#4513]
### Details
I am new to SQLite Studio but when I use PRECEDING in code it gives wrong results in SQLite Studio but when I reproduce the same code in DB Browser for SQLite it gives me the correct result. Please advise how to solve this issue. 
 
### Steps to reproduce
Following query: 
SELECT store_no,
       prod_code,
       actual_sale,
       sum(actual_sale) OVER (ORDER BY actual_sale DESC ROWS BETWEEN 2 PRECEDING AND 2 FOLLOWING) AS Csum
  FROM Sales;

In SQLite produces the following output:
![image](https://user-images.githubusercontent.com/77023283/190695693-24cd98ef-63dd-4922-b0d1-2485960300fc.png)
The output for column Csum is incorrect.

But when I try to reproduce the same code in DB Brower for SQLite it produces the correct output:
![image](https://user-images.githubusercontent.com/77023283/190696584-3530aa03-d5ea-47b6-b1bc-0ab11c0d9b6e.png)

### Operating system
Windows 10

### SQLiteStudio version
 SQLiteStudio (3.3.3)

**Comment by pawelsalawa** [comment]
Is is possible that you provide a sample database for this?

**Comment by Pacode74** [comment]
https://drive.google.com/file/d/14Vr6OqRWGwxEAMSQt_JxaVsGkGj7N5nb/view?usp=sharing

**Comment by pawelsalawa** [comment]
Thanks. Indeed 3.3.x returns wrong results, but the upcoming 3.4.0 seems to already have this fixed. You can download weekly build from https://github.com/pawelsalawa/sqlitestudio/actions

**Comment by Pacode74** [comment]
Thank you Pawel for your quick response and explanation. Look forwards to 3.4.0 release
