### ISSUE TITLE
Support for executing multiple SQL queries in a single file

### ISSUE THREAD

**Issue by dpnishant** [pawelsalawa/sqlitestudio#4521]
### Details
Support for executing multiple SQL queries in a single `.sql` file separated by a semicolon. This shall be very useful for executing batch queries like database, tables, views, rows creation.

### Steps to reproduce
In version `3.3.3`, loading a `.sql` file with more than one queries (each separated by a semicolon `;`), only executes the first query.

**Comment by pawelsalawa** [comment]
You can do it by right-clicking on a database and picking "Execute SQL from file".
