### ISSUE TITLE
Long text truncated in Form view for result of SQL query with a function

### ISSUE THREAD

**Issue by ysalmon** [pawelsalawa/sqlitestudio#4533]
### Details
When the result of a SQL query contains lengthy text, and the SQL query uses a function, the display in the Form panel of the result panel is truncated.

This is not the case in the corresponding panel in the Table panel or a View panel (hope I am clear ;-)), nor, seemingly, for simple SQL queries.

### Steps to reproduce
Insert the following text in a table :
```
Il y a quelques petites erreurs ou imprécisions de-ci de-là, mais c'est vraiment un très bon ensemble. Attention à la ponctuation quand vous rédigez : elle est indispensable pour que votre texte soit immédiatement compréhensible.
```

Do a ``SELECT * FROM table;``. Switch the result view to Form. It will show the whole text.
Do a ``SELECT commentaire FROM table;`` : works too.

But do a ``SELECT replace(commentaire, 'µ', 'µ') FROM table;``. The Form panel will show only :
```
Il y a quelques petites erreurs ou imprécisions de-ci de-là, mais c'est vraiment un très bon ensembl
```

With ``SELECT replace(commentaire, 'µ', 'µ') AS "truc" FROM table;``, the whole text is again shown !

### Operating system
KUbuntu 22.04

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
Can you try it with some pre-3.4 build? You can get recent one for Linux at https://github.com/pawelsalawa/sqlitestudio/actions/runs/3309985599

**Comment by ysalmon** [comment]
In this new version, the problem does not arise !
