### ISSUE TITLE
More intuitive determination of current query

### ISSUE THREAD

**Issue by ysalmon** [pawelsalawa/sqlitestudio#4535]
### Details
Probing pre-3.4, I see a new feature that highlights the query under the text cursor. This is very nice, and also makes apparent what I always found odd, and a picture is better than an explanation :
![Screenshot_20221026_213552](https://user-images.githubusercontent.com/536850/198120089-d1ea730a-5ca4-4d26-ba5b-25ebdb3d0681.png)

Even though the cursor is technically just after the ``SELECT 3 != 4;`` request, it is still on its line, and there is not another query at that position on the same line.

This situation arises easily when you type a query above another one, and want to execute that new query.

So I suggest the current query should be ``SELECT 3 != 4;`` instead of the following line.

**Comment by pawelsalawa** [comment]
Good observation and I agree.
I'm adding this one to 3.4.1. I don't want the 3.4.0 backlog to grow suddenly, especially so close before the 3.4.0 release (there is not that many items left). Especially that this one is not critical.

**Comment by pawelsalawa** [comment]
In commit comment I mentioned the improvement to the highlighter, but the fix works also for which query is actually executed when you hit F9 (or Execute toolbar button).

**Comment by ysalmon** [comment]
Thank you so much. This is very useful because we have to train students to grasp basic SQL, but have very little time to do so as it is just a part of a larger module, and they also are not used to programming environments in general. Every second not spent trying to catch that sort of thing is great !
