### ISSUE TITLE
When sqlitestudio closes the sql editor, there is no pop-up prompt whether to save

### ISSUE THREAD

**Issue by 18229602176** [pawelsalawa/sqlitestudio#4576]
开发团队你们好！
  我在使用sqlitestudio3.4版本的过程中，发现有两个问题：
1.加载包含中文注释的sql文件时，显示为乱码，该问题可自行解决
2.加载sql文件后，如果做了编辑，关闭窗口时不会弹出是否保存对话框，导致所有编辑无效，该问题影像非常大，建议修复
谢谢

**Comment by pawelsalawa** [comment]
Translation:

> Hello development team!
> In the process of using sqlitestudio3.4, I found two problems:
> 1. When loading a sql file containing Chinese comments, it is displayed as garbled characters, and this problem can be solved by itself
> 2. After loading the sql file, if you make edits, the dialog box of whether to save will not pop up when you close the window, causing all edits to be invalid. The image of this problem is very large, and it is recommended to fix it
> thanks

**Comment by pawelsalawa** [comment]
Ad 1) What is file encoding/charset that you use when you create such SQL file?
Ad 2) It will most likely be solved with #4561

**Comment by 18229602176** [comment]
1)文件编码是UTF-8

2)第二个问题我没有表达清楚，我重新表述一下。程序加载SQL文件后，在SQL编辑器中修改了SQL语句，如果忘记点击保存按钮，直接点击关闭SQL编辑器选项卡，此时SQL编辑选项卡会消失，编辑内容也没有被保存。 希望在点击关闭SQL编辑器选项卡时，检测SQL编辑器内容是否做了更改，如果没有更改，弹出是否保存SQL编辑器内容对话框，防止丢失所做的更改。谢谢。

**Comment by pawelsalawa** [comment]
Please use English, if you don't mind.

Translation

> 1) The file encoding is UTF-8
> 
> 2) I did not express the second question clearly, so I will rephrase it. After the program loads the SQL file, modify the SQL statement in the SQL editor. If you forget to click the save button, just click to close the SQL editor tab. At this time, the SQL editing tab will disappear, and the edited content will not be saved. It is hoped that when you click to close the SQL editor tab, it will detect whether the content of the SQL editor has been changed. If there is no change, a dialog box of whether to save the content of the SQL editor will pop up to prevent the loss of the changes. thanks.

**Comment by pawelsalawa** [comment]
Ad 1) Can you provide example file that causes this problem? (you can attach files to posts here)
Ad 2) Yes. As I mentioned, it will be addressed in #4561 (it will cover more than just editor renaming).

**Comment by 18229602176** [comment]
[数据.txt](https://github.com/pawelsalawa/sqlitestudio/files/10089706/default.txt)

**Comment by pawelsalawa** [comment]
The file is not encoded with UTF-8, but rather with GB2312. When converted it to UTF-8 (in Notepad++) it loaded into SQL Editor correctly, showing all Chinese characters.
