### ISSUE TITLE
Several bugs on big table/database

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#4587]
### Discussed in https://github.com/pawelsalawa/sqlitestudio/discussions/4584

<div type='discussions-op-text'>

<sup>Originally posted by **GeneGeneGitHub** November 26, 2022</sup>
* Add a database, choose the file, click Test Connection and it crashes every time.
* tables open much slower
* message about "couldn't check for updates: something about TLS initialization"
* message about "reduced rows to 3125 because of too many columns"
* 3.4.0 now requires dbl-clicking a column header to sort by that column (whereas 3.3.3 required only single-click).  That's not a problem, but on a larger table I tried it on,  3.4.0 wouldn't do the sort in any reasonable time.  I had to Interrupt it.

Reverted back to 3.3.3, which is much more responsive.

Thanks Pawel !</div>

**Comment by pawelsalawa** [comment]
1. Open Table 1 (16 columns): "Number of rows per page was decreased to 3125 due to number of columns (16) in the data view."
Open Table 2 (2 columns): "Number of rows per page was decreased to 3125 due to number of columns (16) in the data view."
Both tables have 2.9M rows. And again, I never changed the default 'Number of data rows per page' from 1000.
1. If I remove the database, close and reopen SQLiteStudio 3.4.0, it continues to tell me the 2-column table has 16 columns. Using the 'Next page' and 'Previous page' buttons generates that same message every time I click one of them.
1. Moving to the next or previous page via the buttons is now so slow (10 seconds on the 16-column table) as to be totally unusable.
1. Opening some other tables now reports 'Only one query can be executed simultaneously'

**Comment by JrgMyr** [comment]
Hi Pawel.

I have observed a special behaviour of version 3.4.0 where queries with function calls run flawlessly on a small test table with five rows but crash SQLiteStudio every single time on a medium sized table with 1.4m rows (file size 480 MB):

`SELECT SupplierId, frmInt(COUNT(*)) AS LineCount FROM Lines GROUP BY 1`

The same query without the custom function "frmInt()"

`SELECT SupplierId, COUNT(*) AS LineCount FROM Lines GROUP BY 1`

runs both on the small and the larger table. The Javascript function [frmInt()](https://github.com/pawelsalawa/sqlitestudio/wiki/Qt_script_frmint) is the one from the [scripts repository](https://github.com/pawelsalawa/sqlitestudio/wiki/Scripts_repository) in the Wiki page.

There seems to be something that triggers a crash when larger tables and custom script functions are combined.

**Comment by pawelsalawa** [comment]
Fixed in 3.4.1 - full explanation of root cause: https://github.com/pawelsalawa/sqlitestudio/issues/4600#issuecomment-1335862585
