### ISSUE TITLE
Could not check for updates (TLS initialization failed).

### ISSUE THREAD

**Issue by DavidRizzo** [pawelsalawa/sqlitestudio#4590]
### Details
Everytime I open the app I get this message, "Could not check for updates (TLS initialization failed)."

### Steps to reproduce

1. Open the app
2. Observe the status window

### Operating system
Windows 11

### SQLiteStudio version
3.4.0

**Comment by pawelsalawa** [comment]
It's known issue under Linux, but it's something new under Windows. Could you run SQLiteStudio from command line using following options? `SQLiteStudio.exe -d` and then inside the app hit the `F12` key to open debug console. Tell me if you see more errors related to the TLS/SSL/Network there?

**Comment by TiagoAzevedo1903** [comment]
I have the same message on Windows 10.

**Comment by TiagoAzevedo1903** [comment]
[20:17:06.250] WARNING:  QSslSocket::connectToHostEncrypted: TLS initialization failed

**Comment by TiagoAzevedo1903** [comment]
WARNING:  QSslSocket::connectToHostEncrypted: TLS initialization failed

**Comment by pawelsalawa** [comment]
Can you please provide a debug output, as I asked in my post above?

**Comment by TiagoAzevedo1903** [comment]
No error appears, just the warning.

WARNING: QSslSocket::connectToHostEncrypted: TLS initialization failed
