### ISSUE TITLE
Shift click and Control click to select results not working as expected

### ISSUE THREAD

**Issue by bobinorlando** [pawelsalawa/sqlitestudio#4593]
After running a query I often need to copy some or all of the result set.
In Ver 3 it was possible to highlight and select an entire row with the mouse or multiple contiguous rows with Shift click or discontinuous rows with Control click. 
In Ver 4 I am able to select but only momentarily - the selection does not stick long enough to copy the selection.

### Operating system
Win 64
Version 10.0.19044 Build 19044

### SQLiteStudio version
3.4.0

**Comment by pawelsalawa** [comment]
I'm not sure why that happens to you, cause I've just checked and it seems to be working as expected. Have you tried to restart the app? Maybe it's something temporary with the window management in Windows?

**Comment by bobinorlando** [comment]
Yes I have restarted the app several times. 
I will attempt to be more precise in my description of the issue. 

In Version 4, Shift click and Ctrl click work as expected when selecting various individual cells in the grid view (and various individual columns and cells).

However, the issue occurs when selecting entire rows by selecting the row number button at the far left of the grid.

In Version 3 there was a minor issue when selecting multiple rows and then de-selecting one or more rows by Ctrl-click -- the first column of the most recently deselected row would still be highlighted faintly and included in the copy but otherwise worked perfectly.

In Version 4, when selecting an entire row by clicking the row button, the row number turns Bold and the entire row is selected as expected. 
Shift-click to select a contiguous group of rows turns the row number button Bold and works as expected.

However, Ctrl-click does not turn the row button Bold and only faintly highlights and selects the first column of the row. It does not select the entire row.

I do notice that if I Ctrl-click the row number and then drag down to the next row it does select the row, but the drag operation is not as expected and was not required in Ver 3.

If I Shift-click a group of contiguous rows to select them, and then attempt to de-select one or more dis-contiguous rows in the highlighted group by Ctrl-click on the row number button, the row number button remains Bold and de-selection does not occur.


Thank you for all you do! SQLiteStudio is an amazing app and I use it daily.

**Comment by pawelsalawa** [comment]
You're absolutely right. To be fixed.
