### ISSUE TITLE
Issue when JS function is used in a query on a big table

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#4596]
Originally posted by @JrgMyr:

Hi Pawel.

I have observed a special behaviour of version 3.4.0 where queries with function calls run flawlessly on a small test table with five rows but crash SQLiteStudio every single time on a medium sized table with 1.4m rows (file size 480 MB):

`SELECT SupplierId, frmInt(COUNT(*)) AS LineCount FROM Lines GROUP BY 1`

The same query without the custom function "frmInt()"

`SELECT SupplierId, COUNT(*) AS LineCount FROM Lines GROUP BY 1`

runs both on the small and the larger table. The Javascript function [frmInt()](https://github.com/pawelsalawa/sqlitestudio/wiki/Qt_script_frmint) is the one from the [scripts repository](https://github.com/pawelsalawa/sqlitestudio/wiki/Scripts_repository) in the Wiki page.

There seems to be something that triggers a crash when larger tables and custom script functions are combined.

**Comment by JrgMyr** [comment]
Great. Can confirm it works on a sample of queries.
