### ISSUE TITLE
can not display chinese (unicode)

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#460]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 610
Originally created at: Thu Jan  5 03:28:26 2012
Originally last updated at: Thu Jan  5 03:28:26 2012

DESCRIPTION:
can not display chinese (unicode)

OPERATING SYSTEM:
Windows 7, intel

APPLICATION VERSION:
2.0.22

TCL PACKAGES:
autoscroll.................... 1.1
crc16......................... 1.1.1
crc32......................... 1.3.1
http.......................... 2.7.5
Itcl.......................... 3.4
Itk........................... 3.4
md4........................... 1.0.5
md5........................... 1.4.4
msgcat........................ 1.4.3
sha1.......................... 2.0.3
sha256........................ 1.0.2
sqlite........................ 2.0
sqlite3....................... 3.7.8
Tcl........................... 8.5.9
Thread........................ 2.6.6
Tk............................ 8.5.9
tkpng......................... 0.7
treectrl...................... 2.3.1
ttk::dialog................... 0.8
ttk::theme::alt............... 8.5
ttk::theme::clam.............. 8.5
ttk::theme::classic........... 8.5
ttk::theme::default........... 8.5
ttk::theme::keramik........... 0.6.1
ttk::theme::keramik\\_alt....... 0.6.1
ttk::theme::plastik........... 0.6.1
ttk::theme::vista............. 1.0
ttk::theme::winnative......... 8.5
ttk::theme::xpnative.......... 8.5
uuencode...................... 1.1.5
winappendfile................. 1.0
yencode....................... 1.1.3

**Comment by pawelsalawa** [comment]
Originally created at: Thu Jan  5 03:28:26 2012

Yes, it can. Many Chinese people already use SQLiteStudio and their national characters with success.

Maybe you have an examples of how you put characters to database and how SQLiteStudio displays them to you?

**Comment by pawelsalawa** [comment]
Originally created at: Thu Jan  5 03:28:26 2012

_Status changed to **rejected**_

**Rejection reason:**
No response from author.

**Comment by holevel6** [comment]
A suggestion for Unicode text support. UTF8 text is displayed correctly. But Unicode-LE and Unicode-BE text are not. It is displayed something like this "��U".

**Comment by CodingOctocat** [comment]
I'm using EFCore 8 + SQLite, fields exist in Chinese, SQLiteStudio can display them normally, but there is one field (models, `List<string>`) where the Chinese is displayed in Unicode, which confuses me.

![image](https://github.com/pawelsalawa/sqlitestudio/assets/7220248/a86854ba-2c7f-454b-b2b2-e06f7ef8a8c9)
