### ISSUE TITLE
UPDATE does not work if the table name is in upper case in Russian language

### ISSUE THREAD

**Issue by Domos234** [pawelsalawa/sqlitestudio#4602]
### Details
UPDATE does not work if the table name is in upper case in Russian language
![image](https://user-images.githubusercontent.com/54128876/205452806-5c2fbc60-1dc3-4087-9457-e945d6cb48ba.png)
![image](https://user-images.githubusercontent.com/54128876/205452820-154f90e7-eb6d-4250-b269-a5e974e210b7.png)

### Steps to reproduce
1. Name the table in uppercase in Russian language
2. Try to update the value in the table

### Operating system
Windows 10 Pro 10.0.19043 build 19043

### SQLiteStudio version
3.4.1

**Comment by pawelsalawa** [comment]
Can you please write here exact name that you use? I'd like to reuse exact letters that you used and I'm afraid I could mistake them, since it's a Cyrillic aphabet.

**Comment by Domos234** [comment]
> Can you please write here exact name that you use? I'd like to reuse exact letters that you used and I'm afraid I could mistake them, since it's a Cyrillic aphabet.

МВ-911
