### ISSUE TITLE
"Show filter inputs by Column" works not smooth and clear button does not work.

### ISSUE THREAD

**Issue by KoenigDickBauch** [pawelsalawa/sqlitestudio#4613]
### Details
If "Show filter inputs by Column" is selected and you fill in a filter. The table is update by changing the focus to the next filter. This waste time if you want to fill in more filter. If you hit the clear button, then the focus change, the table is updated and the clear does not work.

### Steps to reproduce
see details

### Operating system
win10

### SQLiteStudio version
v3.4.1

### correction
Do not update the table by focus change, only by hit ENTER

**Comment by pawelsalawa** [comment]
On top of your report, according to my test I see 2 more items:

- [ ] if you try "clear" the filter using the "x" button inside of it, it does not work (particular filter is not cleared)
- [ ] moving from one filter to another should be possible with the Tab key (which does not work that way right now)

**Comment by KoenigDickBauch** [comment]
Super, I am exited to get the next version

**Comment by pawelsalawa** [comment]
There is an automatic weekly built done during every Sunday-Monday night, so you can get snapshot build on Monday from Actions tab (see on top of this page). It will already include this fix.
