### ISSUE TITLE
View filtering problem

### ISSUE THREAD

**Issue by DenisKvita** [pawelsalawa/sqlitestudio#4618]
### Details
Eror '**Cannot edit this cell. Details: The query execution mechanism had problems with extracting ROWID's properly. This might be a bug in the application. You may want to report this**.' on view cell double click

### Steps to reproduce
1. Open 'data' tab for view 
2. Double click left mouse button on field  and copy value to 'filter' input
3. apply filter
4. trying to repeat step 2 and 3 from this point cause error message '**[15:40:15] Cannot edit this cell. Details: The query execution mechanism had problems with extracting ROWID's properly. This might be a bug in the application. You may want to report this**.'

### Operating system
Windows 10 x64

### SQLiteStudio version
SQLiteStudio v3.4.1 portable

**Comment by pawelsalawa** [comment]
Can you share the query used in the View?

**Comment by pawelsalawa** [comment]
And does the view query use another view?

**Comment by DenisKvita** [comment]
> Can you share the query used in the View?

"Select id,  f1, f2 from table1"  where "id" is primary key

**Comment by DenisKvita** [comment]
Problem appear only on editing view after apply filter.

**Comment by pawelsalawa** [comment]
Can you try with the latest build? https://github.com/pawelsalawa/sqlitestudio/actions/runs/3727815817

**Comment by DenisKvita** [comment]
[Problem demonstration](https://drive.google.com/file/d/1D7Rip0H4o1TrFn0KUFKQxsuJCR2TDORc/view?usp=drivesdk)

**Comment by pawelsalawa** [comment]
Thanks, I'll look into it.
