### ISSUE TITLE
sqlitestudio-3.4.1: qt5ct style is not honored

### ISSUE THREAD

**Issue by sedimentation-fault** [pawelsalawa/sqlitestudio#4634]
### Details
In the dialog where I can select a style (e.g. Adwaita,...), I have selected  "qt5ct-style". This style defines my own colors, which are definitely different from the "white themes". However, these colors are not honored and I see "variations of white" all around.

### Steps to reproduce

- Delete _~/.config/SalSoft/SQLiteStudio/settings3_.
- Start _sqlitestudio_.
- A small dialog asks you to choose language. The dialog is painted in the "qt5ct-style" colors.
- Choose language, say "American English". The main dialog appears **in the "qt5ct-style" colors**:
  ![sqlitestudio-qt5ct-style](https://user-images.githubusercontent.com/22053241/209688813-95860fac-4f3f-41ee-bee9-b88439bcd154.png)
  At this point one is led to think _"all is good, the application obeys qt5ct themes"_. But then:
- Go to Tools --> Open configuration dialog (F10) and choose "qt5ct-style" for style in the "Style" section, just to make sure...
- Exit _sqlitestudio_.
- Restart _sqlitestudio_. The colors have reverted to "variations of white":
  ![sqlitestudio-style-not-followed](https://user-images.githubusercontent.com/22053241/209688816-ea641a48-a999-4905-b147-6f4411abde48.png)
- Try to apply "qt5ct-style" from the same dialog above (F10). Does not work, colors remain "white".
- Try again: choose say, "kvantum-dark", apply it. It works.
- Try to choose "qt5ct-style":
  ![sqlitestudio-select-style](https://user-images.githubusercontent.com/22053241/209688819-b0b1e6f4-3230-49cd-b774-5e0af15cd5dc.png)
- Does not work, white again:
  ![sqlitestudio-style-not-followed](https://user-images.githubusercontent.com/22053241/209688816-ea641a48-a999-4905-b147-6f4411abde48.png)

Deleting _~/.config/SalSoft/SQLiteStudio/settings3_ and restarting _sqlitestudio_ brings the correct (qt5ct) colors back, only to lose them again as soon as one either restarts, or chooses a different style and then sets "qt5ct-style" again.

### Operating system
Linux-5.4.196-gentoo-x86_64,
Qt: 5.15.2
qt5ct: 1.5

### SQLiteStudio version
3.4.1

**Comment by pawelsalawa** [comment]
I've installed qt5ct and configured custom colors there, but I'm unable to make it work with SQLiteStudio even during the first start (when the language dialog shows up). Frankly speaking I have no clue how did you make it work even once.

Be aware, that SQLiteStudio uses its own Qt that is distributed together with application binaries (unless you compiled SQLiteStudio from sources - did you?), so it may something to do with these problems.

**Comment by sedimentation-fault** [comment]
> I've installed qt5ct and configured custom colors there, but I'm unable to make it work with SQLiteStudio even during the first start (when the language dialog shows up). Frankly speaking I have no clue how did you make it work even once.
> 
Do you have these files in your home directory:

```
~/.config/qt5ct/
~/.config/qt5ct/qt5ct.conf
~/.config/qt5ct/colors
~/.config/qt5ct/colors/XXX.conf
~/.config/qt5ct/qss
```
where XXX.conf is text file that contains 4 lines:

```
[ColorScheme]
active_colors=...
disabled_colors=...
inactive_colors=...
```
?  XXX is the base name of the color scheme you created in qt5ct and _~/.config/qt5ct/qt5ct.conf_ contains a section where this file is referenced:

```
[Appearance]
color_scheme_path=/home/<user>/.config/qt5ct/colors/XXX.conf
custom_palette=true
icon_theme=Adwaita
standard_dialogs=gtk3
style=Fusion

...other sections here
```
Did you delete your _~/.config/SalSoft/SQLiteStudio/settings3_? If this file is there from previous installations, you will not get your color scheme the first time. Rename it, if you don't want to delete it.

> Be aware, that SQLiteStudio uses its own Qt that is distributed together with application binaries (unless you compiled SQLiteStudio from sources - did you?), so it may something to do with these problems.

I compiled from sources. :-)

**Comment by sedimentation-fault** [comment]
Let me make a wild guess: 

**it all stays and falls with the **_~/.config/SalSoft/SQLiteStudio/settings3_** file!** 

If that file is not there (e.g. the very first time your start _sqlitestudio_, after a completely fresh install, on a system that did not have it previously), then the application behaves "normally", i.e. like any other _Qt_ application that follows the "standard" way of determining the color scheme - if a _qt5ct_ color scheme is there, use it, otherwise use the standard one from the _Qt_ installation.

But if the file _is_ there, it overwrites this standard way of doing things somehow and although it can set "standard" _Qt_ themes, it misses a user-created  theme like the one described by the files I mentioned above.

**Comment by pawelsalawa** [comment]
The `settings3` file causes problem for you most likely because SQLiteStudio does "restore last used style" operation when this file exists. What I don't understand is why it fails to restore your style, since it's available there anyway.

I will have to recompile my SQLiteStudio against Ubuntu-provided Qt to see if that makes it reproducible for me.

**Comment by sedimentation-fault** [comment]
I tried _strace_, but I was overwhelmed by the number of output lines...if I knew what to _grep_ for, I might be able to filter some crucial _error/not found/..._ message and help you. Do you know what I should look for?

**Comment by sedimentation-fault** [comment]
OK, I did filter strace output by XXX (the name of my qt5ct theme):

```
strace sqlitestudio 2>&1 | grep -i xxx

access("/home/<user>/.config/qt5ct/colors/XXX.conf", F_OK) = 0
openat(AT_FDCWD, "/home/<user>/.config/qt5ct/colors/XXX.conf", O_RDONLY|O_CLOEXEC) = 6
statx(AT_FDCWD, "/home/<user>/.config/qt5ct/colors/XXX.conf", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=597, ...}) = 0
```

so it _does_ read it - not sure what the return codes mean here, but doesn't look like an error.

**Comment by pawelsalawa** [comment]
I've managed to preproduce your problem fully when compiled with Ubuntu-provided Qt.
I'll fix it.

**Comment by sedimentation-fault** [comment]
To be able to study _strace_ output at my leisure, I redirected stdout and stderr to a log file:

```
strace sqlitestudio >> sqlitestudio.log 2>&1
```

Inspecting _sqlitestudio.log_, I see that it tries to read

_/usr/lib64/qt5/plugins/platformthemes/libqgtk3.so.avx2_

almost immediately after it read my _qt5ct_ XXX.conf file (it just reads _/etc/localtime_ in between):

```
newfstatat(AT_FDCWD, "/etc/localtime", {st_mode=S_IFREG|0644, st_size=2298, ...}, 0) = 0
newfstatat(AT_FDCWD, "/etc/localtime", {st_mode=S_IFREG|0644, st_size=2298, ...}, 0) = 0
newfstatat(AT_FDCWD, "/etc/localtime", {st_mode=S_IFREG|0644, st_size=2298, ...}, 0) = 0
close(6)                                = 0
openat(AT_FDCWD, "/usr/lib64/qt5/plugins/platformthemes/libqgtk3.so.avx2", O_RDONLY|O_CLOEXEC) = -1 ENOENT
```

but as you see this file is not there.  Not sure if that's important...

**Comment by sedimentation-fault** [comment]
...and then it reads

_/usr/lib64/qt5/plugins/platformthemes/libqgtk3.so_

```
openat(AT_FDCWD, "/usr/lib64/qt5/plugins/platformthemes/libqgtk3.so", O_RDONLY|O_CLOEXEC) = 6
read(6, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\3201\1\0\0\0\0\0"..., 832) = 832
pread64(6, "\4\0\0\0 \0\0\0\5\0\0\0GNU\0\1\0\1\300\4\0\0\0\31\0\0\0\0\0\0\0"..., 48, 318024) = 48
```

which _is_ there. So may be it overwrites something at this point.

> I've managed to preproduce your problem fully when compiled with Ubuntu-provided Qt.
> I'll fix it.

Thank you for your efforts. :+1:

**Comment by pawelsalawa** [comment]
The `qt5ct` works in a misterious ways. It registers another style, but its color palette is not exactly synched with the `QStyle::standardPalette()` method. SQLiteStudio was first reading the standard palette and then setting it back to the style (with slight adjustments). The problem was, that the standard palette read from the `qt5ct` style had all colors white (like original `Fusion` style) and setting it back to the `qt5ct` style would overwrite your custom colors.

I have no idea what `qt5ct` does underneath, but I made an exception in the code of SQLiteStudio, so that if the style is `qt5ct-style` it will not touch standard palette anymore.

**Comment by sedimentation-fault** [comment]
OK, thank you, I will test it and tell you how it works here.

> The qt5ct works in a misterious ways.

Since (as I read in the Qt docs) _"a palette consists of three color groups: Active, Disabled, and Inactive"_, the _qt5ct_ palette is exactly what is stored in the

_~/.config/qt5ct/colors/XXX.conf_

that I mentioned above. That file contains the Active, Disabled, and Inactive of your color scheme. Therefore, maybe _qt5ct_ just reads and uses that file, without bothering to read or set any "standard palette".

**Comment by pawelsalawa** [comment]
Yes, it's stored there, but when and how it is applied to the runtime application is not clear, because - as I said earlier, when SQLiteStudio reads the `standardPalette()` it looks to have "white" colors, despite using `qt5ct-style`.

**Comment by sedimentation-fault** [comment]
You might want to have a look at how it is done in other Qt applications, e.g. _sqliteman_, _okular_, _virtualbox_...They all work fine here, as far as obeying the _qt5ct_ styles is concerned - and I cannot imagine that they all had a bug report like this that they resolved by explicitly treating _qt5ct_ styles differently from the rest. OTOH they don't offer the possibility to change the color style - but they load whatever style one has set in _qt5ct_ just fine. Just an idea...

So now I'm going to create a patch out of your commit above, apply it here and see how it goes...:-)

**Comment by pawelsalawa** [comment]
Well, they don't let user to change style in runtime (from application itself) and they do not do anything about color palette. That's why it works there.

**Comment by sedimentation-fault** [comment]
Well, it works - almost... :-)

Here's what I did:

To get the commit as a patch from Github, all one has to do is to take the URL of the [commit](https://github.com/pawelsalawa/sqlitestudio/commit/c0022a0a1abbf82a9ee26c25d92cae4853554daf) and append _'.patch'_ to it - Github will give you a "unified patch" automatically that you can download with _curl_ or _wget_:

`curl -o sqlitestudio-3.4.1-load-qt5ct-styles-correctly.patch https://github.com/pawelsalawa/sqlitestudio/commit/c0022a0a1abbf82a9ee26c25d92cae4853554daf.patch`

Then you can apply the patch with `patch -p1 ...`.

As I said, it works - in the sense that if you have set _qt5ct-style_, it is preserved upon restarts and is displayed correctly when you restart _sqlitestudio_.

What does NOT work, however, is this:

Suppose you set another style in the configuration dialog, say _Adwaita dark_ - and press _Apply_. The colors of that style are now applied to the application. Then you go and choose _qt5ct-style_ - and press _Apply_ again. Nothing happens - the colors remain the "old" ones, from the previous style. That is _"Apply"_ does not work for _qt5ct-style_.

If you restart, however, the colors of _qt5ct-style_ are applied correctly. To me this means that the "palette" is not set correctly to that of _qt5ct-style_ when one presses "Apply" - only upon restart.

**Comment by sedimentation-fault** [comment]
A note on the patch: the patch from Github will fail with its first hunk (the one that patches ChangeLog.md). This is OK, since we do not apply all commits that came after v.3.4.1, only this one. You may thus want to delete that hunk from the patch before you apply it, or tell patch to ignore errors.

**Comment by sedimentation-fault** [comment]
> What does NOT work, however, is this:

Is there any work planned on this? IMO this bug is not 100% resolved and was closed prematurely.

**Comment by pawelsalawa** [comment]
There is no further work planned for it. As I debugged it in SQLiteStudio, the `qt5ct` does a non standard hack of some sort to apply color palette and I'm not planning to support such hacks. There is already a workaround in SQLiteStudio for `qt5ct-style` to make it work initially (after start), but handling both startup and during-runtime would require even more workarounds, which then may randomly not work, or `qt5ct` would change something in the way they apply colors palette and yet again SQLiteStudio would have to adjust to it.

Also styling is rather low priority.

**Comment by sedimentation-fault** [comment]
O.K., many thanks anyway for all you have already done.
