### ISSUE TITLE
Software soft locked itself after pasting a broken query in SQL Editor

### ISSUE THREAD

**Issue by DanielAwada** [pawelsalawa/sqlitestudio#4658]
### Details
I was trying to auto generate some queries and run them in the SQL Editor for testing.
During one of the tests I ran a query and the software immediatly crashed. Now, every time I try to reopen it, it exits again making the software unusable. No erros message, looks like it entered a 'soft locked' state.
The query my algorithm generated is obviously broken, its missing the closing brackets at the end of each line. I suspect this creates some kind of recursion that the SQL Editor cant handle and panics.

Tried to reinstall the software. Didn't work.
Tried to update it. Didn't work.
I tried using another computer. It soft locked itself in that other computer too.

Is there any file I can delete that would close all open tabs from outside de software or something like that so I can work on it again?

### Steps to reproduce
Simply copy and paste this query in the SQL Editor:

`
UPDATE
TableA
SET 
KeyColumn = (SELECT KeyColumn FROM TableB WHERE (TableA.KeyColumn = TableB.KeyColumn, 
ColumnA = (SELECT ColumnA FROM TableB WHERE (TableA.KeyColumn = TableB.KeyColumn, 
ColumnB = (SELECT ColumnB FROM TableB WHERE (TableA.KeyColumn = TableB.KeyColumn, 
ColumnC = (SELECT ColumnC FROM TableB WHERE (TableA.KeyColumn = TableB.KeyColumn, 
ColumnD = (SELECT ColumnD FROM TableB WHERE (TableA.KeyColumn = TableB.KeyColumn, 
ColumnE = (SELECT ColumnE FROM TableB WHERE (TableA.KeyColumn = TableB.KeyColumn, 
ColumnF = (SELECT ColumnF FROM TableB WHERE (TableA.KeyColumn = TableB.KeyColumn, 
ColumnG = (SELECT ColumnG FROM TableB WHERE (TableA.KeyColumn = TableB.KeyColumn, 
ColumnH = (SELECT ColumnH FROM TableB WHERE (TableA.KeyColumn = TableB.KeyColumn) 
WHERE 
(TableA.KeyColumn in TableB.KeyColumn)
`

### Operating system
Windows 10 Pro (2 different PCs)

### SQLiteStudio version
3.3.3 and 3.3.4 and 3.4.2

**Comment by pawelsalawa** [comment]
The configuration is stored in `C:\Users\%USERNAME%\AppData\Local\SalSoft\SQLiteStudio` - there is the `settings3` file, which you can delete or rename.

Anyway, I can confirm there is a but - it crashed for me to, so I will fix it.

**Comment by DanielAwada** [comment]
Thank you, I was able to open the program again!
I hope this doesn't happen again, but if it does now that I know how to get around it!
