### ISSUE TITLE
Should -lcurses be -lncurses on *nix?

### ISSUE THREAD

**Issue by onkobu** [pawelsalawa/sqlitestudio#4660]
### Details
.pro file of sqlitestudiocli has a block Unix which includes -lreadline and -lcurses. Yet ldconfig | curses on an average linux machine yields only libncurses in various flavors. Leaving this in the .pro-file makes the build fail because no matching library can be found. Replacing it with -lncurses yields a working build and binary.

### Steps to reproduce
Simply build cli. Then change the sqlitestudiocli.pro replacing -lcurses with -lncurses and it works.

### Operating system
Gentoo Linux, gcc 11, libncurses installed

### SQLiteStudio version
>=3.2.1 (this is when a change to the ebuild was committed fixing this by applying the replacement described above)

**Comment by pawelsalawa** [comment]
I'm not sure about the reason of introducing the curses library in the first place. I've just removed it (it still compiles just fine).

**Comment by onkobu** [comment]
Great, THX
