### ISSUE TITLE
Pasting from spreadsheet ignores blank lines

### ISSUE THREAD

**Issue by ysalmon** [pawelsalawa/sqlitestudio#4673]
### Details
When copying rows from a spreadsheet (LibreOffice Calc), if the first rows are blank, they get ignored by SQLiteStudio, creating an offset in the pasted data.

### Steps to reproduce

1. Create a spreadsheet.
2. In column A line 2, write "example".
3. Create a database and a table in that database, with one column.
4. Create two rows in the table.
5. In the spreadsheet, select the first two rows of the first column, and copy.
6. Paste in SQLiteStudio's data edition interface, in the first row.

The text "example" gets into the first row, instead of the second one.

### Operating system
KUbuntu 22.04.

### SQLiteStudio version
3.4.1

**Comment by pawelsalawa** [comment]
It's not SQLiteStudio's fault. Try to paste the same to notepad. First (empty) row will not be pasted.

**Comment by ysalmon** [comment]
Oh yes, your are right. So a report to LibreOffice it is…
