### ISSUE TITLE
Problem with aliases. Weird error where case letters don't match

### ISSUE THREAD

**Issue by cmedinag** [pawelsalawa/sqlitestudio#4679]
### Details
When using an alias, for instance, in a WITH statement, that alias must be used with the same case letters in the select. Otherwise, a syntax parenthesis mismatch occurs.
It does not happen with previous versions of SQLiteStudio

### Steps to reproduce
WITH test AS (SELECT 3)
SELECT * FROM TEST

Error:
![image](https://user-images.githubusercontent.com/11750481/215728802-fe3de646-631d-4f10-be13-d04ebebae115.png)

Whereas:
WITH test AS (SELECT 3)
SELECT * FROM test

Works perfect
![image](https://user-images.githubusercontent.com/11750481/215728884-2c02b867-4008-430d-acb0-72a54e880bb1.png)

### Operating system
Windows 10

### SQLiteStudio version
3.4.3

**Comment by Mendeo** [comment]
This error also occurs when trying to refer to an alias:
WITH
test AS (SELECT 3),
test2 as (SELECT * FROM test)
SELECT * FROM test2

Versions 3.4.2 and 3.4.3
