### ISSUE TITLE
The height of the watch head is incorrect

### ISSUE THREAD

**Issue by flamecyclone** [pawelsalawa/sqlitestudio#4680]
### Details
The height of the watch head is incorrect

### Operating system
Windows 11 x64

### SQLiteStudio version
3.4.3

![image](https://user-images.githubusercontent.com/70200943/216535458-7aeb91f3-c38a-4d45-8fed-63f4324dad63.png)

**Comment by pawelsalawa** [comment]
Duplicate of #4691
