### ISSUE TITLE
A table with column name "window" could not be opened in SQLiteStudio

### ISSUE THREAD

**Issue by Andreas0707** [pawelsalawa/sqlitestudio#4685]
### Details
A table with column name "window" could not be opened in SQLiteStudio

### Steps to reproduce
create table if not exists test_table
(
	window integer
);

Try to open this table in SQLiteStudio.
No columns are displayed.
The table could not be opened.

### Operating system
Windows 10

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
Have you tried with SQLiteStudio 3.4.3 ?

**Comment by Andreas0707** [comment]
Hello,
i tried SQLiteStudio 3.4.3 now.
Its the same behaviour:
[14:15:19] Could not process the test_table table correctly. Unable to open a table window.
Best Regards

**Comment by pawelsalawa** [comment]
Okay. To be fixed. Thanks for reporting this!
