### ISSUE TITLE
Displaying wrong numbers

### ISSUE THREAD

**Issue by kkayal** [pawelsalawa/sqlitestudio#4690]
### Details
There are 3 bugs related to each other concerning very small numbers. It is partly about displaying a wrong value and partly about storing a wrong intermediate value in the editor, although no change has been made.

### Steps to reproduce
1. Create a blank datase and create the following table
CREATE TABLE foo (
    foo NUMERIC
);

2. Open the table and the "Data" tab
3. Insert a record and double click the "foo" field.
4. Insert the number `-1.7843738e-16`
5. Press ENTER
6.  **BUG 1**: You should now see `-0.0` instead of `-1.7843738e-16`. For my engineering and scientific purposes, this is a significant problem.
7. Right-click on the same field and click "Edit value in editor" in the context menu
8. Verify that the number is actually `-1.7843738e-16` and not `-0.0` as displayed in the table view
9. Double click on the filed again to pretend editing it. But, **DO NOT** type anything and **DO NOT" commit the record
10. Click somewhere outside the field to stop editing the field
11. **BUG 2**: Verify that the displayed number is now "0" and neither `-0.0` nor `-1.7843738e-16` as before
12. Right-click on the filed again
13. Right-click on the same field and click "Edit value in editor" in the context menu again
14. **BUG 3:** Verify that the number is zero and not `-1.7843738e-16` anymore, also in this editor, although we have not changed its value.
15. Edit the value again and insert the same number `-1.7843738e-16`
16. COMMIT the record
17. Close the window and re-open
18 Repeat the steps 9 to 14 to verify that the bugs 2 and 3 also happen although the record was stored in the database.

### Operating system
Windows 10

### SQLiteStudio version
3.4.3

**Comment by kkayal** [comment]
Sorry, the SQLiteStudio version is 3.4.3 and not 18.4.3

**Comment by kkayal** [comment]
After posting this report, I have realised that there is an option to display numbers in scientific notation. See ADDED: #4653 in release notes. After activating this option, the numbers look correct.

I think the correct display option should be the default. The option as discussed in issue #4653. Otherwise more people like me might think there is a big problem.

**Comment by pawelsalawa** [comment]
Scientific notation is generally less common in typical usage.

**Comment by pawelsalawa** [comment]
So if you enable this scientific notation - does it fix your problem?

**Comment by kkayal** [comment]
Yes, with this option selected, the problem is solved. I can only advise to make this option selected by default as I would consider displaying a small number as zero as a bug. When a user actively chooses it this way, then the user knows what he does and that would be his choice.

**Comment by pawelsalawa** [comment]
People usually don't deal with such small numbers. At the same time most people are familiar with decimal notation, rather than scientific. Yes, many people are still familiar with scientific and many deal with such small numbers, but still most of the users keep pretty basic numbers in their databases.

In the past the scientific notation (which was used out of the box) was reported by users as hard to use.
