### ISSUE TITLE
Replace the Ctrl+Backspace key combination for Rollback

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [pawelsalawa/sqlitestudio#4697]
### Details
Remove the Ctrl+Backspace key combination for the rollback operation and assign a different key combination.
Let Ctrl+Backspace delete whole words from the text field, like any other application 

1. Firefox, 
2. Notepad, 
3. Notepad++, 
4. Microsoft Word, 
5. Visual Studio, 
6. Outlook, 
7. Google Chrome, 
8. Opera, 
9. Arduino IDE, 
10. Visual Studio Code
11. Windows Command Prompt
12. Zoom
13. Winmerge
14. ...

### Steps to reproduce
Create a table which takes 20 arbitrary columns and a string field as the last column.
Add a new row to that table and fill out everything. 
When in the string column, make a typo in a word.
Press Ctrl+Backspace to delete the word, because your brain has hard-wired this.
Oops. All your input is gone.

This happened to me the 6th time today which made me upset enough to write this feature request. It's especially frustrating if you have edited several rows.

### Operating system
Windows. Not sure if Ctrl+Backspace is a Windows thing.
Maybe change it on Windows only, if it's not an issue on Linux.

### SQLiteStudio version
I'm using 3.3.3 if that matters.

**Comment by pawelsalawa** [comment]
I'll change default shortcut.

In the meantime, you can modify hotkeys in configuration.

**Comment by pawelsalawa** [comment]
I've changed the default hotkey to Esc.

I've also added a button to configuration dialog to hotkeys page, so that apart from clearing or changing the hotkey, users are now able to restore the original hotkey (SQLiteStudio's default). And yes, SQLiteStudio's default for rollback is now Esc.

While I've changed the default hotkey from Ctrl+Backspace to Esc, it will not change automatically for users who upgrade from older SQLiteStudio. It will be applied automatically only for new users, but old users can change the shortcut as they want (either to their own, or to SQLiteStudio's default).

**Comment by tuffnatty** [comment]
@pawelsalawa It seems to me, Esc is even easier to press by mistake, I would not make such a default for a destructive function.

**Comment by pawelsalawa** [comment]
Okay, but do you have a better candidate, that would be intuitive for such action?
Please keep in mind that many shortcuts are already occupied by the usual desktop hotkeys (`alt+backspace`, `ctrl+backspace` - the one I just changed from, `ctrl+esc`, and so on).

**Comment by thomasw-mitutoyo-ctl** [comment]
We close dialogs with Esc on Windows, we cancel stuff with Esc. I never confirm something with Esc. The Esc key is further away from other keys, since it has extra space. For now Esc looks like a good choice to me. I haven't tried it in production yet, though.

**Comment by tuffnatty** [comment]
@pawelsalawa I thought a little about it, and probably I would leave the default shortcut empty for this function. It's not something you do often, you can reach for the mouse in this rare case.

**Comment by tuffnatty** [comment]
I'm just thinking about non-technical-savvy users, and Rollback is one of the most dangerous (and useful) features in the app.

**Comment by pawelsalawa** [comment]
That's fair point. I'm thinking about alt+shift+backspace, as it seems to be available, at least on my Windows and it's somewhat similar to the previous combination. What do you think?

**Comment by tuffnatty** [comment]
Alt-Shift-Backspace sounds great!
