### ISSUE TITLE
FTS5 queries not working in v3.4.3

### ISSUE THREAD

**Issue by bijugv** [pawelsalawa/sqlitestudio#4701]
### Details
When trying to query using a FTS5 virtual table a syntax error is returned.
[21:51:41] Error while executing SQL query on database 'app_db': near ")": syntax error

The actual query does not have any ")" and the query works fine from sqlite command line tool and also from other ide (e.g dbeaver).

I have rolled back to SqliteStudio Version 3.4.0 which is working fine. 

### Steps to reproduce
1. create a FTS5 virtual table like CREATE VIRTUAL TABLE ft_info USING fts5(id, title, description, tags);
2. insert data 
3. try running a SQL SELECT connecting the virtual table with a base table joining with the same key. e.g
select * from books b join ft_info bi on b.id == bi.id where ft_info match 'humour* rose' ORDER BY bm25(ft_info) LIMIT 5;

even a simple query like SELECT * from ft_info; does not work

### Operating system
Windows 11

### SQLiteStudio version
v3.4.3

**Comment by pawelsalawa** [comment]
Possibly related to #4693
