### ISSUE TITLE
Db File dialog rejects read-only file

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#4707]
Db File dialog rejects read-only file, but user can still type path to file manually in Db File input, so it's an issue with File Dialog only.

It was discussed in #4706

**Comment by tuffnatty** [comment]
@pawelsalawa I have conducted some tests with regards to various functionality before and after this change:

| | Mac, Before | Mac, After | Gnome, Before | Gnome, After | Windows, Before | Windows, After |
| --- | --- | --- | --- | --- | --- | --- |
| #4705 (extra overwrite confirmation) | X | OK | OK | OK | ? | OK | 
| #4707 (rejects read-only file) | OK | OK | OK | OK | X | OK |
| Allows entering non-existing file | OK | (allows at least to choose a folder) | OK | Does NOT allow | OK | OK |

So, the change seemed to fix a problem appearing only in Windows (#4707) but introduced problems on Mac and Linux builds. When I add QFileDialog:DontUseNativeDialog option, all builds work fine both before and after the change, but we lose native GVFS/Recent files/Bookmarks support.

So probably I would suggest to switch from AcceptSave to AcceptOpen only on Windows until a more complex fix for #4705 is ready.

**Comment by pawelsalawa** [comment]
Let's continue in #4796
