### ISSUE TITLE
Can not set a trigger with "UPDATE OF" action in Mac

### ISSUE THREAD

**Issue by psantos9** [pawelsalawa/sqlitestudio#4715]
### Details
When creating a new trigger with the action "UPDATE OF", I would expect to see a modal with the table column names when I click on the "List of columns for UPDATE OF action" button. Instead, clicking on that button doesn't do nothing.
See the [video](https://user-images.githubusercontent.com/1428629/222967507-4a698950-ea25-491c-83fb-98c8c130e886.mov)

### Steps to reproduce
1. Create a new table with a field "updated_at" with INTEGER type.
1. Create new trigger for that table
2. Fill in the "Trigger name" with a random value
3. Set "When:" to AFTER
4. Set in the "Code:" section the following value: UPDATE tenant SET updated_at = unixepoch() WHERE id = NEW.id;
5. Set "Action:" to UPDATE OF
6. Notice that the button "list of columns for UPDATE OF action" gets an exclamation mark and does nothing when the user click on it.

### Operating system
MacO Ventura 13.1 (22C65)

### SQLiteStudio version
7.4.3

**Comment by pawelsalawa** [comment]
Yeah, the window should appear - that is what this button is for there. Maybe it's only MacOS bug, because it works on my Windows correctly. I will verify it.
