### ISSUE TITLE
Error executing query

### ISSUE THREAD

**Issue by mohrlex83** [pawelsalawa/sqlitestudio#4716]
### Details
Executing this query "SELECT [$$ClientBase].*, ((strftime('%Y', 'now') - strftime('%Y', [birthdate])) - (strftime('%m-%d', 'now') < strftime('%m-%d', [birthdate]))) AS [age], (SELECT GROUP_CONCAT([$$Telephone].[number], '; ') FROM [$$Telephone] WHERE [$$Telephone].[clientid]=[$$ClientBase].[id]) AS [phone], [$$PostalAddress].[address], [$$PostalAddress].[city], [$$PostalAddress].[province], [$$PostalAddress].[postalcode], [$$PostalAddress].[country] FROM [$$ClientBase] LEFT JOIN [$$PostalAddress] ON [$$ClientBase].[id]=[$$PostalAddress].[clientid] AND [$$PostalAddress].[principal] ORDER BY [$$ClientBase].[name]" throw an error

### Operating system
Windows

### SQLiteStudio version
3.4.2 and above

**Comment by pawelsalawa** [comment]
Probably related to #4676 (maybe even a duplicate - to be checked).
