### ISSUE TITLE
Wrong behaviour of window functions

### ISSUE THREAD

**Issue by renared** [pawelsalawa/sqlitestudio#4721]
### Steps to reproduce
```
SELECT tid, iter, MIN(avg_loss) AS min_avg_loss
FROM (
  SELECT m.tid, m.iter, AVG(m.loss) OVER (PARTITION BY m.tid ORDER BY m.iter ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS avg_loss
  FROM metric m
  WHERE m.iter != 0
)
GROUP BY tid
ORDER BY min_avg_loss LIMIT 5
```
yields this error:
`[16:26:40] Error while executing SQL query on database 'nnng': near ")": syntax error`

replacing the window by `PARTITION BY m.tid ORDER BY m.iter ROWS BETWEEN 3 PRECEDING AND 3 FOLLOWING` gives no error, but yields wrong results

(I compared with DB Browser for SQLite v3.12.2)

### Operating system
Windows 10 19043.2130

### SQLiteStudio version
v3.4.3

**Comment by pawelsalawa** [comment]
Should be solved now together with #4676
