### ISSUE TITLE
Latest nightly build does not run on Windows 11

### ISSUE THREAD

**Issue by balajiramanathan** [pawelsalawa/sqlitestudio#4743]
### Details
The latest build from the github page does not run on Windows 11.  A task appears on the task manager, but no window is created, and it is not possible to use the software.

### Steps to reproduce
Install latest Windows 64-bit build on Windows 11 home computer, and try to run the software by double-clicking on sqlitestudio.exe.

### Operating system
Windows 11 Home, 64-bit.

### SQLiteStudio version
3.4.4

**Comment by balajiramanathan** [comment]
As a follow-up I can confirm that the build of last week seems to work fine.  So, release build #295 works fine, but release build #296 does not.  The release build #'s are directly from the github site, not from inside SQLiteStudio.  Thank you.

**Comment by pawelsalawa** [comment]
Indeed there is a problem with this build. I will look into it.

**Comment by pawelsalawa** [comment]
It looks that whatever the issue was, it was temporary and it looks to be good now. I've re-built it from master a moment ago and this one runs for me: https://github.com/pawelsalawa/sqlitestudio/actions/runs/4612466048 (while the previous one did not - just like for you).

**Comment by pawelsalawa** [comment]
I will wait up to a day for your confirmation before finally closing this. Then I guess I will prepare 3.4.4 release.

**Comment by balajiramanathan** [comment]
Yes, confirmed that this build works.  Thanks.
