### ISSUE TITLE
Displaying wrong error when table not found in DB.

### ISSUE THREAD

**Issue by jatindeotale** [pawelsalawa/sqlitestudio#4744]
### Details
Displaying wrong error if table not found in DB. It is showing message "Error while executing SQL query on database 'gorilla': near ")": syntax error".  Instead of this error it should be display like "Error while executing SQL query on database 'gorilla': no such table: dummy_xyz".
Please fixed this error.

### SQLiteStudio version
 Version : 3.4.3

**Comment by pawelsalawa** [comment]
This is a common bug, fixed for 3.4.4 together with #4676
