### ISSUE TITLE
Replace function Error

### ISSUE THREAD

**Issue by djdanskoyz** [pawelsalawa/sqlitestudio#4748]
![replace](https://user-images.githubusercontent.com/34094886/229993234-5bd0e43c-d4fe-4b6c-8161-ac2fba45e256.png)
### Details
I'm getting error from replace function "Error while executing SQL query on database near  " )"

### Operating system
window 10

### SQLiteStudio version
v3.4.3

**Comment by pawelsalawa** [comment]
Duplicate of #4693
