### ISSUE TITLE
Database connection details

### ISSUE THREAD

**Issue by jaapvandervelde** [pawelsalawa/sqlitestudio#4763]
### Details
SQLiteStudio remembers previous connections when reopened. However, the user may not remember the details. There's currently no way to identify what a connection is actually connected to, other than "open file's directory", which can still be ambiguous.

A simple "Properties" option when rightclicking a database connection, with information on what it connects to, and perhaps some additional info like what the connection status is and when it was last connected to would be great. But the pimary need is a clear indication of exactly what the connection connects to (file or otherwise).

**Comment by pawelsalawa** [comment]
It's already there. You have 2 options:

1) Edit database connection (which would be the "Properties" you mentioned):
![image](https://user-images.githubusercontent.com/481846/231961978-0c8a4a02-e4a8-4d97-9a0c-507ebeeacf6b.png)

![image](https://user-images.githubusercontent.com/481846/231962002-e820ec24-a72f-4a56-bc7b-173fc3ec8708.png)

2) Hold your mouse over a database and shortly a popup will appear with db details:
![image](https://user-images.githubusercontent.com/481846/231962087-408acdf1-6f4b-4aec-a388-77996401feb1.png)

**Comment by jaapvandervelde** [comment]
Ah, thanks for the reply. I hadn't noticed the popup, apparently I never hover long enough for it to show up and it hadn't occurred to me to even look for that. I just went straight to click or right-clicking on it. This does work for me as well though.

However, I should have noticed it in the Edit database dialog, thanks for taking the time to explicitly point that out. It's not where I was looking for it, but it certainly makes sense and I must have overlooked it when looking around the various screens for this value.
