### ISSUE TITLE
SQL Editor - Displaying Result

### ISSUE THREAD

**Issue by hisenthil** [pawelsalawa/sqlitestudio#4767]
When we execute a query in SQL Editor, results are retrieved and shown as Grid. But there is no option to auto adjust the width of the columns. We have to manually adjust the column width and that too has to be repeated for each column, which is a time consuming process. Please consider auto adjust (e.g., to Fit with data), so that all columns will get auto adjust their width, based on column data. If this is not possible, at least, double click on column connecting place can adjust the width for that column alone.

**Comment by pawelsalawa** [comment]
Isn't this what you're looking for?

![image](https://user-images.githubusercontent.com/481846/232837412-47120b2a-b52e-46fe-832f-ed9b5ae9e26b.png)

**Comment by hisenthil** [comment]
Yess.. This is what i was looking for to manage it now. Thanks for highlighting.
