### ISSUE TITLE
Missing close/minimize icons on Windows

### ISSUE THREAD

**Issue by bpierson** [pawelsalawa/sqlitestudio#4789]
On Windows, icons to minimize/close windows are missing. Only with **windowsvista** theme, so not a huge deal.
![sqlitestudio_missing_icons](https://github.com/pawelsalawa/sqlitestudio/assets/6351149/375c253b-eb3b-4150-96e4-ce0489dcd6ec)

**Comment by pawelsalawa** [comment]
As stated in https://github.com/pawelsalawa/sqlitestudio/issues/3995#issuecomment-790616167 this issue is known in Qt and is resolved in Qt 6.4, so it will be resolved when SQLiteStudio upgrades to it (in SQLiteStudio 3.5.0).

At the same time, I'm marking this a s a duplicate of #3995
