### ISSUE TITLE
Db file dialog issues

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#4796]
@pawelsalawa I have conducted some tests with regards to various functionality before and after this change:

| | Mac, Before | Mac, After | Gnome, Before | Gnome, After | Windows, Before | Windows, After |
| --- | --- | --- | --- | --- | --- | --- |
| #4705 (extra overwrite confirmation) | X | OK | OK | OK | ? | OK | 
| #4707 (rejects read-only file) | OK | OK | OK | OK | X | OK |
| Allows entering non-existing file | OK | (allows at least to choose a folder) | OK | Does NOT allow | OK | OK |

So, the change seemed to fix a problem appearing only in Windows (#4707) but introduced problems on Mac and Linux builds. When I add QFileDialog:DontUseNativeDialog option, all builds work fine both before and after the change, but we lose native GVFS/Recent files/Bookmarks support.

So probably I would suggest to switch from AcceptSave to AcceptOpen only on Windows until a more complex fix for #4705 is ready.

_Originally posted by @tuffnatty in https://github.com/pawelsalawa/sqlitestudio/issues/4707#issuecomment-1567067952_

**Comment by pawelsalawa** [comment]
@tuffnatty  I'm leaning towards using Non-Native dialog on all platforms. It was actually my intention from the very beginning (I thought it was done like it already...). Yes, it drops some of the platform-specific features, as you mentioned, but I'm ready to sacrifice them in exchange for consistent and predictable behavior. What do you think about it?

**Comment by tuffnatty** [comment]
@pawelsalawa I find the native file dialog features (the ability to consistently find files in favorite places) really useful. I do use some applications where I do have to maintain a separate favorite places list for a non-native file dialog. It's not very hard but a bit annoying. But I have heard some people have a real aversion to non-native file dialogs. As it is, basically it's both consistent (with the rest of the system) and usable, just not under Gnome.

**Comment by pawelsalawa** [comment]
Got you. Okay, this issue is here to stay and I will work on it when the time comes.
