### ISSUE TITLE
Executing "Vacuum" on a *.sqlite DB file erases ALL content, not just invalid data

### ISSUE THREAD

**Issue by sveakul** [pawelsalawa/sqlitestudio#4816]
### Details
Problem in title occurs when copying a *.sqlite DB file elsewhere, then attempting to vacuum to remove deleted data content;  this ends up removing ALL the data instead of just the invalid content.

### Steps to reproduce
Load DB in sqlitestudio ("metadb.sqlite"), connect to it, and choose "vacuum" from the Database menu.  Re-save DB file as metadb-1.sqlite, check contents using Notepad and all content (music file metadata) has been removed except "VACUUM;" --not only the past "deleted" data.
### Operating system
Windows 10 x64 22H2

### SQLiteStudio version
3.4.4

**Comment by pawelsalawa** [comment]
What do you mean by "Re-save DB file"? Where do you "re-save" it? In what application?

**Comment by pawelsalawa** [comment]
Ohhh... I know. You press Ctrl+S and you think you are saving this database to a file. No. You are saving contents of your SQL Editor window.

If you want to copy your database to another file, just go to your file manager and just copy the file.
