### ISSUE TITLE
Error running logname : logname: no login name The application will exit now.

### ISSUE THREAD

**Issue by avma** [pawelsalawa/sqlitestudio#4828]
### Details
this message pops up after running the file: 'SQLiteStudio-3.4.4-linux-x64-installer.run' at the very end of the setup process.
this happens both as root or normal user privileges.
### Steps to reproduce
run the file.

### Operating system
OS: Linux Mint 21.1 x86_64
Kernel: 5.15.0-76-generic
DE: Cinnamon 5.6.8

### SQLiteStudio version
3.4.4
![image](https://github.com/pawelsalawa/sqlitestudio/assets/7680483/21e9548b-6d6e-44bf-8b14-85031815dd41)

![image](https://github.com/pawelsalawa/sqlitestudio/assets/7680483/acfdb2c9-0b1e-41c2-9be2-fc1472ce0f28)

**Comment by avma** [comment]
Thanks, I did not mention this in the previous post, but  i'm using the portable version which works great.

**Comment by avma** [comment]
the only problem with this method is i can't review my translation on the fly...

**Comment by pawelsalawa** [comment]
You can. See https://github.com/pawelsalawa/sqlitestudio/wiki/Language_Translations - go to the bottom of page, see section "Testing your translations". In short:
> In SQLiteStudio directory create (if doesn't exist) directory called "translations" or "msg" (either one will work). Copy *.qm files to this created directory.

**Comment by avma** [comment]
i tried the above but could not make it work with the portable installation...

**Comment by pawelsalawa** [comment]
Can you show the directory structure that you're trying?

**Comment by pawelsalawa** [comment]
How about if you use different language code for the file name? Make up some inexistent one. At the moment I don't remember exactly how that works, but on the mentioned wiki page I did mention to use non-conflicting file name for testing in-dev translations.

**Comment by avma** [comment]
ok let me play with it a bit see how it goes...

**Comment by pawelsalawa** [comment]
I mean, the core name of the file (i.e. `coreSQLiteStudio_` has to remain, but the language code might be changed to some inexistent language code.

**Comment by pawelsalawa** [comment]
Okay, I did tests by myself and I was able to preview translations without any fake language codes. I have added `guiSQLiteStudio_pl_PL.qm` file to the `translations` directory and picked this language in the configuration - it works as expected. I can see my (modified for testing) translations.

You can debug if your custom qm file is actually being loaded by running SQLiteStudio with `-d` command line option:
```
./sqlitestudio -d --debug-stdout
```
Then in this command line you should see debug logs. At the very beginning you will see what qm files are being loaded. For example:
```
[22:47:05.159] DEBUG:    Loaded: ":/msg/translations/coreSQLiteStudio_pl_PL.qm"
[22:47:05.160] DEBUG:    Loaded: ":/msg/translations/guiSQLiteStudio_pl_PL.qm"
[22:47:05.161] DEBUG:    Loaded: ":/msg/translations/sqlitestudio_pl_PL.qm"
```
The example above tells us, that no custom file was used. But if I put my custom qm file to translations directory, I get:
```
[22:56:37.838] DEBUG:    Loaded: ":/msg/translations/coreSQLiteStudio_pl_PL.qm"
[22:56:37.838] DEBUG:    Loaded: "translations/guiSQLiteStudio_pl_PL.qm"
[22:56:37.839] DEBUG:    Loaded: ":/msg/translations/sqlitestudio_pl_PL.qm"
```
(note, that it loads only qm files for currently configured language)

**Comment by avma** [comment]
strange... i'm getting the same more or less:
~/SQLiteStudio  ./sqlitestudio -d --debug-stdout   ✔  at 16:54:18 
[16:54:22.968] DEBUG:    Using configuration directory: /home/avi/.config/SalSoft/SQLiteStudio
[16:54:22.969] DEBUG:    Loaded: "translations/coreSQLiteStudio_he_IL.qm"
[16:54:22.970] DEBUG:    Loaded: ":/msg/translations/guiSQLiteStudio_he_IL.qm"
[16:54:22.971] DEBUG:    Loaded: ":/msg/translations/sqlitestudio_he_IL.qm"

I also  downloaded the latest coreSQLiteStudio_he_IL.ts compiled it to *.qm but what i'm seeing is definitely not the recent work.

**Comment by pawelsalawa** [comment]
Are you sure you are comparing correct translations on the UI? I mean that the "coreSQLiteStudio" part are messages that you usually don't see immediately on UI. They can appear after some actions (for example results of query execution, results of importing/exporting, etc, etc), but better to test if this works is to try with "guiSQLiteStudio", as most of messages there are visible on UI immediately, because it often contains labels, window titles, etc.

**Comment by tuffnatty** [comment]
The original installer issue seems to be already fixed by https://github.com/pawelsalawa/sqlitestudio/commit/5c28dd8266e483df6435ec69d0941f6d57543632 .

**Comment by pawelsalawa** [comment]
Correct. Closing.

**Comment by luizcarluz** [comment]
I had same problem

**Comment by cosme12** [comment]
This bug is back again. Can't install on linux mint

**Comment by pawelsalawa** [comment]
What SQLiteStudio version? Where was it downloaded from?

**Comment by cosme12** [comment]
> What SQLiteStudio version? Where was it downloaded from?

Downloaded from website. 
Version: SQLiteStudio-3.4.4-linux-x64-installer.run
Using GUI to install. Portable version works great.

**Comment by pawelsalawa** [comment]
The fix mentioned by @tuffnatty above was committed on April 18th 2023, while version 3.4.4 was released on April 7th, so the fix is available only in the recent development branch.

By the way, @tuffnatty  question to you - do you have idea why Linux builds recently fail? It looks like Python plugin compilation failure, but it's weird, since no changes were made there, isn't it?
