### ISSUE TITLE
Query results not editable when select statement  includes rowid

### ISSUE THREAD

**Issue by audiomuze** [pawelsalawa/sqlitestudio#4842]
### Details
Running the following query against a table yields the correct results but none of the fields are editable:
```
SELECT rowid,
       title,
       subtitle,
       live
  FROM alib
 WHERE subtitle IS NOT NULL
 ORDER BY subtitle;
```

Attempting to edit a field yields:
```
[22:55:52] Cannot edit this cell. Details: The query execution mechanism had problems with extracting ROWID's properly. This might be a bug in the application. You may want to report this.
```
It's the inclusion of rowid in the query that gives rise to the issue.  I'd expect all but rowid to be editable inline.

### Steps to reproduce
Run a similar query on any table and browse the results

### Operating system
Arch Linux 6.4.8-arch1-1

### SQLiteStudio version
3.4.4

**Comment by pawelsalawa** [comment]
Is the `alib` a view, or a table?

**Comment by audiomuze** [comment]
> Is the `alib` a view, or a table?

It's a table.

**Comment by pawelsalawa** [comment]
Oh, only now I noticed you try to edit rowid. No, `ROWID` value is immutable. You cannot edit it.

**Comment by audiomuze** [comment]
> Oh, only now I noticed you try to edit rowid. No, `ROWID` value is immutable. You cannot edit it.

I wasn't trying to edit ```ROWID```, I know it's an internal immutable.   Because its included in the query I'm unable to edit any of the other fields returned by the SELECT statement..

As I said earlier:

> It's the inclusion of rowid in the query that gives rise to the issue. I'd expect all but rowid to be editable inline.

**Comment by pawelsalawa** [comment]
Sorry for my misunderstanding. Again, I misread your statement.

Yes, you are right and it's a bug to fix.
