### ISSUE TITLE
Impossible to select ROWID when specify dbName in FROM statement

### ISSUE THREAD

**Issue by EugeneAsti** [pawelsalawa/sqlitestudio#4843]
### Details
Impossible to select ROWID when specify dbName in FROM statement.
When I want to get ROWID and specify DBName.Table, a get Error:
- Error while executing SQL query on database 'TestDb': no such table: TestDb.TbVars
But, if I remove DB name from query or remove ROWID, it will works.
I need to specify dbName because of my query selects data from different databases

I will be happy if you fix this issue! :)

### Steps to reproduce
For example this query throws error:
SELECT ROWID, fName FROM TestDb.TbVars

### Operating system
Windows 10

### SQLiteStudio version
3.4.4

**Comment by pawelsalawa** [comment]
I've just tried this and it works - it is most likely fixed together with #4842, because it was somewhat related.
