### ISSUE TITLE
Can't copy view to another database

### ISSUE THREAD

**Issue by JrgMyr** [pawelsalawa/sqlitestudio#4844]
When copying a view object from one database to another database, which is generally supported by the GUI, SQLiteStudio throws an error message saying the name would already exist in the target database which is not correct.

This behaviour shows both when "dragging and dropping" with a mouse as well as with regular [Ctrl-C] [Ctrl-V] on the keyboard. SQLiteStudio is version 3.4.4 on Windows 10 and Linux Ubuntu.

Anybody else seeing this behaviour?

**Comment by pawelsalawa** [comment]
Yes, there seems to be a bug related to this. I'll fix it.

In the meantime, fortunately, you can copy view relatively easily, as you just need to go to DDL tab of the view, copy it and execute it on the target database.
