### ISSUE TITLE
Executing SQL script from file doesnt create triggers

### ISSUE THREAD

**Issue by phidrho** [pawelsalawa/sqlitestudio#4872]
### Details
When I execute script via GUI everything works OK and triggers get created.
But when I run same script with "Execute SQL script from file" then triggers don't get created and software doesn't report any error. My script uses custom functions inside triggers from SpatiaLite project, but this module is loaded.
When I used regular, built-in functions inside triggers I did not see this problem happening.

![image](https://github.com/pawelsalawa/sqlitestudio/assets/1849293/ce3e4c2c-1e8d-4b38-b624-a297b07b6bd3)
![image](https://github.com/pawelsalawa/sqlitestudio/assets/1849293/209cf798-3409-456e-a84e-2aedb3a71d72)
![image](https://github.com/pawelsalawa/sqlitestudio/assets/1849293/9d802793-2d03-4c57-a12e-2977e37894f2)

### Steps to reproduce
You can download sample DB and script in ZIP:
[sqlitestudiotriggertest.zip](https://github.com/pawelsalawa/sqlitestudio/files/12588366/sqlitestudiotriggertest.zip)

### Operating system
Windows 10

### SQLiteStudio version
3.4.2

**Comment by getopian** [comment]
still the problem with 3.4.4
