### ISSUE TITLE
New file dialog does not allow to create a nonexisting file (database) in macOS

### ISSUE THREAD

**Issue by lallulli** [pawelsalawa/sqlitestudio#4886]
### Details
In macOS, the new combined file dialog does not allow to enter the name of a nonexisting file for DB creation. Instead, it allows to select a folder.

Thus, in order to create a new database the user has to:
1. Select **Database** > **Add a database**
2. Clic on the button with the icon of a yellow folder
3. Select a __folder__ (the bug lies here: in macOS it is not possible to enter the name of a new __file__)
4. Back in the "Database" dialog, append `/DATABASE_NAME.db` to the path in the __File__ field

### Operating system
macOS

### SQLiteStudio version
SQLiteStudio 3.4.4

**Comment by tuffnatty** [comment]
Dplicate of #4796
