### ISSUE TITLE
Export of database in SQL lists table in wrong order for relationships/FOREIGN KEY

### ISSUE THREAD

**Issue by guyleonis** [pawelsalawa/sqlitestudio#4897]
### Details
When using 'Database/Export Database' function from the GUI and selecting the SQL format in the dialog box, tables are exported alphabetically. This is not correct when relationships (aka FOREIGN KEY) are set between tables. In such a case, the target table should be created before the source table where the FOREIGN KEY instruction is given.

### Steps to reproduce
[test.zip](https://github.com/pawelsalawa/sqlitestudio/files/13348600/test.zip)
In the attached file you have both the database and the SQL Export. In SQL file, e.g. 'distribution locations' table is created before 'files' table. As such, the relationship could not be created. Even more, the 'files' table is dropped.
Other inversions are existing in the SQL file ('auxiliary data' before 'auxiliary data types', ...).

### Operating system
Windows 11 Family / Version 22H2 / Build 22621.2428

### SQLiteStudio version
V3.4.4 (SQLite 3.41.2)

**Comment by pawelsalawa** [comment]
Order of `CREATE TABLE` doesn't affect SQLite foreign keys until the moment when you insert/modify data in these tables. Foreign keys are validated only upon data manipulation. See SQLite docs: https://sqlite.org/foreignkeys.html#fk_schemacommands

> A CREATE TABLE command operates the same whether or not foreign key constraints are enabled. The parent key definitions of foreign key constraints are not checked when a table is created. There is nothing stopping the user from creating a foreign key definition that refers to a parent table that does not exist, or to parent key columns that do not exist or are not collectively bound by a PRIMARY KEY or UNIQUE constraint.

SQLiteStudio exports all tables, so eventually all your tables will be created and data insertions are done only after tables are created, so at that moment all tables exist and foreign keys will be satisfied.

Finally, your SQL from zip file is correctly executed by SQLite (and thus SQLiteStudio too), so I see no reason to complain.
