### ISSUE TITLE
COde nippet for user defined function - Bit field extraction

### ISSUE THREAD

**Issue by rgarnett1955** [pawelsalawa/sqlitestudio#4945]
### Details
Just a code snippet to extract bit fields from an integer  using js. Something that others might find useful. You could add it to the function examples page:

//var bitNo = arguments[0];
//var value = arguments[1];
//var mask = 1;

//return mask << bitNo & value 

return ((1 << arguments[0]) & arguments[1]) >>  arguments[0]

Typical usage:

select
getBit(0, TriggerType) as Max1,
...

**Comment by pawelsalawa** [comment]
Thanks! Added:
https://github.com/pawelsalawa/sqlitestudio/wiki/Qt_script_getbit
https://github.com/pawelsalawa/sqlitestudio/wiki/Scripts_repository
