### ISSUE TITLE
Sql lite studio

### ISSUE THREAD

**Issue by arlatulasi** [pawelsalawa/sqlitestudio#4946]
### Details
Here you describe your problem details, or proposal for enhancement.
When I am selecting query status it maximised to extreme and I am unable to minimise it  I have tried all the keys command - these keys are working for all the windows except the status window in the sql lite studio
### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment]
Invalid report
