### ISSUE TITLE
Tree node disappeared if drag it to query editor

### ISSUE THREAD

**Issue by victor-wiki** [pawelsalawa/sqlitestudio#4952]
### Details
The table tree node disappeared if drag it to query editor.

### Steps to reproduce
Open a new query editor and choose a table tree node from the object navigator, then drag it to the query editor. The selected tree node disappeared after dropped. It needs to refresh the navigator to show the table tree node. I just want to copy the table name to the query editor.

### Operating system
windows 10

### SQLiteStudio version
3.4.0

**Comment by pawelsalawa** [comment]
This is already fixed in 3.4.4 (just verified it).

**Comment by victor-wiki** [comment]
Yes, that's ok, thanks a lot!
