### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by faelp22** [pawelsalawa/sqlitestudio#4958]
I'm using Ubuntu 20.04 AMD64 and I got this error.

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Just to record the solution in case someone else has the same problem.

I just needed to install: sudo apt-get install libxcb-xinerama0

And with that he solved the problem.

**Comment by tuffnatty** [comment]
Thanks! The issue is already solved in the weekly builds.
