### ISSUE TITLE
custom COLLATE

### ISSUE THREAD

**Issue by githubuser181226** [pawelsalawa/sqlitestudio#4974]
Hi.

By default SQLite sorting doesn't account for accented letters (ie. Polish letters: Ł, Ś, Ź..,) and if a string begins with one, ORDER BY ASC clause always puts those at the very end, which is a game breaker for me.

Is it possible to create a custom function to account for accented letters to use it as a COLLATE method and with the custom sorting functionality of the UI (ie. double-clicking on column header)?

So far I've only managed to create a simple javascript function which replaces all the accented letters in a string with ASCII non-accented equivalents, which then I can use in ORDER BY clause, but although it is somewhat helpful (values starting with accented letters are no longer at the end of the sorted list), it is far from optimal, because sorting still isn't correct and I tried using the function in the COLLATE clause, but it doesn't work.

And I can't find any documentation showing how to create javascript custom collate methods, or if that is even possible. 

I'm using SQLiteStudio in Windows as a standalone DB manager for storing and managing data.

Perhaps there is an extension already to fix my issue.
Thank you in advance.

**Comment by tuffnatty** [comment]
Have you already tried the icu extension and the Collation editor menu option?

**Comment by githubuser181226** [comment]
> Have you already tried the icu extension and the Collation editor menu option?

Hi. Thank you for you reply.

I have ICU extension and I don't know how I missed the Collation Editor in the menus before.
Regardless, I still can't understand how to use it. Documenation lacks any clear explanation, it mentions "Collation Editor" only once and tells nothing on how you actually implement custom collation. Are there any examples?

Below is my NoAccents function which replaces accented Polish characters with Latin non-accented equivalents.
How do I implent a custom collation based on that?

`var r = arg1.toLowerCase();
r = r.replace("ą","a~");
r = r.replace("ć","c~");
r = r.replace("ę","e~");
r = r.replace("ł","l~");
r = r.replace("ń","n~");
r = r.replace("ó","o~");
r = r.replace("ś","s~");
r = r.replace("ż","z~");
r = r.replace("ź","z~");
return r;
`

**Comment by githubuser181226** [comment]
> Have you already tried the icu extension and the Collation editor menu option?

Hi. Thank you for you reply.

I have ICU extension installed and and have Collation Editor in the menus.
The documenation lacks clear explanation on how to use it, showing no working examples. In the end I gave up.

Thankfully readme to ICU extension mentioned icu_load_collation function, so I started SQL editor and ran:
```
SELECT icu_load_collation('pl_PL', 'POLSKI');
```
which created new collation named _POLSKI_ which I then used in my tables, and voila - I have proper sorting, both when using UI custom sort and with ORDER BY.

However, if I close the program _POLSKI_ collation gets deleted and upon restarting I get and error telling me about missing _POLSKI_ collation, meaning I have to run the above SQL command again.

Is there a way to make it persistent or to run that command automatically when I open SQLite Studio?

Please, advise.
Thank you.

**Comment by tuffnatty** [comment]
> Is there a way to make a collation created with icu_load_collation persistent

No.

> or to auto-execute SQL commands on program startup?

I don't think it's supported.

Probably in your simple case a simple JavaScript collation definition would be enough (but probably much slower than ICU):
```
return arguments[0].localeCompare(arguments[1], 'pl')
```

**Comment by pawelsalawa** [comment]
I think you may try using WxSQLite3 plugin for the database connection and then add the `SELECT icu_load_collation('pl_PL', 'POLSKI');` to initialization/configuration SQL, while keeping the "password" empty, to avoid encrypting with WxSQLite3, somthing like this:
![image](https://github.com/pawelsalawa/sqlitestudio/assets/481846/2042426d-b2aa-4f92-b259-2cc361d47127)

**Comment by tuffnatty** [comment]
The WxSqlite initialization code trick does not help, because extensions are loaded only after this SQL is executed (and the unknown function errors are being ignored). I would propose to move extension loading above initAfterOpen() call in AbstractDb::openAndSetup(), and to add an initialization SQL option to the standard SQLite driver.
