### ISSUE TITLE
Build breaks on arm64: error: unsupported option '-msse4.1' for target 'aarch64-unknown-freebsd15.0'

### ISSUE THREAD

**Issue by yurivict** [pawelsalawa/sqlitestudio#4981]
### Details
See [log](https://pkg-status.freebsd.org/ampere2/data/main-arm64-default/p5a022ef6a46f_scd4bd9750c1/logs/sqlitestudio-3.4.4_1.log)

Plugins/DbSqliteWx/DbSqliteWx.pro is a culprit.

Version: 3.4.4
clang-19
FreeBSD 15

**Comment by tuffnatty** [comment]
Closing as fixed by #4999.
