### ISSUE TITLE
Build fails on non-Intel architectures due to SIMD flags -msse4.1 -msse4.2 -maes

### ISSUE THREAD

**Issue by yurivict** [pawelsalawa/sqlitestudio#4999]
See the [log](https://pkg-status.freebsd.org/ampere2/data/main-arm64-default/p7ea570788d69_s13a51233e4c/logs/sqlitestudio-3.4.4_2.log).

The line "QMAKE_CFLAGS += -msse4.1 -msse4.2 -maes" in the file Plugins/DbSqliteWx/DbSqliteWx.pro is causing this.

Version: 3.4.4
FreeBSD 14.1

**Comment by tuffnatty** [comment]
A duplicate of #4981.
