### ISSUE TITLE
File chooser cannot select a file with no extension

### ISSUE THREAD

**Issue by sotel** [pawelsalawa/sqlitestudio#5021]
### Details
Goal: Open the SQLITE file from _Vivaldi Browser_ named "Web Data" from inside the settings folder.

The file "WEB data" contains datas about the search engines, used e-mail and web adresses etc. It has no extension like ".db" or ".sqlite" or an other. But I can open it with an other tool without problems. Only SQLITEstudio is not able to open it because it has no extension.  

### Steps to reproduce
Create an SQLite file and save it without extension. If this file isn't known be SQLiteStudio you will not have any posibility to open it again.

Use from the **menu bar** the first entry "Database" und then choose "Add Database".
You can navigate throug the file system to Vivaldis data folder and you will not find the file "Web Data".
Please see this picture: 
![SQLiteStudio_2024-07-23](https://github.com/user-attachments/assets/0a02a00a-d11a-452a-ab38-bc5991fd3483)

### Operating system
(Copy from Windows settings / system using the button "copy":)

Gerätename	xxxxxxxxxxxxxxxxxxxxxxxxxxx
Vollständiger Gerätename	xxxxxxxxxxxxxxxxxxxxxxxxxxx
Prozessor	Intel(R) Core(TM) i5-3360M CPU @ 2.80GHz   2.80 GHz
Installierter RAM	4,00 GB (3,87 GB verwendbar)
Geräte-ID	B44F1E2A-B1F0-41F6-BEB8-CA7513C4370A
Produkt-ID	00330-71231-26411-AAOEM
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor
Stift- und Toucheingabe	Für diese Anzeige ist keine Stift- oder Toucheingabe verfügbar.

### SQLiteStudio version
SQLite Studio 3.4.4 for windows 64 bit

**Comment by pawelsalawa** [comment]
So.. Have you tried to switch filtering to "All files"?
![image](https://github.com/user-attachments/assets/fc2c1f3e-567c-4aaa-b46f-ddc9d5a635e8)

**Comment by sotel** [comment]
Hi Pawel!

Uuups, yes this is working!
This was my fault - I didn't had in mind to set it to "all files" which is obvious to use!

You may want to close this report / ticket.
