### ISSUE TITLE
spurios error in extension manager

### ISSUE THREAD

**Issue by njamescouk** [pawelsalawa/sqlitestudio#5029]
### Details
I have an sqlite extension dll that loads correctly with the sqlite3 command line program. Attempting to load this dll via extension manager results in a red dot and the pop up saying the specified module could not be found.

### Steps to reproduce
As above

### Operating system
Windows 7

### SQLiteStudio version
3.4.4

**Comment by pawelsalawa** [comment]
Are the extension binary compliant with your SQLiteStudio version? I mean is the extension binary of ix64 architecture? It may be you have 32-bit `sqlite3.exe` and loading successfully 32-bit extension there, while it's not loading in SQLiteStudio, cause it's 64-bit.

**Comment by njamescouk** [comment]
ok thanks, will check that out when I get time.

**Comment by njamescouk** [comment]
problem solved, thank you.
