### ISSUE TITLE
copie les tables  dune base de données A vers les tables d'une base de données B

### ISSUE THREAD

**Issue by fanymodeste25** [pawelsalawa/sqlitestudio#5031]
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment]
Translation of the title is:
> copies tables from database A to tables from database B

It does not make sense. I'm closing it as invalid report. If you want to provide more details, please comment here and I will reopen if it's feasible.
