### ISSUE TITLE
bug in filter

### ISSUE THREAD

**Issue by Eyderoe** [pawelsalawa/sqlitestudio#5065]
after filter, true become real true
![image](https://github.com/user-attachments/assets/7d5e6d3b-2cc8-41f4-976c-12b7e35798d3)
![image](https://github.com/user-attachments/assets/f6d21de3-4a48-47ea-a414-37da5271062d)

**Comment by Eyderoe** [comment]
the raw correct data is 17 197 17 197 17 197
after filter become 1 1 1 1 1 1 (column name is "true")
and wonderfully if the column name is "false"
after filter data will become 0 0 0 0 0 0
![image](https://github.com/user-attachments/assets/7050a0e5-c437-4caf-9fdc-e293ca168298)

**Comment by pawelsalawa** [comment]
Oh, I see. Yeah, it seems that during filtering the column names `true` and `false` aren't correctly quoted in subquery by SQLiteStudio, thus returning interpreted integer value of logical value true/false. Indeed this is a bug.

**Comment by Eyderoe** [comment]
yep thanks for your effort
