### ISSUE TITLE
can supprt visual studio build 

### ISSUE THREAD

**Issue by eurake** [pawelsalawa/sqlitestudio#5067]
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by aleroldan156** [comment]
I think this will help you.

https://bit.ly/4eugCty

you may need to install the c compiler
