### ISSUE TITLE
Uncommited structure modification when tab change

### ISSUE THREAD

**Issue by marcpley** [pawelsalawa/sqlitestudio#5077]
### Details
This don't work  when clicking on "Go back to structure tab" :
![Capture d’écran du 2024-10-27 05-44-48](https://github.com/user-attachments/assets/322f08bf-11d7-4639-9e44-0dbf2c85a380)
if "Place data tab as first place" is set in config:
![Capture d’écran du 2024-10-27 05-50-10](https://github.com/user-attachments/assets/83db3751-3218-4211-badc-074675e35248)

### Steps to reproduce
Modify table structure and try to go to data tab before commit the structure modification.

**Comment by marcpley** [comment]
Bug-fix proposal :
In
../guiSQLiteStudio/windows/tablewindow.cpp
line 1345
`ui->tabWidget->setCurrentIndex(0);`
add that before
```
            if (CFG_UI.General.DataTabAsFirstInTables.get())
                ui->tabWidget->setCurrentIndex(1);
            else
```

In
../guiSQLiteStudio/windows/viewwindow.cpp
line 622
`ui->tabWidget->setCurrentIndex(0);`
add that before
```
                if (CFG_UI.General.DataTabAsFirstInViews.get())
                    ui->tabWidget->setCurrentIndex(1);
                else
```

**Comment by pawelsalawa** [comment]
Thank you! Just applied.

P.S. You can always attach diff files (`git diff`) to posts - it will be easier/quicker for you.

**Comment by marcpley** [comment]
Bug-fix proposal :
In
../guiSQLiteStudio/windows/tablewindow.cpp
line 1345
```
            if (res == 1)
            {
                commitStructure(true);
                ui->tabWidget->setCurrentIndex(CFG_UI.General.DataTabAsFirstInTables.get() ? 0 : 1);
                ui->dataView->refreshData();
            }
            else
                ui->tabWidget->setCurrentIndex(CFG_UI.General.DataTabAsFirstInTables.get() ? 1 : 0);
```

**Comment by pawelsalawa** [comment]
Okay, this time I hope it's fully fixed ;) Please `git pulll` and check on your side.
