### ISSUE TITLE
Automatic refresh and grid focus (feature request)

### ISSUE THREAD

**Issue by marcpley** [pawelsalawa/sqlitestudio#5079]
### Details
When inserting or update rows in grid view, triggers firing on commit could generate values for generated columns. But those generated values are not visibles as the user continue to imput data.

User need to click Commit button AND Refresh button AND refocus on the row he work on.

Those options would be great:
- Automatic Refresh table data on Commit
- Keep focused cell on Refresh

**Comment by marcpley** [comment]
I keep thinking about this enhancement...

"Keep focused cell on Refresh" don't need to be an option in config dialog (complexification of config). I think it can be the regular behavior.

"Automatic Refresh table data on Commit" would not be an option in config dialog because the user may want the automatic refresh or not, depending of the modifications he performs.
There is 2 possibilities:
- Add a new button "Commit and refresh" next to the "Commit" button. This is UI complexification.
- Change nothing: the user will click the 2 buttons Commit and Refresh if he need the refresh. This is just one click. The big enhancement is keeping the selected cell (far more difficult to retrieve actually)

**So I simplify my initial request:**
Just try to keep the focused cell on Refresh, all the time (but if it a config option I don't mind).
And eventually change the order of the button, from general to detail: refresh commit rollback addrow deleterow
![Screenshot_20241117_073618](https://github.com/user-attachments/assets/7074b949-032c-4b1d-9ab1-eb0970e0fd2f)
to have the commit and refresh buttons side by side.  More logical order in my opinion.

**Comment by pawelsalawa** [comment]
Seems good.

I just have few notes to be aware of:
- First issue is when you insert a row, commit it and you wish to continue working on it in this way. User may have sorting active for certain column, therefore after refreshing, your newly inserted row may be places somewhere outside of the 1000 rows currently visible for a data page. In such case re-focusing is not possible
- Another is if you add row at the end of 1000 rows (adding 1001 row). It will be pushed to the next page after refreshing, so the same problem appears.
- Maybe there are more cases like that, that I didn't think of at the moment.

In such cases the re-focusing would not work.

**Comment by pawelsalawa** [comment]
@marcpley please fetch update from git and see how it works for you regarding cell focus.

**Comment by marcpley** [comment]
It's working for me too. Great :-)
Triggers list is ok too.
