### ISSUE TITLE
Selecting foreign key in grid view

### ISSUE THREAD

**Issue by marcpley** [pawelsalawa/sqlitestudio#5082]
### Details
Keyboard selecting a value for column with foreign key constrain 
![CAM01735r](https://github.com/user-attachments/assets/c1a2a284-f266-4186-924e-7a1c521a4d5e)
The windows opens on first row, not on the typed value.

### Steps to reproduce
Browse table with a column with foreign key.
Focus a cell in the column with foreign key.
Type the beginning of a valid value with keyboard. Auto-completion works.
Use up or down key to select the previous or next value > first row of the foreign key table.
If using the mouse to open the grid view with foreign key table > same problem, it is focused on first row. 

### Operating system
Linux mint 20.1

### SQLiteStudio version
3.4.4

**Comment by pawelsalawa** [comment]
I've made several improvements to cell editing code, which seems to have fixed this issue too.
