### ISSUE TITLE
Grid view, entering a cell for modification

### ISSUE THREAD

**Issue by marcpley** [pawelsalawa/sqlitestudio#5083]
### Details
To replace the value of a cell we have to focus the cell and simply type the new value. It's good.
![Capture d’écran du 2024-10-30 18-34-56](https://github.com/user-attachments/assets/32282af6-7540-4a4f-9289-e9fb1caeddcc)

To modify the value of a cell we have to focus the cell and entering it
![CAM01737](https://github.com/user-attachments/assets/8276697c-2444-4cd5-aa65-a6615e785be2)
and the value is totally selected. It's not usefull because  if I enter in the cell I don't want to replace it or copy it. Most often 
it's the end of the value that have to be modified. 
So, placing the cursor at the end of the value would be more ergonomic for the db users.

**Comment by pawelsalawa** [comment]
I agree your proposal is more intuitive.

**Comment by marcpley** [comment]
../guiSQLiteStudio/datagrid/fkcombobox.cpp
line 113
Comment this 2 lines:
```
if (!value.isNull() && isEditable())
    lineEdit()->selectAll();
```

**Comment by pawelsalawa** [comment]
This fix alone will apply only for columns with Foreign Key (as fkcombobox is used there). It's good, but it's not complete solution yet.

**Comment by pawelsalawa** [comment]
According to https://forum.qt.io/topic/51878/solved-remove-text-selection-when-qlineedit-gets-focus/4 we have to switch from vanilla `QLineEdit` to our own class that extends `QLineEdit` and overrides `focusInEvent`.

**Comment by pawelsalawa** [comment]
I will try that solution.

**Comment by marcpley** [comment]
I  agree my proposal isn't good when wanting to replace the entire value.

**Comment by pawelsalawa** [comment]
I got the expected behavior by extending `QLineEdit` and selecting contents conditionally (depending on how the edition was triggered).

**Comment by marcpley** [comment]
With this db:
[test.sqlite3.tar.gz](https://github.com/user-attachments/files/17770195/test.sqlite3.tar.gz)

browse "Cultures" table,
click on "Hors serre-6B" in column "Planche"
![image](https://github.com/user-attachments/assets/6a6572c7-9343-40e7-8ac6-1998fbc7d068)

type "no" with keyboard, auto-completion works and propose "nord-1"

if mouse click to open the foreign table grid, it's ok (corrected part of the bug).

but if you don't open the foreign table grid and type keydown key to have "Nord-1A" it don't work, you will have the first row of the foreign table: "Fruitiers-1"

**Comment by pawelsalawa** [comment]
I believe your last comment refers to #5082, right?

**Comment by pawelsalawa** [comment]
Okay, I found a way to fix it. You can `git pull` and verify on your side.
