### ISSUE TITLE
Parameter names

### ISSUE THREAD

**Issue by marcpley** [pawelsalawa/sqlitestudio#5091]
### Details
This don't work:
![Capture d’écran du 2024-11-02 05-29-40](https://github.com/user-attachments/assets/0e0aab66-0ed2-408a-9f17-50ea39bd28f3)
Error message when using it in a view:
[05:29:11] Could not load data for view 1-1 Tempo ITP. Error details: Error while executing SQL query on database 'Potaléger v0.1101': near "2": syntax error

If dParam is renamed dParam1 it works.

If that will be considered as bug, a correction may be managing parameters in descending alpha order.

**Comment by pawelsalawa** [comment]
Right. Also it should be prohibited to use same name for 2 arguments, so there are 2 problems here.

**Comment by marcpley** [comment]
../coreSQLiteStudio/plugins/scriptingsql.cpp
Line 61
```
        for (const QString& key : ctx->variables.keys())
        {
            QString value = "'" + ctx->variables[key].toString() + "'";
            sql.replace(":" + key, value).replace("@" + key, value).replace("$" + key, value);
        }
```
If variables array would be descending alpha sorted, the bug would be fixed. But:
- I'm new tu C++ and I don't know how to cleanly do that.
- I'm afraid to break something elsewhere.

**Comment by pawelsalawa** [comment]
Yes, descending order was a good idea. Apart from that this fix actually was a lot more complex and required way more work than I anticipated. I've committed complete fix for this one.
