### ISSUE TITLE
Archive of older Versions of SqliteStudio?

### ISSUE THREAD

**Issue by TurtleWilly** [pawelsalawa/sqlitestudio#5101]
### Details
I'm unable to locate versions of SqliteStudio older than 3.2.0/3.2.1 (neither here on GitHub under "Releases", nor on the official Homepage). There seems to be no historic archive (or it's not linked up somewhere easy to find?).

*Why?* I'm looking for a version between 3.0.6 and 3.2.0 to run on an older version of [Mac] OS X. 3.0.6 runs, so does 3.2.0/1, but 3.2.0/1 has a weird UI bug (where a progress bar is constantly flickering in the top/left corner of the windows) and 3.0.6 doesn't have an option to disable the default "permanent" switch. I would like to have the option, but not the flicker bug. Not sure such a version exists, if the option was added in 3.2.0 then I would be out of luck, of course, but I'm willing to try. :)

Generally it would be nice to have a full official backlog of all releases (*all* the way back to 1.0 or whatever came first).

### Operating system
OS X 10.10.5 (Yosemite, last version)

### SQLiteStudio version
> 3.0.6, < 3.2.0

**Comment by TurtleWilly** [comment]
I located the Dropbox archive. Hard to download from there with an old browser though. IMHO all this should be properly on the official homepage for easier access. :)

**Comment by pawelsalawa** [comment]
Why is it hard to download from there with older browser?
