### ISSUE TITLE
The selected row in the Query tab is black

### ISSUE THREAD

**Issue by Valyo-N** [pawelsalawa/sqlitestudio#5114]
### Details
The selected row in the Query tab is black and I can't read the code.

### Steps to reproduce
Open any view -> Query tab.

### Operating system
Windows 10 64-bit.

### SQLiteStudio version
SQLiteStudio v.3.4.5
![Screenshot 2024-11-22 171613](https://github.com/user-attachments/assets/06b6bf77-76f9-4814-bfae-2cc444114a17)

**Comment by pawelsalawa** [comment]
This is also discussed in #5113. Probably there will be a quick fix for it in a hotfix 3.4.6. I'm expecting to release it soon. In the meanwhile I'm trying in #5113 to find if there is a workaround for users to use for the moment.

**Comment by Valyo-N** [comment]
Thanks for the quick reply. I read #5113 and tried to change the query
color, but it didn't change. Also, I couldn't disable the highlight in the
General settings.

На пт, 22.11.2024 г., 18:04 ч. Paweł Salawa ***@***.***>
написа:

**Comment by pawelsalawa** [comment]
From the davonnep's comment in the mentioned discussion, what worked for him was to enable custom colors for both "query" and "current line" and setting their color to white.

This is a temporary solution. There will be a hotfix for this.
