### ISSUE TITLE
The query execution mechanism had problems with extracting ROWID's properly.

### ISSUE THREAD

**Issue by DavidJCook64** [pawelsalawa/sqlitestudio#5115]
### Details
Getting the following Error:
Cannot edit this cell. Details: The query execution mechanism had problems with extracting ROWID's properly. This might be a bug in the application. You may want to report this.

### Steps to reproduce
Executed an existing query in a view to return specific rows matching criteria, and tried to edit a column value ("N" to "Y") in one of the results rows.  
Been working under previous versions, upgraded to 3.4.5 last night and immediately started getting the error, so I can't change values anymore in queries.

### Operating system
Windows 11 Pro
Build 22621.ni_release.220506-1250

### SQLiteStudio version
3.4.5

**Comment by pawelsalawa** [comment]
Can you share the query you execute?
Ideally it would be nice if you shared a database you execute it on (you can contact me on support@sqlitestudio.pl, so we can agree on the sharing privately). It would make fixing much quicker.
