### ISSUE TITLE
sql is now blacked out

### ISSUE THREAD

**Issue by mwbidwell** [pawelsalawa/sqlitestudio#5116]
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment]
Duplicate of #5114.
Will be fixed in 3.4.6 (to be released soon).
