### ISSUE TITLE
SELECT import(...) is really slow 

### ISSUE THREAD

**Issue by calarispuntnl** [pawelsalawa/sqlitestudio#5119]
### Details
Today I discovered the import function. Looks great and really useful for my purpose. However:
I am recreating several tables and then add the new csv-data via SELECT IMPORT (see: https://github.com/pawelsalawa/sqlitestudio/discussions/3900). This takes approx. 3 minutes for a table with just 1500 records.
The example below shows just one table, but the entire script recreates 25-30 tables like this.

### Steps to reproduce
My script per table:
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;
DROP TABLE IF EXISTS tData;
CREATE TABLE IF NOT EXISTS tData (
fieldA  INTEGER,
fieldB  INTEGER,
fieldC  INTEGER,
fieldD  INTEGER,
fieldE  INTEGER,
fieldF  TEXT,
fieldG TEXT
);
DROP INDEX IF EXISTS idxA;
CREATE INDEX IF NOT EXISTS idxA ON tData (fieldA, fieldB, fieldC);
COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
SELECT import('myPath/tData.csv', 'CSV', 'tData', 'UTF-8', 'CsvImport.FirstRowAsColumns=true
CsvImport.Separator = 1 ');

### Operating system
WIN 11

### SQLiteStudio version
3.4.6

**Comment by Sierron** [comment]
You can save yourself the drop index line because as per sqlite website:

https://sqlite.org/lang_droptable.html
"The dropped table is completely removed from the database schema and the disk file. The table can not be recovered. All indices and triggers associated with the table are also deleted."

Try creating the indices after filling the tables with content.

**Comment by pawelsalawa** [comment]
@calarispuntnl 3 minutes? Or 3 seconds? I'm asking, cause I've just tried it and it took 3 seconds. Still a bit long (it's a subject to investigate), but way less than 3 minutes, so just wanted co confirm with you.

**Comment by calarispuntnl** [comment]
![image](https://github.com/user-attachments/assets/f452a3dd-b0e8-42d5-828a-67bb15233aa2)
The script ran uninterrupted. As you can see, importing 6572 records took 13 minutes, 25548 records took 1 hour.
When I only recreate the tables and then import the csv's with the import buttons it's all done within a few seconds

**Comment by pawelsalawa** [comment]
Are you using WAL mode in your database? Are you accessing this database by other applications at the same time?

**Comment by calarispuntnl** [comment]
No WAL mode (not that I'm aware of anyway) and there is nothing else accessing the db-file.
Like I said, the only difference is: I now use the sql script ([1] drop / [2] create table + index / [3] import data) for all my tables. 
Before this I did steps [1] and [2] for all my tables and then imported the csv files manually one by one.

**Comment by pawelsalawa** [comment]
Is it possible for you to share the imported csv file? If that helps, you can send it to support@sqlitestudio.pl, so it's not public.

**Comment by pawelsalawa** [comment]
Okay, never mind. I found the performance problem. For me, after the fix it went from 3 seconds to 4 milliseconds and it is most likely responsible for your problem too. Expect the fix to be released with 3.4.7 in few days.
