### ISSUE TITLE
The app freezes when querying table with many big values

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#5134]
Table that has some big values in one or more columns (for example 1MB in a single cell) in multiple rows makes SQLiteStudio freeze when trying to view the data in a grid view.

**Comment by pawelsalawa** [comment]
Performance in such situations have been significantly improved, although if we have hundreds of big values (1MB or more) in the single grid view, it will still be a bit low. Nevertheless, the application should still work after this fix - even in such harsh situations. It should not get freezed.

**Comment by LyttleG** [comment]
Good news Pawel :)
