### ISSUE TITLE
App becomes unresponsive when attempting to close a connection to a live database

### ISSUE THREAD

**Issue by adielmtz** [pawelsalawa/sqlitestudio#5136]
### Details
I have a database that's being modified by another process. Every now and then I wanted to check the data being added into the tables. However, when I try to close the connection, the app hangs until the other process commits or closes its connection.
In the previous version, it would just close the connection and show an error message about not being able to do a WAL checkpoint.

### Steps to reproduce
1. Open a SQLite database with SQLiteStudio.
2. Modify the database externally.
3. Click 'disconnect database' from the database list panel.

### Operating system
Windows 10 22H2

### SQLiteStudio version
3.4.6

**Comment by pawelsalawa** [comment]
Right. There is 1 minute (or so) timeout for this, but I guess it doesn't make sense to wait in such case. I will disable timeout for it to fail fast.
