### ISSUE TITLE
Windows version fails to set database directory correctly

### ISSUE THREAD

**Issue by ChuckM** [pawelsalawa/sqlitestudio#5146]
### Details

New to SQLiteStudio and I thought I would try it out. 

### Steps to reproduce

Downloaded the latest, installed it, and ran it.
Created a database named "foo"
Went to create a table in foo and it failed "Database is read-only"
After much gnashing of teeth, discovered it was trying to work on a database file in the PROGRAM FILES directory where SQLiteStudo was installed, RATHER than either in $USER\AppData\sqliteststudio or $USER\Documents\sqlitestudio\

Once I figured out what it was trying to do I clicked the 'folder' icon at the create step, moved it to the $USER\databases\ folder
(I clicked on create a new folder and named it databases)

Then creating foo and later adding tables to it worked as expected.

### Operating system

Windows 10 x64 / Windows 11 x64

### SQLiteStudio version

3.4.6

**Comment by pawelsalawa** [comment]
Well, there will be another person asking why this is `$USER\AppData\sqliteststudio` or `$USER\Documents\sqlitestudio\` and not some another one.

I need to think what would be the best default working directory here.
