### ISSUE TITLE
Cannot access tables from other open/connected databases

### ISSUE THREAD

**Issue by erykjj** [pawelsalawa/sqlitestudio#5148]
### Details
`Error while executing SQL query on database 'DB1': no such table: DB1.table1`

### Steps to reproduce

- Open and connect to DB1
- Open and connect to DB2
- In SQL editor for DB2:
- `SELECT * FROM DB1.table1;`

### SQLiteStudio version
v3.4.5, 3.4.6, 3.4.7, 3.4.8
**work correctly on v3.4.4**

**Comment by erykjj** [comment]
v3.4.9:

The query executes (produces output), BUT also an error:
`An error occured while executing the count(*) query, thus data paging will be disabled. Error details from the database: no such table: attached.table1`
Total rows loaded shows 0, even though the full list of rows is shown in the Grid view

**Comment by pawelsalawa** [comment]
I'm unable to reproduce it here. Would it be possible for you to share the database privately (through support@sqlitestudio.pl)?

**Comment by erykjj** [comment]
Fixed in v3.4.10.

Thank you!
