### ISSUE TITLE
QFont issue causing execution issue for 3.4.8

### ISSUE THREAD

**Issue by audiomuze** [pawelsalawa/sqlitestudio#5152]
### Details
Here you describe your problem details, or proposal for enhancement.
Installed 3.4.8 (from Arch AUR and subsequently from [download](https://github.com/pawelsalawa/sqlitestudio/releases/download/3.4.8/SQLiteStudio-3.4.8-linux-x64-installer.run)
and get the same result on both:

```
/opt/SQLiteStudio/sqlitestudio
QFont::fromString: Invalid description 'Noto Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Hack,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
```

Both noto-fonts and ttf-hack are confirmed installed.

### Steps to reproduce
See above.

### Operating system
6.12.1-arch1-1

### SQLiteStudio version
3.4.8

**Comment by pawelsalawa** [comment]
Does it happen too if you rename [your config file](https://github.com/pawelsalawa/sqlitestudio/wiki/Configuration_directory_location) temporarily and try with fresh config?

**Comment by audiomuze** [comment]
That solves it, but how to get back my 30 pages of scripts?

**Comment by pawelsalawa** [comment]
Okay. You will just fix your old config while running SQLiteStudio temporarily on this "empty" new config. Keep your original config file renamed. Start the app and then add your renamed settings file as database (as the config actually is SQLite3 database). 

In that database there is the `settings` table. You need to execute following delete on it:
```
delete from settings where [group] = 'Fonts';
```
That's it. Close the app, restore original file and try it out.

**Comment by audiomuze** [comment]
> Okay. You will just fix your old config while running SQLiteStudio temporarily on this "empty" new config. Keep your original config file renamed. Start the app and then add your renamed settings file as database (as the config actually is SQLite3 database).
> 
> In that database there is the `settings` table. You need to execute following delete on it:
> 
> ```
> delete from settings where [group] = 'Fonts';
> ```
> 
> That's it. Close the app, restore original file and try it out.

Thanks, that did the trick.
