### ISSUE TITLE
Selected window in Window list

### ISSUE THREAD

**Issue by marcpley** [pawelsalawa/sqlitestudio#5160]
When there is a lot of open windows, and have to frequently switch between them, the selected windows is not easylli found in the list.

![image](https://github.com/user-attachments/assets/db4dbf04-0ad2-4c0a-ada2-d7293ae8c932)

It depend of theme of the operating system of course.
The tab name could be bold if selected. Or underlined.
When there is only one opened database, no need to add the database name after the table name, it waste room.
![image](https://github.com/user-attachments/assets/d7b8df63-2778-49c4-ba9a-754e100d9c1a)

In Databases panel the selected table or view is well highlighted
![image](https://github.com/user-attachments/assets/a9cfbc4d-f776-450c-a2c0-06b173ed72ec)
but there is no correspondance with the selected window, this increase the difficulty to know what are the data in main screen.

**Comment by pawelsalawa** [comment]
Current window button style is one issue.
Database panel synchronization is another.
Both are relevant and important, yet different matters. Let's put the second one into its own, separate issue, alright?

**Comment by pawelsalawa** [comment]
I've created #5165 for the second proposal/request.

**Comment by pawelsalawa** [comment]
As for the first problem reported in this issue, I've addressed it this way:
![image](https://github.com/user-attachments/assets/03b5825e-d4b5-48b8-95e6-cd17352e14d3)

![image](https://github.com/user-attachments/assets/2f17a1f7-72b2-476c-811f-f30b7008c0dd)

With that, I've finished all issues for 3.4.10 and I started GitHub actions to build all binaries few moments ago. If everything goes well, the 3.4.10 will be tomorrow.

**Comment by marcpley** [comment]
Perfect :-)
