### ISSUE TITLE
feature request: customizing toolbar icons size, color etc

### ISSUE THREAD

**Issue by massimo-cassandro** [pawelsalawa/sqlitestudio#5176]
toolbar icons are really small and have poor contrast with the background color

![Screenshot 2024-12-20 at 14 12 35](https://github.com/user-attachments/assets/d3634655-b82c-4e61-abef-cd04965a9e10)

It would be a great improvement if users could choose:
* the icons size (with two or three default sizes)
* whether or not to display a label under the icons
* the display mode (high contrast, dark theme, B/W etc...)

I think svg icons could easily enable all these features

I'm available for a  pull request about new svg icons, if thery are needed

**Comment by pawelsalawa** [comment]
All your points are aimed in issue #5102. Feel free to join discussion there and contribute if you like (though there is already one person preparing whole svg iconset).
