### ISSUE TITLE
SQLiteStudio 3.4.11 Windows x64 installer not released

### ISSUE THREAD

**Issue by SpecterShell** [pawelsalawa/sqlitestudio#5177]
### Details
The Windows x64 installer for SQLiteStudio 3.4.11 is not released (and thus the download link is broken). Only the Windows x86 installer exists.

### Steps to reproduce
1. Go to https://github.com/pawelsalawa/sqlitestudio/releases/tag/3.4.11
2. The Windows x64 installer `SQLiteStudio-3.4.11-windows-x64-installer.exe` does not exist, and the corresponding download link in the table is also broken.

### Operating system
Windows

### SQLiteStudio version
3.4.11

**Comment by pawelsalawa** [comment]
Right. Thanks! Fixed.
